### ISSUE TITLE
Druid's set8 T1 bonus has incorrect interaction with Improved Tranquility talent that leads to 0s CD of Tranquility ability

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#10100] opened 2022-01-09 13:47 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2754

8 Pieces of T1 reduce CD of Tranquility by 50%, druid talent Improved Tranquility reduces Cooldown from 8 mins to 4 mins, if combined with 8 pieces of T1 it gives 0 sec CD instead 50% of 4 mins = 2 mins. So when you have talent and 8 pieces of T1 you get 0 sec CD instead 2 min CD.
![image](https://user-images.githubusercontent.com/80590226/148683756-074f466d-d0c9-4873-a523-26af15f81921.png)

Tester:

The issue is confirmed. Druid's [set8 T1 bonus](https://wowgaming.altervista.org/aowow/?spell=23556) has incorrect interaction with [Improved Tranquility](https://wowgaming.altervista.org/aowow/?spell=17124) talent that leads to 0s CD of [Tranquility](https://wowgaming.altervista.org/aowow/?spell=740) ability

![WoWScrnShot_010922_163552](https://user-images.githubusercontent.com/85256266/148684789-157a8945-7ad5-461d-9778-62a2752cba8f.jpg)

### Expected Blizzlike Behaviour

Correct CD calculation

### Steps to reproduce the problem

.learn 740
.aura 17124
.aura 23556

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2022-01-09 14:13
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6461.

**Closed** 2022-01-09 14:28 UTC
Labels: Invalid-Intended/WontFix/Blizzlike
