### ISSUE TITLE
Game Event Start Date & Calendar

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#2550] opened 2020-01-06 19:41 UTC
##### SMALL DESCRIPTION:

The start date (example "Love is in the air" id 8) for game events is not correct (one month early, should start about 04.02.2020) and the event is not shown in the game calendar. 

![image](https://user-images.githubusercontent.com/55922592/71843583-874e4b80-30c4-11ea-9753-55541389a420.png)
![image](https://user-images.githubusercontent.com/55922592/71843630-a0ef9300-30c4-11ea-9d73-824847331372.png)

Also the upcoming events "Noblegarden" (id 9) & "Children's Week" (id 10) are not shown in the calendar ingame. 

April 2019 
-------------
![image](https://user-images.githubusercontent.com/55922592/71843726-ced4d780-30c4-11ea-8971-dce81e6ef802.png)

April 2020 
-------------
![image](https://user-images.githubusercontent.com/55922592/71843807-fc218580-30c4-11ea-9073-978324da8aab.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The game event 8 should start in february. 
The upcoming events should be shown in the calendar.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .event activelist 
2. .event 8
3. 

##### EXTRA NOTES:

2020-01-06 19:00:29 Loading Game Event Data...
2020-01-06 19:00:29 >> Loaded 120 holiday dates in 1 ms
2020-01-06 19:00:29 No suitable start date found for holiday 327.
2020-01-06 19:00:29 No suitable start date found for holiday 423.
2020-01-06 19:00:29 No suitable start date found for holiday 181.
2020-01-06 19:00:29 No suitable start date found for holiday 201.
2020-01-06 19:00:29 No suitable start date found for holiday 321.
2020-01-06 19:00:29 No suitable start date found for holiday 283.
2020-01-06 19:00:29 No suitable start date found for holiday 284.
2020-01-06 19:00:29 No suitable start date found for holiday 285.
2020-01-06 19:00:29 No suitable start date found for holiday 353.
2020-01-06 19:00:29 No suitable start date found for holiday 404.
2020-01-06 19:00:29 No suitable start date found for holiday 400.
2020-01-06 19:00:29 No suitable start date found for holiday 420.
2020-01-06 19:00:29 >> Loaded 69 game events in 4 ms

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 0f590d03974a+ 2020-01-02 07:43:04 +0000 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 pro 64 bit

##### MODULES:

- Auctionhouse Bot
- Solo LFG
- Autobalance

##### OTHER CUSTOMIZATIONS:

Max skill on level/login

**Comment by pklloveyou** [comment] 2020-01-06 20:38
confirm

**Comment by solidmaxtor** [comment] 2020-01-06 20:59
Confirm problem

**Comment by Bogir** [comment] 2020-01-06 21:41
confirm

**Comment by Ashland** [comment] 2020-01-07 05:17
Confirmed , I had one issue with this recent commit I did a pr for could it be to do with this maybe https://github.com/azerothcore/azerothcore-wotlk/pull/2368

**Comment by Stoabrogga** [comment] 2020-01-07 07:56
I don't think it is related to PR #2368. The only thing changed in this PR is setting the end date into the future for events with end_time set to NULL, so that the events don't run out. The error message in the server log is caused by this function:
https://github.com/azerothcore/azerothcore-wotlk/blob/4a8f1de5381d1cf53cdcc4c5bb7d9ef7c99a8a8f/src/server/game/Events/GameEventMgr.cpp#L1733-L1808
I don't see any reference to the end time of the game event there. Could it be that the maximum occurrence is read from DBC?

**Comment by Bogir** [comment] 2020-01-07 08:09
> Could it be that the maximum occurrence is read from DBC?

Incorrect only in Calendar. It isn't shown event, but event's stard trigger calculated approximately normal (+/-2..5 days depending from timezone or something else)
![изображение](https://user-images.githubusercontent.com/25766571/71878704-58c08700-313d-11ea-8ee8-93c504e68ec8.png)
![изображение](https://user-images.githubusercontent.com/25766571/71878817-a937e480-313d-11ea-9655-2a4ac0fa9f76.png)
![изображение](https://user-images.githubusercontent.com/25766571/71878879-cec4ee00-313d-11ea-86fd-42bb4114ab45.png)
this event must be during 2 week before St Valentines day (+/-)
It must be started in Febrary, not in middle January
However, calendar is not showing it. But at last year it was shown.

**Comment by Stoabrogga** [comment] 2020-01-07 08:44
The next date is calculated in this function, but I sadly don't have an idea what's going wrong there:
https://github.com/azerothcore/azerothcore-wotlk/blob/4a8f1de5381d1cf53cdcc4c5bb7d9ef7c99a8a8f/src/server/game/Events/GameEventMgr.cpp#L71-L108

**Comment by Ashland** [comment] 2020-01-07 09:33
I thought maybe it had to do with the arnt art tone changes in that commit 
`UPDATE `game_event` SET `start_time` = '1970-01-01 08:00:00', `end_time` = '1970-01-01 08:00:00' WHERE `eventEntry` IN
 (13, 17, 22, 31, 48, 49, 55, 56, 57, 58, 59, 60, 65, 66); `

**Comment by pklloveyou** [comment] 2020-01-07 09:37
I've tried them all, not because of the above

**Comment by pklloveyou** [comment] 2020-01-07 09:44
Client limitations? But I can't find that in DBC

**Comment by Stoabrogga** [comment] 2020-01-07 09:51
These events are not in use:
```
(13, 17, 22, 31, 48, 49, 55, 56, 57, 58, 59, 60, 65, 66)
```

The end_time for the following events has been set to NULL. The core automatically calculates the end_time for these events while reading the table (current date + 2 years):
```
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 18, 
19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 
37, 38, 39, 40, 41, 42, 43, 44, 45, 50, 51, 52, 53, 54, 62, 63, 
64, 67, 68, 69, 70, 71)
```
```cpp
uint64 endtime          = fields[2].GetUInt64();
if (fields[2].IsNull())
    endtime             = time(nullptr) + 63072000; // add 2 years to current date
```
A small bug existed concerning importing too small dates (probably due to time zone issues), which was fixed in PR #2462.

**Comment by petunindan** [comment] 2020-01-09 10:32
Hello! I also ran into this problem and started looking for a solution. I tried changing the year at start_time of the event "Love in the air" from 2013 to 2019 and now it works as it should (I changed the system time to 02/14/2020 to check this). I hope this information helps you. Forgive my English, I partially use Google translator.
P.S. Unfortunately, the holiday is not displayed on the calendar.

Jan. 9:

![WoWScrnShot_010920_132136](https://user-images.githubusercontent.com/59688471/72059926-0372aa00-32e4-11ea-877a-53e873230a6a.jpg)

Feb. 14:

![WoWScrnShot_021420_132314](https://user-images.githubusercontent.com/59688471/72059958-15544d00-32e4-11ea-89a4-077ed219ade5.jpg)

DB:

![LA_DB](https://user-images.githubusercontent.com/59688471/72060070-53ea0780-32e4-11ea-9cbf-ef10a1f5666a.jpg)

**Comment by Endeffect-AT** [comment] 2020-01-10 21:31
May this could be helpful useful to fix this:

https://github.com/TrinityCore/TrinityCore/issues/24045

**Comment by natnat201193** [comment] 2020-01-10 22:25
if you are getting No suitable start date found, then that may not fix it here, worth a try though. AZC may need some other changes from TC for it to work, idk.

**Comment by Endeffect-AT** [comment] 2020-01-10 23:25
it can also be helpful to know that there are several people working on the same problem and maybe they can solve it faster together.  Didn't say this is the solution.  Thanks

**Comment by Stoabrogga** [comment] 2020-01-12 09:09
Ok, in order to fix this you need to add new values to the table `holiday_dates`. For example, the last entry with ID 9 for holiday 423 ("Love is in the Air") contains the date value 319881216 which means 2019-02-05 (see https://wowdev.wiki/DB/Holidays). You can add a new entry for 2020-02-05:
```sql
INSERT INTO `holiday_dates` (`id`, `date_id`, `date_value`) VALUES
(423,10,(20 << 24) | ((02 - 1) << 20) | ((05 - 1) << 14));
```
After restarting the server you'll see the correct date for this holiday. You can use this format for the date value of new entries:
(**YY** << 24) | ((**MM** - 1) << 20) | ((**DD** - 1) << 14)

We should eventually implement another way sometime in the future, as it is a tedious task to add all the holiday dates. Plus, the maximum possible year which can be specified this way is 2031 (only 5 Bits for the year) and there can only be a maximum of 26 entries per holiday event. Here's the code which creates the packet:
https://github.com/azerothcore/azerothcore-wotlk/blob/c15206fc152a547dc39e50e8964738f8f115747a/src/server/game/Handlers/CalendarHandler.cpp#L144-L164

**Comment by solidmaxtor** [comment] 2020-01-14 08:27
tested show fine in calendar now @Stoabrogga.

**Comment by Stoabrogga** [comment] 2020-01-14 08:53
Thanks @solidmaxtor. However, we need the dates for all the other events, too. Perhaps we can use parts of the SQL script mentioned in the TC issue @Endeffect-AT posted above. I just don't have the time to work on this currently, sorry (I also normally have the holiday events disabled on my server because I find them annoying).

**Comment by pklloveyou** [comment] 2020-01-15 11:51
```c++
INSERT INTO `holiday_dates` VALUES (181, 0, 220708864);
INSERT INTO `holiday_dates` VALUES (181, 1, 238354432);
INSERT INTO `holiday_dates` VALUES (181, 2, 254885888);
INSERT INTO `holiday_dates` VALUES (181, 3, 270974976);
INSERT INTO `holiday_dates` VALUES (181, 4, 288620544);
INSERT INTO `holiday_dates` VALUES (181, 5, 305152000);
INSERT INTO `holiday_dates` VALUES (181, 6, 322256896);
INSERT INTO `holiday_dates` VALUES (181, 7, 339034112);
INSERT INTO `holiday_dates` VALUES (181, 8, 355811328);
INSERT INTO `holiday_dates` VALUES (181, 9, 372588544);
INSERT INTO `holiday_dates` VALUES (181, 10, 389365760);
INSERT INTO `holiday_dates` VALUES (201, 0, 221708288);
INSERT INTO `holiday_dates` VALUES (201, 1, 238469120);
INSERT INTO `holiday_dates` VALUES (201, 2, 255229952);
INSERT INTO `holiday_dates` VALUES (201, 3, 272646144);
INSERT INTO `holiday_dates` VALUES (201, 4, 289406976);
INSERT INTO `holiday_dates` VALUES (201, 5, 305610752);
INSERT INTO `holiday_dates` VALUES (201, 6, 322371584);
INSERT INTO `holiday_dates` VALUES (201, 7, 339148800);
INSERT INTO `holiday_dates` VALUES (201, 8, 355926016);
INSERT INTO `holiday_dates` VALUES (201, 9, 372703232);
INSERT INTO `holiday_dates` VALUES (201, 10, 389480448);
INSERT INTO `holiday_dates` VALUES (321, 0, 210092032);
INSERT INTO `holiday_dates` VALUES (321, 1, 226689024);
INSERT INTO `holiday_dates` VALUES (321, 2, 243286016);
INSERT INTO `holiday_dates` VALUES (321, 3, 260374528);
INSERT INTO `holiday_dates` VALUES (321, 4, 276955136);
INSERT INTO `holiday_dates` VALUES (321, 5, 294060032);
INSERT INTO `holiday_dates` VALUES (321, 6, 310657024);
INSERT INTO `holiday_dates` VALUES (321, 7, 327434240);
INSERT INTO `holiday_dates` VALUES (321, 8, 344211456);
INSERT INTO `holiday_dates` VALUES (321, 9, 360988672);
INSERT INTO `holiday_dates` VALUES (321, 10, 377765888);
INSERT INTO `holiday_dates` VALUES (321, 11, 394543104);
INSERT INTO `holiday_dates` VALUES (327, 0, 218529792);
INSERT INTO `holiday_dates` VALUES (327, 1, 235192320);
INSERT INTO `holiday_dates` VALUES (327, 2, 252952576);
INSERT INTO `holiday_dates` VALUES (327, 3, 269484032);
INSERT INTO `holiday_dates` VALUES (327, 4, 285540352);
INSERT INTO `holiday_dates` VALUES (327, 5, 303169536);
INSERT INTO `holiday_dates` VALUES (327, 6, 319209472);
INSERT INTO `holiday_dates` VALUES (327, 7, 335806464);
INSERT INTO `holiday_dates` VALUES (327, 8, 353419264);
INSERT INTO `holiday_dates` VALUES (327, 9, 369491968);
INSERT INTO `holiday_dates` VALUES (327, 10, 386088960);
INSERT INTO `holiday_dates` VALUES (374, 0, 279986176);
INSERT INTO `holiday_dates` VALUES (374, 1, 287342592);
INSERT INTO `holiday_dates` VALUES (374, 2, 290471936);
INSERT INTO `holiday_dates` VALUES (374, 3, 293601280);
INSERT INTO `holiday_dates` VALUES (374, 4, 296747008);
INSERT INTO `holiday_dates` VALUES (374, 5, 304103424);
INSERT INTO `holiday_dates` VALUES (374, 6, 307232768);
INSERT INTO `holiday_dates` VALUES (374, 7, 309821440);
INSERT INTO `holiday_dates` VALUES (374, 8, 312950784);
INSERT INTO `holiday_dates` VALUES (374, 9, 320864256);
INSERT INTO `holiday_dates` VALUES (374, 10, 323452928);
INSERT INTO `holiday_dates` VALUES (374, 11, 326582272);
INSERT INTO `holiday_dates` VALUES (374, 12, 329711616);
INSERT INTO `holiday_dates` VALUES (374, 13, 337035264);
INSERT INTO `holiday_dates` VALUES (374, 14, 340197376);
INSERT INTO `holiday_dates` VALUES (374, 15, 343982080);
INSERT INTO `holiday_dates` VALUES (374, 16, 347127808);
INSERT INTO `holiday_dates` VALUES (374, 17, 353779712);
INSERT INTO `holiday_dates` VALUES (374, 18, 357613568);
INSERT INTO `holiday_dates` VALUES (374, 19, 360742912);
INSERT INTO `holiday_dates` VALUES (374, 20, 363888640);
INSERT INTO `holiday_dates` VALUES (374, 21, 371245056);
INSERT INTO `holiday_dates` VALUES (374, 22, 374374400);
INSERT INTO `holiday_dates` VALUES (374, 23, 377503744);
INSERT INTO `holiday_dates` VALUES (374, 24, 380649472);
INSERT INTO `holiday_dates` VALUES (374, 25, 388005888);
INSERT INTO `holiday_dates` VALUES (375, 0, 280444928);
INSERT INTO `holiday_dates` VALUES (375, 1, 287801344);
INSERT INTO `holiday_dates` VALUES (375, 2, 290930688);
INSERT INTO `holiday_dates` VALUES (375, 3, 294060032);
INSERT INTO `holiday_dates` VALUES (375, 4, 297205760);
INSERT INTO `holiday_dates` VALUES (375, 5, 304562176);
INSERT INTO `holiday_dates` VALUES (375, 6, 307691520);
INSERT INTO `holiday_dates` VALUES (375, 7, 310820864);
INSERT INTO `holiday_dates` VALUES (375, 8, 318816256);
INSERT INTO `holiday_dates` VALUES (375, 9, 321323008);
INSERT INTO `holiday_dates` VALUES (375, 10, 324452352);
INSERT INTO `holiday_dates` VALUES (375, 11, 328253440);
INSERT INTO `holiday_dates` VALUES (375, 12, 335577088);
INSERT INTO `holiday_dates` VALUES (375, 13, 338722816);
INSERT INTO `holiday_dates` VALUES (375, 14, 341868544);
INSERT INTO `holiday_dates` VALUES (375, 15, 344997888);
INSERT INTO `holiday_dates` VALUES (375, 16, 352321536);
INSERT INTO `holiday_dates` VALUES (375, 17, 355483648);
INSERT INTO `holiday_dates` VALUES (375, 18, 358629376);
INSERT INTO `holiday_dates` VALUES (375, 19, 361758720);
INSERT INTO `holiday_dates` VALUES (375, 20, 364347392);
INSERT INTO `holiday_dates` VALUES (375, 21, 372244480);
INSERT INTO `holiday_dates` VALUES (375, 22, 375390208);
INSERT INTO `holiday_dates` VALUES (375, 23, 377962496);
INSERT INTO `holiday_dates` VALUES (375, 24, 381108224);
INSERT INTO `holiday_dates` VALUES (375, 25, 388464640);
INSERT INTO `holiday_dates` VALUES (376, 0, 286294016);
INSERT INTO `holiday_dates` VALUES (376, 1, 288800768);
INSERT INTO `holiday_dates` VALUES (376, 2, 292601856);
INSERT INTO `holiday_dates` VALUES (376, 3, 295731200);
INSERT INTO `holiday_dates` VALUES (376, 4, 303054848);
INSERT INTO `holiday_dates` VALUES (376, 5, 306233344);
INSERT INTO `holiday_dates` VALUES (376, 6, 309362688);
INSERT INTO `holiday_dates` VALUES (376, 7, 312492032);
INSERT INTO `holiday_dates` VALUES (376, 8, 319815680);
INSERT INTO `holiday_dates` VALUES (376, 9, 322994176);
INSERT INTO `holiday_dates` VALUES (376, 10, 326123520);
INSERT INTO `holiday_dates` VALUES (376, 11, 329252864);
INSERT INTO `holiday_dates` VALUES (376, 12, 336035840);
INSERT INTO `holiday_dates` VALUES (376, 13, 339738624);
INSERT INTO `holiday_dates` VALUES (376, 14, 342327296);
INSERT INTO `holiday_dates` VALUES (376, 15, 345456640);
INSERT INTO `holiday_dates` VALUES (376, 16, 352780288);
INSERT INTO `holiday_dates` VALUES (376, 17, 355942400);
INSERT INTO `holiday_dates` VALUES (376, 18, 359088128);
INSERT INTO `holiday_dates` VALUES (376, 19, 362217472);
INSERT INTO `holiday_dates` VALUES (376, 20, 370196480);
INSERT INTO `holiday_dates` VALUES (376, 21, 372703232);
INSERT INTO `holiday_dates` VALUES (376, 22, 375848960);
INSERT INTO `holiday_dates` VALUES (376, 23, 379633664);
INSERT INTO `holiday_dates` VALUES (376, 24, 386957312);
INSERT INTO `holiday_dates` VALUES (376, 25, 389464064);
INSERT INTO `holiday_dates` VALUES (404, 0, 228982784);
INSERT INTO `holiday_dates` VALUES (404, 1, 245743616);
INSERT INTO `holiday_dates` VALUES (404, 2, 262504448);
INSERT INTO `holiday_dates` VALUES (404, 3, 279248896);
INSERT INTO `holiday_dates` VALUES (404, 4, 296009728);
INSERT INTO `holiday_dates` VALUES (404, 5, 312770560);
INSERT INTO `holiday_dates` VALUES (404, 6, 329646080);
INSERT INTO `holiday_dates` VALUES (404, 7, 346423296);
INSERT INTO `holiday_dates` VALUES (404, 8, 363200512);
INSERT INTO `holiday_dates` VALUES (404, 9, 379977728);
INSERT INTO `holiday_dates` VALUES (404, 10, 396754944);
INSERT INTO `holiday_dates` VALUES (423, 0, 219299840);
INSERT INTO `holiday_dates` VALUES (423, 1, 236077056);
INSERT INTO `holiday_dates` VALUES (423, 2, 252723200);
INSERT INTO `holiday_dates` VALUES (423, 3, 269713408);
INSERT INTO `holiday_dates` VALUES (423, 4, 286359552);
INSERT INTO `holiday_dates` VALUES (423, 5, 303169536);
INSERT INTO `holiday_dates` VALUES (423, 6, 319881216);
INSERT INTO `holiday_dates` VALUES (423, 7, 336658432);
INSERT INTO `holiday_dates` VALUES (423, 8, 353435648);
INSERT INTO `holiday_dates` VALUES (423, 9, 370212864);
INSERT INTO `holiday_dates` VALUES (423, 10, 386990080);
```

**Closed** 2020-04-24 12:13 UTC
