### ISSUE TITLE
[Core/SpellIco]Lost spell icon in combat

### ISSUE THREAD

**Issue by kuramajssken001** [azerothcore/azerothcore-wotlk#2803] opened 2020-03-25 10:00 UTC
**SMALL DESCRIPTION:**
Some skill ICONS disappear from the skill bar when the warrior class switches stance during combat.
I believe the same problem should exist in other classes, such as druids.
**STEPS TO REPRODUCE THE PROBLEM:**
Use the warrior or druid class to switch stance in combat.
**BRANCH(ES):**
master

**AC HASH/COMMIT:** 
fa57954ff9d3bea2dc3eaada49d2842b3e6b9254
**OPERATING SYSTEM:**
**MODULES:**
**DEMO:**
https://youtu.be/Ml_NxhD-_Ok

**Comment by Viste** [comment] 2020-03-25 11:08
??? skills disappear  when you switch from arms to defense and again to arms in arms setup?
or how?

**Comment by lineagedr** [comment] 2020-03-25 11:27
Does this occur with ALL addons disabled?

**Comment by kuramajssken001** [comment] 2020-03-25 11:49
@Viste yeah,

**Comment by kuramajssken001** [comment] 2020-03-25 12:20
> Does this occur with ALL addons disabled?

This has nothing to do with addons.

**Comment by Viste** [comment] 2020-03-25 12:27
can you turn on DB logs and try do this and look at console what you see?

**Comment by pklloveyou** [comment] 2020-03-25 17:34
![image](https://user-images.githubusercontent.com/18535853/77567135-ae692c00-6f01-11ea-8599-64653293370a.png)
![image](https://user-images.githubusercontent.com/18535853/77567158-b88b2a80-6f01-11ea-92e2-dc32e0ce4f68.png)
![image](https://user-images.githubusercontent.com/18535853/77567174-bde87500-6f01-11ea-83ba-c85baf639ff1.png)

**Comment by pklloveyou** [comment] 2020-03-25 17:35
No errors, what modules do you use?

**Comment by pklloveyou** [comment] 2020-03-25 17:40
I tried the Druid, too, and it's fine.

**Comment by kuramajssken001** [comment] 2020-03-27 03:25
> I tried the Druid, too, and it's fine.

This is not 100% likely to trigger.

**Comment by kuramajssken001** [comment] 2020-03-30 07:01
@pklloveyou @Viste @FrancescoBorzi 

https://youtu.be/Ml_NxhD-_Ok

**Comment by Helias** [comment] 2020-03-30 12:17
This is so strange, did you try with another client? without any addons?
just to be sure that the problem is related to the server

**Comment by kuramajssken001** [comment] 2020-03-30 12:33
without any addons @Helias

**Comment by Viste** [comment] 2020-03-30 14:13
Its china client?

**Comment by Viste** [comment] 2020-03-30 14:21
i try to reproduce it on last master with en_GB client today and write results here

**Comment by kuramajssken001** [comment] 2020-03-30 14:29
@Viste TW Client
Did you reproduce it successfully?

**Comment by aradep** [comment] 2020-11-29 08:43
Unable to reproduce on latest master. Looks like a problem with macros and not something core-related.

@kuramajssken001 Are you still experiencing this issue?

**Comment by FrancescoBorzi** [comment] 2020-11-29 10:23
closing, we can reopen it if we are able to reproduce the issue

**Closed by FrancescoBorzi** 2020-11-29 10:23 UTC
Labels: Invalid - CannotReproduce, Not confirmed
