### ISSUE TITLE
Odur Algalon Major BUG

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15539] opened 2023-03-22 10:42 UTC
### Current Behaviour

Odur BUG: If Ogalon destroys the group, the BOSS will not be refreshed, but can only stay in a daze

### Expected Blizzlike Behaviour

When the group is destroyed, the player's running corpse BOSS is refreshed normally and can rejoin the battle

### Steps to reproduce the problem

There are no steps, because BOSS will no longer appear after the group is destroyed

### Extra Notes

Sorry to bother you again. Previously, # 15382 was merged into # 15379. However, today, I saw that # 15379 has been repaired and closed. However, it seems that the issue with Algalon has not been repaired. It was just updated with the latest source code, but it still does not refresh after the Algalon group was destroyed. Please fix it for your convenience in the future. Thank you very much

### AC rev. hash/commit

AZEROTHCORE REV.4134C2DADA78+ 2023-03-14 06:35:16 +0000 (MASTER BRANCH) (WIN64.RELWITHDEBINFO,STATIC)

### Operating system

WINDOWS SERVER 2019

**Comment by Andyk10** [comment] 2023-03-25 06:14
I've encountered issues with many bosses resetting, including the Blood Council in ICC and Scourgelord Tyrannus in the Pit of Saron.

**Comment by yukijean** [comment] 2023-03-28 05:15
Can anyone help solve this problem? Thank you.

**Comment by heyitsbench** [comment] 2023-03-31 11:42
Why do you keep closing this?

**Comment by acidmanifesto** [comment] 2023-03-31 11:43
> Why do you keep closing this?

Its obvious. He wants visibility on the git feed.

**Comment by yukijean** [comment] 2023-03-31 11:45
The issue has been reopened

**Comment by heyitsbench** [comment] 2023-03-31 11:45
> The issue has been reopened

Now don't close it until it's been fixed. :)

**Comment by yukijean** [comment] 2023-03-31 12:01
OK THANK YOU

**Comment by yukijean** [comment] 2023-04-08 12:22
@heyitsbench Can you fix this problem

**Comment by yukijean** [comment] 2023-04-16 14:51
@Nyeriah Hello, may I ask if you have time to fix this issue recently? I have tried to fix it many times but it has failed, and now the ULD cannot fully experience it, which is very uncomfortable

**Comment by yukijean** [comment] 2023-04-17 02:45
@Si1ker Hello, may I ask if you have time to fix this issue recently? I have tried to fix it many times but it has failed, and now the ULD cannot fully experience it, which is very uncomfortable

**Comment by Nyeriah** [comment] 2023-04-17 03:42
Algalon despawns on evade and since he's a tempspawn he needs to be respawned externally by the instance script.

**Comment by yukijean** [comment] 2023-04-17 03:59
@Nyeriah I don't understand this very well, because I replaced the current CPP with the code in the previous Algalon CPP that can be refreshed normally, which has failed all the time. I ask you to repair it if you have time. The copy is incomplete, and the whole team is disappointed

**Comment by Tony931023** [comment] 2023-07-13 07:23
confirmed, it still happens that after dying the npc does not respawn and the bug event remains

**Comment by kerricsson** [comment] 2023-08-07 16:35
Still relevant at revision  AzerothCore rev. c866e17406f4 2023-08-06 23:02:54 +0200 (master branch) (Unix, Debug, Static) :
![изображение](https://github.com/azerothcore/azerothcore-wotlk/assets/104144379/17c39167-61e3-41cc-a988-7b3cc1b9ccd0)

**Closed** 2023-09-25 11:07 UTC
Labels: Confirmed, Instance - Raid - Northrend, 80
