### ISSUE TITLE
[RAID] UBRS First door is always open

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#608] opened 2017-09-07 13:35 UTC
**Description**:  If I recall, the large door at the end of the first section is supposed to be closed until all the mobs are dead.

**Expected**
> The first room is divided in 7 little chambers, in each of these chambers 4 orcs which you must defeat to unlock the runes. Once the seven runes are unlit, the door to the next room opens. 
http://wow-pro.com/dungeon_and_raid_guides/60_jame039s_upper_blackrock_spire_guide_ubrs

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by poszer** [comment] 2019-02-07 08:21
You are saved to instance, the doors will stay opened since you already clean the rooms, killing these creatures inside, even if you recall. Try to reset instance .i u all and give it a try ( The doors are always closed, until mobs from rooms are killed ).
Closing, cannot reproduce

**Closed by poszer** 2019-02-07 08:21 UTC
Labels: Good first issue, Instance - Raid - Vanilla, Priority - Trivial
