### ISSUE TITLE
Lady Jaina Proudmoore ( Hall of reflection) HC OR normal same behavior 

### ISSUE THREAD

**Issue by indigowowserver** [azerothcore/azerothcore-wotlk#15520] opened 2023-03-20 21:59 UTC
### Current Behaviour

Lady Jaina Proudmoore on last boss Lich king when you talk to her to start the fight .
she just walk slowly after and does not run like it should .

instance name : Hall of Reflection 
difficulty : hc or normal  

### Expected Blizzlike Behaviour

She should start running . not walking :D

you can see in the video below blizzlike behaviour

https://youtu.be/RRLmxq3Q4Gc?t=281

### Source

https://youtu.be/RRLmxq3Q4Gc?t=281

### Steps to reproduce the problem

1 - go to icecrown and then instance gate Hall of reflection
2- start the first boss fight and finish it and get to last encounter with lk
-3 talk to her at the end to start encounter and you will see that she is walking and not running when you start it .

### AC rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80032
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-144-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 291014951 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

windows 10 x64

**Comment by avarishd** [comment] 2023-03-20 22:07
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13080

**Closed by avarishd** 2023-03-20 22:07 UTC
Labels: Invalid-MissingHash/Commit
