### ISSUE TITLE
[Battered Hilt] BUG QUESTS

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2079] opened 2019-07-10 07:01 UTC
Description:  bug quests of https://www.wowhead.com/item=50380/battered-hilt

1. [The Halls Of Reflection] drop item bug , horde / alliance - drop failed!
2. [The Purification of Quel'Delar] drop item bug, horde / alliance - drop failed!
3. [A Suitable Disguise] full buged.

More of quests for this quest fix.

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/6db0a438d9dff3d1fab5f904657ed281f5dee6c7

OS: windows 2017

MODULES:
Anticheat

**Comment by spinzaku** [comment] 2019-07-10 08:56
All 3 quests works for me. using 5086af8
Check if characters are in raid group or not when they loot especially Quel'Delar

**Comment by poszer** [comment] 2019-07-10 09:21
All quests working, confirmed. @wowmane Could you stop opening random issues, which doesn't exist on AC, please. Closing this 
P.S Thanks @spinzaku for confirm

**Closed by poszer** 2019-07-10 09:21 UTC
Labels: Invalid - CannotReproduce
