### ISSUE TITLE
[Midsummer Festival] Torch Tossing quest is repeatable/daily

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6623] opened 2021-06-28 05:32 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/956

##### CURRENT BEHAVIOUR:

Torch tossing quest is repeatable daily (https://wowgaming.altervista.org/aowow/?quest=11731).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Torch tossing quest should be only doable 1 time, then opening up the daily quest More Torch Tossing (https://wowgaming.altervista.org/aowow/?quest=11921)

##### SOURCE:

https://tbc.wowhead.com/quest=11731/torch-tossing#comments
##### STEPS TO REPRODUCE THE PROBLEM:

1. Complete Torch Tossing and More Torch Tossing quests
2. Check in next day and see Torch Tossing Available again, but not More Torch Tossing

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 53ab534) :

![WoWScrnShot_062821_082704](https://user-images.githubusercontent.com/82579073/123585017-17b5aa00-d7eb-11eb-9760-042df3876477.jpg)
![WoWScrnShot_062821_082723](https://user-images.githubusercontent.com/82579073/123585043-27cd8980-d7eb-11eb-9dc5-642e0a2f980c.jpg)
![WoWScrnShot_062821_082742](https://user-images.githubusercontent.com/82579073/123585067-361ba580-d7eb-11eb-9b37-968b1a42aa88.jpg)
![WoWScrnShot_062821_082805](https://user-images.githubusercontent.com/82579073/123585101-45025800-d7eb-11eb-9345-22eee818b2ee.jpg)

**Comment by FrancescoBorzi** [comment] 2021-09-03 10:51
> I can't confirm it.

can any @azerothcore/bug-triaging help here? 

also we need to close the original CC issue if needed

**Comment by markvetx** [comment] 2021-09-21 10:22
From #6497 - Hey, guys. Brewfest started on AC yesterday, and there is the same bug with seasonal quests. Basically, when you're completing a non-repeatable seasonal quest, you're getting a reward and quest is completed.. but after logging out and in you can take (or sometimes just turn-in the quest) and get your reward repeatedly.

**Comment by Kitzunu** [comment] 2021-12-05 19:12
Closing as it wasnt reproduced after Ultranix couldn't reproduce the issue.

If there are other issues not tied to this one they should be opened in a separate issue

**Closed by Kitzunu** 2021-12-05 19:12 UTC
Labels: Quest, ChromieCraft Generic, Not confirmed
