### ISSUE TITLE
Server crash via SQL error

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2459] opened 2019-11-19 20:49 UTC
The player tried to withdraw money from the bank. And the server crashed.

**Server_2019-11-19_02-34-27.log**
2019-11-19 20:00:01 ERROR: Error while parsing SQL. Core fix required.

**SQLdriver.log**
```
2019-11-19 20:00:01 SQL: An error occurred formatting string "INSERT INTO log_money VALUES(%u, %u, "%s", "%s", %u, "%s", %u, "<GB WITHDRAW> %s (guild id: %u, members: %u, new amount: %I64u, leader guid low: %u, char level: %u)", NOW())" : invalid type specifier
2019-11-19 20:00:01 ERROR: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'An error occurred formatting string "INSERT INTO log_money VALUES(%u, %u, "%s", ' at line 1
```

##### STEPS TO REPRODUCE THE PROBLEM:
1. Open Guild-Bank
2. Withdraw > 10 Gold
3. SQL error, server shutdown.

##### EXTRA NOTES:
SThe SQL statement at Guild.cpp never changed and worked fine except for this point.

##### BRANCH(ES):
master ded3bd8900e1+

##### OPERATING SYSTEM:
 Windows 7/10, MySQL server ver: 5.7.21

SQL-table has old records made by this statement, and then it was recorded fine:
(ip censored)
81	807	Antony 192.***.***.118	0		1000000	<GB WITHDRAW> Ultra Guild (guild id: 19, members: 11, new amount: 13218292, leader guid low: 807, char level: 80)	2019-11-11 14:29:58

**Comment by Bogir** [comment] 2019-11-19 20:51
**OPERATING SYSTEM:**
<!-- Windows 7/10, MySQL server ver: 5.7.21


SQL-table has old records made by this statement, and then it was recorded fine:
(ip censored)
81	807	Antony 192.***.***.118	0		1000000	<GB WITHDRAW> Ultra Guild (guild id: 19, members: 11, new amount: 13218292, leader guid low: 807, char level: 80)	2019-11-11 14:29:58

**Comment by Bogir** [comment] 2019-11-19 20:57
Reproduced carefully by me. 
Only English characters at my nickname  (Admin)
Guid 8
Guild 2
IP ordinary 192.xxx.xxx.125
Amount 11 Gold

(Statement takes variables: **session->GetAccountId(), player->GetGUIDLow(), player->GetName().c_str(), session->GetRemoteAddress().c_str()**)

2019-11-19 23:36:11 SQL: An error occurred formatting string "INSERT INTO log_money VALUES(%u, %u, "%s", "%s", %u, "%s", %u, "<GB WITHDRAW> %s (guild id: %u, members: %u, new amount: %I64u, leader guid low: %u, char level: %u)", NOW())" : invalid type specifier
2019-11-19 23:36:11 ERROR: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'An error occurred formatting string "INSERT INTO log_money VALUES(%u, %u, "%s", ' at line 1

**Comment by Helias** [comment] 2019-11-19 21:18
I can't reproduce the bug, I'm on Ubuntu (linux) 18.04.3 LTS, are you using any modules?

**Comment by Bogir** [comment] 2019-11-19 21:25
Mods was added 7 months ago 

mod-anticheat-master
mod-congratsonlevel
mod-gmsecurity-master
mod-learnspells-master
mod-npcbuffer
mod-transmog-master

**Comment by Bogir** [comment] 2019-11-19 21:32
![изображение](https://user-images.githubusercontent.com/25766571/69188269-42c71a80-0b2d-11ea-9171-827af279b504.png)

**Comment by Helias** [comment] 2019-11-19 22:04
another user is having a similar error, could you try to revert this commit?

https://github.com/azerothcore/azerothcore-wotlk/commit/a3206c56dc7b2e7421d2dfaee56bad0a195d6c58

**Comment by Helias** [comment] 2019-11-19 22:14
If you can try also this:
- open calendar
- create a new event
- invite a player

the server crashes?
a use reported me this today but I can't reproduce the bug, maybe it's a Windows problem?

**Comment by Helias** [comment] 2019-11-19 22:17
I just tested your issue in the test server of my friend.

But I still can't reproduce it on Linux.

**Comment by Bogir** [comment] 2019-11-19 22:26
yes, the server crashed after inviting the player to a new event
![изображение](https://user-images.githubusercontent.com/25766571/69191919-8ec98d80-0b34-11ea-9df9-86727873dc62.png)

Perhaps it’s the case of the MySQL server for Windows ?

**Comment by Viste** [comment] 2019-11-19 22:32
> another user is having a similar error, could you try to revert this commit?
> 
> [a3206c5](https://github.com/azerothcore/azerothcore-wotlk/commit/a3206c56dc7b2e7421d2dfaee56bad0a195d6c58)

and how its related ?

**Comment by Helias** [comment] 2019-11-19 23:20
I reverted this commit https://github.com/azerothcore/azerothcore-wotlk/commit/aac3648b5c92c9d47431f45b36184afd6666a989
and everything seems to work.

@Winfidonarleyan, pls, take a look on this isssue.

Another details is that I'm working on Windows 10 with mariaDB.

@Bogir are you using mariadb?

**Comment by Viste** [comment] 2019-11-19 23:48
strange thing @Winfidonarleyan use windows and mariadb X_X

**Comment by Bogir** [comment] 2019-11-20 00:28
Everything is fine now

**Comment by Bogir** [comment] 2019-11-20 00:29
Everything is fine now

**Comment by Helias** [comment] 2019-11-20 08:31
@Bogir how did you solve?

**Comment by Bogir** [comment] 2019-11-20 09:04
@Helias 
I reverted this commit aac3648+

**Comment by Helias** [comment] 2019-11-20 10:41
This issue should remain opened until the bug is fixed on master.

**Comment by solidmaxtor** [comment] 2019-11-20 13:36
ubuntu 16 and ubuntu 18 work fine no crash.

**Comment by Helias** [comment] 2019-11-20 14:24
Who got this kind of bug test your core with this PR https://github.com/azerothcore/azerothcore-wotlk/pull/2460

I tried to reproduce the bug on linux using mariadb but I didn't succeed.

@Bogir, test it if you can, so don't revert that commit and add the PR commit to your local server :pray:

**Comment by Bogir** [comment] 2019-11-20 15:32
PR #2460 
![изображение](https://user-images.githubusercontent.com/25766571/69252482-1c07f300-0bc4-11ea-91a5-fc8269b4cb6f.png)

**Closed** 2019-11-22 15:42 UTC
Labels: Confirmed, Priority - Critical
