### ISSUE TITLE
Drowning in Maraudon

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10271] opened 2022-01-20 16:18 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2836

There is a place in Maraudon where you can get drown on a floor.

![image](https://user-images.githubusercontent.com/62797536/150374241-1bb5782f-e4c7-4a85-87c0-2ef0624a3f24.png)
Breath bar appears.

![image](https://user-images.githubusercontent.com/62797536/150374351-f02aeedb-25ac-48d7-ad9d-cc3c3ffdc69d.png)
Party member died due to drowning.

Tester:

The issue is confirmed.

![WoWScrnShot_012022_171232](https://user-images.githubusercontent.com/62797536/150378241-e08f9c46-8fd2-4bbf-82d3-110027400b41.jpg)

### Expected Blizzlike Behaviour

You should not drown at this position.

### Steps to reproduce the problem

Original report:
1. Go to the place on the map

Tester:
1. `.go creature 26946` - this NPC stands right besides the corrupt area

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by LukasVolgger** [comment] 2022-01-20 17:56
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/2437

**Closed by LukasVolgger** 2022-01-20 17:57 UTC
Labels: Confirmed, 40-49
