### ISSUE TITLE
I have a small fix, but I do not know how to PR

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/azerothcore-wotlk#778] opened 2018-02-02 08:06 UTC
I have a small fix, but I do not know how to PR, I hope also can make some contribution to AzerothCore!

**Comment by DarkmoonRabbit** [comment] 2018-02-02 08:14
MC NO.1 BOSS anger skills can not disperse the problem....
If you can PR, please fix it and submit it.
PS: Thank you, "big boobs" for my help!

/src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_magmadar.cpp
 
 enum Spells
 {
-    SPELL_FRENZY        = 19451,
+    SPELL_FRENZY = 23128,

**Comment by talamortis** [comment] 2018-02-02 08:43
Im sorry i dont understand the issue with this boss why are you changing the spell?

**Comment by DarkmoonRabbit** [comment] 2018-02-02 08:50
@talamortis This skill(19451) can not be "Tranquilizing Shot" to disperse.

**Comment by talamortis** [comment] 2018-02-02 09:15
please try this SQL 

INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (19451, 23128 0, 'Enrage for boss_magmadar');

**Comment by BarbzYHOOL** [comment] 2018-02-02 11:59
Darkmoonrabbit, the wiki explains how to PR, that's how I made my first PR and I added a bit more details so you should get it.

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request

**Comment by ShinDarth** [comment] 2018-02-02 12:53
also you can find really a lot of generic information about how to use `git`, `GitHub` and PRs in general on google

**Comment by talamortis** [comment] 2018-02-07 05:35
has anyone tried the sql? if its working how it should be with the sql Ill push fix.

**Comment by DarkmoonRabbit** [comment] 2018-02-15 02:05
@talamortis
I test .

**Comment by talamortis** [comment] 2018-02-15 06:33
and did it work correctly?

**Comment by DarkmoonRabbit** [comment] 2018-02-16 03:28
@talamortis
Still not, the implementation of sql statement, the boss will appear at the same time two buff.

**Comment by ShinDarth** [comment] 2018-02-16 09:05
guys, feel free to keep the discussion but I'm closing this since it's not a bug

**Closed by ShinDarth** 2018-02-16 09:05 UTC
