### ISSUE TITLE
[Warlock] Pet disappears sometimes when mounting up

### ISSUE THREAD

**Issue by LordArcanine** [azerothcore/azerothcore-wotlk#10545] opened 2022-02-05 17:30 UTC
### Current Behaviour

When you mount pets dismiss and when you unmount they dont come back, this is not blizzlike because warlock use soul shards to summon his pets.

### Expected Blizzlike Behaviour

to re summon the current pet when you unmount

### Steps to reproduce the problem

1.- Summon a pet as a warlock
2.- Mount
3.- Unmount

### AC rev. hash/commit

0b02ba87fc60d538b78a401604eb8955b895515f

### Operating system

Ubuntu 20.04

### Custom changes or Modules

mod-morphsummons

**Comment by Scortas** [comment] 2022-02-07 16:24
Hey I found a temporary "fix". Closing and starting the server fixes it for me.

Wonder if there is a gm command for instant spawning of pets to remedy this if I don't have the opportunity to restart server.

**Comment by temperrr** [comment] 2022-02-26 06:41
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I get random episodes where my pet wont spawn after I dismount so have to resummon it over and over.
Had 2 periods today where it didnt work first was in wsg and second was just in the open world - then suddenly out of nowhere it started working again. Then I went for dinner and came back on and again it does not work.

### Expected Blizzlike Behaviour

Pet should spawn if it is summoned before u use mount and then dismount - works sometimes.

### Source

_No response_

### Steps to reproduce the problem

I cant reproduce - seems random

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/2852

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4


### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)


### Customizations

None


### Server

ChromieCraft

**Comment by Nefertumm** [comment] 2022-03-05 19:56
Fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/acd3ed8759477e6059b31f88377a790f3a0d8133

**Closed by Nefertumm** 2022-03-05 19:56 UTC
Labels: Confirmed, ChromieCraft Generic, Class - Warlock, Priority-Medium
