### ISSUE TITLE
(Vault of Archavon): Archavon the Stone Watcher

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3183] opened 2020-07-09 21:35 UTC
https://www.wowhead.com/npc=31125/archavon-the-stone-watcher

**SMALL DESCRIPTION**:
When this NPC grabs and holds the character in his hand, he immediately begins to use the ability (although it should not) https://www.wowhead.com/spell=58678/rock-shards
Some strange bug also happens. He lets go of the character and the character stands under him and cannot move around two seconds, although there is no debuff.
He also uses the ability https://www.wowhead.com/spell=58678/rock-shards too often.

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Knindzagxg** [comment] 2020-07-17 17:41
Grip and Shards are supposed to happen, and that's only mechanic why tanks have to act quickly.

Same for the Shards (Beside jump) - There's nothing wrong with mechanic, since while doing it in raid everyone have to spread and "kite" it away from others.

Tip: Do not test boss fights alone, cause multiple mechanics will happen to you only, since there are no others targets around.

**Comment by wowissues** [comment] 2020-07-17 17:59
> Grip and Shards are supposed to happen, and that's only mechanic why tanks have to act quickly.
> 
> Same for the Shards (Beside jump) - There's nothing wrong with mechanic, since while doing it in raid everyone have to spread and "kite" it away from others.
> 
> Tip: Do not test boss fights alone, cause multiple mechanics will happen to you only, since there are no others targets around.

I checked with 3 people

**Comment by BarbzYHOOL** [comment] 2020-07-20 16:43
wowissues, give us concrete proofs that he's not acting how he should plz else we close the issue

**Comment by FrancescoBorzi** [comment] 2020-11-28 19:29
closing as this hasn't been confirmed. If it will be confirmed, it can be reopened.

**Closed by FrancescoBorzi** 2020-11-28 19:29 UTC
Labels: Invalid - Intended/WontFix/Blizzlike

**Comment by Voxstrasza** [comment] 2020-11-28 19:32
here's a video from 2009

https://www.youtube.com/watch?v=7F86rdQRiBs&ab_channel=WoWAholics101
