### ISSUE TITLE
Instance pooling behavior works in an unexpected manner.

### ISSUE THREAD

**Issue by neifion-00000000** [azerothcore/azerothcore-wotlk#12376] opened 2022-07-13 20:35 UTC
### Current Behaviour

It seems like pooling in instances is created one time rather than each instance having its own pooling.  On server reboot, there will be a new version.

I tested this by using multiple characters in ZG to check out herbs / mines / spawns I've pooled.

### Expected Blizzlike Behaviour

Every time you enter a new instance it should have pooling rerolled.

### Source

Blizzard servers functionality.

### Steps to reproduce the problem

1. Create a character and goto ZG, look at pooled objects
2. Leave the instance and reset or create a new character and re-enter
3. See they have not changed positions

### AC rev. hash/commit

35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

W10

**Comment by neifion-00000000** [comment] 2022-07-29 17:59
this is confirmed to also apply to creatures

**Comment by heyitsbench** [comment] 2022-10-24 21:15
Duplicate of #6658, closing.
❤️

**Closed by heyitsbench** 2022-10-24 21:15 UTC
Labels: Confirmed
