### ISSUE TITLE
[Sunken Temple] Idol of Hakkar gossip

### ISSUE THREAD

**Issue by pop-pig** [azerothcore/azerothcore-wotlk#6965] opened 2021-07-15 19:48 UTC
### Current Behaviour

The Idol of Hakkar ( https://wowgaming.altervista.org/aowow/?object=148838 ) inside the Sunken Temple (lowest level, near Atal'Alarion ) currently has a gossip option (you can "right click to interract") even if you don't have the quest Secret of the Circle ( https://wowgaming.altervista.org/aowow/?quest=3447 ).
The gossip chat will then display "Greetings, <character name>".
![WoWScrnShot_071521_213329](https://user-images.githubusercontent.com/81818678/125847569-11489cd9-57fa-4e23-8803-9f4317dea163.jpg)

### Expected Blizzlike Behaviour

I'm not sure on this, but I don't think the Idol should be clickable (no wheelie interaction mouse icon) if you don't have the quest (be it because you didn't take it, or you completed it before).

### Steps to reproduce the problem

1. ".tele st"
2. ".go c 34521" will teleport you to Atal'alarion
3. Click the 6 snake statues in order (N - S - SW - SE - NW - NE) for the Idol of Hakkar to appear
4. Right click the Idol

### AC rev. hash/commit

AzerothCore rev. 4d6766d6a997+ 2021-07-15 15:52:19 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by Kitzunu** [comment] 2021-07-16 23:32
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6902

**Closed by Kitzunu** 2021-07-16 23:32 UTC
Labels: 40-49, Instance - Dungeon - Classic
