### ISSUE TITLE
[Molten Core] Lucifron Dominate Mind can't be dispelled by Paladin

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9773] opened 2021-12-19 09:01 UTC
### Current Behaviour

Paladin Cleanse can't dispel Dominate Mind.

### Expected Blizzlike Behaviour

Dominate Mind should be dispellable by both Priest Dispel and Paladin Cleanse.

### Source

https://classic.wowhead.com/guides/lucifron-molten-core-strategy-wow-classic

### Steps to reproduce the problem

Go to lucifron
get mind controlled by adds
try to dispel

### AC rev. hash/commit

de49c3bead5f+ 

### Operating system

Linux

### Custom changes or Modules

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Eronox** [comment] 2021-12-21 22:45
The issue seems to be caused due to the fact that the targeted player is hostile, making a fail check before even reaching the part of checking the auras.  

Frankly, I don't have any good idea on how to solve this 🤷‍♂️

**Comment by Nyeriah** [comment] 2021-12-21 22:50
Yes, unlike priest's dispel paladins got TARGET_UNIT_TARGET_ALLY as valid target
Mind Controlled players are not a valid **ALLY**
So it cannot be cast on them and we cannot change the target type

The spell cast fails during the preparation fase: it checks and finds that the target is hostile and doesn't execute any check past that point.

**Comment by temperrr** [comment] 2021-12-22 14:24
Well, we had the same issue with Priest before  (See https://github.com/azerothcore/azerothcore-wotlk/pull/9689)

**Comment by Nyeriah** [comment] 2021-12-22 14:45
Yes, but as I said, priets got a different target type. @UltraNix do you have any info on this you could share with us? Or are we correct to think this works as intended?

**Comment by temperrr** [comment] 2021-12-22 15:04
It could very well eb a change is behaviour from vanilla to wotlk, not sure about that

**Comment by UltraNix** [comment] 2021-12-22 15:31
@Nyeriah Not fixed by 1cc9ea83a?

**Comment by Nyeriah** [comment] 2021-12-22 15:33
> @Nyeriah Not fixed by [1cc9ea8](https://github.com/azerothcore/azerothcore-wotlk/commit/1cc9ea83abb26333004ba128a5368fae7304a507)?

Only priest dispel, paladin's cleanse no, check my comment at https://github.com/azerothcore/azerothcore-wotlk/issues/9773#issuecomment-999146540 -- it's what I gathered so far while testing things with Eronox

**Comment by UltraNix** [comment] 2021-12-22 15:37
And what error is sent? "Nothing to dispel" or "Target is invalid"?

**Comment by Nyeriah** [comment] 2021-12-22 15:42
> And what error is sent? "Nothing to dispel" or "Target is invalid"?

Nothing to dispell, but that's the only error ever sent. "Target is invalid" is not ever used with this spell

**Comment by Nyeriah** [comment] 2021-12-22 16:07
I forgot to mention: we tried changing TARGET_ALLY to TARGET_ANY to test and it worked, that's how we knew for sure it was failing during the target check in preparation phase

**Comment by UltraNix** [comment] 2021-12-22 16:56
This error is handled (in that case) by client, so there is nothing I can do with it.

**Closed by UltraNix** 2021-12-22 16:56 UTC
Labels: Confirmed, 60, Instance - Raid - Vanilla, Priority-Medium
