### ISSUE TITLE
Mining/Herb Node Distance Fix [$150]

### ISSUE THREAD

**Issue by heyaapl** [azerothcore/azerothcore-wotlk#2510] opened 2019-12-17 19:11 UTC
##### SMALL DESCRIPTION:
I've been working for the better part of four months cleaning up all GOB nodes (Ore, Herbs, Chests, Quest Objects, etc) to reduce the over-spawning issues by remapping the entire GOB Pool tables. However, I'm now running into issues with how AzerothCore spawns in new nodes. It arbitrarily spawns nodes at the rate defined in the database, without Blizzlike considerations for reducing double-spawning 2 Copper Ore nodes next to each other.

##### EXTRA NOTES:
At a high-level, I'm thinking this would require either an additional table or single column to the existing Pool_Template table that would store a minimum distance that must exist between node spawning. A default value of 0 keeps the current spawning system the same, while a value of say 15 would require 15 points would require a distance of 15 XYZ coordinates is required before a node could spawn next to it. This will help (a) reduce the number of groupings needed in the database to better control spawn rates of nodes (b) allow for easier maintenance and control for server owners who would like to control the spawn rates of nodes.

This will require both core changes and database changes. I can assist with the SQL updates but will need assistance with the core edits and testing.

##### BRANCH(ES):
master

**Comment by Ali-Khazaee** [comment] 2019-12-17 20:36
As i understand you want to make object do not get spawned near each other as minimum distance 15 yard ?

**Comment by heyaapl** [comment] 2019-12-17 20:40
> As i understand you want to make object do not get spawned near each other as minimum distance 15 yard ?
This should be configurable by Pool_Template, as depending on the GOB in question, it may change. Also to clarify, I think for this we should avoid using in-game yards and instead a distance of XYZ from each spawn point. But for example, 15 points away makes sense for say Copper Ore nodes in Durotar, but will need to be different for the Christmas Present GOBs below the Christmas Tree or other Quest GOBs in small spaces.

**Comment by Ali-Khazaee** [comment] 2019-12-17 20:49
Those node spawn points are took from game so they shouldn't get changed also in retail i have seen object get spawns near each other but not in same point, so this shouldn't be configurable by Pool_Template, They should not spawn in same point twice right ?

**Comment by heyaapl** [comment] 2019-12-17 21:21
This is part of a larger issue with how nodes are spawning. The example I gave is literally just an example of how the functionality should be built, not the actual data side, which will be in control of node spawning. Double-spawning of the same GOB doesn't happen, but two GOBs which may spawn near, but not exactly on top of eachother is present, and is not a behavior you'll see in a Blizzard server. A comprehensive overhaul of this might be in order, but this gives us enough controls to tweak it to make it as blizzlike as possible, while also enabling server administrators the ability to have greater control over spawn rates.

**Comment by FALL1N1** [comment] 2020-11-15 00:20
Can anyone test if it's working properly in TrinityCore? I can just backport it from there.

**Comment by BarbzYHOOL** [comment] 2021-01-17 18:08
@kitzunu you have a tc to test? lol

**Comment by Kitzunu** [comment] 2021-01-17 18:10
How do I test it? 

Also TC has a new pooling system if I remember correctly

**Comment by BarbzYHOOL** [comment] 2021-01-17 18:20
Need to verify if on TC this issue is present or not. They over spawn, if i recall in searing gorges. Oh yeah check here https://github.com/azerothcore/azerothcore-wotlk/issues/2211

**Comment by UltraNix** [comment] 2021-04-29 08:06
I think that the main problem here is that many nodes/veins/herbs are not pooled together or pooled wrongly.

**Comment by UltraNix** [comment] 2021-04-29 08:08
@heyaapl  I think that the main problem here is that many nodes/veins/herbs are not pooled together or pooled wrongly.
I can provide an extra parameter to pool_template table to define minimal distance (which can be changed whenever you want) between spawns from the same pool.

**Comment by UltraNix** [comment] 2021-04-29 08:08
@heyaapl  I think that the main problem here is that many nodes/veins/herbs are not pooled together or pooled wrongly.
I can provide an extra parameter to pool_template table to define minimal distance (which can be changed whenever you want) between spawns from the same pool.
What do you think @FrancescoBorzi ?

**Comment by FrancescoBorzi** [comment] 2021-04-29 13:38
> @heyaapl I think that the main problem here is that many nodes/veins/herbs are not pooled together or pooled wrongly.
> I can provide an extra parameter to pool_template table to define minimal distance (which can be changed whenever you want) among spawns from the same pool.
> What do you think @FrancescoBorzi ?

cc @Hacki95 @Zoidwaffle who have recently worked with pooling (I haven't)

**Comment by Hacki95** [comment] 2021-04-29 15:29
Minimum distance would be great to have. And yes you are right @UltraNix most zones aren't pooled at all, I am currently working on this. 

One thing about the minimum distance, certain zones are missing many spawns right now so in certain cases there might be no way around spawning them next to each other. I think the check should work like this: Try to spawn everything with the mindistance in mind, if that doesn't work spawn them the old way.

If you can, maybe this bug could be fixed as well with one PR: https://github.com/azerothcore/azerothcore-wotlk/issues/5523

**Comment by UltraNix** [comment] 2021-04-29 19:18
@Hacki95 So you prefer spawning 2 nodes next to each other than spawning only one node, if these two are the only nodes in the zone, right?

**Comment by Hacki95** [comment] 2021-04-29 21:31
yes I would say this makes sense as its an error on our part at the moment because for some zones we have too few spawnpoints.

**Comment by UltraNix** [comment] 2021-04-30 09:32
Hmm, but pools are not connected to zones - it might be undoable.
I can add a parameter and set defualt value (e.g. 2 or 3 yards). Objects will not be spawned on top of each other, but if the count of spawned objects are less than the limit from the pool, the system will populate it with the "duplicated ones" to reach that limit. What do you think?

**Comment by Hacki95** [comment] 2021-04-30 09:43
Does it matter if they are? The thing I was keeping in mind was zones like #5522. There are only 6 possible spawn points and 5 should spawn. If there were a case there where 2 chests are near each other they should probably still spawn if there are no other options.

Let me try to contact a few guys and ask around what their opinions are. I will get back at you tomorrow maybe earlier, the people should be online in the evening.

**Comment by UltraNix** [comment] 2021-04-30 09:51
> I think its pretty rare that zones overlap, and the pools normally just combine objects from one zone anyway.

Not always and I have to cover all the possibilites (e.g. quests or other pools that are not filled based on zone).

> There are only 6 possible spawn points and 5 should spawn.  If there were a case, where 2 chests are near each other they should probably still spawn if there are no other options.

In that case, the 6th will not spawn - limit is 5. But in case where they are 2 spawn points that are duplicated --> 4 chests spawn and 1 additional on top of these 2 left (still 5 chests are spawned) (if I understand correclty). But still - the problem with these duplicated spawns comes from database.

**Comment by Hacki95** [comment] 2021-04-30 10:06
You are right, I am definitely trying to get some more input on this. I will try to redirect some people to the discussion here who might know a thing or two.

**Comment by 55Honey** [comment] 2021-04-30 10:16
I like the idea of adding a min_distance column. We can set them all to 10m for a start and adjust them to 5 or 15 per zone, if it doesn't match the desired distance, e.g. mass-spawns of Grave Moss.

There should definitely be WotLK specialists involved in this.

**Comment by Hacki95** [comment] 2021-05-01 21:29
Sorry for not getting back earlier!

So I spoke to @T1ti and it seems like the proper way to not make nodes spawn to close too each other is by simply pooling smaller pools into a larger one. 

I am not exactly sure we need the mindistance feature at all, but I want to do some additional testing and research to make sure there are not any edge cases where this feature might still be useful after all.

For now I would say don't begin to work on it yet @UltraNix. I pointed some more people to this discussion but so far it doesn't look like there are many people with an opinion about this feature.

**Comment by UltraNix** [comment] 2021-05-02 05:39
@Hacki95 I agree. This is problem with DB and should be fixed by correcting entries in database.

**Comment by Gultask** [comment] 2022-10-29 00:37
For anyone's who's curious, here's how this is solved:
https://github.com/cmangos/classic-db/commit/8650faa2c4c9f8662c42e06f8943e9e7ab505294

In Retail, if you look closely you can see that are individual pools for each node (personally confirmed it for ores, at least). So most of the time there aren't any ores close to each other. It's not impossible to see "clumping" in Retail, however, as some individual pools might happen to spawn their nodes really close to each other, it's inevitable and I've seen many examples of that.
Are individual pools an universal truth to blizzlike spawns? I don't think so. There *seems* to be exceptions to it.

Neifion's work like here: https://github.com/azerothcore/azerothcore-wotlk/pull/13573 has been phenomenal in progressing this long-standing issue with AC.

**Comment by neifion-00000000** [comment] 2022-10-29 09:47
yup just echoing to agree with gultask, and while for sanity purposes the linked method is prolly most logical to work with, on a fully solved or even estimated system you don't need the pools inside of pools since only 1 object will spawn in pools anyway.  Obviously they're a necessary stepping stone though since no one has time for that level of tedium though.

**Comment by Kitzunu** [comment] 2023-10-22 02:15
Spoke with Neifion and Bench, this is invalid

**Closed by Kitzunu** 2023-10-22 02:15 UTC
Labels: DB, Help Wanted, Bounty, Needs Developer
