### ISSUE TITLE
Battered Hilt Questline: Tempering the Blade

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3850] opened 2020-12-06 01:12 UTC
##### CURRENT BEHAVIOUR:

It's not possible to temper the blade since when you click it nothing happens.

![image](https://user-images.githubusercontent.com/60325009/101268810-910e8200-375f-11eb-9190-cbdf96904540.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://www.youtube.com/watch?v=ynwZseSrbK8&ab_channel=TheForgeNetworkHQ

##### STEPS TO REPRODUCE THE PROBLEM:

1. .gm on
1. .go 201736
3. q a 24476
4. Right click the usable item

##### AC HASH/COMMIT:

d4b71dc70d3f

**Comment by LukasVolgger** [comment] 2020-12-06 08:21
This is not an issue, u have to use the blade when the Boss is alive.

**Comment by LukasVolgger** [comment] 2020-12-06 08:22
If you use the blade when the Boss is alive it's working

**Comment by Hacaw** [comment] 2020-12-08 20:08
Based on the first 2 comments https://www.wowhead.com/quest=24476/tempering-the-blade#comments you should be able to use the item after the boss is killed.

**Comment by Kitzunu** [comment] 2020-12-10 17:45
probably spell target too narrow or something

**Comment by wizzymore** [comment] 2020-12-27 02:04
It doesn't work for you because you killed the boss without attacking it.

It is usable with the Crucible of Souls, and to get this one spawned you need to enter in combat with the boss.

The only think i can confirm here is that the item can be used without having the boss killed which i will come with a fix for.

**Comment by wizzymore** [comment] 2020-12-27 02:10
Also you can check this:
https://www.wowhead.com/quest=24476/tempering-the-blade#comments:id=911172

**Comment by LukasVolgger** [comment] 2020-12-27 12:16
Thx @wizzymore for your feedback! In that case we can close this issue as everything is fine here like in the given yt video.

**Closed** 2020-12-27 12:17 UTC
Labels: Confirmed
