### ISSUE TITLE
Base health (HP) and attributes (stats) are wrong

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#737] opened 2017-12-12 20:10 UTC
**Description**:
Stats are completely screwed. Kyrion reported it but nobody checked it but it's extremely problematic.

**Current behaviour**:
Look at the stats here (HP and agility/str/etc)
https://cdn.discordapp.com/attachments/284323424032129024/390231198951145487/bugged_stats_29th_october.png
This is for a level 80 on 29th of october revision. Almost no health and the stats are not the same as before.

These are better stats on 12th of october
https://cdn.discordapp.com/attachments/284323424032129024/390231382628106240/ALMOST_correct_stats_12th_october.png

It's much better but we can still note that the rogue has too high HP compared to what WOWWIKI says (link below)

Another bug is that a level 1 undead rogue has 22 stamina instead of 21 stamina (maybe this is related to the too high HP)

**Expected behaviour**:

What it should be: http://wowwiki.wikia.com/wiki/Base_health
http://wowwiki.wikia.com/wiki/Rogue

**Steps to reproduce the problem**:

1. Just make a level 80 character
2. 
3. 

**Branch(es)**: master

**AC hash/commit**:  a2170f218b85bc534062835eb8d0dcb2b35ea9f0

**Operating system**:  
debian 8

Modules: AnticheatModule mod-duelreset mod-gmsecurity mod-random-enchants VASAutoBalanceModule
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by BarbzYHOOL** [comment] 2017-12-12 20:11
I put "critical" label because the guys running a live server will be in real trouble with that bug.

**Comment by Yehonal** [comment] 2017-12-13 00:53
Base health is health without stamina. So if you add stamina to the base health you get 8k for rogue

**Comment by Yehonal** [comment] 2017-12-13 01:01
Anyway, about 29th october issue, can't confirm

![image](https://user-images.githubusercontent.com/147092/33916431-17765474-dfa9-11e7-91f8-97bf5c38df4a.png)

i've latest revision and rogue has 8484 hp....with 106 stamina that means 880 hp bonus on base health 

in fact 8484 - 880 = 7604 that is the base health of rogue...

So if anyone has the same issue, i should close it or you've to provide a better way to replicate this bug.

**Comment by talamortis** [comment] 2017-12-13 18:55
![image](https://user-images.githubusercontent.com/6143065/33956671-2d6a012a-e037-11e7-9d33-a24c5e5ab5e2.png)

i think @BarbzYHOOL is correct

**Comment by Yehonal** [comment] 2017-12-13 19:04
I can't reproduce it. I'll try on a fresh rev later

**Comment by talamortis** [comment] 2017-12-13 19:05
this is with latest rev 👍

**Comment by BarbzYHOOL** [comment] 2017-12-13 19:26
Kyrion also reported it before me in the chat (kyrion = nemepy here)

But you were right for the second bug I reported, it's just that wowwiki is not clear about base health without stamina I guess (considering that stamina only gives health, it doesn't seem to make much sense to separate it but ok). Though we have 1 more stamina at lvl 1 xD

**Comment by talamortis** [comment] 2017-12-13 19:35
![image](https://user-images.githubusercontent.com/6143065/33958587-b1fa7d66-e03c-11e7-97bf-4dcdfbf87663.png)
this is from an earlier rev i think it was from when i fixed the crab disguise

**Comment by BarbzYHOOL** [comment] 2017-12-13 19:40
I quickly checked the (superficial check of few rows) these tables player_classlevelstats and player_levelstats and they are the same.

**Comment by BarbzYHOOL** [comment] 2017-12-13 19:48
Talamortis is on windows
I'm on linux

Also we don't have the same modules (no module in common), my modules:
AnticheatModule mod-duelreset mod-gmsecurity mod-random-enchants VASAutoBalanceModule

**Comment by talamortis** [comment] 2017-12-13 19:51
ive reset my conf file just to make sure its not that causing the error

**Comment by talamortis** [comment] 2017-12-13 19:53
![image](https://user-images.githubusercontent.com/6143065/33959419-4becdfac-e03f-11e7-9b0c-e936dbe1e74c.png)
can confirm its something todo with the conf file

**Comment by BarbzYHOOL** [comment] 2017-12-13 20:12
Ok, thanks to talamortis I identified the error.

The error comes from the option:
MaxPlayerLevel = 29

The max health will be capped at 29.
Very lucky that talamortis had this setting in his conf too.

Now this could be fixed or something added in the conf to explain it.
Also with this setting all summoned mobs will be level 31 (or 32), which can lead to false issue report.

**Closed** 2017-12-21 11:17 UTC
Labels: Priority - Low

**Comment by BarbzYHOOL** [comment] 2017-12-22 15:40
I know it's really not important now we know how to avoid it but the issue will be reported by other people and waste a bit of their time.

**Comment by ShinDarth** [comment] 2017-12-24 14:04
everyone should first look for existing issues before opening a new one, so one is free to comment this issue instead of wasting time in opening another
