### ISSUE TITLE
Arena creation & charter multiple bugs

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2720] opened 2020-02-26 19:18 UTC
##### SMALL DESCRIPTION:

If I create a team with the arena charter (2v2), when i ask another player to sign., when hovering on the item, it displays nothing

##### CURRENT BEHAVIOUR:

- [ ] When the arena charter is ready to be returned to the NPC, it is not showing details when hovering the mouse on it
- [ ] You can't return the arena charter and create the arena team unless you log out, or move the arena charter from 1 slot to another in your bags.
- [ ] The "Arena Organizer" does not display any gossip text when talking to him. Same for "Arena Battlemaster" BUT they have a gossip_menu_id in their creature_template
- [ ] Also, there is no quest mark "?" when you have completed the arena charter and have to return it

##### STEPS TO REPRODUCE THE PROBLEM:

1. Log with two accounts on two chars lvl 80 from same faction
2. `.go cr 70995` with one of them
3. Buy a 2v2 arena charter

##### EXTRA NOTES:

Someone else tested and found no bug :(

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

08796ec61572150d73627b8bf340f842edc98b62

##### OPERATING SYSTEM:

deb9

##### MODULES:

mod-1v1-arena

**Comment by Maurowin** [comment] 2020-02-26 21:26
Not confirm for me ;)

**Comment by BarbzYHOOL** [comment] 2020-03-08 19:51
@Maurowin 

>On the other hand what is not normal I think is if I fire members of my team and/or I leave the 2v2 team as at the end of the video I remain in the queue.

Fix:

```cpp
    // Player cannot be removed during queues
    if (BattlegroundQueueTypeId bgQueue = BattlegroundMgr::BGQueueTypeId(BATTLEGROUND_AA, arenaTeam->GetType()))
    {
        GroupQueueInfo ginfo;
        BattlegroundQueue& queue = sBattlegroundMgr->GetBattlegroundQueue(bgQueue);
        if (queue.GetPlayerGroupInfoData(_player->GetGUID(), &ginfo))
            if (ginfo.IsInvitedToBGInstanceGUID)
            {
                SendArenaTeamCommandResult(ERR_ARENA_TEAM_QUIT_S, "", "", ERR_ARENA_TEAMS_LOCKED);
                return;
            }
}
```
in this file https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/ArenaTeamHandler.cpp#L236 (from TC, suggested by @frytik)

this should work or require a bit of modification

**Comment by dcombat** [comment] 2020-03-09 10:29
I ported it few days ago, feel free to cherry pick it

https://github.com/dcombat/azerothcore-wotlk/commit/d034186b4528d9d30c531ac01a525e594da1503a

**Comment by BarbzYHOOL** [comment] 2020-03-12 00:35
@dcombat everything working as intended? if so, do you want to make a PR out of it?

**Comment by dcombat** [comment] 2020-03-14 12:22
Everything works yes, i'm out of the country and looks like i'll be stuck for a while, i'm afraid you'll have to do it

**Comment by aradep** [comment] 2020-11-29 04:05
<details><summary>Can't reproduce these on latest master with latest 1v1 arena module. Seems to be fixed</summary>

- [x]  When the arena charter is ready to be returned to the NPC, it is not showing details when hovering the mouse on it
- [x]  You can't return the arena charter and create the arena team unless you log out, or move the arena charter from 1 slot to another in your bags.
- [x]  The "Arena Organizer" does not display any gossip text when talking to him. Same for "Arena Battlemaster" BUT they have a gossip_menu_id in their creature_template
</details>

.

- [x]  On the other hand what is not normal I think is if I fire members of my team and/or I leave the 2v2 team as at the end of the video I remain in the queue.

Fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/3803

**Closed** 2021-01-08 01:39 UTC
Labels: Fix included, Priority - High
