### ISSUE TITLE
SPAM ANNOUNCE BATTLEGROUND

### ISSUE THREAD

**Issue by merdlin** [azerothcore/azerothcore-wotlk#2714] opened 2020-02-26 04:43 UTC
SPAM ANNOUNCE BATTLEGROUND

##### SMALL DESCRIPTION:
There is spam in the ad to join BG, I would like to know if there is any correction for this?

##### EXPECTED BLIZZLIKE BEHAVIOUR:
there should be a delay in the bg announce join

##### CURRENT BEHAVIOUR:
Players click several times to join the battlefield, which makes it an unwanted ad.

##### STEPS TO REPRODUCE THE PROBLEM:
Steps to reproduce the problem:
- keep clicking on join the battlefield

##### BRANCH(ES):
SPAM CHAT

##### OPERATING SYSTEM:
WINDOWS SERVER 2016

**Comment by V3nomAnc3r** [comment] 2020-02-26 05:42
Confirmed rev https://github.com/azerothcore/azerothcore-wotlk/commit/68698483647082aa0f0771ece3a7ff9d2def8203

**Comment by FrancescoBorzi** [comment] 2020-02-26 21:12
@mythicwowbr ingles por favor (english please)

si no puede hablar inglés, adjunte el texto en español y en inglés traducido con un traductor

**Comment by mythicwowbr** [comment] 2020-02-26 21:48
@FrancescoBorzi translated.

**Comment by solidmaxtor** [comment] 2020-02-28 02:09
Use this options, only show if bg start and if player join only show to this player stats pre-bg
```
#
#    Battleground.QueueAnnouncer.Enable
#        Description: Announce battleground queue status to chat.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

Battleground.QueueAnnouncer.Enable = 1

#
#    Battleground.QueueAnnouncer.PlayerOnly
#        Description: Battleground queue announcement type.
#        Default:     0 - (System message, Anyone can see it)
#                     1 - (Private, Only queued players can see it)

Battleground.QueueAnnouncer.PlayerOnly = 1
```

**Comment by merdlin** [comment] 2020-02-28 02:27
it is a good suggestion but it does not solve the problem of advertising for everyone.

**Comment by solidmaxtor** [comment] 2020-02-29 01:22
install fresh core and test. No problem for me i not have spam.

**Comment by merdlin** [comment] 2020-03-01 02:34
I have the latest version of the core and have spam.

**Comment by IntelligentQuantum** [comment] 2020-03-01 09:46
![Screenshot_20200301_131100](https://user-images.githubusercontent.com/14080516/75623372-a649f500-5bbe-11ea-90c5-b24fb1f7d294.png)

Confirmed https://github.com/azerothcore/azerothcore-wotlk/commit/857e799298c06f328d4b0f189148cbcbb51595e3 With Cfbg module

**Comment by FrancescoBorzi** [comment] 2020-03-01 09:58
so the issue is with CFBG module? @IntelligentQuantum can you please test **wihtout** that module?

**Comment by IntelligentQuantum** [comment] 2020-03-01 10:10
Without CFBG, it works fine

**Comment by merdlin** [comment] 2020-03-01 14:13
then it may be the module that has this problem.

**Comment by FrancescoBorzi** [comment] 2020-03-01 19:17
exactly, please @merdlin  report it to https://github.com/azerothcore/mod-cfbg

I close this issue here as it's not a bug in the main core

thanks @IntelligentQuantum for your feedback

**Closed by FrancescoBorzi** 2020-03-01 19:17 UTC
Labels: Not confirmed

**Comment by BarbzYHOOL** [comment] 2020-03-01 20:59
and next time @merdlin put the modules you use especially if your issue is about BG and you use mod-CFBG -__-
