### ISSUE TITLE
[CRASH] SERVER!

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#964] opened 2018-07-03 16:52 UTC
I do not know, I'm not sure
Because of Game Master and some Players when Leave and join Battleground!

SERVER WiLL TO CRASHED!

<Details>

--- DEBUG: --- START

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff483e700 (LWP 43300)]
[New Thread 0x7ffff3c3d700 (LWP 43303)]
[New Thread 0x7ffff2abc700 (LWP 43307)]
[New Thread 0x7fffb4b3b700 (LWP 43310)]
[New Thread 0x7fffa5f3a700 (LWP 43311)]
[New Thread 0x7fffa5739700 (LWP 43312)]
[New Thread 0x7fffa4738700 (LWP 43313)]
[New Thread 0x7fffa3f37700 (LWP 43314)]
[New Thread 0x7fffa2f36700 (LWP 43315)]
[New Thread 0x7fffa2735700 (LWP 43316)]
[New Thread 0x7fff66c34700 (LWP 43453)]
[Thread 0x7fff66c34700 (LWP 43453) exited]

Thread 6 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa5f3a700 (LWP 43311)]
Trinity::Assert (file=0x7ffff57f4750 <_IO_stdfile_2_lock> "", line=-179091635, function=0x7fffa5f3a700 "", message=0x3ab <error: Cannot access memory at address 0x3ab>) at /home/azerothcore/src/common/Debugging/Errors.cpp:20
20	    *((volatile int*)NULL) = 0;

--- DEBUG: BACKTRACE FULL

#0  Trinity::Assert (file=0x7ffff57f4750 <_IO_stdfile_2_lock> "", line=-179091635, function=0x7fffa5f3a700 "", message=0x3ab <error: Cannot access memory at address 0x3ab>) at /home/azerothcore/src/common/Debugging/Errors.cpp:20
        st = {static SYMBUFSIZ = 4096, static UNSUPPORTED = 0x7ffff74e99e0 <ACE_Stack_Trace::UNSUPPORTED> "<stack traces unsupported platform>", static UNABLE_TO_GET_TRACE = <same as static member of an already seen type>, buf_ = "/home/debug/bin/worldserver(_ZN12Battleground19RemovePlayerAtLeaveEP6Player+0x2f1) [0xd19071]\n/home/debug/bin/worldserver(_ZN15BattlegroundMap19RemovePlayerFromMapEP6Playerb+0x2c) [0xbd29fc]\n/home/deb"..., buflen_ = 763}
#1  0x000000000097771b in BattlegroundMgr::BuildBattlegroundStatusPacket (this=<optimized out>, data=0x7fffa5f383d0, bg=0x7fffa4ba7780, QueueSlot=2 '\002', StatusID=0 '\000', Time1=939, Time2=<optimized out>, arenatype=<optimized out>, teamId=<optimized out>, isRated=<optimized out>, forceBgTypeId=<optimized out>) at /home/azerothcore/src/server/game/Battlegrounds/BattlegroundMgr.cpp:144
No locals.
#2  0x0000000000d19071 in Battleground::RemovePlayerAtLeave (this=<optimized out>, player=<optimized out>) at /home/azerothcore/src/server/game/Battlegrounds/Battleground.cpp:1112
        participant = true
        teamId = <optimized out>
#3  0x0000000000bd29fc in BattlegroundMap::RemovePlayerFromMap (this=0x7fff3d40d9c0, player=0x7fff58ff4ac0, remove=false) at /home/azerothcore/src/server/game/Maps/Map.cpp:2895
        bg = 0x7fffa4ba7780
#4  0x0000000000a58ab9 in Player::TeleportTo (this=0x7fff58ff4ac0, mapid=571, x=<optimized out>, y=<optimized out>, z=<optimized out>, orientation=<optimized out>, options=0, target=<optimized out>) at /home/azerothcore/src/server/game/Entities/Player/Player.cpp:2425
        oldmap = 0x7fffa5f34b60
        mEntry = <optimized out>
        pet = <optimized out>
#5  0x0000000000c2d42d in WorldSession::Update (this=<optimized out>, diff=<optimized out>, updater=...) at /home/azerothcore/src/server/game/Server/WorldSession.cpp:279
        _startMSTime = <optimized out>
        processedPackets = 0
        movementPacket = <optimized out>
        packet = 0x7fff692ae9d0
#6  0x0000000000cbef91 in World::UpdateSessions (this=<optimized out>, diff=<optimized out>) at /home/azerothcore/src/server/game/World/World.cpp:2687
        pSession = 0x7fffa1757000
        sess = <optimized out>
        currTime = <optimized out>
#7  0x0000000000cbe37d in World::Update (this=0x7ffff4ea4008, diff=10) at /home/azerothcore/src/server/game/World/World.cpp:2047
No locals.
#8  0x000000000096f943 in WorldRunnable::run (this=<optimized out>) at /home/azerothcore/src/server/worldserver/WorldThread/WorldRunnable.cpp:44
        executionTimeDiff = <optimized out>
        diff = 10
        realCurrTime = 11701376
        realPrevTime = 11701376
#9  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#10 0x00007ffff62a0494 in start_thread (arg=0x7fffa5f3a700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffa5f3a700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735977596672, 9159647393092482753, 0, 140737488348383, 0, 140737354125376, -9159528751852407103, -9159628322049214783}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#11 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

--- DEBUG: INFO REGISTERS

rax            0x3ab	939
rbx            0x7fffa5f3a700	140735977596672
rcx            0x7ffff553474d	140737309263693
rdx            0x7ffff57f4750	140737312147280
rsi            0x0	0
rdi            0x7fffa5f34b60	140735977573216
rbp            0x0	0x0
rsp            0x7fffa5f38800	0x7fffa5f38800
r8             0x7fffa5f3a700	140735977596672
r9             0x3ab	939
r10            0x73	115
r11            0x0	0
r12            0x0	0
r13            0x7fffffffe4df	140737488348383
r14            0x0	0
r15            0x7ffff7ffd040	140737354125376
rip            0x7ffff5541acf	0x7ffff5541acf <clone+63>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

--- DEBUG: CALLS (x/32i $pc)

=> 0x7ffff5541acf <clone+63>:	mov    %rax,%rdi
   0x7ffff5541ad2 <clone+66>:	callq  0x7ffff55115e0 <__GI__exit>
   0x7ffff5541ad7 <clone+71>:	mov    0x2b039a(%rip),%rcx        # 0x7ffff57f1e78
   0x7ffff5541ade <clone+78>:	neg    %eax
   0x7ffff5541ae0 <clone+80>:	mov    %eax,%fs:(%rcx)
   0x7ffff5541ae3 <clone+83>:	or     $0xffffffffffffffff,%rax
   0x7ffff5541ae7 <clone+87>:	retq   
   0x7ffff5541ae8:	nopl   0x0(%rax,%rax,1)
   0x7ffff5541af0 <lseek64>:	mov    $0x8,%eax
   0x7ffff5541af5 <lseek64+5>:	syscall 
   0x7ffff5541af7 <lseek64+7>:	cmp    $0xfffffffffffff001,%rax
   0x7ffff5541afd <lseek64+13>:	jae    0x7ffff5541b00 <lseek64+16>
   0x7ffff5541aff <lseek64+15>:	retq   
   0x7ffff5541b00 <lseek64+16>:	mov    0x2b0371(%rip),%rcx        # 0x7ffff57f1e78
   0x7ffff5541b07 <lseek64+23>:	neg    %eax
   0x7ffff5541b09 <lseek64+25>:	mov    %eax,%fs:(%rcx)
   0x7ffff5541b0c <lseek64+28>:	or     $0xffffffffffffffff,%rax
   0x7ffff5541b10 <lseek64+32>:	retq   
   0x7ffff5541b11:	nopw   %cs:0x0(%rax,%rax,1)
   0x7ffff5541b1b:	nopl   0x0(%rax,%rax,1)
   0x7ffff5541b20 <__umount>:	xor    %esi,%esi
   0x7ffff5541b22 <__umount+2>:	jmpq   0x7ffff5541b30 <umount2>
   0x7ffff5541b27:	nopw   0x0(%rax,%rax,1)
   0x7ffff5541b30 <umount2>:	mov    $0xa6,%eax
   0x7ffff5541b35 <umount2+5>:	syscall 
   0x7ffff5541b37 <umount2+7>:	cmp    $0xfffffffffffff001,%rax
   0x7ffff5541b3d <umount2+13>:	jae    0x7ffff5541b40 <umount2+16>
   0x7ffff5541b3f <umount2+15>:	retq   
   0x7ffff5541b40 <umount2+16>:	mov    0x2b0331(%rip),%rcx        # 0x7ffff57f1e78
   0x7ffff5541b47 <umount2+23>:	neg    %eax
   0x7ffff5541b49 <umount2+25>:	mov    %eax,%fs:(%rcx)
   0x7ffff5541b4c <umount2+28>:	or     $0xffffffffffffffff,%rax

--- DEBUG: THREAD APPLY ALL BACKTRACE

Thread 11 (Thread 0x7fffa2735700 (LWP 43316)):
#0  0x00007ffff55420c3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff747c670 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#2  0x00007ffff747da9b in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.3.3.so
#3  0x00007ffff747f005 in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#4  0x00007ffff74bd272 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000c3809f in ReactorRunnable::svc (this=<optimized out>) at /home/azerothcore/src/server/game/Server/WorldSocketMgr.cpp:160
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7fffa2735700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fffa2f36700 (LWP 43315)):
#0  0x00007ffff55420c3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff747c670 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#2  0x00007ffff747da9b in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.3.3.so
#3  0x00007ffff747f005 in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#4  0x00007ffff74bd272 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000c3809f in ReactorRunnable::svc (this=<optimized out>) at /home/azerothcore/src/server/game/Server/WorldSocketMgr.cpp:160
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7fffa2f36700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fffa3f37700 (LWP 43314)):
#0  0x00007ffff62a97dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000db733b in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/thread:323
#2  ACORE::Thread::Sleep (msecs=<optimized out>) at /home/azerothcore/src/common/Threading/Threading.cpp:110
#3  0x000000000096fbca in AuctionListingRunnable::run (this=<optimized out>) at /home/azerothcore/src/server/worldserver/WorldThread/WorldRunnable.cpp:119
#4  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff62a0494 in start_thread (arg=0x7fffa3f37700) at pthread_create.c:333
#6  0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fffa4738700 (LWP 43313)):
#0  0x00007ffff55420c3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff747c670 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#2  0x00007ffff747da9b in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.3.3.so
#3  0x00007ffff747f005 in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#4  0x00007ffff74bd272 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.3.3.so
#5  0x000000000096a574 in RARunnable::run (this=<optimized out>) at /home/azerothcore/src/server/worldserver/RemoteAccess/RARunnable.cpp:68
#6  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff62a0494 in start_thread (arg=0x7fffa4738700) at pthread_create.c:333
#8  0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fffa5739700 (LWP 43312)):
#0  0x00007ffff553a3c3 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff776e27b in ?? () from /lib/x86_64-linux-gnu/libreadline.so.7
#2  0x00007ffff776e504 in rl_read_key () from /lib/x86_64-linux-gnu/libreadline.so.7
#3  0x00007ffff7756513 in readline_internal_char () from /lib/x86_64-linux-gnu/libreadline.so.7
#4  0x00007ffff7756d65 in readline () from /lib/x86_64-linux-gnu/libreadline.so.7
#5  0x00000000009696ca in CliRunnable::run (this=<optimized out>) at /home/azerothcore/src/server/worldserver/CommandLine/CliRunnable.cpp:148
#6  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff62a0494 in start_thread (arg=0x7fffa5739700) at pthread_create.c:333
#8  0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fffa5f3a700 (LWP 43311)):
#0  Trinity::Assert (file=0x7ffff57f4750 <_IO_stdfile_2_lock> "", line=-179091635, function=0x7fffa5f3a700 "", message=0x3ab <error: Cannot access memory at address 0x3ab>) at /home/azerothcore/src/common/Debugging/Errors.cpp:20
#1  0x000000000097771b in BattlegroundMgr::BuildBattlegroundStatusPacket (this=<optimized out>, data=0x7fffa5f383d0, bg=0x7fffa4ba7780, QueueSlot=2 '\002', StatusID=0 '\000', Time1=939, Time2=<optimized out>, arenatype=<optimized out>, teamId=<optimized out>, isRated=<optimized out>, forceBgTypeId=<optimized out>) at /home/azerothcore/src/server/game/Battlegrounds/BattlegroundMgr.cpp:144
#2  0x0000000000d19071 in Battleground::RemovePlayerAtLeave (this=<optimized out>, player=<optimized out>) at /home/azerothcore/src/server/game/Battlegrounds/Battleground.cpp:1112
#3  0x0000000000bd29fc in BattlegroundMap::RemovePlayerFromMap (this=0x7fff3d40d9c0, player=0x7fff58ff4ac0, remove=false) at /home/azerothcore/src/server/game/Maps/Map.cpp:2895
#4  0x0000000000a58ab9 in Player::TeleportTo (this=0x7fff58ff4ac0, mapid=571, x=<optimized out>, y=<optimized out>, z=<optimized out>, orientation=<optimized out>, options=0, target=<optimized out>) at /home/azerothcore/src/server/game/Entities/Player/Player.cpp:2425
#5  0x0000000000c2d42d in WorldSession::Update (this=<optimized out>, diff=<optimized out>, updater=...) at /home/azerothcore/src/server/game/Server/WorldSession.cpp:279
#6  0x0000000000cbef91 in World::UpdateSessions (this=<optimized out>, diff=<optimized out>) at /home/azerothcore/src/server/game/World/World.cpp:2687
#7  0x0000000000cbe37d in World::Update (this=0x7ffff4ea4008, diff=10) at /home/azerothcore/src/server/game/World/World.cpp:2047
#8  0x000000000096f943 in WorldRunnable::run (this=<optimized out>) at /home/azerothcore/src/server/worldserver/WorldThread/WorldRunnable.cpp:44
#9  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff62a0494 in start_thread (arg=0x7fffa5f3a700) at pthread_create.c:333
#11 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fffb4b3b700 (LWP 43310)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e1b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.3.3.so
#2  0x000000000096f0af in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::wait_not_empty_cond (this=<optimized out>, timeout=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1776
#3  0x000000000096dd51 in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff2d77798, first_item=@0x7fffb4b39678: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1968
#4  0x00007ffff74527a5 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000db6c6c in DelayExecutor::svc (this=<optimized out>) at /home/azerothcore/src/common/Threading/DelayExecutor.cpp:48
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7fffb4b3b700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7ffff2abc700 (LWP 43307)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e1b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.3.3.so
#2  0x000000000096f0af in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::wait_not_empty_cond (this=<optimized out>, timeout=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1776
#3  0x000000000096dd51 in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4e9e280, first_item=@0x7ffff2aba678: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1968
#4  0x00007ffff74527a5 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000dbb263 in DatabaseWorker::svc (this=<optimized out>) at /home/azerothcore/src/common/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7ffff2abc700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7ffff3c3d700 (LWP 43303)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e1b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.3.3.so
#2  0x000000000096f0af in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::wait_not_empty_cond (this=<optimized out>, timeout=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1776
#3  0x000000000096dd51 in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4e9e140, first_item=@0x7ffff3c3b678: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1968
#4  0x00007ffff74527a5 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000dbb263 in DatabaseWorker::svc (this=<optimized out>) at /home/azerothcore/src/common/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7ffff3c3d700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7ffff483e700 (LWP 43300)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e1b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.3.3.so
#2  0x000000000096f0af in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::wait_not_empty_cond (this=<optimized out>, timeout=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1776
#3  0x000000000096dd51 in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4e9e000, first_item=@0x7ffff483c678: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1968
#4  0x00007ffff74527a5 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000dbb263 in DatabaseWorker::svc (this=<optimized out>) at /home/azerothcore/src/common/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7ffff483e700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7fe2f00 (LWP 43296)):
#0  0x00007ffff62a16cd in pthread_join (threadid=140735977596672, thread_return=0x0) at pthread_join.c:90
#1  0x00007ffff5dcd0f7 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000db724f in ACORE::Thread::wait (this=0x7fffffffe6d0) at /home/azerothcore/src/common/Threading/Threading.cpp:46
#3  0x0000000000972686 in Master::Run (this=<optimized out>) at /home/azerothcore/src/server/worldserver/Master.cpp:302
#4  0x0000000000970e39 in main (argc=<optimized out>, argv=<optimized out>) at /home/azerothcore/src/server/worldserver/Main.cpp:137

--- DEBUG: --- STOP

</Details>

Azerothcore Version
https://github.com/azerothcore/azerothcore-wotlk/commit/613b586485abe2462ce74802f634adf50e6231c0

OS: Linux

Modules =Anticheat

**Comment by talamortis** [comment] 2018-07-03 18:37
how to reproduce?

**Comment by Hir0shi** [comment] 2018-07-03 21:09
I do not know

please see on crash log!

**Comment by AyaseCore** [comment] 2018-07-04 03:52
Many issues were marked in a flash. XD

**Comment by Hir0shi** [comment] 2018-07-04 10:46
I'm really sorry!

Are i lying? this is crash my version azerothcore! i builded on mode debug and creat crash log for help azerothcore project!

If you do not want to check and have problems! And it's hard for you.

I do not insist, NP

**Comment by Selectah** [comment] 2018-07-04 23:52
Try to reproduce this issue again with a full BG or forcejoin as a GameMaster. 

It looks like this is caused by a GameMaster after joining a full BG queue.

**Comment by FALL1N1** [comment] 2018-07-09 11:19
use gdb and post full log

**Comment by Hir0shi** [comment] 2018-07-09 11:49
@FALL1N1 

this is use by gdp and debug mod+ full crash log

I do not know what the Crash!

I guess:
1.gm join bg
2.ap player
3.tele dalaran or more maps..
4.leave queue

But I'm not sure

**Comment by BarbzYHOOL** [comment] 2018-08-27 00:34
Someone confirms or I close it.

**Closed** 2018-09-23 18:58 UTC
Labels: Not confirmed
