### ISSUE TITLE
Heavy Golden Necklace of Battle Item=20831

### ISSUE THREAD

**Issue by blinkysc** [azerothcore/azerothcore-wotlk#20546] opened 2024-11-13 13:15 UTC
### Current Behaviour

When using Heavy Golden Necklace of Battle item=20831 the spell Heavy Golden Necklace of Battle spell=25211 will fall off when you shapeshift

### Expected Blizzlike Behaviour

Spell should stay when shapeshifting

### Steps to reproduce the problem

.additem 20831
.learn 768

Use 20831
Shapeshift and observe

### AC rev. hash/commit

545bb18af4ed
Also on ChromieCraft

### Operating system

Debian 12.8

**Comment by heyitsbench** [comment] 2024-11-13 13:19
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/19823.

**Closed by heyitsbench** 2024-11-13 13:19 UTC
