### ISSUE TITLE
Stealth is being removed by warrior's Intervene ability

### ISSUE THREAD

**Issue by CosmeF** [azerothcore/azerothcore-wotlk#2472] opened 2019-11-28 01:11 UTC
##### SMALL DESCRIPTION:
Warrior spell id 3411 (Intervene) is wrongly removing stealth from rogues, druids and probably more.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It shouldn't remove stealth, of any class.

##### CURRENT BEHAVIOUR:
A test based on 2v2 arena shows that, no matter the distance, the Intervene warrior spell removes stealth from the oponent rogue or druid.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create 2 groups for arena skirmish 2v2, one with a warrior with intervene spell, and other with a rogue with stealth.
2. Call a .skirmish on any arena, and use stealth with the rogue, away from the warrior, but in a specific spot of arena, to see how it shows once stealth is removed.
3. Use intervene with the warrior on your teammate, and see the enemy rogue appear.

##### EXTRA NOTES:
I've tested this issue on an older version of azerothcore (AzerothCore rev. 500c04+ 2019-02-27), and it still was on it. I don't know if it helps or not.

##### BRANCH(ES):
Master

##### AC HASH/COMMIT:
e1ee77e173e177d16b676ac8fac137eab3bfe818

##### OPERATING SYSTEM:
Ubuntu 18.04.3 LTS
Debian 10 (backup server, same branch & hash/commit)

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by CosmeV** [comment] 2019-11-28 01:26
It may be related to [issue #2371](https://github.com/azerothcore/azerothcore-wotlk/issues/2371)

**Comment by lineagedr** [comment] 2019-11-28 02:06
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellInfo.cpp#L2629 Here its considered as a not positive effect

I guess that's why it removes stealth here https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L3014

**Comment by Viste** [comment] 2019-11-28 04:07
> https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellInfo.cpp#L2629 Here its considered as a not positive effect
> 
> I guess that's why it removes stealth here https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L3014

true

**Comment by solidmaxtor** [comment] 2019-11-28 06:08
Confirm this problem

**Comment by xDevICCI** [comment] 2019-11-28 21:00
Any test this query ?

INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES
(3411, 64);

postdata: @SPELL_ATTR0_CU_DONT_BREAK_STEALTH            = 64,
https://wotlk.evowow.com/?spell=3411

**Comment by EpicDR** [comment] 2019-11-28 21:13
> Any test this query ?
> 
> INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES
> (3411, 64);
> 
> postdata: @SPELL_ATTR0_CU_DONT_BREAK_STEALTH = 64,
> https://wotlk.evowow.com/?spell=3411

i tried before, doesn't work.

**Comment by xDevICCI** [comment] 2019-11-28 21:16
// Intervene
        case 3411:
            spellInfo->AttributesEx |= SPELL_ATTR1_NOT_BREAK_STEALTH;
            break;

i  believe  try work this in spellmgr.cpp

**Comment by CosmeF** [comment] 2019-12-01 05:33
If I modify https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L3014 in this way:

`    if (m_caster != unit && m_caster->IsHostileTo(unit) && !m_spellInfo->IsPositive() && !m_triggeredByAuraSpell && m_spellInfo->SpellIconID != 2267 && unit->IsControlledByPlayer() && (!m_caster->IsTotem() || m_spellInfo->Id == 64695))
    {
        if (m_spellInfo->SpellIconID != 59667)			//CosmeF: temp fix for intervene removing stealth issue
	    unit->RemoveAurasByType(SPELL_AURA_MOD_STEALTH);
    }`

It seems to work but only for rogue stealth. Can somebody point me where in the code the rest of stealth mechanics are handled? (mage invisibility - druid prowl - night elf racial - others)? That would be much appreciated.

Also, I know I'm probably messing whith some important mechanics by doing this, but is just to learn some stuff and maybe get some unelegant temporal solution.

**Comment by CosmeF** [comment] 2019-12-01 08:16
By adding this condition:

`if (m_spellInfo->Id != 59667)`

before every "removeauras" function call, it seems to work with mage and druid, and probably the racial aswell, but this certainly is far from a proper code solution.

**Comment by Undead02** [comment] 2019-12-02 17:44
> LINE 3684
> 
> ```
>     // Intervene
>     case 3411:
>         spellInfo->AttributesEx |= SPELL_ATTR1_NOT_BREAK_STEALTH;
>         break;
> ```
> 
> i believe try work this in spellmgr.cpp

This insnt work because this attr dont break stealth if you rogue and use in stealth cloak of shadow for example

**Comment by lineagedr** [comment] 2019-12-02 18:03
Just remove the if statement https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellInfo.cpp#L2629 and it won't remove stealth. I don't know why it's added in the first place if it's considered a negative effect does it do anything?

**Comment by CosmeF** [comment] 2019-12-02 23:57
> 
> 
> Just remove the case https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellInfo.cpp#L2627 and stealth will no longer be removed by intervene. I don't know why it's added in the first place if it's considered a negative effect does it do anything?

Tested, and it doesn't work.

**Comment by lineagedr** [comment] 2019-12-03 00:03
@CosmeF It worked for me can you upload your SpellInfo.cpp after you'v edited it.

**Comment by CosmeF** [comment] 2019-12-03 00:19
https://pastebin.com/vTwfPkrC

I've tested it with a tauren druid on dalaran arena 2v2.

**Comment by lineagedr** [comment] 2019-12-03 00:22
@CosmeF  Removing the case fixes stealth not prowl

**Comment by CosmeF** [comment] 2019-12-03 02:48
@lineagedr Thats similar to the condition I was testing, but I find out it works in every case but mage Invisibility. I recently find out tho that on the same file, if you include the spell id 59667 condition that you agreed is needed, and also change this line:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L2955

to this:

`if (m_caster->_IsValidAttackTarget(unit, m_spellInfo) && /*Intervene Trigger*/ m_spellInfo->Id != 59667)`

it seems to work on every case I've tested (mage Invisibility, NElf Racial, Druid Prowl and Rogue Stealth).

**Comment by lineagedr** [comment] 2019-12-03 14:30
@CosmeF How do you remove the mage invis? I've tried but even after intervening the mage is still in invis.

**Comment by CosmeF** [comment] 2019-12-03 15:55
@lineagedr I just do de exact same test as the steps on the issue, except I change the rogue for undead mage. I've tested several times without the changes on line 2955, and the mage always showed up due to intervene trigger, so I had to include it.

**Comment by CosmeF** [comment] 2019-12-06 05:53
I've made a PR to address this issue. Hopefully we can have some positive feedback soon.

**Comment by Shard-MW** [comment] 2019-12-13 22:45
Mmh, I can't reproduce it on 69ebb5081bab5abfd5e9cc1fb86a955493ba2215

https://mega.nz/#!k19gXCrQ!4L04ZcjN8GAnONydjDZ1GzZfEx7qr7O8cilRefUNh4A

**Comment by Stoabrogga** [comment] 2019-12-22 08:31
Closing this, as PR #2492 has been merged with commit e4fc5de.

**Closed by Stoabrogga** 2019-12-22 08:31 UTC
Labels: Confirmed
