### ISSUE TITLE
[spell] Berserk

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#488] opened 2017-05-16 21:21 UTC
**Description**:
Berserk for cat druids is not working correctly with reducing energy cost.
It's aura effect is being applied before other passive talent auras that also reduce energy cost.

**Current behaviour**:
The energy cost of Shred with Shredding Attacks and Berserk is 12 (60 * 0.5 - 18) when it should be 21 ((60-18) * 0.5).
The energy cost of Mangle is 11.5 (45 * 0.5 - 5 - 6) when it should be 17 ((45-5-6) * 0.5)
and so on for the other spells.

This is not an issue on Trinity Core, but I haven't found the difference yet.

**Steps to reproduce the problem**:

1. make an 80 druid with talents in Shredding Attacks and Berserk
2. Use Berserk and Shred on a dummy.
3. Observe energy meter not going down to 79.

**Branch(es)**: master

**AC hash/commit**: cfd2d7e

**Comment by ShinDarth** [comment] 2017-05-17 06:25
Missing commit hash, please read:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by HeartWell** [comment] 2017-05-18 18:09
Shred cost 60 energy, learn two tal Shredding Attacks - 18 energy 60-18 = 42 if you have aura berserk -50% energy in for cat. 60-18:2= 21 right? Where bag?

**Comment by PolarCookie** [comment] 2017-05-22 13:37
The tooltip will say 21, but if you use shred and watch the energy bar it's 12.
Very noticable when testing AC and TC next to eachother.

**Comment by HeartWell** [comment] 2017-05-22 16:35
At the bar, I have 79 energy 100 - 21, with after using spells with aura. where you see 12 I don't know.

**Comment by PolarCookie** [comment] 2017-05-22 18:31
Here's me testing on AC
https://webmshare.com/EBBwx

Here's me testing on TC
https://webmshare.com/wKKox

Reason I even made this ticket is because someone noticed this on Northcraft.
https://northcraft.org/bugtracker/view.php?id=693

**Comment by talamortis** [comment] 2017-05-27 21:30
if this issue is invalid can we close?

**Comment by Viste** [comment] 2017-06-12 20:21
we can close it all as @HeartWell  say

**Comment by lineagedr** [comment] 2021-01-10 12:16
Confirm. After testing on https://github.com/azerothcore/azerothcore-wotlk/commit/7cf097eab2fc1425638557903f06a8922ee74ec1 

It does in fact consume 12 energy instead of 21.

There's something wrong in: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.h#L2966

No idea why this was closed.

**Comment by FrancescoBorzi** [comment] 2021-01-10 21:07
thanks @lineagedr for your feedback

**Comment by Kitzunu** [comment] 2021-05-23 03:17
I cannot reproduce this on a75b84ab2e4a47de8152ef9627ed3ea2ca00901a

**Closed by Kitzunu** 2021-05-23 03:17 UTC
Labels: Confirmed
