### ISSUE TITLE
Achievements: The Perfect Storm

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#11998] opened 2022-06-10 10:55 UTC
### Current Behaviour

the achievement: [The Perfect Storm](https://wotlkdb.com/?achievement=783) of the Eye of the storm is not completed when you win with a score 1600 to 0

### Expected Blizzlike Behaviour

When you win with a score of 1600 to 0, it should give you the achievement [The Perfect Storm](https://wotlkdb.com/?achievement=783)

### Steps to reproduce the problem

1.  .deb bg
2. join the queue of the bg Eye of the Storm
3. capture all 4 bases and hope to win with a score of 1600 a 0

### AC rev. hash/commit

AzerothCore rev. 324112ff4fcb+ 2022-05-19 19:13:06 -0300 (master branch) (Win64, Release, Static)

### Operating system

Ubuntu 20.04

**Comment by sudlud** [comment] 2023-10-14 19:25
Just tested this on a2c6af4c5 with Level 80 Horde Troll Priest

cannot reproduce - Achievements get's granted as expected when winning with a score of 1600 to 0:

![WoWScrnShot_101423_212114_Achievement_the_perfect_storm](https://github.com/azerothcore/azerothcore-wotlk/assets/7723845/e2180d41-801f-4763-872c-22846ffd1b0e)

**Comment by sudlud** [comment] 2023-10-15 17:31
@Kitzunu can we close this issue?

**Comment by heyitsbench** [comment] 2023-10-15 17:33
Might be intermittent. @Tony931023, if you manage to reproduce on more recent revisions, feel free to re-open the issue.

**Comment by sudlud** [comment] 2024-04-04 06:34
just tested this on 40bbba64d with level 80 human character

```
.debug bg

join Eye of the Storm Battleground

capture all 4 bases
.go xyz 2300 1400 1200
.go xyz 2285 1730 1200
.go xyz 2045 1730 1200
.go xyz 2050 1400 1200

win at 1600/1600
```

The achievement was NOT granted.

![WoWScrnShot_040424_082946](https://github.com/azerothcore/azerothcore-wotlk/assets/7723845/f5582960-ebb2-4855-9b82-e76f716e35d3)

**Comment by sudlud** [comment] 2024-04-04 06:42
with level 80 horde troll priest it was also NOT granted at 40bbba64d

![WoWScrnShot_040424_084056](https://github.com/azerothcore/azerothcore-wotlk/assets/7723845/53e5fef7-8cb8-446f-9227-4e3843c1862b)

**Comment by sudlud** [comment] 2024-04-04 07:11
tested on another level 80 horde character - again achievement NOT granted.

I'd really like to know what I did different for https://github.com/azerothcore/azerothcore-wotlk/issues/11998#issuecomment-1763146137

**Closed** 2024-04-04 21:29 UTC
Labels: Confirmed, Battlegrounds, 61-64
