### ISSUE TITLE
Frequent disconnection from servers on an irregular basis

### ISSUE THREAD

**Issue by 127y** [azerothcore/azerothcore-wotlk#16148] opened 2023-05-01 02:14 UTC
### Current Behaviour

f8cce45e8a5b49f63c413ed250acf3f84b7ebd24  no problem

upgrade to 26e79da8a8d33b3c8f53797ea359e45ef261fd4c

Frequent disconnection from servers on an irregular basis

No logs, no prompts

It seems like worldserver.exe has been closed. Actually, worldserver.exe has not been closed. In normal operation

Re logging in to the ID allows for normal gaming, but it still disconnects from the server from time to time. I don't know where the problem is, there is no record in the log, nor is there any prompt f8cce45e8a5b49f63c413ed250acf3f84b7ebd24 no problem

### Expected Blizzlike Behaviour

f8cce45e8a5b49f63c413ed250acf3f84b7ebd24  no problem

### Steps to reproduce the problem

Wild dungeon Frequent disconnection from servers on an irregular basis

### Extra Notes

no

### AC rev. hash/commit

26e79da8a8d33b3c8f53797ea359e45ef261fd4c
Frequent disconnection from servers on an irregular basis

### Operating system

windows 11 x64

### Custom changes or Modules

no

**Comment by heyitsbench** [comment] 2023-05-01 02:16
Possible duplicate of #16100, try to set [Warden.ClientResponseDelay](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/apps/worldserver/worldserver.conf.dist#L1486) in your worldserver.conf to 0 and see if it resolves the issue.

**Comment by Gultask** [comment] 2023-05-01 02:18
Try this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/16144

**Comment by 127y** [comment] 2023-05-01 02:43
The problem has been resolved. Thank you very much @heyitsbench @Gultask  Thank you very much

Both methods are still effective

**Comment by zxnhrdz** [comment] 2023-05-02 05:01
It still drops randomly, but it doesn't have much effect. It gives me the feeling that it has a certain relationship with the start of the battle in Dongyong Lake.

**Comment by zxnhrdz** [comment] 2023-05-02 05:36
It could also be caused by #16115

**Comment by Kitzunu** [comment] 2023-07-30 13:30
Going to close as fixed by 91486ac46faf8c978e2d46771dbba103736efe87

**Closed by Kitzunu** 2023-07-30 13:30 UTC
