### ISSUE TITLE
Various issues with Felguard's intercept

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8725] opened 2021-10-24 21:44 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2187

Generally felguard has no problem casting Anguish and Cleave on cooldown after being sent to attack enemy, but if he charges prior to attack, those abilities aren't being cast if set on autocast, although can be cast manually still.

Tester:

The issue is confirmed. [Felguard](https://wowgaming.altervista.org/aowow/?npc=17252), [Intercept](https://wowgaming.altervista.org/aowow/?spell=30151). Conditions: only Passive stance, player should press Intercept ability(not Attack):
1. Using Intercept in range of ability leave pet "passive".
2. Using Intercept out of range of ability prevent using autocast abilities.

https://user-images.githubusercontent.com/85256266/138613911-032370f6-08de-476d-9341-96a8a915989c.mp4

https://user-images.githubusercontent.com/85256266/138614086-1cdf945e-3334-430a-90e8-617ec29d7adb.mp4

### Expected Blizzlike Behaviour

Felguard should always cast abilities set on autocast either he did charge or not.

Tester:

I guess if you using intercept(technicaly doing damage to target) it should stop passive behavior.

### Source

X

### Steps to reproduce the problem

X

### Extra Notes

Maybe regarding to https://github.com/azerothcore/azerothcore-wotlk/issues/6065

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by laasker** [comment] 2021-12-22 21:06
I cant reproduce this (tested on a dummy target), maybe https://github.com/azerothcore/azerothcore-wotlk/pull/9635 or https://github.com/azerothcore/azerothcore-wotlk/pull/9570 has fixed this, can you test again @Shineslippers ?

**Comment by Shineslippers** [comment] 2021-12-24 09:57
Maybe on Dummies it work, but issue still exist in open world. Just tested it again.

**Comment by UltraNix** [comment] 2022-03-06 20:19
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/9635

**Closed by UltraNix** 2022-03-06 20:19 UTC
Labels: Confirmed, 50-59, Class - Warlock
