### ISSUE TITLE
[server]world server crash 0518

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11800] opened 2022-05-18 14:16 UTC
### Current Behaviour

crash log:

https://gist.github.com/mpfans/f7f2086518a56f10d21e11849e0bf267

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

822aff29e680d7ddce1064abf8a543999c914c98 + PR #11740  + PR #11741

### Operating system

Ubuntu20.04

**Comment by acidmanifesto** [comment] 2022-05-18 14:27
This stands out to me
'''
0x00000000011e025c in Acore::Assert (file=..., line=<optimized out>, function=..., debugInfo="", message="owner->GetPetStable()->CurrentPet", fmtMessage="Get invalid current pet") at /home/polly/azerothcore/src/common/Debugging/Errors.cpp:112 formattedMessage = "#", '-' <repeats 70 times>, "#\n \n>> ASSERTION FAILED\n\n# Location '/home/polly/azerothcore/src/server/game/Entities/Pet/Pet.cpp:559'\n# Function 'SavePetToDB'\n#"...
'''

**Comment by mpfans** [comment] 2022-05-18 14:35
so repeat it  https://github.com/azerothcore/azerothcore-wotlk/issues/11650  ?

**Comment by UltraNix** [comment] 2022-05-21 08:13
Duplicate of #11683 11650

**Closed by UltraNix** 2022-05-21 08:13 UTC
