### ISSUE TITLE
Obsidian Sancrum Fire WALL !!!

### ISSUE THREAD

**Issue by Djuni1993** [azerothcore/azerothcore-wotlk#18598] opened 2024-03-21 09:31 UTC
### Current Behaviour

Current Behaviour
there is a bug, 10-man raid of Obsidian Sanctum.
the fire wall when from one side is normal, from other side has a bug. when fire wall move to middle, it's disappear.

Extra Notes
No response

### Expected Blizzlike Behaviour

fire wall move to middle, don't disappear.

### Source

Blizzlike 

### Steps to reproduce the problem

100% occurs

### AC rev. hash/commit

bb284c9

### Operating system

Ubuntu 20.04

**Comment by Djuni1993** [comment] 2024-03-21 09:34
https://www.youtube.com/watch?v=vaG0MDBv0zs

**Comment by heyitsbench** [comment] 2024-03-22 01:45
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15428.

**Closed by heyitsbench** 2024-03-22 01:45 UTC
