### ISSUE TITLE
Crash skirmish arena

### ISSUE THREAD

**Issue by Dude100** [azerothcore/azerothcore-wotlk#5290] opened 2021-04-14 20:38 UTC
## STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

## AC HASH/COMMIT:

AzerothCore rev. c49f687668a1 

## OPERATING SYSTEM:

Debian 10 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

## MODULES:

mod-individual-xp  
mod-transmog

## CUSTOMIZATIONS:

When a player joins arena skirmish the server crashes.

https://pastebin.com/5sF8ih4Q

**Comment by Kitzunu** [comment] 2021-04-14 20:42
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5279

**Closed by Kitzunu** 2021-04-14 20:42 UTC
