### ISSUE TITLE
Feature: custom string table

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3785] opened 2020-11-28 00:09 UTC
For custom stuff, we could have a table called `custom_strings` or `custom_text`

```
feature | id | text_english | text_spanish etc...
-------------------------------------
transmog | 1 | Hello | Hola
transmog | 2 | Hello | Hola
barbz_npc | 1 | test | testo
```

this would allow to not bother anymore with custom IDs in all the text tables

this can maybe be applied to other aspects of the game but dunno if worth it

note: maybe this is a bad idea, cause if we start to do this for every table, we will end up with custom_creature, custom creature_template, custom_item_template etc.....

**Comment by Kitzunu** [comment] 2023-08-26 23:32
Basically duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/754

**Closed by Kitzunu** 2023-08-26 23:32 UTC
Labels: Suggestion
