### ISSUE TITLE
[Ashenvale] Ilkrud Maghtrull's minion does not engage combat

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6885] opened 2021-07-11 07:24 UTC
Original report: https://github.com/chromiecraft/chromiecraft/issues/1163

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Ilkrud Maghtrull's minion does not engage combat. She remains stationary as if she were a neutral NPC.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Succubus should engage combat along with her master. Moreover, she should be aggressive on pull range, not neutral.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Fire scar Shrine
2. Engage Ilkrud without damaging the succubus

##### EXTRA NOTES:

**Proof:**
https://www.youtube.com/watch?v=R9ILnKuMwl4

**Ilkrud Maghtrull IDs:**

Guid 32439
Entry 3664

**Succubus IDs:**
GUID 0
Entry 10928

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 920825b7594e) :

![WoWScrnShot_071121_102043](https://user-images.githubusercontent.com/82579073/125186266-08dee680-e232-11eb-9f14-8ef77f409721.jpg)
![WoWScrnShot_071121_102104](https://user-images.githubusercontent.com/82579073/125186273-198f5c80-e232-11eb-8435-6552148f61ca.jpg)

**Comment by Azcobu** [comment] 2021-07-11 08:17
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6239

**Closed by Azcobu** 2021-07-11 08:17 UTC
Labels: 20-29, Confirmed
