### ISSUE TITLE
NPC has wrong model

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#20304] opened 2024-10-26 18:25 UTC
### Current Behaviour

![Screenshot_6](https://github.com/user-attachments/assets/44d889cd-1d71-46a7-885f-7c2c69e24e4d)

25115
![Screenshot_7](https://github.com/user-attachments/assets/0196b503-6bfa-41bf-a7a5-a58a5541baff)

24938
![Screenshot_8](https://github.com/user-attachments/assets/cd87d552-7c88-4fdd-8033-a65d610ede60)

### Expected Blizzlike Behaviour

![Screenshot_5](https://github.com/user-attachments/assets/6e6d3108-6aec-41ce-bfcd-4a6ec23afd91)

### Steps to reproduce the problem

1. .go xyz 12923 -6927 4 530

### Extra Notes

Used AC Data v16 enUS https://github.com/wowgaming/client-data/releases/tag/v16
and fresh server installation with all current updates

### AC rev. hash/commit

2ebbd5648857

### Operating system

Windows

### Custom changes or Modules

no

**Comment by heyitsbench** [comment] 2024-10-26 18:31
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/10795.

**Closed by heyitsbench** 2024-10-26 18:31 UTC
