### ISSUE TITLE
[server]world server 1101

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13632] opened 2022-11-01 12:12 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/712845fee81a29b6ba707a2ab30f14c7

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/77a52b8001ba6292b87138471deb7d8aa7b84e4b

### Operating system

Ubuntu20.04

**Comment by acidmanifesto** [comment] 2022-11-01 12:44
Do u have any modules dealing with auction house running by chance?

This is catching my attention specifically.

```
auctionLisingThread = warning: 557070.541736 RTTI symbol not found for class 'std::_Sp_counted_deleter<std::thread*, main::$_14, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'557070.541742 warning: 557070.541821 RTTI symbol not found for class 'std::_Sp_counted_deleter<std::thread*, main::$_14, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'557070.541823 
```

**Comment by mpfans** [comment] 2022-11-01 12:45
only anticheat module

**Comment by acidmanifesto** [comment] 2022-11-01 13:04
> only anticheat module

im not seeing the anticheat module being listed in any part of the crash log you posted so we can rule that out. i see it saying its a prepared statement, but not entirely sure what. so i am going to see if i can take some time in looking into this in depth for you and see what the issue could be.

For comparison we are not having this issue on CC at the moment, however, CC has not opened up other expansion areas like you have already on your end.

**Comment by acidmanifesto** [comment] 2022-11-01 13:25
@mpfans 
All i can see is that there is a error executing a PreparedStatement 103680.
The issue is, we only have 455 character prepared statements. technically 456 if you count the max
https://github.com/azerothcore/azerothcore-wotlk/blob/5a7822282f2e96304892376343e5f8f5c9334d8f/src/server/database/Database/Implementation/CharacterDatabase.h#L31-L524

However, i am seeing references to instances in that log as well.
which may be related to https://github.com/azerothcore/azerothcore-wotlk/commit/a6a2ca8ef76716f5b58b4ed2ae53d0bde424775b#diff-642c906075729a1eb0ec3dcdcf01e08de47d00ca88464b74b876f14f468f086e

Which is the gameobject saving that was implemented some time ago but only effects 4 instances:
Deadmines
Gnomeregan
Scholomance
Stratholme

Although simular in what it does in regards to the logs I can not say with confidence that commit is the issue.
can you by chance compare your characterdatabase.cpp and characterdatabase.h files to see if there may of been some sort of left over from a previous PR you have tested?

**Comment by acidmanifesto** [comment] 2022-11-01 13:32
Can you show me what rows you for:
216
336
376

in the acore_characters.instance table?

**Comment by mpfans** [comment] 2022-11-01 13:50
`characters.instance` have 3651 rows of data

**Comment by acidmanifesto** [comment] 2022-11-01 13:55
> > 
> 
> guid 216 ? or ?

ID

**Comment by mpfans** [comment] 2022-11-01 13:57
![image](https://user-images.githubusercontent.com/18187177/199250461-4fc96c46-6a92-4b91-822a-35acb941d6ba.png)

**Comment by acidmanifesto** [comment] 2022-11-01 13:58
> ![image](https://user-images.githubusercontent.com/18187177/199250461-4fc96c46-6a92-4b91-822a-35acb941d6ba.png)
> 

 Sorry I meant instance

**Comment by mpfans** [comment] 2022-11-01 14:00
> > ![image](https://user-images.githubusercontent.com/18187177/199250461-4fc96c46-6a92-4b91-822a-35acb941d6ba.png)
> 
> Sorry I meant instance

I know...  no instance id 216

**Comment by acidmanifesto** [comment] 2022-11-01 14:04
> Player character guid?
> 
> 

At this case i am not certain. Lets see what shows up.

**Comment by mpfans** [comment] 2022-11-01 14:15
> > Player character guid?
> 
> At this case i am not certain. Lets see what shows up.

guid 13680 is  a deleted character

![image](https://user-images.githubusercontent.com/18187177/199254477-7aee3f3b-6f57-4f19-ba27-bc6d55037d2b.png)

**Comment by mpfans** [comment] 2022-11-01 14:28
on worldserver.conf   I set `CharDelete.Method = 1`.. so guid 13680 is a deleted character

**Comment by acidmanifesto** [comment] 2022-11-01 15:20
Thanks for that info. I will try to follow up. I need to ask some staffers for some insight

**Comment by acidmanifesto** [comment] 2022-11-01 15:31
> > > Player character guid?
> > 
> > At this case i am not certain. Lets see what shows up.
> 
> guid 13680 is  a deleted character
> 
> ![image](https://user-images.githubusercontent.com/18187177/199254477-7aee3f3b-6f57-4f19-ba27-bc6d55037d2b.png)
> 
> 
> 

I am trying to see how it is all connected. But can u delete that entry to see if it ends the problem? I know you have no way to replicate it. But if the crashing isnt repeated after a certain amount of time we can try to narrow down the issue.

**Comment by mpfans** [comment] 2022-11-02 00:50
> I am trying to see how it is all connected. But can u delete that entry to see if it ends the problem? I know you have no way to replicate it. But if the crashing isnt repeated after a certain amount of time we can try to narrow down the issue.

ok... deleted

**Comment by Kitzunu** [comment] 2022-11-06 17:59
Will close as it is a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13172
And better to contain everything in the same issue.

**Closed by Kitzunu** 2022-11-06 17:59 UTC
