### ISSUE TITLE
The dialogue texts of the guards in the four main cities are not completely localized

### ISSUE THREAD

**Issue by xfxfxff** [azerothcore/azerothcore-wotlk#14904] opened 2023-02-08 14:54 UTC
### Current Behaviour

I use zhCN client to play. I right-clicked a Darnassus Sentinel to open a dialogue menu. In this menu: The auction house, The guild master, the mailbax and The battle master have not been completely localized. Then I went to Ironforge, Stormwind City, Undercity, Orgrimmar and Thunder Bluff. Ironforge, Undercity and Thunder Bluff are the same as Darnassus. Only Stormwind City and Orgrimmar are complete.

PS: I don't know which table in database control those texts. If someone knows please tall me. I want to do further test.
**Darnassus:**
![卫兵对话中的本地化不完整](https://user-images.githubusercontent.com/3389676/217565150-cd72c094-71f0-4860-9335-b37080116301.jpg)
**Ironforge:**
![铁炉堡](https://user-images.githubusercontent.com/3389676/218026542-d20f6534-155b-41af-88e0-432fc6516b9a.jpg)
**Undercity:**
![幽暗城](https://user-images.githubusercontent.com/3389676/218026653-05dd0a45-579a-4155-976a-ace7b1a0614d.jpg)
**Thunder Bluff:**
![雷霆崖](https://user-images.githubusercontent.com/3389676/218026728-1e699a6f-9530-414d-9421-b12a5ccbbb9c.jpg)

### Expected Blizzlike Behaviour

They should show Chinese.

### Steps to reproduce the problem

1. zhCN client
2. right-click any Guard in Darnassus, Ironforge, Undercity or Thunder Bluff to open a dialogue menu.

### AC rev. hash/commit

AzerothCore rev. 7338fc2+ 2023-01-30 18:23:06 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80032
Using CMake version: 3.22.1
Compiled on: Linux 5.15.79.1-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/xfxfx/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/xfxfx/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/xfxfx/azeroth-server/data/mmaps. Total size: 2192910800 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Ubuntu 20.04

**Comment by heyitsbench** [comment] 2023-03-29 13:37
Duplicate of #11333?

**Comment by xfxfxff** [comment] 2023-04-01 15:37
> 

Yes，they are the same question. I didn't find #11333.

**Comment by xfxfxff** [comment] 2023-04-01 15:41
> Duplicate of #11333?
Yes，they are the same question. I didn't find #11333 when I wrote.

**Closed** 2023-04-01 15:45 UTC
Labels: Invalid-Duplicate
