### ISSUE TITLE
[Excessive Threat Generation] by Druids in Flight Form

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#19710] opened 2024-08-24 00:19 UTC
### Current Behaviour

 Druids in Flight Form are generating an abnormal amount of threat, particularly when landing critical hits. Upon landing a critical hit, the druid is generating between 20k and 30k threat, which is significantly higher than expected. A video demonstrating this issue has been attached.

### Expected Blizzlike Behaviour

The amount of threat generated by a critical hit should be proportional to the damage dealt, but within the normal range for the threat system.

### Steps to reproduce the problem

1 Create a druid character.
2 Transform into Flight Form.
3 Perform a critical hit attack on a target.
4 Observe the amount of threat generated.

### Extra Notes

 It is suggested to review the damage table for the Flight Form spell and the threat calculation formula for critical hits. Additionally, it would be beneficial to investigate any potential interactions with auras, equipment effects, or passive abilities that may be affecting threat generation.

### AC rev. hash/commit

.server debug
AC> AzerothCore rev. 30a790117be9+ 2024-08-23 06:38:00 +0200 (master branch) (Unix, Release, Static)
Connected players: 8. Characters in world: 7.
Connection peak: 8.
Server uptime: 6 minute(s) 4 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 1ms
|- Median: 1ms
|- Percentiles (95, 99, max): 4ms, 5ms, 5ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-119-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: npc_gambler.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg
|- mod-duel-reset
|- mod-learn-spells

### Operating system

Ubuntu 22

### Custom changes or Modules

mod-anticheat, mod-breaking-news-override, mod-cfbg, mod-duel-reset, mod-learn-spells

**Comment by heyitsbench** [comment] 2024-08-24 04:45
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/19562.

**Closed by heyitsbench** 2024-08-24 04:45 UTC
