### ISSUE TITLE
Vault of Archavon - Alliance controlled WG, but Horde was able to zone in VOA using glitch

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#2084] opened 2019-07-11 15:37 UTC
Vault of Archavon - Alliance controlled WG, but Horde was able to zone in VOA using glitch

##### SMALL DESCRIPTION:

Vault of Archavon - Alliance controlled WG, but Horde was able to zone in VOA using glitch

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should not be able to glitch inside

##### CURRENT BEHAVIOUR:

Vault of Archavon - Alliance controlled WG, but Horde was able to zone in VOA using glitch.

Glitch: 
https://www.youtube.com/watch?v=y-DoUHNEGhI.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do the same as this: https://www.youtube.com/watch?v=y-DoUHNEGhI. 
2. Get in Vault of Archavon even if ur faction doesnt control Wintergrasp

##### EXTRA NOTES:

Fix glitch
Maybe kick players if there faction isnt controlling Wintergrasp
Or boss immune if raids faction doesnt control Wintergrasp

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5086af8

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by wowmane** [comment] 2019-07-11 18:46
this is for CFBG.

**Comment by poszer** [comment] 2019-07-11 18:50
> this is for CFBG.

Could you stop with random comments not related to PR. As you can see, here is reported map glitch where are players able to enter in Vault of Archavon without controling WG. What CFBG Have with this ? Nothing. I can reproduce it on version without CFBG. So, please stop with your comments since they doesn't make any sense. If you have something smart to report, related to issue in word, than report it. But avoid these random comments everywhere pointing on CFBG!

**Comment by Stoabrogga** [comment] 2019-07-11 23:10
The video is from October 2010, so the behaviour seems to be blizzlike... should this be fixed nevertheless?

**Comment by spinzaku** [comment] 2019-07-12 02:00
> The video is from October 2010, so the behaviour seems to be blizzlike... should this be fixed nevertheless?

Yes please. WG would be meaningless if people just glitch in. Maybe easiest way to fix this?
-Kick raid group if there faction doesn't control WG
-Bosses turned stone/immune if raid group faction doesn't control WG
-fix wall glitch (if its not clientside?)

**Comment by Stoabrogga** [comment] 2019-07-12 07:54
Hmm, can this perhaps be fixed by placing an invisible, impassable game object to prevent the glitch?

**Comment by spinzaku** [comment] 2019-07-12 08:52
> Hmm, can this perhaps be fixed by placing an invisible, impassable game object to prevent the glitch?

if its the whole area where they can glitch in. Then that would beg great.
But if it's just that one specific spot. People will find another wall to glitch in

**Comment by poszer** [comment] 2019-07-12 15:10
Tested, even if they enter inside, they can't attack boss, can't do nothing. If someone find any problem here, just put gob invisible walls around and done

**Comment by spinzaku** [comment] 2019-07-13 05:23
> Tested, even if they enter inside, they can't attack boss, can't do nothing. If someone find any problem here, just put gob invisible walls around and done

okay! as long as they can't attack boss then good

**Comment by poszer** [comment] 2019-07-13 06:20
> > Tested, even if they enter inside, they can't attack boss, can't do nothing. If someone find any problem here, just put gob invisible walls around and done
> 
> okay! as long as they can't attack boss then good

Yeah, they can't attack boss. Closing this issue :+1:

**Closed by poszer** 2019-07-13 06:20 UTC
Labels: Battleground, Priority - Low

**Comment by spinzaku** [comment] 2019-07-13 11:23
But i still think you need to add a GOB fix. hehe but up to u now
