### ISSUE TITLE
(Critical) Mobs don't evade if you try to run away from them

### ISSUE THREAD

**Issue by PadreWoW** [azerothcore/azerothcore-wotlk#20777] opened 2024-11-30 12:10 UTC
### Current Behaviour

Mobs don't evade if you try to run away from them

### Expected Blizzlike Behaviour

Mobs should evade if they too far from spawn point

### Steps to reproduce the problem

Just aggro any mob and try to run away

### AC rev. hash/commit

a22403356c08ae21bdb2e7083fa1ae89c60523f0

### Operating system

win 10

**Comment by sudlud** [comment] 2024-11-30 12:37
probably caused by / duplicate of #5116?

**Comment by TheSCREWEDSoftware** [comment] 2024-11-30 12:40
Are you able to provide any video or the creatures / abilities / class that were present when this issue happened?

**Comment by YggdrasilWotLK** [comment] 2024-12-07 09:49
In the classic beta, mob leashes (effectively, their evade range and timer) was extended by 12 seconds every time the mob hits a player. Not sure if it was the same on WotLK classic but this isn't necessarily "un-blizzlike"

https://classicwow.live/guides/793/leash-behavior?g=classic 
```
If I aggro a gray mob and kite for 10 sec then get hit once, the leash has been extended. I can then resume kiting for another 10 sec, rinse/repeat.
```

**Comment by sihensel** [comment] 2024-12-08 13:52
The leash timer resetting when a mob does damage to the player is definetly not preset on current Classic WoW realms.
Only player actions that generate threat/aggro reset the leash timer (damage, healing/shielding and cc), but not the mob's own damage.
With Azerothcore, it is especially annoying when traversing the world and aggroing a meelee mob - they will chase you until you are dead, no matter the distance, since they can continually hit you which resets their leash timer.

**Comment by heyitsbench** [comment] 2024-12-08 13:56
> The leash timer resetting when a mob does damage to the player is definetly not preset on current Classic WoW realms.

See my comment on the other issue.

**Closed** 2024-12-08 20:04 UTC
