### ISSUE TITLE
Duskwood Mining Nodes all spawn in almost the same location

### ISSUE THREAD

**Issue by NikDidIt** [azerothcore/azerothcore-wotlk#13598] opened 2022-10-30 02:56 UTC
### Current Behaviour

Mining Nodes all spawn in almost the same location

### Expected Blizzlike Behaviour

Mining nodes should be spread out over the zone.

### Steps to reproduce the problem

go to Duskwood - Roland's Doom area.

![image](https://user-images.githubusercontent.com/34872121/198860400-f840e18b-601a-4d29-8845-f27dce387a8a.png)

### AC rev. hash/commit

b0c09a359681 2022-10-23

![image](https://user-images.githubusercontent.com/34872121/198860446-5469110c-cf62-4e56-8315-d3b17b2fdce2.png)

### Operating system

Debian Docker

### Custom changes or Modules

None

**Comment by heyitsbench** [comment] 2022-10-30 03:20
Closing this as a duplicate of #10382 and #10260.

**Closed by heyitsbench** 2022-10-30 03:20 UTC

**Comment by Gultask** [comment] 2022-10-30 03:22
But thanks for reporting, though!

It's been a long-standing issue with AzerothCore DB. What it needs is pooling.
I've made some PRs that includes examples of it for ores if you're interested: https://github.com/azerothcore/azerothcore-wotlk/pull/13597
