### ISSUE TITLE
[server] world crash 0603

### ISSUE THREAD

**Issue by SKingOWN** [azerothcore/azerothcore-wotlk#11949] opened 2022-06-04 03:46 UTC
### Current Behaviour

4 crashes
https://gist.github.com/SKingOWN/236ea78f30313f0deb0596a268761fb0
https://gist.github.com/SKingOWN/d526d91a5caede2ba179e130bf0df7ee
https://gist.github.com/SKingOWN/c25362744de92e37450c4b2ccd9597c5
https://gist.github.com/SKingOWN/192fc2c6ade992cb6b511299fb46aa8d

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

4fbec972a8fe55d73744205322298791ded0c204

### Operating system

Ubuntu 20.04

**Comment by SKingOWN** [comment] 2022-06-04 03:50
Again
https://gist.github.com/SKingOWN/5c42d72dbfaa8a82d13dfa66f7cc4fc8

**Comment by SKingOWN** [comment] 2022-06-04 04:19
I think the crash occurs when a client that has corrupted files connects and sends a packet with non-utf8 data and the crash is raised when this check fails:
```
if (requireValidUtf8 && !utf8::is_valid(value.begin(), value.end()))
        throw ByteBufferInvalidValueException("string", value.c_str());
```

**Comment by SKingOWN** [comment] 2022-06-04 05:41
I've temporarily fixed the crash but I'm still waiting for an optimal solution since I'm not an expert in azerothcore code yet.

**Comment by UltraNix** [comment] 2022-06-04 13:41
Duplicate of #11928

**Closed by UltraNix** 2022-06-04 13:41 UTC
Labels: Priority-Critical, HasBacktrace
