### ISSUE TITLE
[Crafting] Find Herbs Tracking still usable after unlearned Herbalism

### ISSUE THREAD

**Issue by ataniker** [azerothcore/azerothcore-wotlk#7017] opened 2021-07-18 18:57 UTC
### Current Behaviour

Server: **ChromieCraft**
Find Herbs Tracking is still useable with the Minimap Button and Spellbook after unlearning the Skill.
https://i.imgur.com/3F5n6sW.jpg

### Expected Blizzlike Behaviour

Every Tracking skill should be removed after unlearning the associated Gathering Profession.

### Steps to reproduce the problem

I have learned Herbalism up to the 2. skill (around 80-100).
Unlearned Herbalism skill.
Learned Skinning.

### AC rev. hash/commit

no such command on ChromieCraft

### Operating system

Windows 10 x64

## Addons
- Auctionator
- Bagnon
- Postal
- Prat
- Atlas Loot

**Comment by iraizo** [comment] 2021-07-20 18:20
the commit is https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

**Comment by FrancescoBorzi** [comment] 2021-07-21 18:39
@ataniker 

> no such command on ChromieCraft

the command is `.server info` or you can just check the latest commit of https://github.com/chromiecraft/azerothcore-wotlk

Players normally just report to https://github.com/chromiecraft/chromiecraft so they don't have to bother with AC requirements

**Comment by temperrr** [comment] 2021-07-29 05:27
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/1044

**Closed by temperrr** 2021-07-29 05:27 UTC
Labels: ChromieCraft Generic
