### ISSUE TITLE
(Core/Gossip): Click menu error

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#17413] opened 2023-10-04 09:22 UTC
### Current Behaviour

This is a very common mistake, and you can make it happen anywhere
Clicking on the menu has no effect
Sorry, I can't open YouTube here

https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/5440d37c-a8a7-4d62-b89c-89bc543d408c

### Expected Blizzlike Behaviour

It shouldn't get stuck

### Steps to reproduce the problem

1. `.go xyz -8809 578 96 0`
2. Operate like in a video

### AC rev. hash/commit

29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Windows 10 x64

### Custom changes or Modules

No

**Comment by heyitsbench** [comment] 2023-10-04 15:06
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15989.

**Closed by heyitsbench** 2023-10-04 15:06 UTC
