### ISSUE TITLE
Herald Volazj boss phase bug

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#15550] opened 2023-03-23 12:40 UTC
### Current Behaviour

The problem is that it does not enter the phase
and does not copy people

https://user-images.githubusercontent.com/52524476/227205037-e368a708-e77c-4293-83e9-3ebab5fe577d.mp4

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=ts3FHfPXqLQ

### Steps to reproduce the problem

.go c 132298

### AC rev. hash/commit

rev. 2f52fc9a85cd

### Operating system

window server 2019 64bit

### Custom changes or Modules

mod-anticheat
mod-boss-announcer
mod-cfbg
mod-duel-reset
mod-level40
mod-level65
mod-quick-teleport

**Comment by avarishd** [comment] 2023-03-24 06:48
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7796

**Closed by avarishd** 2023-03-24 06:48 UTC
