### ISSUE TITLE
AC Ulduar Hodir boss fight issue

### ISSUE THREAD

**Issue by xclid** [azerothcore/azerothcore-wotlk#5859] opened 2021-05-15 10:03 UTC
**CURRENT BEHAVIOUR:**

Boss Hodir Unable to start fighting, Flash Freeze keeps flashing and can't select.

Video's here.

https://youtu.be/1h4zSnzg7bk

If you need more details, you can contact me on Discord.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The fight is triggered when the player attacks Flash Freeze.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. .gm on
2. .go c 136262
3. .gm off
4. Try to do anything if it can trigger boss fight.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
376a7983b394f5269b9c4538ff987b9f4b418fc2

**OPERATING SYSTEM:**

win10

**MODULES:**

mod-ah-bot
mod-anticheat
mod-cfbg
mod-eluna-lua-engine
mod-individual-xp
mod-transmog

**CUSTOMIZATIONS:**

**Comment by CrazyJDev** [comment] 2021-05-16 15:15
It looks like it's an issue in the Reset call that causes them to constantly despawn and respawn. Going to look into why that's constantly being called.

**Comment by CrazyJDev** [comment] 2021-05-16 20:26
@xclid So I've got it working, but I don't typically don't try to commit changes. The issues was in the IsInRoom call, for whatever reason it simply will not work with ENTRANCE_DOOR. I worked around that by comparing the Y axis in a different way. 

I changed if `(!IsInRoom(&ENTRANCE_DOOR, Axis::AXIS_Y, true)) || !IsInRoom(&EXIT_DOOR, Axis::AXIS_Y, true)`
into: `if (me->GetPositionY() <= ENTRANCE_DOOR.GetPositionY() || me->GetPositionY() >= EXIT_DOOR.GetPositionY())`

The above does unveil another issue which is Hodir not resetting when getting outside of his room, which I fixed by adding `boss_hodirAI::EnterEvadeMode();` before the return call.

**Comment by claudiodfc** [comment] 2021-06-14 00:40
It was me that implemented this and the tester gave a positive feedback on this fight so I'm unsure what's going on. I made the isinroom function to avoid creating the weel over and over but whatever

**Comment by steenburgh** [comment] 2021-06-20 05:52
Confirmed on 725f1cbda08d28d2c717fe02119f731489dd11a7

**Comment by steenburgh** [comment] 2021-06-20 05:52
This makes the boss impossible to kill, so I'm flagging this as Priority: 'High'

**Closed** 2021-09-12 22:12 UTC
Labels: Priority-High, Instance - Raid - Northrend, Fix Included, CORE, Confirmed
