### ISSUE TITLE
Conflagrate causing 1 damage / Warlock destruction

### ISSUE THREAD

**Issue by Drakelol** [azerothcore/azerothcore-wotlk#5289] opened 2021-04-14 16:51 UTC
Conflagrate causing 1 damage / Warlock destruction

Conflagrate Spell is doing only 1 damage, even with high gear
https://wotlkdb.com/?spell=17962

Spell details: Consumes an Immolate or Shadowflame effect on the enemy target to instantly deal damage equal to 60% of your Immolate or Shadowflame, and causes an additional 40% damage over 6 sec.

STEPS TO REPRODUCING THE PROBLEM:

1. Catch a Dummy's target
2.  Cast the spell Immolate
3.  Cast the spell Conflagrate 
4.  Visualize that it will do 1 damage

rev. c05fa1a0a915

**Comment by GMKyle** [comment] 2021-04-14 17:12
There are spells that have issues damaging normal dummies (Shadow Priest: Devouring Plague). If you what a dps/damage test try attacking  the heroic dummy version.

**Comment by Drakelol** [comment] 2021-04-14 17:17
> There are spells that have issues damaging normal dummies (Shadow Priest: Devouring Plague). If you what a dps/damage test try attacking the heroic dummy version.

I tested it on other characters of the same level, and the damage is 1

**Comment by GMKyle** [comment] 2021-04-14 17:56
Herioc Dummy has skull(boss) lvl, also have more HP(the normal dummys has 10 if i remember)

**Comment by Drakelol** [comment] 2021-04-14 17:59
As I said, I have already tested it in different ways, in several dummies and in several characters on the same level

**Comment by GMKyle** [comment] 2021-04-14 18:33
You made me restart my lap -_-  Just joking all good xD, sry but i can't reproduce,I test in orgrimmar with a new char damaging many dummies using Conflagrate, we need some1 else test this, good luck!!

**Comment by Drakelol** [comment] 2021-04-14 18:37
> You made me restart my lap -_- Just joking all good xD, sry but i can't reproduce,I test in orgrimmar with a new char damaging many dummies using Conflagrate, we need some1 else test this, good luck!!

No problems my dear, thank you so much for trying =)
Let's wait for someone to help = D

**Comment by Drakelol** [comment] 2021-04-15 22:02
@Helias  @Kitzunu   sorry to mark you, but can you help me with this problem?

**Comment by Kitzunu** [comment] 2021-04-15 22:05
If I remember I will look in the weekend

**Comment by Drakelol** [comment] 2021-04-15 22:07
> Se eu me lembrar vou olhar no fim de semana

Thank you very much

**Comment by FrancescoBorzi** [comment] 2021-04-16 17:40
@Drakelol are you using a clean AC? any modules or other customisations?

**Comment by Drakelol** [comment] 2021-04-16 17:49
> @Drakelol are you using a clean AC? any modules or other customisations?

Yes,I am using a clean azeroth core and updating along with updates from the azeroth core itself

**Comment by Branel** [comment] 2021-04-18 16:48
Can't reproduce

**Comment by Drakelol** [comment] 2021-04-18 17:08
> Can't reproduce
Are you also having this problem?

**Comment by Kitzunu** [comment] 2021-04-24 15:55
I cannot reproduce this https://github.com/azerothcore/azerothcore-wotlk/commit/26a477dd126c68a46f265b97dd439d9982bba1d1 thereby closing this issue

![image](https://user-images.githubusercontent.com/24550914/115964742-24393000-a526-11eb-89f3-3574a6249db1.png)

**Closed by Kitzunu** 2021-04-24 15:55 UTC
Labels: Not confirmed
