### ISSUE TITLE
[SUGGESTION] progressive server 

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#3774] opened 2020-11-26 15:26 UTC
It would be nice to have a module or events to have a progressive server.

Let me explain. A system that allows to give access patch by patch to WOTLK in a simple and automatic way.

Restricting the continuos to patch 1 and so on.

This includes the :

- dungeons
- raids
- season pvp (stuffs)
- the emblems provided by the group search tool
- pnj who provide the stuffs via the emblems etc...
- etc...

This would make the game more immersive and blizzlike.

I don't know how the development of a module takes place and if it allows to switch from one patch to another without rebooting the server. But the events in game (example: Christmas) could allow to do that automatically depending on the date we select and without server restart.

If this kind of experience is of interest to the peoples. Maybe everyone and me included could put bounty to motivate and reward this hard research and development work.

**Comment by FrancescoBorzi** [comment] 2020-11-26 16:34
@Maurowin I think what you mean is basically what I wrote here: https://github.com/azerothcore/forum/issues/124

@Si1ker as you did this work already, can you help to build such DB migrations?

**Comment by Maurowin** [comment] 2020-11-26 17:54
@FrancescoBorzi In principle, yes! It is to make a progressive server with the outgoing content as on the official one.

**Comment by Voxstrasza** [comment] 2020-11-27 03:16
keep in mind this also involves removing certain items and spells from profession trainers, a lot of research needs to go into it.

**Comment by Maurowin** [comment] 2020-11-27 07:43
It's big work yes !

For season pvp, I'm not sure, but there are NPCs dedicated to each season and other NPCs that group all the stuffs together. So yes, I think there will have to be some restrictions.

**Comment by grimgravy** [comment] 2020-11-29 13:33
@Maurowin, in the database still exists these pvp season.

**Comment by Maurowin** [comment] 2020-12-02 08:45
@grimgravy it disable stuffs of next season ?

**Comment by FrancescoBorzi** [comment] 2020-12-02 10:33
as this is a duplicate of https://github.com/azerothcore/forum/issues/124

let's keep discussing it there

**Closed by FrancescoBorzi** 2020-12-02 10:33 UTC
Labels: Suggestion
