### ISSUE TITLE
Worldserver crashed at connectig  ASSERTION FAILED 

### ISSUE THREAD

**Issue by wthslw001** [azerothcore/azerothcore-wotlk#17582] opened 2023-10-25 15:26 UTC
### Current Behaviour

#----------------------------------------------------------------------#
 
>> ASSERTION FAILED

# Location '/home/WOW/80/azeroth-core-wotlk/src/server/game/Movement/Spline/MoveSpline.cpp:28'
# Function 'ComputePosition'
# Condition 'Initialized()'
 
#----------------------------------------------------------------------#
Segmentation fault

### Expected Blizzlike Behaviour

Nothing

### Steps to reproduce the problem

The server crashes directly during operation.

### AC rev. hash/commit

b3bc89214776f29401f66e5e4fc4a38db2433295

### Operating system

Ubuntu 20.04

**Comment by heyitsbench** [comment] 2023-10-25 15:27
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/17571.

**Closed by heyitsbench** 2023-10-25 15:27 UTC
