### ISSUE TITLE
(DB/creature_template): Death Knight Understudy wrong spell bar order

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#4139] opened 2021-01-02 20:23 UTC
NPC name: [Death Knight Understudy](https://www.wowhead.com/npc=16803/death-knight-understudy)
NPC ID:16803
Location: Naxxramas (Map 533) at Military Quarter

Abilities:
[Blood Strike](https://www.wowhead.com/spell=61696/blood-strike)
[Taunt](https://www.wowhead.com/spell=29060/taunt)
[Bone Barrier](https://www.wowhead.com/spell=29061/bone-barrier)

##### CURRENT BEHAVIOUR:

Currently:
Blood Strike is in **Button 2**
Taunt is in **Button 3**
Bone Barrier is in **Button 4**

![image](https://user-images.githubusercontent.com/61223313/103465775-71d62680-4d04-11eb-8a2f-685223819e49.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As described in https://wowwiki.fandom.com/wiki/Instructor_Razuvious
![image](https://user-images.githubusercontent.com/61223313/103465801-af3ab400-4d04-11eb-8ac1-0a6178172fcf.png)

This can be also confirmed in the TankSpot video for this encounter (4 dic 2008)
https://www.youtube.com/watch?v=8elL14VTND8    **0:12**

##### STEPS TO REPRODUCE THE PROBLEM:

1. Adjust raid difficulty to 10man
2. .go xyz 2812.673 -3089.319 272.425 533 3.300
3. Use an (Obedience Crystal)[https://www.wowhead.com/npc=29912/obedience-crystal] to control a Death Knight Understudy
4. Check the spell positioning on your bar ❌ 

##### EXTRA NOTES:

The spells are well located in creature_template but are not at the moment of taking control over the NPC

```sql
SELECT * FROM `creature_template` WHERE `entry` IN (16803, 29941);
```

![image](https://user-images.githubusercontent.com/61223313/103465932-dd6cc380-4d05-11eb-96ef-2c34a336c356.png)

##### AC HASH/COMMIT:

79aa560

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

HD textures
Legion models

**Comment by Kitzunu** [comment] 2021-01-02 20:42
@Si1ker can you give me a screenshot from the video? Cant check it now but I might know the issue

**Comment by r0m1ntik** [comment] 2021-01-02 20:49
@Kitzunu 
![Снимок экрана 2021-01-02 в 21 49 14](https://user-images.githubusercontent.com/40755539/103466328-67d41800-4d44-11eb-8efe-b2611a7b2755.png)

**Comment by Kitzunu** [comment] 2021-01-02 20:54
I think the issue is that it just skips spell 1 - 3 and squishes them together since they have no values

**Comment by grimgravy** [comment] 2021-01-03 01:59
The current image shows a different way of control than the video. Therefore, there is this error.

**Comment by Kitzunu** [comment] 2023-04-23 11:57
Closing this due to https://github.com/azerothcore/azerothcore-wotlk/issues/16047 being a generic issue

**Closed by Kitzunu** 2023-04-23 11:57 UTC
Labels: Confirmed, Instance - Raid - Northrend
