### ISSUE TITLE
(Docker) Persistent volume for ac-database

### ISSUE THREAD

**Issue by h0lysp4nk** [azerothcore/azerothcore-wotlk#2946] opened 2020-04-26 19:03 UTC
(Docker) Persistent volume for ac-database

##### SMALL DESCRIPTION:

- Running AzerothCore in docker and issuing the command `docker-compose down` or when the container is stopped issuing `docker system prune` will remove the data in the database as their isn't a persistent volume.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- When the container is removed regardless of it being done by docker-compose or the docker command itself the data in the container should persist. This can be done by using a docker volume.

##### CURRENT BEHAVIOUR:

- Issuing the command `docker-compose down` or whilst the container is stopped issuing `docker system prune` will remove all data from the database.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Build AzerothCore with Docker
2. Start the containers
3.  Issue `docker-compose down`
3b. You can also issue `docker-compose stop && docker system prune` to test when the container is down.
4. Start the containers again and you'll notice that the database has been reinitialised.

##### EXTRA NOTES:

I'll be creating a PR shortly with a fix. If this isn't really required feel free to close :)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

cdf518aba1d16e6a45d363859aa073e0c0170edf

##### OPERATING SYSTEM:

- Ubuntu 18.04 LTS

##### MODULES:

- Not relevant

##### OTHER CUSTOMIZATIONS:

- Not relevant

**Comment by FrancescoBorzi** [comment] 2020-04-26 19:25
> Running AzerothCore in docker and issuing the command docker-compose down or when the container is stopped issuing docker system prune will remove the data in the database as their isn't a persistent volume.

this is not a bug, this is how docker container works, to stop a container without destroying it you should use:

> docker-compose stop

there are plenty of guides about how to persist DB servers that run on docker containers on the web, but I agree we should add something to our documentation (even if it's not strictly related to AC).

Closing as it's not a bug

**Comment by FrancescoBorzi** [comment] 2020-04-26 19:30
> Running AzerothCore in docker and issuing the command docker-compose down or when the container is stopped issuing docker system prune will remove the data in the database as their isn't a persistent volume.

this is not a bug, this is how docker container works right? to stop a container without destroying it, shouldn't one use?

```
docker-compose stop
```

but I agree we should add something to our documentation (even if it's not strictly related to AC).

Edit: currently we have this in our Docker FAQ:

![image](https://user-images.githubusercontent.com/75517/80317514-8f153580-8804-11ea-9a01-b23999e60594.png)

**Comment by h0lysp4nk** [comment] 2020-04-26 19:32
Yes, I'm aware of this. But, the problem is if you have the containers stopped and run a command such as `docker system prune` which will remove all inactive containers you'll lose all of the data.

**Comment by FrancescoBorzi** [comment] 2020-04-26 19:53
@h0lysp4nk got it, thanks

**Closed** 2020-05-24 10:35 UTC
Labels: Docker
