### ISSUE TITLE
[Hunter][Spell] Explosive shot should stack with different ranks

### ISSUE THREAD

**Issue by BugSquisher9000** [azerothcore/azerothcore-wotlk#16579] opened 2023-06-17 23:21 UTC
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

[70]

### Current Behaviour

Downranked explosive shots are overriding the previously casted explosive.

### Expected Blizzlike Behaviour

Different ranks should stack.

### Source

www.github.com/JamminL/wotlk-classic-bugs/issues/514](http://www.github.com/JamminL/wotlk-classic-bugs/issues/514

https://www.wowhead.com/wotlk/spell=56344/lock-and-load#comments:id=993102

https://www.youtube.com/watch?v=oapdS8BUCh0&ab_channel=VeramosGaming

Patch 3.3.2

Just tested this with recount. When LnL procs you can cast explosive shot(rank 4) explosive shot(rank 3) explosive shot(rank 4) and it will get all 9 ticks and it does more damage than an explosive shot(rank 4) spam. Very handy when you need that big burst of damage and every second counts.

### Steps to reproduce the problem

Proc Lock n Load and try to cast different ranks right after each other. ( 2>1>2 )

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

"Originally reported https://github.com/chromiecraft/chromiecraft/issues/5787"

**Comment by BugSquisher9000** [comment] 2023-06-17 23:25
day 1 of fixing this

**Comment by heyitsbench** [comment] 2023-06-17 23:29
> day 1 of fixing this

Once again, stop.

**Comment by BugSquisher9000** [comment] 2023-06-17 23:31
> > day 1 of fixing this
> 
> Once again, stop.

stick to your class mate, looks like none reported that melee swing will go off when you bladestorm

**Comment by heyitsbench** [comment] 2023-06-17 23:38
> stick to your class mate, looks like none reported that melee swing will go off when you bladestorm makes me wonder if that is intended or just not to reduce warrior dps to become bitch sunder armor in raids

[Review this.](https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by heyitsbench** [comment] 2023-06-18 00:43
Duplicate of #16480.

**Closed by heyitsbench** 2023-06-18 00:43 UTC
