### ISSUE TITLE
Pets give every boss parry haste

### ISSUE THREAD

**Issue by Joshmash** [azerothcore/azerothcore-wotlk#19964] opened 2024-09-13 16:47 UTC
### Current Behaviour

Pets such as [army of the dead](https://www.wowhead.com/wotlk/spell=42650/army-of-the-dead) or [gnomish battle chicken](https://www.wowhead.com/wotlk/item=10725/gnomish-battle-chicken)  when hitting boss in the face can lead to a parry but then boss gets the ability to parry haste from them

### Expected Blizzlike Behaviour

Boss shouldn't get parry haste mechanic  from [army of the dead](https://www.wowhead.com/wotlk/spell=42650/army-of-the-dead) or [gnomish battle chicken](https://www.wowhead.com/wotlk/item=10725/gnomish-battle-chicken)

### Source

https://www.twitch.tv/mrkingua/clip/EvilSpunkyGnatMau5-XLEPjyG2Yqq6xjU9
Dk cast army of the dead before pull and when battle starts ghouls hitting boss in the face 
![image](https://github.com/user-attachments/assets/0eed98df-52da-4262-93cf-e0b765edfc3d)
Lich King's autoattack speed 1.5 without debuffs

### Steps to reproduce the problem

1. go to the lich king as dk
2. type .cheat power .cheat cooldown
3. cast army of the dead as much as you want
4. make ghouls hit in the face
5. see the result

### AC rev. hash/commit

AzerothCore rev. 06012a4c0029 2024-09-10 12:34:12 +0300(TS branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 22.04.4 LTS

### Custom changes or Modules

List of enabled modules:
|- mod-1v1-arena
|- mod-cfbg
|- mod-congrats-on-level
|- mod-duel-reset
|- mod-globalchat
|- mod-individual-xp
|- mod-npc-spectator
|- mod-pvp-titles
|- mod-transmog

**Comment by heyitsbench** [comment] 2024-09-13 17:49
Seems to be a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/3713.

**Closed by heyitsbench** 2024-09-13 17:49 UTC

**Comment by heyitsbench** [comment] 2024-09-13 19:21
There are no bosses that have parry hasting disabled, see https://github.com/azerothcore/azerothcore-wotlk/pull/19927. If you have evidence that ghouls are not supposed to invoke parry hasting even on bosses that normally do have parry hasting, feel free to provide a source for that.
