### ISSUE TITLE
[server] world server crash 0916

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13034] opened 2022-09-16 14:13 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/bf42892ef4247ca27b08e8af5c989e42

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### Extra Notes

Probably the same as #13010

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d40e3340fb83c8477230269eb6656adaca5b9879

### Operating system

Ubuntu20.04

**Comment by UltraNix** [comment] 2022-09-17 07:46
Duplicate of #13010

**Closed by UltraNix** 2022-09-17 07:46 UTC
