### ISSUE TITLE
[Icecrown Citadel] Combat start dialog with Muradin Bronzebeard are broken

### ISSUE THREAD

**Issue by Alexander990608** [azerothcore/azerothcore-wotlk#11064] opened 2022-03-17 18:25 UTC
### Current Behaviour

Combat start dialog with Muradin Bronzebeard are broken!

### Expected Blizzlike Behaviour

ICC Saurfang combat start dialog Muradin Bronzebeard iit should be running ok.

### Source

https://wowwiki-archive.fandom.com/wiki/Deathbringer_Saurfang?oldid=2386527#Quotes

### Steps to reproduce the problem

1. Go to Icecrown Citadel.
2. Start battle with Deathbringer Saurfang by speaking with Muradin.

### AC rev. hash/commit

0ca0a85

### Operating system

Debian 10 x64

**Comment by heyitsbench** [comment] 2023-07-14 02:43
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/8921.

**Closed by heyitsbench** 2023-07-14 02:43 UTC
