### ISSUE TITLE
[Quest] Vahlarriel's Search - Dalinda Not Spawning

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5593] opened 2021-05-02 10:54 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/506

Currently Dalinda (GUID 26987) sometimes fails to spawn for the quest Vahlarriel's Search (https://classic.wowhead.com/quest=1438/vahlarriels-search) 

Tester's notes - I ran the quest 3 times - the first time worked, the next two times (which were on other characters) there was no sign of her until I used .respawn.

The original report was that she was being killed by mobs, but I tried teleporting directly to her after accepting the quest, and there was no sign of her, no body, and mobs weren't in combat. It seems that she never appeared in the first place.

I also noticed some missing text - for the 'Return to Vahlarriel' quest, she's supposed to say "Elune be with us! Let's make haste from this evil fortress" when you start the escort, and "I will hurry back to Vahlarriel. Finish off those that you can--I should be fine on my own from here." when you complete it. (source: https://github.com/TrinityCore/TrinityCore/issues/22112)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dalinda should be spawned and ready to move her quest chain on.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start the questchain to find Dalinda https://classic.wowhead.com/quest=1437/vahlarriels-search
2. Progress through the questchain until you get tasked to search for her in the Thunder Axe Fortress
3. Try to find her in the right building in the middle (Round room, crystal in the middle)
4. She most likely won't be there, kill all the mobs in the room and wait for her to respawn

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anglerf1sh** [comment] 2021-05-02 13:37
It's not that she doesn't spawn, it's just that you most likely checked on her when she was recently killed and her body despawned (after roughly 10-15 seconds). The .respawn command simply respawned her since she was killed in the last 5 mins or so. I just went there again to check it and as soon as Dalinda spawns she aggros the mobs near her and they start attacking her. I don't think this is the intended behavior. 
![WoWScrnShot_050221_153456](https://user-images.githubusercontent.com/82279027/116815107-4ea96f80-ab5c-11eb-9443-0751531e7d2d.jpg)

**Comment by Azcobu** [comment] 2021-05-02 15:19
Well, can't argue with a screenshot like that. I used a GM command to teleport directly to her after accepting Vahlarriel's Search 3/3 (https://classic.wowhead.com/quest=1438/vahlarriels-search), so thought there couldn't have been the time for her to fight, die, and despawn. Anyway, thanks for the update.

**Comment by anglerf1sh** [comment] 2021-05-02 15:54
The process of spawning, dying and despawning is really fast with her :D

**Comment by Si1ker** [comment] 2021-05-02 18:33
So I'm closing this


No quest accepted - gm off

![image](https://user-images.githubusercontent.com/61223313/116823549-6673fa00-ab42-11eb-91f5-3b2b55fd3a12.png)



quest accepted - gm off

![image](https://user-images.githubusercontent.com/61223313/116823567-7b508d80-ab42-11eb-913d-98266720a6f9.png)


No issue encountered. 🐱

**Closed by Si1ker** 2021-05-02 18:33 UTC
Labels: 30-39
