### ISSUE TITLE
Shattered Sun Marksman

### ISSUE THREAD

**Issue by may-ruz** [azerothcore/azerothcore-wotlk#18644] opened 2024-04-01 02:31 UTC
### Current Behaviour

The Shattered Sun Marksman either appears as a blank model with floating bow weapon or appear as an imp. 

### Expected Blizzlike Behaviour

The Shattered Sun Marksman is supposed to be either appear as Draenei or Blood Elf.

### Steps to reproduce the problem

Visit Shattrath City - Terrace of Light (Outland) & Isle of Quel'Danas (Eastern Kingdoms).

### Extra Notes

Tested with clients using old texture and HD texture pack.
Both clients show the same bug.

### AC rev. hash/commit

AzerothCore rev. 2aaf8474ba7c 2024-03-31 16:59:59 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 9 second(s)
Update time diff: 1ms. Last 500 diffs summary:
Mean: 1ms
Median: 1ms
Percentiles (95, 99, max): 2ms, 4ms, 83ms
Using SSL version: OpenSSL 3.0.11 19 Sep 2023 (library: OpenSSL 3.0.11 19 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 101106
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.1.0-18-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/arthas/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/arthas/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/arthas/azeroth-server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_01_20_00.sql
Latest WorldDatabase update: 2024_03_31_01.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Debian GNU/Linux 12 (bookworm) x86_64

**Comment by heyitsbench** [comment] 2024-04-01 02:49
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/10795.

**Closed by heyitsbench** 2024-04-01 02:49 UTC
