### ISSUE TITLE
Mage Water Elemental sometimes can't be dismissed and can't be resummoned maybe because of distance~

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#1885] opened 2019-05-25 15:01 UTC
Mage Water Elemental sometimes can't be dismissed and can't resummon

##### SMALL DESCRIPTION:

Sometimes dead water elemental can't be dismissed and when we try to summon nothing happens.
but if we were able to dismiss the water elemental, we can summon again 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When a water elemental dies, it should auto dismiss.
Water elemental should still summon even after u can summon again

##### CURRENT BEHAVIOUR:

Sometimes dead water elemental can't be dismissed and when we try to summon nothing happens.
but if we were able to dismiss the water elemental, we can summon again

##### STEPS TO REPRODUCE THE PROBLEM:

1. level a mage 
2. get water elemental talent
3. try using waterelemental, let it die, sometimes u cant dismiss, it should auto dissmiss. after casing water elemental nothing happens

or

try mounting then doing it ?
summon ur water elemental
mount and run away
sometimes it doesnt move
then it cant be summoned again

##### EXTRA NOTES:

I sent a video to Poszer👑 of the actual bug happening

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

Azerothcore rev. ded199dd7e7b+ 

##### OPERATING SYSTEM:

 Ubuntu 16/18 etc.

**Comment by poszer** [comment] 2019-05-25 15:10
Yeah, i saw your video. But i can't reproduce it :thinking:

**Comment by poszer** [comment] 2019-05-25 15:18
Could you please test it without modules, or removing the modules one by one. It can be caused by one of them. Not sure, but i can't reproduce this in any way (Tested in combat, on die, on auto despawn, on coldsnap -> resummon, it works for me without problem).

**Comment by spinzaku** [comment] 2019-05-25 15:37
it might be the same issue, i was able to produce the bug again by:

try mounting then doing it ?
summon ur water elemental
mount and run away
sometimes it doesnt move
then it cant be summoned again

**Comment by poszer** [comment] 2019-05-25 15:38
> it might be the same issue, i was able to produce the bug again by:
> 
> try mounting then doing it ?
> summon ur water elemental
> mount and run away
> sometimes it doesnt move
> then it cant be summoned again

Problem is distance. We should add follow speed like it's done for hunter pets

**Comment by spinzaku** [comment] 2019-05-25 15:42
Try 
letting pet fight monster
run awy far with or w/o mount
will produce same bug. haha

**Comment by lineagedr** [comment] 2019-05-25 22:26
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_mage.cpp#L1049

Remove this check.

**Comment by FrancescoBorzi** [comment] 2019-05-26 17:48
@lineagedr please open a PR

**Comment by Viste** [comment] 2019-06-03 01:26
and get crash )) nice fixing

**Comment by Viste** [comment] 2019-06-03 15:30
and make crash in some cases. nice fixing!

**Comment by lineagedr** [comment] 2019-06-13 23:10
> and make crash in some cases. nice fixing!

I'm positive that removing the 
``if (!pet->IsAlive())`` line will not cause a crash. I've had it on my core for over an year now and I have no encountered any crashes. Post crash log.

**Comment by spinzaku** [comment] 2019-07-11 20:30
does 
if (!pet->IsAlive())
fix this 100%?

**Comment by Voxstrasza** [comment] 2020-11-28 04:13
Cannot reproduce as of 3`7d1f2be4729`.

Water Elemental seems to have been reworked in December 2019.

Closing.

**Closed by Voxstrasza** 2020-11-28 04:13 UTC
Labels: CORE, Class - Mage, Priority - High
