### ISSUE TITLE
Lament of the Highborne contains HTML code ingame

### ISSUE THREAD

**Issue by Flerex** [azerothcore/azerothcore-wotlk#325] opened 2017-01-13 22:34 UTC
**Description**: The item _Lament of the Highborne_ contains HTML not parsed in the game.

**Current behaviour**: http://imgur.com/FPWEBFE

**Expected behaviour**: The HTML code should be parsed

**Steps to reproduce the problem**:

.additem 30632

**Branch(es)**: master

**AC hash/commit**:  e30ae1d4c329b8a203ed0d75b6eccccef30cba66

**Modules**:  No

**Other Customizations**: No

**Comment by lineagedr** [comment] 2017-01-13 22:38
lmao

**Comment by Flerex** [comment] 2017-01-13 22:38
#topPriority

**Comment by markvetwow** [comment] 2017-01-25 16:17
Just delete the backslash in first <br> tag.  Table page_text id = 2990.

**Comment by sucofog** [comment] 2017-02-09 13:12
Not a valid bug, is problem of locales, i got mine working fully:

![image](https://cloud.githubusercontent.com/assets/734950/22784717/7a69f3c0-eed1-11e6-9207-0d729af7ccb4.png)

![image](https://cloud.githubusercontent.com/assets/734950/22784736/90227098-eed1-11e6-927a-f119a4b4127f.png)

![image](https://cloud.githubusercontent.com/assets/734950/22784783/b8701ed8-eed1-11e6-8655-d68f6431f329.png)

Latest revision of AC.

**Comment by starrheld** [comment] 2017-02-10 09:45
Same as @sucofog - so please close this issue down.
Can't reproduce..

**Closed** 2017-02-10 10:37 UTC
Labels: priority: low
