### ISSUE TITLE
[server]world server crash 0818

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#17029] opened 2023-08-18 09:50 UTC
### Current Behaviour

crash log :
https://gist.github.com/mpfans/d7a4afbd7962568ca3bc75706f3bdc78

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/4f015d09678038be49e9d12114c3147e499d82ef

### Operating system

Ubuntu20.04

**Comment by walkline** [comment] 2023-08-18 11:41
I couldn't reproduce it, but I know that this crash as well as this one - https://github.com/azerothcore/azerothcore-wotlk/issues/16180 related to the 27258 creature - Wintergarde Gryphon - (guid 17388398618590878562 from the logs).

I tried to reproduce it, but without luck.

Maybe someone have an idea (or better luck) how to reproduce it, you can use this guidance:
```
.tele wintergardekeep
.quest add 12237
Use whistle.
Mount gryphon.
Do something...
Exit vehicle -> crash (couldn't reproduce).
```

**Comment by walkline** [comment] 2023-08-18 11:52
And this one the same crash - https://github.com/azerothcore/azerothcore-wotlk/issues/16375, Wintergarde Gryphon again (guid 17388398618590892590 - entry 27258).

**Comment by mpfans** [comment] 2023-08-18 14:20
> And this one the same crash - #16375, Wintergarde Gryphon again (guid 17388398618590892590 - entry 27258).

```.tele wintergardekeep
.quest add 12237
Use whistle.
Mount gryphon.
Do something...
Exit vehicle -> crash (couldn't reproduce).```

Can this be reproduced?

**Comment by walkline** [comment] 2023-08-18 14:31
I couldn't reproduce it.

However, based on your crash log, it is highly probable that your player performed actions similar to the steps I described. Would you consider testing those steps on your end?

**Comment by mpfans** [comment] 2023-08-18 14:46
Tested once but did not reproduce. I need to test multiple times on the testing server

**Comment by walkline** [comment] 2023-08-18 19:42
It's difficult to reproduce, and I believe it becomes easier to replicate under conditions of intensive RAM memory usage, such as in a production environment with high online.

Nevertheless, I have identified the root cause, and should be fixed here - https://github.com/azerothcore/azerothcore-wotlk/pull/17032.

**Closed** 2023-08-19 20:30 UTC
