### ISSUE TITLE
[Buffs] Wrong stacking behavior for Totem of Wrath / Demonic Pact

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3790] opened 2020-11-28 10:07 UTC
CURRENT BEHAVIOUR:
[Demonic Pact](https://wotlkdb.com/?spell=47240) does not overwrite [Totem of Wrath](https://wotlkdb.com/?spell=57722) if the bonus spelldamage gained from [Demonic Pact](https://wotlkdb.com/?spell=47240) is lower than the 280SP provided by [Totem of Wrath](https://wotlkdb.com/?spell=57722).

In theory it is possible to have the whole raid buffed with both a 280SP [Totem of Wrath](https://wotlkdb.com/?spell=57722) AND a 279SP [Demonic Pact](https://wotlkdb.com/?spell=47240) at best.

While a warlock usually has more than 2700SP in later stages of the game, they can just lower the points spent on [Demonic Pact](https://wotlkdb.com/?spell=47240) to keep the bonus below 280 SP and prevent it from overwriting  the totem.

EXPECTED BLIZZLIKE BEHAVIOUR:
Totem of Wrath and [Demonic Pact](https://wotlkdb.com/?spell=47240) both provide spellpower. They should overwrite each other / only the stronger one should be active since they belong to the same group of buffs.

STEPS TO REPRODUCE THE PROBLEM:
- Group a Warlock with 2400SP or less and 5/5 [Demonic Pact](https://wotlkdb.com/?spell=47240) and an Elemental Shaman.
- (Alternatively spec less points to keep the bonus from [Demonic Pact](https://wotlkdb.com/?spell=47240) below 280SP)
- Make the Elemental Shaman cast [Totem of Wrath](https://wotlkdb.com/?spell=57722), granting the 280 SP bonus to both toons.
- Let the warlocks pet attack a dummy until it crits, providing the [Demonic Pact](https://wotlkdb.com/?spell=47240) on top of [Totem of Wrath](https://wotlkdb.com/?spell=57722)

EXTRA NOTES:
Recasting [Totem of Wrath](https://wotlkdb.com/?spell=57722) always succesfully overwrites a weaker [Demonic Pact](https://wotlkdb.com/?spell=47240). Just not the other way around as described above.

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by Kitzunu** [comment] 2020-12-10 01:15
Easy fix with spell groups in db

**Comment by Si1ker** [comment] 2021-09-15 23:52
Duplicate of #3790

**Closed by Si1ker** 2021-09-15 23:52 UTC

**Comment by 55Honey** [comment] 2021-09-16 07:34
@Si1ker how is this a duplicate of itself?

**Comment by Si1ker** [comment] 2021-09-16 09:54
> @Si1ker how is this a duplicate of itself?

@55Honey edited !
