### ISSUE TITLE
[server] world server crash 1016

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13427] opened 2022-10-16 05:20 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/07c4f226726b02d8a4ad7cc68d604b8d

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

7ee14d44bf2384960edbcd05afaee30af345f0f1

### Operating system

Ubuntu20.04

**Comment by UltraNix** [comment] 2022-10-22 07:49
Duplicate of #13172

**Closed by UltraNix** 2022-10-22 07:49 UTC
Labels: Invalid-Duplicate, Priority-Critical, HasBacktrace
