### ISSUE TITLE
Judgement of light/wisdom proc have a cd

### ISSUE THREAD

**Issue by Joshmash** [azerothcore/azerothcore-wotlk#20236] opened 2024-10-17 22:53 UTC
### Current Behaviour

Auto attacking target with judgement of [light](https://www.wowhead.com/wotlk/spell=20271/judgement-of-light)/[wisdom](https://www.wowhead.com/wotlk/spell=53408/judgement-of-wisdom) aura will only proc once per 3-4 sec

### Expected Blizzlike Behaviour

Judgement of [light](https://www.wowhead.com/wotlk/spell=20271/judgement-of-light)/[wisdom](https://www.wowhead.com/wotlk/spell=53408/judgement-of-wisdom) should not have cd on proc

### Source

https://www.youtube.com/watch?v=2z_CJ-JN4Ok 1:57 prot warrior gets heal from judgement 2 times in less then a  1 sec

### Steps to reproduce the problem

1. use judgement of [light](https://www.wowhead.com/wotlk/spell=20271/judgement-of-light)/[wisdom](https://www.wowhead.com/wotlk/spell=53408/judgement-of-wisdom)
2.  attack target of your judgement
3. see the result 

### AC rev. hash/commit

AzerothCore rev. dfa92434ec30 2024-10-16 22:20:46 +0300 (TS branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 22.04.4 LTS

### Custom changes or Modules

List of enabled modules:
|- mod-1v1-arena
|- mod-congrats-on-level
|- mod-duel-reset
|- mod-globalchat
|- mod-individual-xp
|- mod-npc-spectator
|- mod-pvp-titles
|- mod-transmog

**Comment by heyitsbench** [comment] 2024-10-17 23:05
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/4209.

**Closed by heyitsbench** 2024-10-17 23:05 UTC
