### ISSUE TITLE
[Barrens] Razormane Hunter loses rogue's Sap after his pet being attacked

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6294] opened 2021-06-10 04:30 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/825

##### CURRENT BEHAVIOUR:

Razormane Hunter loses rogue's Sap after his pet being attacked by player (rogue).

Razormane Hunter: https://wowgaming.altervista.org/aowow/?npc=3265
Razormane Wolf: https://wowgaming.altervista.org/aowow/?npc=3939

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Razormane Hunter should not lose rogue's Sap after his pet being attacked by player.

##### SOURCE:

According to ability description https://wowpedia.fandom.com/wiki/Sap "Sap does not have a chance to break early, always lasting the full duration unless the sapped target is hit." hitting hunters pet should not brake it.
##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Barrens, near 55 ; 26, and find a Razormane Hunter.
2. Sap(rogue ability) the Razormane Hunter then attack his Wolf. Now Hunter is losing sap

##### EXTRA NOTES:

This problem may occured with other npcs with pet. Now I'm not able to check it on other npcs due low lvl character.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 28664a2f9bbf):

![WoWScrnShot_061021_071314](https://user-images.githubusercontent.com/82579073/121464749-20217e80-c9bd-11eb-8301-ac638c4d2da1.jpg)
![WoWScrnShot_061021_071627](https://user-images.githubusercontent.com/82579073/121464778-316a8b00-c9bd-11eb-8647-773429b87d72.jpg)
![WoWScrnShot_061021_072041](https://user-images.githubusercontent.com/82579073/121464816-447d5b00-c9bd-11eb-93ae-3d7847c5a942.jpg)

**Comment by Eldarix** [comment] 2021-06-10 04:31
It took me several attempts but I was able to reproduce it and confirm it.

**Comment by necropola** [comment] 2021-06-10 10:22
Duplicate of #4790 
and the correpsonding CC issue https://github.com/chromiecraft/chromiecraft/issues/191
whcih were both closed for whatever reason

**Closed** 2021-10-05 01:50 UTC

**Comment by claudiodfc** [comment] 2021-12-14 12:22
Might be related to PetAI/GuardianAI.
