### ISSUE TITLE
Pets aggro on right clicking

### ISSUE THREAD

**Issue by patou01** [azerothcore/azerothcore-wotlk#8698] opened 2021-10-23 06:31 UTC
### Current Behaviour

If you right-click a mob, your pet will run to it and attack it.

If you right click an NPC pet, the mob will run to you. https://drive.google.com/file/d/1ttD8yw145oxmJ1VatmkNyi2Uj6bo8xEs/view?usp=sharing

### Expected Blizzlike Behaviour

The pets should only attack upon being in combat or being told to do so. ie after a bolt has been fired (or hit?) or a gun shot.

### Steps to reproduce the problem

1. Use a warlock
2. summon pet
3. right click a mob with pet in defensive

### AC rev. hash/commit

1101f9dd2a8f7c049b728ddb5302997e00dc3038

### Operating system

win10 x64

**Comment by Shineslippers** [comment] 2021-12-08 15:20
This report i will close as duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/8669

**Closed by Shineslippers** 2021-12-08 15:20 UTC
Labels: Priority-High
