### ISSUE TITLE
Server Crash while killing Ango'rosh Mauler/Souleaters in Zangarmarsh

### ISSUE THREAD

**Issue by Loopher** [azerothcore/azerothcore-wotlk#19928] opened 2024-09-10 06:08 UTC
### Current Behaviour

Killing the Ango'rosh Maulers's and Souleaters near Overlord Gorefist's hut, the server will crash without warning.   When it comes backup, the database has rolled back to a period 5 minutes before the crash.

Quest: Us Or Them
Zone: Zangarmarsh

### Expected Blizzlike Behaviour

Killing the mobs, should give you credit on the "Us Or Them" quest and the server should remain online.

### Steps to reproduce the problem

1. Fly to the floating island in the North West section of the map.
2. Go to Overlord Gorefist's hut and begin killing the Ango'rosh Maulers's and Ango'rosh Souleaters.
3. Typically takes 4 or 5 mobs to die before the server crashes.

### AC rev. hash/commit

AzerothCore rev. f8a28b6883f7 2024-08-30 22:38:08 +0800 (Playerbot branch) (Unix, Release, Static)
Connected players: 4. Characters in world: 1103.
Connection peak: 5.
Server uptime: 24 minute(s) 5 second(s)
Update time diff: 11ms. Last 500 diffs summary:
|- Mean: 105ms
|- Median: 102ms
|- Percentiles (95, 99, max): 216ms, 240ms, 373ms
Using SSL version: OpenSSL 3.0.13 30 Jan 2024 (library: OpenSSL 3.0.13 30 Jan 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 101106
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.1.0-23-amd64
Worldserver listening connections on port %u
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-account-mounts
|- mod-ah-bot
|- mod-autobalance
|- mod-no-hearthstone-cooldown
|- mod-playerbots

### Operating system

Debian 6.1.99-1 (2024-07-15) x86_64

### Custom changes or Modules

List of enabled modules:
|- mod-account-mounts
|- mod-ah-bot
|- mod-autobalance
|- mod-no-hearthstone-cooldown
|- mod-playerbots

**Comment by manstfu** [comment] 2024-09-10 07:46
Can't reproduce on rev. 6f5b504e4cfa
![image](https://github.com/user-attachments/assets/e36754d2-8624-48f3-8ecd-b044b8b10d8f)

**Comment by vanilla20002** [comment] 2024-09-11 12:10
There was no collapse

**Comment by Nyeriah** [comment] 2024-09-11 17:25
Please post a crash log when reporting crashes. Closing as it can't be reproduced and has no log.

**Closed by Nyeriah** 2024-09-11 17:25 UTC
