### ISSUE TITLE
loot bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#7444] opened 2021-08-19 09:24 UTC
### Current Behaviour

Players do not enter the dungeon/raid ,can enter the dungeon after killing the boss, can pick up items dropped by the boss

### Expected Blizzlike Behaviour

If you are not involved in killing, you will not be able to pick up any items, including gold

### Steps to reproduce the problem

1. character A and character B form a team
2. character A enter any dungeon/raid and kill a boss(don't touch the boss's corpse after killing)
3. character B enter the same dungeon as character A,then walk to character A
4. character A touch the boss corpse
5. character B can participate in picking

### AC rev. hash/commit

AzerothCore rev. 6ff9b21b736c+ 2021-08-13 15:49:13 +0000 (master branch) (Unix, RELWITHDEBINFO, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80025
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-73-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
Using World DB: ACDB 335.3
Using World DB Revision: 2021_08_13_01
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

ubuntu 20.04

### Custom changes or Modules

none

**Comment by mpfans** [comment] 2021-08-19 09:25
@FrancescoBorzi @UltraNix  This is a serious bug,need to raise priority

**Comment by UltraNix** [comment] 2021-08-19 09:39
```
character B can participate in picking
```
What do you mean? Character B can loot the corpse or maybe can greed/need on items?

**Comment by mpfans** [comment] 2021-08-19 09:43
> ```
> character B can participate in picking
> ```
> 
> What do you mean? Character B can loot the corpse or maybe can greed/need on items?

yes .. but need character A touch the corpse of the boss first

**Comment by Kitzunu** [comment] 2021-08-19 11:01
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/2104 which also has bounty on it.

**Closed by Kitzunu** 2021-08-19 11:01 UTC
Labels: Priority-High
