### ISSUE TITLE
Dustwallow Marsh - Firemane Drakes on Alcaz Island Missing Patrol Patterns

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6237] opened 2021-06-05 14:17 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/785

Firemane Drakes (https://wowgaming.altervista.org/aowow/?npc=23969) on ALcaz Island are stationary and do not fly around in the air.
![firemanedrake](https://user-images.githubusercontent.com/80769357/120890429-dfafb280-c602-11eb-8072-7647709b2338.jpg)

GUID 15318, 12813, 17427, 17284, 18574

Tester: confirmed. The drakes are mostly meant to be unattackable scenery so it doesn't really affect gameplay, but it's not Blizzlike.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Firemane Drakes should be flying around in a patrol pattern.

##### SOURCE:

https://tbc.wowhead.com/npc=23969/firemane-drake#comments

https://youtu.be/dOJTj0Ax2Go?t=96

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2. Observe stationary drakes

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by heyitsbench** [comment] 2023-10-01 06:07
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/3781?

**Closed** 2023-10-01 07:12 UTC
Labels: 30-39, Priority-Low, Needs sniff
