### ISSUE TITLE
[Quest] favor for krazek (quest id 627)

### ISSUE THREAD

**Issue by declart** [azerothcore/azerothcore-wotlk#18621] opened 2024-03-28 14:17 UTC
### Current Behaviour

Lesser bloodstone deposit, seem to not be located where they are supposed to be.
It seems they are spawning after server restart, but not respawing as soon as someone pick them up, currently making this quest undoable.

### Expected Blizzlike Behaviour

Lesser bloodstone deposit, must be avaible even if don't have the quest.

### Source

https://www.wowhead.com/classic/it/item=4278/lesser-bloodstone-ore#english-comments

### Steps to reproduce the problem

1. go Arathi coordinate 85.6 32.5.
2. try to find them, eventually pick them up.
3. see if they will respawn.

### AC rev. hash/commit

AzerothCore rev. 02cf369fe239

### Operating system

windows 10 x64

**Comment by heyitsbench** [comment] 2024-03-28 16:04
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5912.

**Closed by heyitsbench** 2024-03-28 16:04 UTC
