### ISSUE TITLE
BG Alterac Valley (low lvl) bosses die.

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#2453] opened 2019-11-18 15:23 UTC
Bosses from both side die every second and respawn (loop). On Alterac Valley before 80lvl version.
And additional: no main gate if clear game cache and go on Alterac Valley.

##### STEPS TO REPRODUCE THE PROBLEM:
1. creat character, ".level 50" and ".debug bg" go Alterac Valley.
2. go to bosses room.

modules:
Eluna-master.zip
mod-1v1-arena-master.zip
mod-ah-bot-master.zip
mod-autobalance-master.zip
mod-duel-reset-master.zip
mod-eluna-lua-engine-master.zip
mod-instance-reset-master.zip
mod-npc-talent-template-master.zip
mod-random-enchants-master.zip
mod-transmog-master.zip

**Comment by Helias** [comment] 2019-11-18 15:39
With the level 50 I can't see the BG, so I used a character lvl 60.
Anyway, I can't reproduce this bug, probably one of the modules cause it?

**Comment by Mitradis** [comment] 2019-11-18 18:13
On 60 lvl no problem YOU MUST BE 51 LVL

**Comment by Helias** [comment] 2019-11-18 18:41
At level 51 the bosses still seem fine for me.

Test this in a clean azerothcore.

Confirmed the problem about main gate

**Comment by Mitradis** [comment] 2019-11-18 20:07
yeah, its autobalance module. Just need add npc from this bg in AutoBalance.DisabledID list.

**Comment by Helias** [comment] 2019-11-18 20:50
I will fix the missing gate

**Comment by Mitradis** [comment] 2019-11-18 20:57
i am add Entry id in AutoBalance.DisabledID and this not help....

**Comment by Helias** [comment] 2019-11-18 21:32
Ok, but that is a problem about the auto balance module, so you need to open a issue in the module repo for that.

**Comment by Helias** [comment] 2019-11-18 21:41
It's probably a sort of cache problem, the server spawn it but the client didn't see until reload.

If I delete cache, open one client with one account and join AV and afterwards open a second account and join AV, the second one will see the gate.

Unfortunately the first one can bypass the gate as they aren't spawned, it's really strange.


![immagine](https://user-images.githubusercontent.com/519778/69096267-5eaabd80-0a54-11ea-94f3-8fc9d9bee007.png)

**Comment by Zausender** [comment] 2019-11-18 22:10
It's old issue (about doors). Also, if you leave that place while the doors isn't opened, you will be teleported back in some seconds on starting position.

**Comment by Helias** [comment] 2019-11-18 22:13
@Zausender I'm working on it, probably I fixed this problem.
About the teleport, yes, the BGs working in this way, if you use `.gm on` and remove the door in any BGs you will be teleported if you go towards the enemy base.

**Comment by Helias** [comment] 2019-11-18 22:38
Here the fix: https://github.com/azerothcore/azerothcore-wotlk/pull/2456
Test if you can :wink:

**Comment by Mitradis** [comment] 2019-11-18 22:56
good, work =)
And i am fix Autobalance DisabledID here https://github.com/azerothcore/mod-autobalance/issues/28

**Comment by Helias** [comment] 2019-11-19 14:11
Sorry but the issue should remain open until the fix will be merged to master.

**Comment by Mitradis** [comment] 2019-11-19 14:53
sory, im new in GitHub. i make Fork and add all PR with "To Be Merge" for testing. Now i can better test all PR.

**Comment by FrancescoBorzi** [comment] 2019-11-19 15:22
@Mitradis you can also just follow this: http://www.azerothcore.org/wiki/How-to-test-a-PR

**Comment by Helias** [comment] 2019-12-06 16:03
This issue should be remain open UNTIL [this PR](https://github.com/azerothcore/azerothcore-wotlk/pull/2456) won't be merged in the master branch of azerothcore-wotlk repo.

**Closed** 2019-12-12 06:47 UTC
Labels: Confirmed
