### ISSUE TITLE
[NPC]Goblin Commoners spawned in Booty Bay during no active events #640

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#5834] opened 2021-05-14 04:52 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

"Originally reported https://github.com/chromiecraft/chromiecraft/issues/640"

There are two (https://wowgaming.altervista.org/aowow/?npc=20102) Goblin Commoners spawned at alliance flight master in Booty Bay, GUID 726 & 727
![commoner](https://user-images.githubusercontent.com/80769357/118162039-95cb1680-b420-11eb-9a0e-a2f7a7efff93.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Goblin Commoners should only be spawed during holiday events.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Check that no holiday event is currently active (no Midummer Fire Festival, No Pilgrims, No Noblegarden etc...)
2. Go to Booty Bay Alliance Flightmaster or Teleport to provided GUID
2. Observe the two Goblin Commoners

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

--

I was opening a thread about it just when I saw that someone had already done it :)

Confirmed and reproduced on a local AC server :

![WoWScrnShot_051421_073207](https://user-images.githubusercontent.com/82579073/118223534-343f9200-b48a-11eb-973c-0fa5c1b92a7a.jpg)
![WoWScrnShot_051421_074454](https://user-images.githubusercontent.com/82579073/118223552-3bff3680-b48a-11eb-891b-02241f783660.jpg)
![WoWScrnShot_051421_074526](https://user-images.githubusercontent.com/82579073/118223561-40c3ea80-b48a-11eb-9c86-b9590e3ff564.jpg)
![WoWScrnShot_051421_074545](https://user-images.githubusercontent.com/82579073/118223568-44f00800-b48a-11eb-94d7-0b320381ea42.jpg)

**Comment by Helias** [comment] 2021-05-15 22:28
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/4330 and https://github.com/azerothcore/azerothcore-wotlk/issues/4335
I opened a PR, but I have to rewrite different part, I don't know when I'll have the time, anyways, this issue is duplicate, so I am closing this

**Closed by Helias** 2021-05-15 22:28 UTC
Labels: ChromieCraft Generic, Confirmed, Help wanted, Priority - Low
