### ISSUE TITLE
Feature: Interval spawn time for creatures

### ISSUE THREAD

**Issue by Efymer** [azerothcore/azerothcore-wotlk#7592] opened 2021-08-27 18:50 UTC
### Describe your feature request or suggestion in detail

There are some cases where the spawn times of a creature needs to be an interval.
To handle spawn time for some rares for example (described in this issue: https://github.com/azerothcore/azerothcore-wotlk/issues/7588):

![image](https://user-images.githubusercontent.com/79163132/131175261-2a185cbc-6c1f-4ac7-961f-20507d38a796.png)

The current implementation in AzerothCore is a static value, which is an impediment in order to implement those blizzlike respawn times.

### Describe a possible solution to your feature or suggestion in detail

Right now AzerothCore uses a `spawntimesecs` field under the creature table.

**My proposal is to implement it the same way vMaNGOS handles it:**
In the `creature` table, there are two fields regarding spawn time `spawntimesecsmin` and `spawntimesecsmax`.

**Comment by JamesGent** [comment] 2021-08-31 09:46
What book is this table from?

**Comment by dantav** [comment] 2021-11-09 11:58
That would make the respawns more life like, maybe even bliz like, not sure thats how it was done. Maybe also add a global config to scale the corpse/mob respawn timer. I implemented something like that in my fork.

**Comment by Gultask** [comment] 2022-10-31 21:25
Closing due to duplicate of: https://github.com/azerothcore/azerothcore-wotlk/issues/5751

**Closed by Gultask** 2022-10-31 21:25 UTC
Labels: ChromieCraft Generic, Suggestion, Priority-Medium
