### ISSUE TITLE
Bug [core] Pet stuck in warsong gulch [$35]

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4603] opened 2021-02-18 13:18 UTC
##### ISSUE: FACTION SIDE: 

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)
**Hunters and Warlocks**
##### CONTENT PHASE:
 Every Content Phases, not linked to a specific level

##### SMALL DESCRIPTION:
If you join WG with your pet, 100% of time when you get down from the hill near the Alliance Graveyard, your pet stuck on the top of the hill and it cannot follow you. (Take a look of the picture below)
![WoWScrnShot_021821_133921](https://user-images.githubusercontent.com/78354696/108358820-780a5e80-71ef-11eb-855e-49e2175e8530.jpg)

Spell: Every PETS
Zone: Warsong Gulch

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pets should follow their masters without stucking on the top of the hill

##### CURRENT BEHAVIOUR:
Pets stuck on the top of the alliance graveyard in **Warsong Gluch**,  moreover in Horde Graveyard they have to climb from the right of the hill and the master have to wait for their arrival.

##### STEPS TO REPRODUCE THE PROBLEM:

**Step 1** Join Warsong Gulch with a class that has Pet (hunter or warlock)
**Step 2** Get down from the top of Alliance Graveyard (100% of stuck the pet) or from Horde Graveyard (the pet has to climb from the right of the hill, and it comes to his master very slowly)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Related: https://github.com/chromiecraft/chromiecraft/issues/88

**Comment by JamesGent** [comment] 2021-02-18 13:23
Can confirm have had both warlock and hunter pets stick here.

**Comment by FrancescoBorzi** [comment] 2021-02-22 00:16
@Yehonal any update about this? this is quite important to fix

**Comment by FrancescoBorzi** [comment] 2021-03-04 23:14
@Yehonal

**Comment by Stifler82** [comment] 2021-03-27 10:59
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by UltraNix** [comment] 2021-04-01 19:59
It's not fixable to me due to this file https://github.com/azerothcore/azerothcore-wotlk/commit/c8f43d85849c40e08d0da38913489426a0c35388#diff-1112e71683f3846188be11dff3849305b218f551b531913dbe360939ad206f25 and calculations done here - I don't get it at all.
This filter is the cause of the problems described here.

**Comment by Yehonal** [comment] 2021-04-01 22:04
That filters adds the slope "difficulty" to the dijkstra algorithm used for
the pathfinding. Thus having the creatures "preferring" a smoother path
rather then climbing mountains. We could skip negatives angles (downhills)
or completely remove that calculation eventually

Il gio 1 apr 2021, 21:59 UltraNix ***@***.***> ha scritto:

**Comment by Yehonal** [comment] 2021-04-02 09:00
I've checked that code a little bit better, and I think what happens is that when you fall down to a cliff, the pathfinding finds too high slopes on every possible paths and the algorithm doesn't work properly then. When it happens on the retail the pet is literally teleported close to the character, I think that on wotlk the pet should be forced to walk down to the cliff instead, so maybe we should check for the "force" flag on pet chasing movement generator instead?

**Comment by UltraNix** [comment] 2021-04-02 09:54
The "force" flag is already present, but it's ignored by pathgenerator, because it throws an error earlier.
`dtStatus PathGenerator::FindSmoothPath`
```
if (dtStatusFailed(_navMeshQuery->moveAlongSurface(polys[0], iterPos, moveTgt, &_filter, result, visited, (int*)&nvisited, MAX_VISIT_POLY)))
        {
            return DT_FAILURE;
        }
```

**Comment by UltraNix** [comment] 2021-04-02 09:57
In `PointMovementGenerator`, whenever the path returns `NO_PATH`, it builds the path anyway with `init.MoveTo`. Maybe just copy it to `FollowGenerator` for pets?

**Comment by Yehonal** [comment] 2021-04-02 11:17
> In `PointMovementGenerator`, whenever the path returns `NO_PATH`, it builds the path anyway with `init.MoveTo`. Maybe just copy it to `FollowGenerator` for pets?

I followed the logic and yes, that's definitely the solution. We return NO_PATH but the path generation for the pet must always be forced when no path is available.

I think the problem is here: https://github.com/azerothcore/azerothcore-wotlk/blob/HEAD/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp#L338

I'm from the smartphone and I cannot test it today

**Comment by Yehonal** [comment] 2021-04-02 11:19
I've also checked the @Footman PR here: https://github.com/azerothcore/azerothcore-wotlk/pull/5097/files and that one doesn't fix this bug, so my suggestion is to open a PR by removing/changing that stop condition so it can be easily tested and merged asap

**Comment by UltraNix** [comment] 2021-04-02 11:26
I'll do it.

**Comment by Yehonal** [comment] 2021-04-02 11:32
ok thanks :) by the way I'm curious if that condition was placed there intentionally for some reason, or is it a copy/paste mistake. 

@Footman any idea?

**Comment by Stifler82** [comment] 2021-04-05 23:28
@FrancescoBorzi @Yehonal @Helias 
Maybe fixed:
- here https://github.com/azerothcore/azerothcore-wotlk/pull/4922
or
- here https://github.com/azerothcore/azerothcore-wotlk/pull/5103

**Comment by Helias** [comment] 2021-04-06 13:22
if it's fixed in the one of the two we could leave the bounty to @UltraNix, we just need some tests here

**Closed** 2021-04-16 10:04 UTC
Labels: Battleground, Bounty, CORE, ChromieCraft Generic, Confirmed, Priority - Medium, mmap/vmap
