### ISSUE TITLE
[Core] Server crash due to Tyrande Whisperwind

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/azerothcore-wotlk#2680] opened 2020-02-18 21:45 UTC
##### SMALL DESCRIPTION:
If you try to talk with the Tyrande Whisperwind (NPC ID 17948) - the server will instantly shut down with an error

##### STEPS TO REPRODUCE THE PROBLEM:

1. .npc add 17948
2. Right click to Tyrande Whisperwind

##### BRANCH(ES):
master

##### OPERATING SYSTEM:
ubuntu

**Comment by solidmaxtor** [comment] 2020-02-18 22:44
Confirm crash but this NPC is envolve with ScritpName ```npc_tyrande_whisperwind```

Many others creatures only work fine if have correct Guid and/or correct location.

**Comment by dev-master21** [comment] 2020-02-18 22:47
> Confirm crash but this NPC is envolve with ScritpName `npc_tyrande_whisperwind`
> 
> Many others creatures only work fine if have correct Guid and/or correct location.

Yes. I checked and made sure that this is so. 
If you try to do:
.go cr id 17948 and click to Tyrande Whisperwind. Server will not shut down

anyway, you can do something with this, so that people would mean that the server can shut down.

**Comment by Stoabrogga** [comment] 2020-02-18 22:56
This NPC is not meant to be summoned outside of Hyjal Summit, as it is using as specific CreatureScript for this encounter:
https://github.com/azerothcore/azerothcore-wotlk/blob/b6cb9247ba96a862ee274c0765004e6d2e66e9e4/src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp#L199

**Comment by pklloveyou** [comment] 2020-02-19 00:25
Any creature with an instance script can cause a server crash in real life

**Comment by Si1ker** [comment] 2020-02-19 08:06
I can confirm it will crash your server but as pklloveyou said: "any creature with an instance script can cause a server crash..."

This NPC is working as expected into Hyjal. This should be closed as it is not an issue, (dungeon) scripted NPCs are not meant to be outside their instances/dungeons for any reason from a blizzlike perspective.

This could be one of the reasons why we have different versions of a Boss/NPC.
-> .lookup creature [creature name]

**Comment by Helias** [comment] 2020-02-19 18:47
Agree with @Si1ker

**Closed by Helias** 2020-02-19 18:47 UTC

**Comment by BarbzYHOOL** [comment] 2020-02-19 21:27
happened to me before too
