### ISSUE TITLE
Halls of Stone dwarf escort getting stuck

### ISSUE THREAD

**Issue by nlwrenn** [azerothcore/azerothcore-wotlk#1915] opened 2019-05-30 15:56 UTC
Halls of Stone dwarf escort getting stuck

##### SMALL DESCRIPTION:
After defeating the gauntlet in Halls of Stone, Brann Bronzebeard gets stuck and the final boss door cannot be opened.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Once the event is over the player should be able to talk to Brann to start an event that triggers roleplay text into an eventual escort to the last boss door.

##### CURRENT BEHAVIOUR:
After defeating the gauntlet in Halls of Stone, Brann Bronzebeard gets stuck after being talked to.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Defeat gauntlet in Halls of Stone
2. Speak with brann to start the roleplay
3. Note how he gets stuck and will not proceed to open the door

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
dfdedd36bb205ee3cf486e94fa8649129fc3678d

**Comment by Selyria** [comment] 2019-05-31 14:23
Sry, I couldn't reproduce your problem. I also made a video once.

Any modules or something on the server?

So my database and core are mostly up to date and unedited by mods or homemade fixes.

AC: https://youtu.be/hqct86kVo4Q

**Comment by poszer** [comment] 2019-05-31 18:08
Can't reproduce this also. Be sure to test this as player @nlwrenn not as GM, for me everything work.
Since @Selyria also confirmed everything is fine, i'm closing this issue

**Closed by poszer** 2019-05-31 18:08 UTC
Labels: Invalid - CannotReproduce
