### ISSUE TITLE
[Dungeon][Blackfathom Deeps] Pre-Aku'mai Event

### ISSUE THREAD

**Issue by markvetx** [azerothcore/azerothcore-wotlk#5668] opened 2021-05-06 14:46 UTC
**CURRENT BEHAVIOUR:**

If you die during the event where you need to use x4 Fire of Aku'Mai, you can't redo it because the objects doesn't reset it's state.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

You must have the opportunity to re-do the event after the wipe

**STEPS TO REPRODUCE THE PROBLEM:**

1. .go c 27424
2. Clear the room
3. Try to use `Fire of Aku'mai` and die
4. After some time, mobs will despawn, and you will not be able to use object again.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
6947789

**OPERATING SYSTEM:**

Arch Linux 5.11

**MODULES:**

[mod-autobalance](https://github.com/azerothcore/mod-autobalance)
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)

**Comment by Si1ker** [comment] 2021-05-06 18:46
Steps followed.

But even if there is a wipe the gobjects will remain active 🤔 

![image](https://user-images.githubusercontent.com/61223313/117349735-f7abdf00-ae68-11eb-872c-5212ba0ce51b.png)


So you can re-take the "event" from where it was left and continue the dungeon

![image](https://user-images.githubusercontent.com/61223313/117349822-11e5bd00-ae69-11eb-87ea-47eff3a046e3.png)

**Comment by markvetx** [comment] 2021-05-07 04:06
@Si1ker  I'm sorry. I described step 4 incorrectly, but still. The point is that if you wipe on some wave, after some time the mobs will despawn and you can't re-do that wave.

For example, try to die when all 4 objects are active, if you die on last wave you can't re-do the event i.e. you can't continue the run and kill the last boss.

**Comment by necropola** [comment] 2021-06-25 23:55
Duplicate of #5213

**Closed by necropola** 2021-06-25 23:55 UTC
Labels: Instance - Dungeon - Classic, Invalid - Duplicate
