### ISSUE TITLE
Gargoyle Target Switch

### ISSUE THREAD

**Issue by justdothings** [azerothcore/azerothcore-wotlk#117] opened 2016-08-27 14:37 UTC
**Description**: Gargoyle Target switch incorrect

**Current behaviour**: Incorrect gargoyle target switch. switchs target on ghoul target but if you attack different target it will attack dktarget.

**Expected behaviour**: gargoyle must attack ghoul target, if ghoul is dead or target than should change target on dktarget

**Steps to reproduce the problem**:
1. Get 2 target
2. get gargoyle and ghoul
3. attack with ghoul first target and with dk second target, gargoyle will switchtarget and attack on dktarget.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  3d5d8a663cbbc825998aa02445958d47f9004461

**Operating system**:  windows server 2008

**Modules**:  NO

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
##

**Comment by DevRival** [comment] 2016-08-27 19:37
How do you know what needs to change the targets are? Gargoyle is not a pet, and this spell how many times you can tell everyone. Target is her enemy which buff then it picks a target within 3 meters. 5 years for the game Unholy DK on ru off. Sorry my bad English.

**Comment by justdothings** [comment] 2016-08-27 22:23
so why you added targetswitch  depended on ghouls target it doesnt work it changes target but if dk attacks another target it changes again check it on arena tournament, if ghoul is dead than it should change target on dks target but when ghoul is alive it should attack ghouls target.

**Comment by justdothings** [comment] 2016-08-27 22:29
if i want to attack healer and gargoyle dps it will not work, when i change target with ghoul and i hit healer it will change target too and start attack healer too.
here is the problem after ghoul target script written this 
                    if (dkTarget && dkTarget != me->GetVictim() && me->IsValidAttackTarget(dkTarget))
                    {
                        me->GetMotionMaster()->Clear(false);
                        SwitchTargetAndAttack(dkTarget);
                        return;
                    } 
before this script it needs something which defines ghoul is dead or alive than should attack dks target.
sorry for my bad english too.

**Comment by DevRival** [comment] 2016-08-28 04:19
Gargoyle does not change the purpose,  together with the ghoul that's a bug, this should not be, because the gargoyle that spell and not a pet.

**Comment by DevRival** [comment] 2016-08-28 09:49
Comment wowhead.

`And finally, the DK cannot control it for the duration so you could save someone by pulling it to yourself with a taunt, the DK can only set the initial target so he cant switch it back if you taunt it`

**Comment by justdothings** [comment] 2016-08-28 13:14
so why they changed on ghoul targetswitch?

**Comment by DevRival** [comment] 2016-08-28 13:43
I don't now, need ask for @ShinDarth

**Comment by justdothings** [comment] 2016-08-28 13:50
i tested again on Warmane blackrock realm (AT) and it works on ghoul target.

**Comment by DevRival** [comment] 2016-08-28 14:04
Do not compare a pirated server. I speak as working on off.

**Comment by DevRival** [comment] 2016-08-28 14:06
Just read wowhead there says it all really.

**Comment by DevRival** [comment] 2016-08-29 14:34
Can someone answer of the leading developers?

**Comment by justdothings** [comment] 2016-08-29 15:10
@Yehonal

**Comment by DevRival** [comment] 2016-08-29 15:14
And @ShinDarth

**Comment by ShinDarth** [comment] 2016-08-29 16:31
I'm sorry but I'm not sure to have understood where the problem is

**Comment by talamortis** [comment] 2016-08-29 17:18
Gargoyle is a spell it should only focus the player that the spell has been casted on.

**Comment by DevRival** [comment] 2016-09-21 15:27
Leading developers, please note this is a gross mistake.

**Comment by talamortis** [comment] 2016-10-08 20:00
@ShinDarth  or @Yehonal  Please close this issue, as its not classed as a bug.

**Comment by HeartWell** [comment] 2016-10-08 20:02
What do you say? Gargoyle is not controlled by a pet ghoul.

**Comment by talamortis** [comment] 2016-10-08 20:03
its not no, its a spell it attacks the player or npc it has been casted on.

**Comment by HeartWell** [comment] 2016-10-08 20:05
Gargoyle now be managed by a panel of pet ghoul, and this should not be.

**Comment by talamortis** [comment] 2016-10-08 20:07
http://wowwiki.wikia.com/wiki/Summon_Gargoyle - Since the spell came out it doesnt say anything in the updates that it can be controlled or even on the ingame tooltip

**Comment by HeartWell** [comment] 2016-10-08 20:34
Commed for wowhead.

> And finally, the DK cannot control it for the duration so you could save someone by pulling it to yourself with a taunt, the DK can only set the initial target so he cant switch it back if you taunt it

**Comment by HeartWell** [comment] 2016-11-08 10:15
Close this fix.

**Closed** 2016-11-08 10:48 UTC
