### ISSUE TITLE
Quest: Steamtank Suprise (Questline: Wrathgate) Not able to complete it.

### ISSUE THREAD

**Issue by Dutchevil** [azerothcore/azerothcore-wotlk#20237] opened 2024-10-17 22:58 UTC
### Current Behaviour

Tested on (deathknight (alliance / warrior)
You have to deploy 7th legion en you have to sabotage 6 plague wagons
The first part goes good the sabatoge fails
Its seems there walks a gnome to the wagon and it explode but it wont count for the quest so you are unable to fufill the quest

### Expected Blizzlike Behaviour

You have to deploy 7th legion en you have to sabotage 6 plague wagons
The first part goes good the sabatoge fails
Its seems there walks a gnome to the wagon and it explode and is counted towards the quest.
making you able to complete the quest.

### Source

A player with 6+ years experience with wow noted this to me.

### Steps to reproduce the problem

Tested on (deathknight (alliance / warrior)

1. Start the questline "Wrathgate"
2. Start the quest: Steamtank Suprise
3. deloy the 7th legion
4. Sabotage 6 plague wagons and see them explode here it fails they arent counted for the quest  making the quest unable to complete.

### AC rev. hash/commit

AzerothCore rev. 9182e970d4ba 2024-10-16 15:01:01 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 31 second(s)
Update time diff: 10ms. Last 435 diffs summary:
|- Mean: 12ms
|- Median: 10ms
|- Percentiles (95, 99, max): 11ms, 58ms, 560ms
Using SSL version: OpenSSL 3.2.2 4 Jun 2024 (library: OpenSSL 3.2.2 4 Jun 2024)
Using Boost version: 1.81.0
Using CMake version: 3.30.2
Using MySQL version: 80039
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.26100
Worldserver listening connections on port %hu
Realmlist (Realm Id: 2) configured in port 8086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in C:/testserver/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/testserver/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/testserver/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: acore_cms_subscriptions.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-breaking-news-override
|- mod-transmog
|- mod-weekendbonus

### Operating system

Windows 11 x64

### Custom changes or Modules

mod-breaking-news-override
mod-transmog
mod-weekendbonus

**Comment by cgrahamseven** [comment] 2024-10-18 21:56
I can confirm that it is not giving you credit for blowing up the plague wagons. Looking a little bit further into it, there are two spells in the dbc; 49122 - Plague Wagon Credit and 49123 - Plague Wagon Kill Credit. The first doesn't appear to do anything when cast, even around plague wagons, although it references Misc Value A of 27625 and says that is for the kill credit. 

Casting spell 49123 causes spell effect missile strike to occur which kills the player and anyone else in a radius around him apparently, including npcs. Even though this destroys the plague wagons in game, it still doesn't give credit. 

What I found did give credit though was spawning creature 27625 (Plague Wagon Credit) and then killing it either yourself or with spell 49123. 

At this point though I'm unsure how the plague wagons and plague wagon credits are meant to be used. I am assuming that plague wagon credit (27625) is the one that is supposed to be killed (likely from the gnomeplosion skill 49118 which is triggered from 49123). However, because 27625 has a name of "Plague Wagon Credit" in game, I'm not sure this is supposed to be visible to players. Maybe someone else has more insight on that.

**Comment by kissingers** [comment] 2024-10-19 09:55
might be fixed now, because the spell can not see before.
https://github.com/azerothcore/azerothcore-wotlk/commit/7abbca0f5b4ab3a15d78db7ec40e3b4358bed7da

**Comment by cgrahamseven** [comment] 2024-10-22 23:06
I debugged this a bit further and it looks like the steamtank is supposed to eventually cast 49122 (Plague Wagon Credit) on the player. I tested this by using the gm command '.cast back 49122' while selecting the steamtank I was riding in and it gave me credit for a kill. 

Looking at the smart_scripts table, it seems that Plague Wagons that are spawned throughout the area are given SmartAI entries to react to SMART_EVENT_HAS_AURA. Basically, when the gnome summons the scourge discombobulater (49114), it will place AURA 49215 (Self-Destruct) on the plague wagon. That should then trigger the SMART_EVENT_HAS_AURA which in turn is supposed to do a SMART_ACTION_SET_DATA with the target of the Steamtank (27587). The steamtank has several SmartAI entries and one of those is SMART_EVENT_DATA_SET. When it gets the data set from the plague wagon it is supposed to cast spell 49122 (Plague Wagon Credit) on the owner of the tank. I turned on debugging for smart ai and while I do see some of the events occurring, I do not ever see the SMART_ACTION_SET_DATA from the plague wagon. So my guess is there is some bug there that needs to be looked into in order to resolve this properly.

**Comment by cgrahamseven** [comment] 2024-10-23 22:54
Found the root cause of the steamtank not being able to give the player credit. In SmartScript.cpp there is a check under the case for SMART_ACTION_CAST that probably shouldn't apply to vehicles. It is failing the spell cast:

```
// If target is rooted we move out of melee range before casting, but not further than spell max range.
if (isWithinLOSInMap && isWithinMeleeRange && isRangedAttack && isTargetRooted && canCastSpell)
{
    failedSpellCast = true; // Mark spellcast as failed so we can retry it later
    float minDistance = std::max(meleeRange, spellMinRange) - distanceToTarget + NOMINAL_MELEE_RANGE;
    CAST_AI(SmartAI, me->AI())->MoveAway(std::min(minDistance, spellMaxRange));
    continue;
}
```

I'll go ahead and submit a fix for it.

**Closed** 2024-10-24 09:57 UTC
