### ISSUE TITLE
Spell Shadowmeld

### ISSUE THREAD

**Issue by r0m1ntik94** [azerothcore/azerothcore-wotlk#3266] opened 2020-08-07 11:32 UTC
##### CURRENT BEHAVIOUR:
[Shadowmeld](https://www.wowhead.com/spell=58984/shadowmeld) the spell does not remove aggro and combat

[Proof](https://youtu.be/h4HicN87nCE)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[Shadowmeld](https://wowwiki.fandom.com/wiki/Shadowmeld)

##### STEPS TO REPRODUCE THE PROBLEM:

1. aggro the mob
2. use a spell ( .cast 58984 )

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/a37ea1b60ee2e42a3953687bae3237d400e6fabf
##### OPERATING SYSTEM:

Ubuntu 18

**Comment by HeartWell** [comment] 2020-08-08 06:53
It all depends on the distance to the goal and the level.

**Comment by r0m1ntik94** [comment] 2020-08-08 10:10
@HeartWell no, and not class druid. All Night elf class

**Comment by r0m1ntik94** [comment] 2020-08-08 10:14
Shadowmeld just don't work, 0 effect 0 aura

**Comment by HeartWell** [comment] 2020-08-08 13:32
Need more tests.

**Comment by Kitzunu** [comment] 2020-08-08 20:24
Important to note
Is SHOULD drop combat with any norma NPC
It SHOULD NOT drop combat with boss fights

**Comment by Kitzunu** [comment] 2020-08-09 15:45
Btw do you have this issue only with Shadowmeld or any spell that has SPELL_AURA_MOD_STEALTH

**Comment by Kitzunu** [comment] 2020-08-09 16:27
I have a fix for this, but I need to test it first so it doesn't drop combat in boss fights

**Comment by r0m1ntik94** [comment] 2020-08-09 16:41
@Kitzunu any spell SPELL_AURA_MOD_STEALTH

**Comment by r0m1ntik94** [comment] 2020-08-09 16:52
@Kitzunu [https://www.youtube.com/watch?v=dU7HjzbZZeM](https://www.youtube.com/watch?v=dU7HjzbZZeM)

**Comment by Kitzunu** [comment] 2020-08-09 16:53
Please test the PR, because I cannot reproduce the issue with no aura using the default spell that comes with nightelf

**Comment by r0m1ntik94** [comment] 2020-08-11 13:00
@Kitzunu can close issues, #3272 fix this.

**Comment by FrancescoBorzi** [comment] 2020-08-11 13:08
@r0m1ntik94 no, the issue should stay open until the fix is on `master` branch. It will be automatically closed when merging the PR ;)

**Comment by r0m1ntik94** [comment] 2020-08-11 13:19
Ahh ok, thank :)

**Closed** 2020-08-30 20:50 UTC
Labels: Confirmed
