### ISSUE TITLE
Tamed Beast is slow

### ISSUE THREAD

**Issue by banehammer** [azerothcore/azerothcore-wotlk#7010] opened 2021-07-17 19:13 UTC
### Current Behaviour

Tamed Beast is very slow in following the character

### Expected Blizzlike Behaviour

Tamed Beasts are like following instantly and in much faster pace

### Steps to reproduce the problem

1. Just tame a beast with a Taming Rod

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/76863ac11fb27e6f88aa862488a79572bdc68db0

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment] 2021-07-17 21:07
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6098

**Closed by Kitzunu** 2021-07-17 21:07 UTC
