### ISSUE TITLE
GObject rotation broken [$100]

### ISSUE THREAD

**Issue by d3tr0l** [azerothcore/azerothcore-wotlk#1043] opened 2018-10-01 22:05 UTC
EXPECTED BLIZZLIKE BEHAVIOUR:

The GObjects should "rotate", change angles when defined in the DB table gameobject column rotation0, rotation1, rotation2, rotation3

Also, the command for this ingame is weird. It should offer .gobject turn [3 rotations] instead it is only offering the "...same as current character orientation."

STEPS TO REPRODUCE THE PROBLEM:
try any gobject ingame, or spawn fresh one...try to change angle/s. The orientation is working, the rotation is not.

BRANCH(ES):

master
AC HASH/COMMIT:

commit 205e8eb
-> have not updated since
OPERATING SYSTEM:

Win 10 x64, latest update
MODULES:

no
OTHER CUSTOMIZATIONS:

none

I hope my explanation is clear. TC had this issue too, they ported that stuff from mangos...it was some time around y2015 so it is possible it was not included in sunwell. If you find my report invalid, please explain how and if even is this stuff working.

**Comment by sucofog** [comment] 2018-10-02 08:38
https://github.com/TrinityCore/TrinityCore/commit/02cef6f034804eb7291f7539936226c0552cad7f
and
https://github.com/TrinityCore/TrinityCore/commit/b239afb0ef3086020637f43c8a48a38eef6b9fee

**Comment by StygianTheBest** [comment] 2018-12-12 15:45
Does it create a new guid with the new XYZR values? I've talked with Rochet2 about adapting hos GoMove project to AC, and here's a reason it might be broken right now. 

> @Styx One core problem with gomove is that each time you move an object the object must be respawned. With the way AC is set up at the moment this will spend a GUID each time. The original GOMove had a hack to prevent spending guids.
On newer TC core the guid problem is solved as DB guids are not spent, instead ingame spawns have different guids to DB guid and respawning a gameobject at a different location is no longer an issue.

**Comment by Shard-MW** [comment] 2019-07-20 12:18
Works for me.
I just had to relog to see the changes

**Comment by FALL1N1** [comment] 2020-11-15 06:22
I could not reproduce this on https://github.com/azerothcore/azerothcore-wotlk/commit/314bff8480682f4d284cfb32b62539f996c10695, can someone provide more information?

http://prntscr.com/vjdj7d

**Comment by UltraNix** [comment] 2021-03-14 20:05
Yep - cannot confirm this too. Problems with saving/not updating gobs after turn/move is described here: #1588.

**Comment by Si1ker** [comment] 2021-03-14 20:17
@FrancescoBorzi @Helias 👀

**Comment by Helias** [comment] 2021-03-15 11:37
need a double check before close this, but yes the missing feature that update the gobject to the player probably made some confusion here

**Closed** 2021-05-03 01:25 UTC
Labels: Bounty, CORE, Priority - Low
