### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by xclid** [azerothcore/azerothcore-wotlk#6913] opened 2021-07-13 01:29 UTC
### build error

```
[ 26%] Linking CXX executable authserver
[ 26%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundSA.cpp.o
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdaterUtil::CheckExecutable()':
DBUpdater.cpp:(.text+0x26d): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: DBUpdater.cpp:(.text+0x288): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text+0x30b): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text+0x323): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text+0x42a): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `std::filesystem::__cxx11::path::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
DBUpdater.cpp:(.text._ZNSt10filesystem7__cxx114pathaSEONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZNSt10filesystem7__cxx114pathaSEONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x6e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<LoginDatabaseConnection>::Create(DatabaseWorkerPool<LoginDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E]+0x5dc): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E]+0xc51): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `std::filesystem::__cxx11::path::path<char [17], std::filesystem::__cxx11::path>(char const (&) [17], std::filesystem::__cxx11::path::format)':
DBUpdater.cpp:(.text._ZNSt10filesystem7__cxx114pathC2IA17_cS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2IA17_cS1_EERKT_NS1_6formatE]+0x8a): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<LoginDatabaseConnection>::Update(DatabaseWorkerPool<LoginDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E]+0x217): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E]+0x236): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<LoginDatabaseConnection>::Update(DatabaseWorkerPool<LoginDatabaseConnection>&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
DBUpdater.cpp:(.text._ZZN9DBUpdaterI23LoginDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_EENKUlRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE_clESC_[_ZZN9DBUpdaterI23LoginDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_EENKUlRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE_clESC_]+0x43b): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<LoginDatabaseConnection>::Populate(DatabaseWorkerPool<LoginDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x2ee): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x326): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x34c): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x360): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x388): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x548): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x574): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x58b): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x5b3): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x6ba): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23LoginDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x7f3): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
DBUpdater.cpp:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x81): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `std::filesystem::__cxx11::path::extension() const':
DBUpdater.cpp:(.text._ZNKSt10filesystem7__cxx114path9extensionEv[_ZNKSt10filesystem7__cxx114path9extensionEv]+0x14): undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZNKSt10filesystem7__cxx114path9extensionEv[_ZNKSt10filesystem7__cxx114path9extensionEv]+0x11e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `std::filesystem::__cxx11::path::path<char [5], std::filesystem::__cxx11::path>(char const (&) [5], std::filesystem::__cxx11::path::format)':
DBUpdater.cpp:(.text._ZNSt10filesystem7__cxx114pathC2IA5_cS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2IA5_cS1_EERKT_NS1_6formatE]+0x8a): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<WorldDatabaseConnection>::Create(DatabaseWorkerPool<WorldDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E]+0x5dc): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E]+0xc51): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<WorldDatabaseConnection>::Update(DatabaseWorkerPool<WorldDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E]+0x219): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E]+0x238): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<WorldDatabaseConnection>::Update(DatabaseWorkerPool<WorldDatabaseConnection>&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
DBUpdater.cpp:(.text._ZZN9DBUpdaterI23WorldDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_EENKUlRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE_clESC_[_ZZN9DBUpdaterI23WorldDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_EENKUlRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE_clESC_]+0x43b): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<WorldDatabaseConnection>::Populate(DatabaseWorkerPool<WorldDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x2f0): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x328): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x35c): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x370): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x398): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x558): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x584): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x59b): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x5c3): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x6ca): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI23WorldDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x803): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<CharacterDatabaseConnection>::Create(DatabaseWorkerPool<CharacterDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E]+0x5dc): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE6CreateER18DatabaseWorkerPoolIS0_E]+0xc51): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<CharacterDatabaseConnection>::Update(DatabaseWorkerPool<CharacterDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E]+0x220): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_E]+0x23f): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<CharacterDatabaseConnection>::Update(DatabaseWorkerPool<CharacterDatabaseConnection>&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
DBUpdater.cpp:(.text._ZZN9DBUpdaterI27CharacterDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_EENKUlRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE_clESC_[_ZZN9DBUpdaterI27CharacterDatabaseConnectionE6UpdateER18DatabaseWorkerPoolIS0_EENKUlRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE_clESC_]+0x43b): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `DBUpdater<CharacterDatabaseConnection>::Populate(DatabaseWorkerPool<CharacterDatabaseConnection>&)':
DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x2f7): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x32f): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x35c): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x370): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x398): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x558): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x584): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x59b): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x5c3): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x6ca): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: DBUpdater.cpp:(.text._ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E[_ZN9DBUpdaterI27CharacterDatabaseConnectionE8PopulateER18DatabaseWorkerPoolIS0_E]+0x803): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: ../database/libdatabase.a(DBUpdater.cpp.o): in function `std::filesystem::__cxx11::path::operator=(std::filesystem::__cxx11::path&&)':
DBUpdater.cpp:(.text._ZNSt10filesystem7__cxx114pathaSEOS1_[_ZNSt10filesystem7__cxx114pathaSEOS1_]+0x103): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../database/libdatabase.a(UpdateFetcher.cpp.o): in function `UpdateFetcher::ReceiveIncludedDirectories() const':
UpdateFetcher.cpp:(.text+0x8ad): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x177f): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../database/libdatabase.a(UpdateFetcher.cpp.o): in function `UpdateFetcher::FillFileListRecursively(std::filesystem::__cxx11::path const&, std::set<std::pair<std::filesystem::__cxx11::path, UpdateFetcher::State>, UpdateFetcher::PathCompare, std::allocator<std::pair<std::filesystem::__cxx11::path, UpdateFetcher::State> > >&, UpdateFetcher::State, unsigned int) const':
UpdateFetcher.cpp:(.text+0x24da): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x2524): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x2541): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x2549): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x255f): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x2594): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x25e1): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x25ec): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x2707): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x28f0): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: UpdateFetcher.cpp:(.text+0x2d22): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: ../../common/libcommon.a(StartProcess.cpp.o): in function `Acore::StartProcess(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
StartProcess.cpp:(.text+0x1f1): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: StartProcess.cpp:(.text+0x274): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../../common/libcommon.a(StartProcess.cpp.o): in function `Acore::AsyncProcessResultImplementation::StartProcess()':
StartProcess.cpp:(.text._ZN5Acore32AsyncProcessResultImplementation12StartProcessEv[_ZN5Acore32AsyncProcessResultImplementation12StartProcessEv]+0x206): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: StartProcess.cpp:(.text._ZN5Acore32AsyncProcessResultImplementation12StartProcessEv[_ZN5Acore32AsyncProcessResultImplementation12StartProcessEv]+0x27e): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/authserver/CMakeFiles/authserver.dir/build.make:170: src/server/authserver/authserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1097: src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundWS.cpp.o
```

### Expected Blizzlike Behaviour

pass

### Steps to reproduce the problem

Build with 
debian 10 x64
mariadb 10.5
clang 12.0.1
cmake 3.20.1

### AC rev. hash/commit

1fa51e5168bce813342aeda41d993ed5a4b21cf5

### Operating system

Debian 10 x64

**Comment by necropola** [comment] 2021-07-13 11:58
Duplicate of #6889 
PR incoming ...

**Closed** 2021-07-13 11:59 UTC
Labels: Invalid - Duplicate
