### ISSUE TITLE
[Important] SQL updates are not working and break the server

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#271] opened 2016-12-01 23:08 UTC
**Description**:
SQL updates don't work and break the server (I've seen same errors 2 months ago but I applied sql one by one to make it work)

**Current behaviour**:
When you update with this kind of update:
```
-- assembled updates
ALTER TABLE version_db_characters CHANGE COLUMN 2016_08_25_00 2016_11_18_00 bit;

--
-- Do not remove this file when we archive sql under this folder
-- it is needed for pending sql importer
--
-- DB update 2016_08_25_00 -> 2016_11_19_00
DROP PROCEDURE IF EXISTS `updateDb`;
DELIMITER //
CREATE PROCEDURE updateDb ()
proc:BEGIN DECLARE OK VARCHAR(100) DEFAULT 'FALSE';
START TRANSACTION;
ALTER TABLE version_db_characters CHANGE COLUMN 2016_08_25_00 2016_11_19_00 bit;
```
There is this error **ERROR 1054 (42S22): Unknown column '2016_08_25_00' in  version_db_world'"**
This causes the rest of the sql update to fail and then the server can't start.

**Expected behaviour**: It should replace this line:
`ALTER TABLE version_db_characters CHANGE COLUMN 2016_08_25_00 2016_11_19_00 bit;`

By:
`ALTER TABLE version_db_characters CHANGE COLUMN 2016_11_18_00 2016_11_19_00 bit;`

**Steps to reproduce the problem**:

1. Make a new db (world, auth or characters)
2. Apply the base sql
3. Apply the update (in command line the error is 100% there)

**Branch(es)**: all, it was already there 2 months ago if I'm right

**Operating system**:  Linux

**Other Customizations**: no, fresh install, BUT I used the db_assembler though

**Comment by 3majed** [comment] 2016-12-04 09:10
Hello falzard. I am don't have a fix for this error but I knew a way to avoid the errors after millions of tries. (this is for new ppl how are making there server after the azerothercore 1.x).  What i did is just avoid all the audate sqls @ this date 2016_11_18_00. 

Again this is a way to avoid the errors and server works fine but idk if its right way or not

**Comment by falzard** [comment] 2016-12-04 19:25
It will happen everytime new SQL files are added. Many people had this problem and said it in gitter chat.

**Comment by ShinDarth** [comment] 2016-12-04 19:43
which is the update file causing this error to you?

**Comment by falzard** [comment] 2016-12-04 21:41
All the ones with something like that in first line:
```ALTER TABLE version_db_characters CHANGE COLUMN 2016_08_25_00 2016_11_18_00 bit;


--
-- Do not remove this file when we archive sql under this folder
-- it is needed for pending sql importer
--
**-- DB update 2016_08_25_00 -> 2016_11_19_00**```


It's a fresh install. And it happened on world db and characters and certainly auth.

I assembled the sql files in the db_assembler because I'm doing it from command line and it's extremely annoying to deal with. I don't know which one then but if you read the chat @3ndos had the same problem and more people before him.

**Comment by falzard** [comment] 2016-12-10 20:09
Possibly this one world_update_2016_12_07_12_08_26.sql

**Comment by Kapel** [comment] 2016-12-17 01:16
Today on gitter I guess I've found the solution for the problem or perhaps a tip for someone looking for the solution. 
I've done a db_assembly today and in each update file is the same error. While importing in console it said about an error in "CALL updateDb();"

The problem is that the procedure can't find the actual column. 
It's caused by the ALTER table in line 2 in all those files.
 In line 2 we change the name and in line 14 (in the procedure) we reffer to the original name. While calling the procedure, it can't find the right column name.

The two solutions:
a) comment out line 2, so the name of the column does not change and the procedure can change it on it's own.
b) correct the procedure so it reffers to the 'changed' name;
Example:

IF we have:
line 2: ALTER TABLE version_db_world CHANGE COLUMN 2016_11_06_02 2016_11_18_00 bit;
line 14: ALTER TABLE version_db_world CHANGE COLUMN 2016_11_06_02 2016_11_19_00 bit;

Solution a) comment out line 2
Solution b) looks like:
line 2: ALTER TABLE version_db_world CHANGE COLUMN 2016_11_06_02 **2016_11_18_00** bit;
line 14: ALTER TABLE version_db_world CHANGE COLUMN **2016_11_18_0**0 2016_11_19_00 bit;


Of course it should work in all the update_database files. Just change version_db_world to the one needed: version_db_auth or version_db_characters

Hope this helps.

**Comment by Yehonal** [comment] 2016-12-17 11:56
https://github.com/azerothcore/azerothcore-wotlk/commit/3040693c2e64ad6f990051154f701a0b398c172e

**Comment by StygianTheBest** [comment] 2017-08-17 19:37
I ran into these issues today trying to build a new database with the output of db_assembler. I was getting the same errors using Navicat, so I tried them in HeidiSQL and they worked fine. Not sure what the deal is there, but keep that in mind if you run into database issues in the future.

Version: https://github.com/azerothcore/azerothcore-wotlk/commit/f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by Kaev** [comment] 2017-12-04 08:40
iirc this is a Navicat bug. I remember even back in TBC people advised you to use other tools than Navicat because of this bug. We could rewrite it so it works in Navicat - Or we could leave it like it is and advise to use e.g. HeidiSQL like everyone else did over the years.

Best solution imo: Add an option to the db assembler to import all the SQL files so we don't need to handle any external tool bugs. :)

**Comment by Deku** [comment] 2018-05-25 01:50
@BarbzYHOOL this should be closed

**Closed** 2018-05-25 08:06 UTC
