### ISSUE TITLE
[server]world server crash 0520

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11812] opened 2022-05-20 16:09 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/812687f8ac63c5bc9c13bc7ac27f2903

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

324112ff4fcb52416dea7444c9c80a7781b57ebf

### Operating system

Ubuntu20.04

**Comment by UltraNix** [comment] 2022-05-21 08:13
Duplicate of #11650

**Closed by UltraNix** 2022-05-21 08:13 UTC
