### ISSUE TITLE
Quest dialogue fails to close when finishing quest with just the right amount of bag slots free

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6296] opened 2021-06-10 05:10 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/827

##### CURRENT BEHAVIOUR:

When delivering a quest (for instance, when completing [Wild Hearts](https://wowgaming.altervista.org/aowow/?quest=429) I had just 2 slots open in my bag, just enough for the quest rewards. I received the rewards but the quest dialogue failed to close (as if I had trouble finishing the quest). After I close the dialogue by clicking the quest X button, the next quest is available, meaning the game recognizes the previous quest was successfuly finished.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When finishing a quest with enough empty slots in the character bag for the rewards to be collected, end the quest successfuly.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Rane Yorick in Silverpine Forest
2. Start the quest Wild Hearts
3. Collect the Discolored Vorg Hearts
4. Deliver the quest to  Apothecary Renferrel with just 2 free slots in your bag

##### EXTRA NOTES:

The quest mentioned is [Wild Hearts](https://wowgaming.altervista.org/aowow/?quest=429)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 28664a2):

![WoWScrnShot_061021_080324](https://user-images.githubusercontent.com/82579073/121468030-d340a680-c9c2-11eb-9a52-3e2496038b2b.jpg)
![WoWScrnShot_061021_080339](https://user-images.githubusercontent.com/82579073/121468072-e2bfef80-c9c2-11eb-8ea8-e8900e689f4a.jpg)
![WoWScrnShot_061021_080348](https://user-images.githubusercontent.com/82579073/121468102-f10e0b80-c9c2-11eb-8034-13a80c7a9d84.jpg)

Not only exists this error, it also says that the inventory is full without being true:

![WoWScrnShot_061021_080408](https://user-images.githubusercontent.com/82579073/121468150-0125eb00-c9c3-11eb-97ac-9957afd6ecd2.jpg)

The next quest is indeed available:

![WoWScrnShot_061021_080743](https://user-images.githubusercontent.com/82579073/121468239-2155aa00-c9c3-11eb-992d-0c811c866249.jpg)

**Comment by buddiman** [comment] 2021-06-11 00:07
This seems to be a Core Problem. I can confirm this bug and where and when it's happening.
I've tested this additionally. with [a similar quest](https://wotlk.evowow.com/?quest=509) 
Be sure if you test this to have more than the number of needed items for the quest.

This only happens when there is a follow up quest which provides an item while accepting the quest.
The error occurs during the call of the function `CanAddQuest()` in QuestHandler.cpp in line 302. 
Because the inventory is full after the quest, `CanAddQuest()` returns false and Sends the "Inventory is full" error message.
Because of the false return, `_player->PlayerTalkClass->SendQuestGiverQuestDetails(nextQuest, guid, true);` doesn't get called. And thats where the quest window doesn't update or close.

I can't say what the original behaviour on retail was, but I think the questgiver should show the new quest regardless of your inventory space and the error should only be shown when trying to accept the new quest. I've think I've got a fix for this, I'm going to open a PR tomorrow.

**Closed** 2021-06-18 15:05 UTC
Labels: 1-19, Confirmed, Loot, Priority - Low, Quest
