### ISSUE TITLE
Mutiple quest items generated

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4418] opened 2021-02-02 17:54 UTC
### CURRENT BEHAVIOUR:
When looted in perfect sync (Interact with target activated via keybroadcasting), quest items which should drop only for one toon, can be looted with 2-5 toons. Without perfect sync, only one toon gets the reward.
Tested on Pygmy Surf Crawler and Makrura Spellhide for the quest "A Solvent Spirit".

### EXPECTED BLIZZLIKE BEHAVIOUR:
Only one quest item per corpse should be obtaiable for these kind of collection quests. Not one per toon.

### STEPS TO REPRODUCE THE PROBLEM:
To reproduce it one would need an external program, e.g. Hotkeynet.
Then have it send a key to all windows in perfect sync to make them all loot an once.

### EXTRA NOTES:
Does not affect normal solo play or not even normal party play.

### AC HASH/COMMIT:
https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

### OPERATING SYSTEM:
OS:
Ubintu 20.04

### MODULES:
Chromiecraft server

### OTHER CUSTOMIZATIONS:
Chromiecraft server

**Comment by Kitzunu** [comment] 2021-02-02 18:18
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/4415

**Closed by Kitzunu** 2021-02-02 18:18 UTC

**Comment by 55Honey** [comment] 2021-02-02 18:48
Sorry :)
