### ISSUE TITLE
[quest] `Boiling Point` bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#12369] opened 2022-07-12 08:27 UTC
### Current Behaviour

Defeat the quest NPC and cannot complete the quest

### Expected Blizzlike Behaviour

After defeat, you will complete the quest
https://www.youtube.com/watch?v=muNuag2AdM0

### Steps to reproduce the problem

1. .q a 11627
2.  .go c id 28416
3. kill it
4. .go c id 28418
5. kill it

### AC rev. hash/commit

71b8cea82801e9cd8858594e47fcdaf19adfdfba

### Operating system

Ubuntu20.04

**Comment by htc16** [comment] 2022-07-14 20:28
https://github.com/azerothcore/azerothcore-wotlk/issues/10313

**Comment by UltraNix** [comment] 2022-07-17 09:09
Duplicate of #12380 10313

**Closed by UltraNix** 2022-07-17 09:09 UTC
