### ISSUE TITLE
In Memoriam (Quest) - Bug again

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2138] opened 2019-07-25 03:44 UTC
In Memoriam (Quest) bug again

##### SMALL DESCRIPTION:

The quest can't be completed for some players but can be completed on some.  I have tested players who are exalted with Sons of Hodir and already finished the chain quest and can't see Horn fragments.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to see horn fragment.

##### CURRENT BEHAVIOUR:

The quest can't be completed for some players but can be completed on some.  I have tested players who are exalted with Sons of Hodir and already finished the chain quest and can't see Horn fragments.

We tested this with party and without, same problem happens.

GM Character:
Can see horn fragment without issues (only did .quest add 12975)
![WoWScrnShot_072519_113403](https://user-images.githubusercontent.com/18629476/61844419-ef6ff300-aed1-11e9-942b-cbf69eee0af6.jpg)

Exalted Player, finished all main Sons of Hodir quests and dailies except In Memoriam( .quest add 12975 ) Can't see horn fragment:
![ty](https://user-images.githubusercontent.com/18629476/61844426-f39c1080-aed1-11e9-848e-b82a94eb1b8a.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Better test this on live server w/ people who finished main quest or exalted players?
2. .quest add 12975
3. Find Horns

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

 d9d84c4

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment] 2019-07-25 22:48
Interesting, i can't reproduce it. 
![Screenshot_1](https://user-images.githubusercontent.com/41213210/61913922-f84ade00-af3e-11e9-99ce-e80154c2a2ef.jpg)


Can you check your database, please : 

World Database -> gameobject -> ID = 192081  is 'phaseMask' set to 1?

If no, reapply SQL from this commit https://github.com/azerothcore/azerothcore-wotlk/commit/2575665285cc918dcf040947d71bd6b1e2b7e118

**Comment by andoys** [comment] 2019-07-25 23:23
This is the database: 
![gameobj](https://user-images.githubusercontent.com/18629476/61915240-2f88b180-af76-11e9-8610-c32a42a126bc.png)

Yep phaseMask' set to 1

**Comment by LichKing255** [comment] 2019-10-15 08:30
not confirm. this fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/1933 nad if phasemask = 1 then players can see it. player can't see before this commit.

close this.

**Comment by Stoabrogga** [comment] 2019-10-15 08:44
Actually this was fixed in #2231. Phasemask 1 is wrong here, it has to be 4, because the whole area is phased after proceeding with the "Sons of Hodir" quest chain.

**Closed by Stoabrogga** 2019-10-15 08:44 UTC
Labels: Not confirmed, Quest
