### ISSUE TITLE
SQL error (duplicate entry)

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2498] opened 2019-12-09 18:41 UTC
I've noticed at server's console SQL error (4 times for today). It seems - reason is Hunter's pet.
![изображение](https://user-images.githubusercontent.com/25766571/70461841-a0b2a680-1aca-11ea-96b8-fafb66ec93b8.png)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

dda507aaca33

##### OPERATING SYSTEM:

Windows 7

I don't know how to reproduce this error

**Comment by milestorme** [comment] 2019-12-25 21:09
cannot reproduce

**Comment by Stoabrogga** [comment] 2020-01-18 15:21
Closing this in favor of #2589.

**Closed by Stoabrogga** 2020-01-18 15:21 UTC
