### ISSUE TITLE
Talisman of Acsendance

### ISSUE THREAD

**Issue by veredis1** [azerothcore/azerothcore-wotlk#12835] opened 2022-08-23 22:41 UTC
### Current Behaviour

Stacks 40 SP with every damage instance and spell (for example Dots, playing as WL) and is over after some seconds.

### Expected Blizzlike Behaviour

Cast spells, Stack 40 SP

### Steps to reproduce the problem

1. equip Talisman of Acsendance
2. activate trinket
3. cast spells

### Extra Notes

Issue has been allready reported nearly a year ago :>
https://github.com/azerothcore/azerothcore-wotlk/issues/8676

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Windos 10

**Comment by Synful-Syn** [comment] 2022-08-28 15:28
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/8676 and https://github.com/azerothcore/azerothcore-wotlk/issues/11881

**Closed by Synful-Syn** 2022-08-28 15:28 UTC
