### ISSUE TITLE
[quest] learn to ride in.....

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1495] opened 2019-02-18 23:29 UTC
<DESCRIPTION:

all the "learn to ride in ....." quests can't be obtained

EXPECTED BLIZZLIKE BEHAVIOUR:

When you reach level 20 in your mail you get a quest [item](https://wowgaming.altervista.org/aowow/?search=Riding+Training+Pamphlet) that allows you to complete the [quest](https://wowgaming.altervista.org/aowow/?search=learn+to+ride)

CURRENT BEHAVIOUR:

nothing arrives by mail

STEPS TO REPRODUCE THE PROBLEM:

-create a pg and increase the level up to 20
-wait and look your mail

p.s.: I found a possible fix to this [sito](https://community.atlantiss.eu/index.php?/topic/14499-riding-trainer-pamphlet-lvl20/)

BRANCH(ES):
staging

AC HASH/COMMIT:
commit: [aade455](https://github.com/azerothcore/azerothcore-wotlk/commit/aade455eff8d6ab24fc0d0a558ec78acfd763aff)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by poszer** [comment] 2019-03-20 00:58
Can't reproduce issue. For me, everything works as it should be:

**Images below as proof:**

**Alliance**
![learnalli](https://user-images.githubusercontent.com/41213210/54651484-61af7180-4ab3-11e9-9e91-5d3ad32ab5d8.jpg)

**Horde**
![learniSilvermoon](https://user-images.githubusercontent.com/41213210/54651485-61af7180-4ab3-11e9-9e66-d78ce40e991c.jpg)

Closing this

**Closed by poszer** 2019-03-20 00:58 UTC
Labels: Invalid - CannotReproduce
