### ISSUE TITLE
Mage Quest - Investigate the blue recluse

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#903] opened 2018-06-02 10:59 UTC
**Description**: Quest's doesn't working properly - SAI should be fixed.

**Current behaviour**: When you use provided items to see hidden npcs and to attack them, once you bring them to 1 hp, coffer doesn't appear to be looted.

**Expected behaviour**: Coffer should appear to be looted for quest item.
Check video how is supposed to work - https://www.youtube.com/watch?v=t0jFkP1k2ag

Quest ID - 1920

**Steps to reproduce the problem**: Not sure, will leave to someone with more exp.

**AC hash/commit**: 778cd9a

**Operating system**:  Linux, Debian 9

**Modules**:  Congrats on level, Premium.

**Other Customizations**: No, not at all.

**Comment by Trystanosaurus** [comment] 2018-06-02 12:02
This one should have been fixed by commit 7e1c5b1 I've tried the horde equivalent quest (investigate the alchemists shop) and it was at least finishable with this commit).

**Comment by Knindzagxg** [comment] 2018-06-02 12:05
Sadly it's not.
Object doens't appear at all.

**Comment by Stoabrogga** [comment] 2018-06-03 17:40
The coffer doesn't appear automatically, you'll have to use "[Chest of Containment Coffers](https://wowgaming.altervista.org/aowow/?item=7247)" after the Rift Spawn is stunned and then use the closed coffer which spawns under the Rift Spawn. The Rift Spawn is then sucked into the coffer, which leads to a "[Filled Containment Coffer](https://wowgaming.altervista.org/aowow/?item=7292)". Tested both quests, "[Investigate the Blue Recluse](https://wowgaming.altervista.org/aowow/?quest=1920)" and "[Investigate the Alchemist Shop](https://wowgaming.altervista.org/aowow/?quest=1960)", successfully.

**Comment by Knindzagxg** [comment] 2018-06-03 17:54
Tried myself.
Adds appear they get stuned, but when i use item nothing happen at all.

**Comment by Knindzagxg** [comment] 2018-06-04 15:52
Check video bellow.

Ignore on coffers u see on side - I manually added them for people so they complete quest.

https://www.youtube.com/watch?v=jX5H7EaJIWw&feature=youtu.be

**Comment by Stoabrogga** [comment] 2018-06-04 17:05
Sorry, but I cannot reproduce the error. Did a fresh install of the server (latest commit https://github.com/azerothcore/azerothcore-wotlk/commit/e222cbbc0a19abe407cbb8df1fc8e04ddde19d16, Ubuntu 16.04) with new DB. The quest is working for me.

**Comment by Knindzagxg** [comment] 2018-06-04 17:21
Weird.

I'll check all commits to see if i missed any.

**Comment by Knindzagxg** [comment] 2018-06-06 15:41
I missed commit which Trystanosaurus suggested.

You can close this one - It's working perfectly.

**Closed** 2018-06-06 18:20 UTC
