### ISSUE TITLE
Instant Log out and Ability to log off during combat

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6188] opened 2021-06-02 09:07 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/760

##### CURRENT BEHAVIOUR:

1. Instant log off outside of Inn
2. Ability to Log off during combat

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. 20 second timer to log off
2. Unable to log off during combat

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Used Log out in STV area outside of booty bay instantly
2. Enter combat with mob and client will log out within 20 seconds timer
3. 
4.

##### EXTRA NOTES:

Seem to happen on june 2, 2021

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment] 2021-06-02 09:28
I have not been able to confirm it in my local installation, but I have several friends who play Chromiecraft who have told me that it certainly happens sometimes.

**Comment by gurveleg** [comment] 2021-06-02 10:19
I can log out instantly (or with timer when in combat) anywhere in Winterspring since today. Yesterday it still worked like it should,

**Comment by gurveleg** [comment] 2021-06-03 05:44
Today there is again log out timer in Winterspring. No idea what caused the instant log outs yesterday.

**Comment by UltraNix** [comment] 2021-07-27 12:45
I can't reproduce the 1st. one.
As the second bug - you still can't logout if you are in combat. But if click Logout and then the mob aggroed, you are still able to logout safe - I don't if it is a bug.

**Comment by UltraNix** [comment] 2021-08-28 14:37
I will close this soon if there will be no confirmation.

**Comment by FrancescoBorzi** [comment] 2021-08-31 09:32
@UltraNix maybe it's worth asking on the original issue too: https://github.com/chromiecraft/chromiecraft/issues/760

cc @azerothcore/bug-triaging

**Comment by Kitzunu** [comment] 2021-08-31 22:35
@Jinmcx

**Comment by IntelligentQuantum** [comment] 2021-09-06 17:08
> I can't reproduce the 1st. one.
> As the second bug - you still can't logout if you are in combat. But if click Logout and then the mob aggroed, you are still able to logout safe - I don't think it is a bug.

Exactly, It's not bug

**Comment by Helias** [comment] 2021-09-06 17:26
What about to close this so?

**Comment by FrancescoBorzi** [comment] 2021-09-07 23:52
if you close it, don't forget to also address https://github.com/chromiecraft/chromiecraft/issues/760

**Closed** 2021-09-11 14:34 UTC
Labels: Priority-Medium, Help wanted, Not confirmed, ChromieCraft Generic
