### ISSUE TITLE
WorldServer or DataBase Broken Update?

### ISSUE THREAD

**Issue by virgo77** [azerothcore/azerothcore-wotlk#9781] opened 2021-12-19 14:29 UTC
### Current Behaviour

Hi!
I updated the core this saturday, and I'm experiencing a DB issue that is really annoying.
When I launch the WorldServer, I got lots of errors when loading the maps: https://pastebin.com/0vQYjMJr

I tried to migrate my DB on an another SQL Instance, like MariaDB 10.5.12 on Debian 11 but WorldServer semms not to support it. It says that it does not support MariaDB below 10.5 (I don't know why)
I saw an another post here for the MariaDB 10.6 instead: https://github.com/azerothcore/azerothcore-wotlk/issues/7086

I don't know what's wrong but I can't use my server anymore.

Many help please :)

### Expected Blizzlike Behaviour

No errors? (i don't know what to answer here)

### Steps to reproduce the problem

Just PULL an update of the Core since the this Saturday #3 update
Recompile the core: launch CMake and reconfigure it, twice, then 'Generate', then 'Open Project'
In Visual Studio, check to be in RelWithDebInfo x64
In ALL_BUILD, Clean then Build (all results are OK "========== Build All: 25 succeeded, 0 failed, 0 skipped ==========")
Then copy the .EXE and . PDB files from the core\build\bin\RelWithDebInfo to the server folder
Launch the AuthServer.exe, then the WorldServer.exe
And, errors...

### Extra Notes

OS: Windows Server 2022 Standard, updated
As a VM: yes
CPU as vCPU: Intel Core i9 9900k (6 vCPU)
RAM: 24 GB
HDD: SSDs
Free Space: 190 GB

Database: MySQL Server Community Edition 8.0.26

Last AC update: 2021-12-18_3

CMake and Visual Studio Compilation: OK - No Errors

My worldserver.conf and worldserver.conf.dist from the last update compared and no changes since the last November ones.

### AC rev. hash/commit

AzerothCore rev. 2b79a9ffcfeb 2021-12-18 06:50:41 +0000 (master branch)

### Operating system

Windows Server 2022 Standard

### Custom changes or Modules

The only changes I made are on the worldserver.conf file.

I activated these two options:
- PreloadAllNonInstancedMapGrids = 1
- SetAllCreaturesWithWaypointMovementActive = 1

I made these changes because I would like that all the mobs were launched. Because each time I get close to see them, they are poping then falling to the ground, then they get replaced to their waypoint...

The other changes are simple: sql server, name, password and logs. That's all!

**Comment by Shineslippers** [comment] 2021-12-19 14:33
That's duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/9763

**Closed by Shineslippers** 2021-12-19 14:33 UTC
Labels: Needs Developer

**Comment by virgo77** [comment] 2021-12-19 14:35
Hi Shineslippers!
Thanks for your update.

As I saw what you modified on my post, here is my AC Version:
AzerothCore rev. 61c7488698d4 2021-11-21 11:41:51 -0300 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by Shineslippers** [comment] 2021-12-19 14:37
You can see `AC rev. hash/commit` at 1st line of your log. Please use it next time. regarding to issue as said Kitzunu: `You can still compile. This is just a weird db error that doesnt affect anything`

**Comment by virgo77** [comment] 2021-12-19 14:38
yep I just saw it... really annoying to see all these error lines. Hope it will be corrected.
Thanks at all :)
