### ISSUE TITLE
Deep freeze dealing damage instead of just stun

### ISSUE THREAD

**Issue by Voorh** [azerothcore/azerothcore-wotlk#6783] opened 2021-07-07 01:55 UTC
### Current Behaviour

When you use Deep freeze it is dealing damage to players

### Expected Blizzlike Behaviour

The right thing would be to stun and not deal damage, dealing damage would only be on targets that are immune to stun, which is not the case for a player.

### Steps to reproduce the problem

1.create mage
2. dueling with another player
3. Use Deep freeze and look that will stun and deal damage at the same time.

### AC rev. hash/commit

> 27b2026

### Operating system

Windows

**Comment by Kitzunu** [comment] 2021-07-07 01:56
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6616

**Closed by Kitzunu** 2021-07-07 01:56 UTC

**Comment by Voorh** [comment] 2021-07-07 01:57
> duplicate of #6616
Omg, he replied quickly, but it's been blocked for days... will there be correction?

**Comment by Kitzunu** [comment] 2021-07-07 01:58
As for any issue in the repository. It will be fixed when someone wants to fixed it.
