### ISSUE TITLE
Vmaps | Mmaps | Recastnav and FleeingMovement

### ISSUE THREAD

**Issue by SoulBasementGc** [azerothcore/azerothcore-wotlk#979] opened 2018-07-18 07:43 UTC
STEPS TO REPRODUCE THE PROBLEM:

1. run Server for 10 characters
2. inv group ,go DF , if die can't load graveyard for revive
3. inv group. join BG, dismount don't work in place's must dis
4. portal after use for again use not work and dissapper
5. Some spells for characters have problem (sorry , spells sum pet's) 
6. Some characters show unknow Zone map
7. And ...
Test With 40 characters , Without modules
maybe problems is for this commit e772b08c6808bae29db96ed2f51ee5b34d768da4

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

8767372ebfad4713d3e8b60a5331ee1f705cc267

##### OPERATING SYSTEM:

Win 10, 7 & Ubuntu 16

**Comment by BarbzYHOOL** [comment] 2018-07-18 17:19
> Some spells for characters have problem

helpful

**Comment by BarbzYHOOL** [comment] 2018-07-18 17:34
Hmm, you need to reextract the mmaps and vmaps because we changed them again and didn't upload them yet

**Comment by dunjeon** [comment] 2018-07-18 19:30
@BarbzYHOOL 
I extracted these maps 7-18-2018. 
https://mega.nz/#!A3ISTICZ!IqhgC7AqlCvIJaFeFjsN35iJW_8WinOMbVuRi9J5NMc

But, I don't think the worldserver would load with incorrect maps.

**Comment by BarbzYHOOL** [comment] 2018-07-18 19:57
for this particular case yes because the maps number hasn't been increased (maybe a mistake)

**Comment by devfrom** [comment] 2018-07-19 13:52
I confirm this, even with new maps extracted these errors still continues

**Comment by SoulBasementGc** [comment] 2018-07-20 03:23
Worldserver Can't load maps so unknow Zone in maps , If this problem is re-created, the data maps must be replaced with the new data card as it is damaged .
These problems are very clear and bug the whole system.
Now you can see that most of the issues that are being republished are on the maps side of the story.
Despite this problem, no fixed fixes remain . 
It is not possible to view this problem by testing a character , With revert this comment e772b08c6808bae29db96ed2f51ee5b34d768da4, the problem will be fixed or the comment will be reviewed and corrected

**Comment by vhipercode** [comment] 2018-07-20 03:52
@BarbzYHOOL @Stoabrogga @FALL1N1 
I confirm this problem.

below some images to be analyzed.

![unknown 3](https://user-images.githubusercontent.com/39068627/42982275-fcdabb36-8bb6-11e8-9458-d5cb2f9d4ee0.png)
![unknown](https://user-images.githubusercontent.com/39068627/42982276-fd33ca0a-8bb6-11e8-9f16-36928869536b.png)
![unknown 1](https://user-images.githubusercontent.com/39068627/42982277-fd4ea0be-8bb6-11e8-978d-4f8df9c1bf94.png)
![unknown 2](https://user-images.githubusercontent.com/39068627/42982278-fd679024-8bb6-11e8-8e13-76307ccd2186.png)

**Comment by SoulBasementGc** [comment] 2018-07-20 04:03
@vhipercode thank you.
This issue is important and has created a very bad challenge

**Comment by Stoabrogga** [comment] 2018-07-20 07:48
Sorry, but I cannot reproduce the errors. I compiled the core including the tools (commit 8767372ebfad4713d3e8b60a5331ee1f705cc267, Ubuntu 16.04):
```
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/testuser/server/ -DTOOLS=1 -DSCRIPTS=1
make -j 2
make install
```

extracted everything again to build up a new "data" directory:
```
~/server/bin/mapextractor
mkdir ~/server/data
cp -r dbc maps ~/server/data
~/server/bin/vmap4extractor
mkdir vmaps
~/server/bin/vmap4assembler Buildings vmaps
cp -r vmaps ~/server/data
mkdir mmaps
~/server/bin/mmaps_generator
cp -r mmaps ~/server/data
```

I can only test alone, though, but don't see any errors in the server log.

**Comment by BarbzYHOOL** [comment] 2018-07-20 13:32
Can someone clearly explain how to reproduce that issue??? damn you guys think it's going to be magically fixed or what?? @SoulBasementGc @devfrom @vhipercode

**Comment by dunjeon** [comment] 2018-07-20 23:15
I am unable to confirm. Like Stoabrogga, I was only able to test solo, but my logs are clean.
The error report is a little hard to track so I tested it the best I could. (My test server was built with windows 10 x64 running on windows server 2012.

**Comment by dunjeon** [comment] 2018-07-21 00:47
Delay my last.  While testing Kelthuazd, I can confirm a zone Unknown error log says:
(Naxxramas) Zone: Unknown

**Comment by Knindzagxg** [comment] 2018-07-21 07:31
Can't confirm this - Tested mentioned maps and etc, but everything works fine for me.
Maybe you had error if you extracted your own maps - Try using one Talamortis uploaded.

**Comment by SoulBasementGc** [comment] 2018-07-21 07:58
@Knindzagxg How did you test?!!! . This is a complete problem inside the WordServer. Also inside the game , solo test is not suitable for appearing, please correct test.

**Comment by Knindzagxg** [comment] 2018-07-21 08:04
Was checking mentioned maps while monitoring WS -> Had 0 errors during that.
Also, no "Unknown" part for while on any map (O option)

**Comment by vhipercode** [comment] 2018-07-21 22:13
@Knindzagxg test with 10 or more players

**Comment by SoulBasementGc** [comment] 2018-07-22 05:35
@Knindzagxg with a player test , There is no specific map for this problem and there is no problem with the start server.
You join Dungeon  with 5 characters in a group after some time you can see or 10 characters online and move maps

**Comment by legends-wow** [comment] 2018-07-22 11:53
I confirm this, even with new maps extracted these errors still continues

2018-07-22 12:29:45 ERROR: VMapManager2: could not load 'data/vmaps/Sholazar_Crystal_07.m2.vmo'
2018-07-22 12:29:45 ERROR: VMapManager2: could not load 'data/vmaps/Sholazar_Crystal_07.m2.vmo'
2018-07-22 12:30:18 ERROR: VMapManager2: could not load 'data/vmaps/He_Tent_01.m2.vmo'
2018-07-22 12:30:24 ERROR: VMapManager2: could not load 'data/vmaps/Titanchest_Noanim.m2.vmo'
2018-07-22 12:38:10 ERROR: VMapManager2: could not load 'data/vmaps/Wg_Wall01C.wmo.vmo'
2018-07-22 12:38:45 ERROR: VMapManager2: could not load 'data/vmaps/Wg_Wall01D.wmo.vmo'

**Comment by btechn01** [comment] 2018-07-22 11:54
I confirm this, even with new maps extracted these errors still continues

2018-07-22 12:29:45 ERROR: VMapManager2: could not load 'data/vmaps/Sholazar_Crystal_07.m2.vmo'
2018-07-22 12:29:45 ERROR: VMapManager2: could not load 'data/vmaps/Sholazar_Crystal_07.m2.vmo'
2018-07-22 12:30:18 ERROR: VMapManager2: could not load 'data/vmaps/He_Tent_01.m2.vmo'
2018-07-22 12:30:24 ERROR: VMapManager2: could not load 'data/vmaps/Titanchest_Noanim.m2.vmo'
2018-07-22 12:38:10 ERROR: VMapManager2: could not load 'data/vmaps/Wg_Wall01C.wmo.vmo'
2018-07-22 12:38:45 ERROR: VMapManager2: could not load 'data/vmaps/Wg_Wall01D.wmo.vmo'

**Comment by Hir0shi** [comment] 2018-07-23 01:54
Confirm!

**Comment by BarbzYHOOL** [comment] 2018-07-23 02:03
4 people said there is no bug though

can someone tell exact steps?

**Comment by Meltie2013** [comment] 2018-07-23 05:22
I just want to point a few things out on why these errors are here, but need to confirm some things here.

1) What version of TrinityCore is you guys merge the tools and map updates from?
2) Why are there different versions of maps used in the tools, from different commits made?

Just wanted to point some of the main issue that will cause these issues. Also, I was testing this project with some thing and while in the world server, I was seeing loads of issues with VMaps not loading in zones/areas.

By comparing some of the commits for these updates, it appears these were taken from 7.2.x Tool/Map update from TrinityCore instead of 3.3.5a.

**Comment by Stoabrogga** [comment] 2018-07-23 06:37
I took the modifications from 3.3.5:
Original PR: #926 (see AC commit a18d1474a3691f34b763925ff2cc922828394e42)
TC commits from where I took over the changes:
https://github.com/TrinityCore/TrinityCore/commit/c35793941b3aae9b54dce92389aa528d40050754
https://github.com/TrinityCore/TrinityCore/commit/89d641f1e68d11359a2398ff51d3d6eee1470ae8
https://github.com/TrinityCore/TrinityCore/commit/f8fd0b7a2c0a9acd084f011c614d529e49397479
https://github.com/TrinityCore/TrinityCore/commit/7ef22e43057080926685eb45f0fce3f2f3d58c61

Because of an issue affecting Wintergrasp (#972 ) I created a second PR #976 (see AC commit 8e9faf848865769d8e1d851889f04eae07fb976a) which reverted the WMO changes from the first two TC commits mentioned:
https://github.com/TrinityCore/TrinityCore/commit/c35793941b3aae9b54dce92389aa528d40050754
https://github.com/TrinityCore/TrinityCore/commit/89d641f1e68d11359a2398ff51d3d6eee1470ae8

So effectively only changes from these two TC commits are currently active in AC:
https://github.com/TrinityCore/TrinityCore/commit/f8fd0b7a2c0a9acd084f011c614d529e49397479
https://github.com/TrinityCore/TrinityCore/commit/7ef22e43057080926685eb45f0fce3f2f3d58c61

**Comment by BarbzYHOOL** [comment] 2018-07-23 14:50
@dunjeon the issue you reported is already there BEFORE stoabrogga's commits so not related (still an issue)

**Comment by BarbzYHOOL** [comment] 2018-07-23 21:34
I tested myself and I see 0 issue... this feels like a conspiracy

**Comment by DeActiver** [comment] 2018-07-24 03:07
Confirm : 4e27109

**Comment by Knindzagxg** [comment] 2018-07-24 11:40
Still 0 issues for me.
Wasn't lazy so did full test on DK chain quests and had only 1 error inside my log - SAI wise.

`2018-07-24 13:11:42 ERROR: Vehicle GuidLow: 2027917, Entry: 28670 attempts to uninstall, but already has STATUS_UNINSTALLING! Check Uninstall/PassengerBoarded script hooks for errors.
`
Full preview of quests and as i said above, i had 0 issues with maps, grip or quests itself.

I'm guessing you guys extracted your own maps, and from what i heard, you had some RAM issues as well. Try to download maps which Tala updated few days ago.

![GitHub Logo](https://i.imgur.com/OVSuGxy.jpg)
![GitHub Logo](https://i.imgur.com/fG3zxzn.jpg)
![GitHub Logo](https://i.imgur.com/gYP7mv4.jpg)
![GitHub Logo](https://i.imgur.com/VYfDAhv.jpg)
![GitHub Logo](https://i.imgur.com/KcS17KL.jpg)
![GitHub Logo](https://i.imgur.com/7BFPijA.jpg)
![GitHub Logo](https://i.imgur.com/geZj2mc.jpg)
![GitHub Logo](https://i.imgur.com/GIAETYK.jpg)
![GitHub Logo](https://i.imgur.com/LGGOE4Q.jpg)
![GitHub Logo](https://i.imgur.com/t8e4xsI.jpg)
![GitHub Logo](https://i.imgur.com/Gl6Z10a.jpg)
![GitHub Logo](https://i.imgur.com/jeHUxHg.jpg)

**Comment by devfrom** [comment] 2018-07-24 12:54
You still keep insisting that there is no mistake, and that has been done several tests, understand that the error is linked in the vmapas.

the error in the worldserver log does not stay all the time, it pops up a few times.

because of the error being in the vmaps it is as if certain maps were not extracted so this map is not loaded in the game, so the reason to appear (Zone Unknown) and players can not explore maps and gain experience in them is because of this.

It is no use to want to inform that there is no mistake, because it has. there's no use wanting to test for a few minutes alone that nothing appears.

I have tested it several times in the clean source code, with new maps extracted and the error still continues.

@BarbzYHOOL @Stoabrogga 

I urge you to remove the modifications that have been made to TrinityCore and correct these errors after correcting this you can place in the official repository.

![image](https://user-images.githubusercontent.com/41171790/43138821-7f401248-8f26-11e8-81af-e8732466ba60.png)

**Comment by Knindzagxg** [comment] 2018-07-24 13:44
Been checking / running trough mentioned zones to see will i get any error ... Still nothing.

**Comment by BarbzYHOOL** [comment] 2018-07-24 14:35
> I urge you to remove the modifications that have been made to TrinityCore and correct these errors after correcting this you can place in the official repository.

You urge us nothing especially if you really don't know what you're talking about. Nobody clearly showed us how to reproduce the issue.
We all spent a lot of time testing this issue, Knindza just tried to load the "wmo" in your screenshot and it worked fine, so I'm closing this issue because nothing has been proven.

**Closed by BarbzYHOOL** 2018-07-24 14:35 UTC
Labels: Invalid - CannotReproduce, Not confirmed, Priority - High

**Comment by Swiftsmoke** [comment] 2018-07-25 07:01
Sorry I know this is a closed report however:

I was experiencing this issue too and finally found that it was related to creature_template table. I am still trying to figure out what has changed in the table to break it. That said once you start using a fresh world it fixes the above issue.
