### ISSUE TITLE
DB/Quest: Volatile Mutations

### ISSUE THREAD

**Issue by cherbert** [azerothcore/azerothcore-wotlk#14115] opened 2022-12-10 15:51 UTC
### Current Behaviour

NPC Questgiver: Botanist Taerix on Azuremyst Island

Quest - [Volotile Mutations](https://www.wowhead.com/wotlk/quest=9371/)

### Expected Blizzlike Behaviour

Quest "Volatile Mutations" should not be given before the quest "[Urgent Delivery!](https://www.wowhead.com/wotlk/quest=9409/urgent-delivery)" has been completed. The flavor text makes no sense if given at the same time. 

### Source

https://www.wowhead.com/wotlk/quest=9371/botanist-taerix

### Steps to reproduce the problem

Create new Draenei character and login into the Draenei starting area. Walk to the NPC Botanist Taerix.

### AC rev. hash/commit

AzerothCore rev. f8948253dd38 2022-12-10 13:20:16 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 10 x64

**Comment by heyitsbench** [comment] 2022-12-10 15:52
> I was told AzerothCore is the better core. Yet it's database clearly isn't.

No need to be that way.

**Comment by heyitsbench** [comment] 2022-12-10 15:59
Cannot reproduce on dc766b430c8e7ee1c90967a533d96b68b61b9584. Looks like it's been fixed on AC [in the past](https://github.com/azerothcore/azerothcore-wotlk/pull/4111).

**Comment by cherbert** [comment] 2022-12-10 16:00
> > I was told AzerothCore is the better core. Yet it's database clearly isn't.
> 
> No need to be that way.

I apologise. It's just frustrating seeing basic glaring starter zone quests broken. TrinityCore fixed it 6 years ago. I get the vibe that this core is better and I just spent the afternoon compiling it and getting it all up and running only to run into one of the most common db flaws that you would expect to find in a 10 year old mango database dump. It might be stupid and small but it just worries me about what else is broken if something like this is missed? I get the impression most people jump in to these servers and just run raids without caring much about vanilla wow experience.

**Comment by cherbert** [comment] 2022-12-10 16:04
> Cannot reproduce on [dc766b4](https://github.com/azerothcore/azerothcore-wotlk/commit/dc766b430c8e7ee1c90967a533d96b68b61b9584). Looks like it's been fixed on AC [in the past](https://github.com/azerothcore/azerothcore-wotlk/pull/4111).

OK, if this is the case then maybe the trickererbot fork is broken? I built it from here https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

If this is the case then I apologise.

**Comment by heyitsbench** [comment] 2022-12-10 16:06
https://user-images.githubusercontent.com/38561765/206864081-abeb7d04-7454-4d3a-a5ba-a634012609d4.mp4

Unless I'm doing something wrong, it looks to be specific to @trickerer's branch.

**Comment by cherbert** [comment] 2022-12-10 16:09
ok, I'm an idiot. I reported the wrong quest. I was actually referring to the Volatile Mutations quest from the NPC round the corner. She offers it too early before you have completed Urgent Delivery. If you can confirm if that is indeed wrong I'll delete this and redo the bug report.

Sorry.

**Comment by heyitsbench** [comment] 2022-12-10 16:17
> I was actually referring to the Volatile Mutations quest from the NPC round the corner. She offers it too early before you have completed Urgent Delivery.

This I can confirm. Looks like [that quest](https://www.wowhead.com/wotlk/quest=10302) should only be available after completing [Botanist Taerix](https://www.wowhead.com/wotlk/quest=9371) which (I'm assuming) becomes available after completing Urgent Delivery, unless the last report is incorrect. 😛

> If you can confirm if that is indeed wrong I'll delete this and redo the bug report.

No need to delete it, you can just edit the issue.

**Comment by heyitsbench** [comment] 2022-12-10 16:23
Submitted a PR that should fix this issue. Feel free to test it out if you're able. 😀

**Comment by cherbert** [comment] 2022-12-10 20:02
> Submitted a PR that should fix this issue. Feel free to test it out if you're able. 😀

Sorry I took so long to get back to you. I was doing a re-compile. I can confirm this has fixed it and the quest line now behaves as intended.

Thank you!

**Closed** 2022-12-10 20:02 UTC
