### ISSUE TITLE
Huge Memory Leak 6 hours  = 1.694gb-> 2.810gb

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1887] opened 2019-05-25 16:03 UTC
Huge Memory Leak 6 hours  = 1.694 -> 2.810gb

##### SMALL DESCRIPTION:

Huge Memory Leak 6 hours  = 1.694 -> 2.810gb
check attach picture for more info

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be no memory leak? 
![61503231_797648367302293_5676357202210717696_n](https://user-images.githubusercontent.com/18629476/58372005-b525bc00-7f49-11e9-8302-ada2a3ffd53a.png)

##### CURRENT BEHAVIOUR:

memory leak 6 hours  = 1.694gb -> 2.810gb

##### STEPS TO REPRODUCE THE PROBLEM:

1. start server with 20+ people
2. wait 6-7 hours
3. just keeps on leaking

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

Azerothcore rev. ded199dd7e7b+

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by BarbzYHOOL** [comment] 2019-05-25 16:42
if it's a memory leak, then it will run out of memory and mega crash

never happened

**Comment by Selyria** [comment] 2019-05-25 20:34
So my server has been running for 12 days and I have a consumption of about 1.9GB ram on Windows 10 players are between 12-43 on it

**Comment by BarbzYHOOL** [comment] 2019-05-25 20:40
http://www.azerothcore.org/wiki/FAQ

**Comment by FrancescoBorzi** [comment] 2019-05-26 17:51
> In computer science, a memory leak is a type of resource leak that occurs when a computer program incorrectly manages memory allocations[1] in such a way that memory which is no longer needed is not released.

https://en.wikipedia.org/wiki/Memory_leak

You're only showing that the memory used by AC increases after a while. I don't see any leak here.

I'm closing this because it's not about a memory leak and not even about an issue. Thank you anyway for your contribution.

**Closed by FrancescoBorzi** 2019-05-26 17:51 UTC

**Comment by fmrmx** [comment] 2019-06-15 19:25
In fact there is a memory leak in AzerothCre, since the owners made a mess with grids and wintergrasp somewhere between 2017-2018, i fixed that long ago but i do not remember where the error was.

**Comment by BarbzYHOOL** [comment] 2019-06-15 20:01
not as easy as spitting bullshit

**Comment by FrancescoBorzi** [comment] 2019-06-15 22:22
> i fixed that long ago but i do not remember where the error was

so why didn't you share the solution by then?

**Comment by fmrmx** [comment] 2019-06-27 05:17
I do not need to reproduce anything, you all know that AC has some failures regarding memory management, stop acting like you all dont know about that, i will attack a picture of a fresh TC server with up to 25 days up and running and see what is the normal memory usage for a worldserver snapshot

![imagen](https://user-images.githubusercontent.com/5169055/60238453-b449b800-9870-11e9-890c-f01c5e67f752.png)
 
so look at the memory and cpu usage, and i have also apache, mysql and some node modules running along with worldserver, authserver and postfix, so stop acting like you all dont know about memory errors on your core.

**Comment by poszer** [comment] 2019-06-27 05:35
> In fact there is a memory leak in AzerothCore, since the owners made a mess with grids and wintergrasp somewhere between 2017-2018, i fixed that long ago but i do not remember where the error was, but is related to gameobject active in grids.
> 
> i do not know why they keep closing issues, ah yea is the easy way.

Proofs? Way to reproduce it? Ah yes, there is no way

**Comment by fmrmx** [comment] 2019-06-27 23:06
i am not interested in posting proofs, or ways to reproduce it, and i dont need to, i am not a server owner anymore, that was long ago, but there memory errors, stop trying to act like you all dont know, and closing issues, because there are like 10 reports of memory leaks and all closed, at least accept it lol.

**Comment by poszer** [comment] 2019-06-27 23:21
> i am not interested in posting proofs, or ways to reproduce it, and i dont need to, i am not a server owner anymore, that was long ago, but indeed there are memory errors, stop trying to act like you all dont know, and closing issues, because there are like 10 reports of memory leaks and all closed, at least accept it lol.

If there is, we need to find each memory leak source.  The issue is accepted, but not reproduced :) If the Google Chrome use 2,5Gb than what's the problem of AC using 2,8 with some players online. Have a good day

**Comment by FrancescoBorzi** [comment] 2019-06-27 23:24
@fmrmx it's not about accepting it or not. We close duplicate reports because it makes no sense to report the same (generic) thing multiple times (and it just creates caos). We demand details because without them we are not able to fix the issue, since most of the reports unfortunately are too generic.

**Comment by milestorme** [comment] 2019-06-28 00:35
10 days uptime on my test for this memory hasn’t moved above 15% , I have grids set to not unload , I see no memory leaks at all I see very stable numbers

**Comment by fmrmx** [comment] 2019-06-28 00:53
well at least check out some parts of the wintegrasp code , because there are some problems with AC, and yes 2.8g is a problem because most cores uses 1.3 to 1.6 gb of ram, and scales according to population, but AC increases up to 4-5gb i have observed that when some player logs in, there is a tiny memory increase, but when the player logs out, that tiny space remains forever until server restart, i am unable to reproduce the problem, because there is no glitch, it is simply memory usage increase, if it where an instance/spell/script problem, it would be more easier. i will atach you a screen of my core, so you can see the normal memory usage of a TrinityCore/SunwellCore based server.

![imagen](https://user-images.githubusercontent.com/5169055/60309741-fd534800-9914-11e9-94e4-8ce36e7b8db4.png)

2 days, 5 hours uptime.

i have

worldserver
authserver
mysql
apache
node
php
 
all running on the same machine, 2gb ram ubuntu 16.0x no problems at all

**Comment by milestorme** [comment] 2019-06-28 08:23
no memory leak here many months of testing, came from TrinityCore before Azerothcore

**Comment by fmrmx** [comment] 2019-06-28 20:03
> 
> 
> no memory leak here many months of testing, came from TrinityCore before Azerothcore, no memory leaks their either, this is paranoia without a shred of networking evidence , im guessing like most others with abnormal issues you modified your core, because AC runs very well especially the way it utilizes multi cores, but you all type top not top -H -p [pid] , geez , you stinged on hardware and are now screaming memory leak.

Not quite, what is the point of reporting issues of a modified core?, that is nonsense. lol, my harware is perfectly working and i have advanced linux management knowledge, i dont sting anything lol. you are not talking to a skid dude.

**Comment by fmrmx** [comment] 2019-06-28 20:33
ok i found a problem in this lines.

https://github.com/TrinityCore/TrinityCore/pull/7992/commits/cefcab32bbad8d4eadcc8d072da1932bcc4e23a3

for every user online, gameobjects loads, and stay in memory, if this two lines are deleted, it is possible to come back to old 1.0x AzerothCore but that lines is a hack, TC never merged those changes, because of this.

`the set active usage for gobjects on azeroth is a pure suicide cuz then every player on the continent has this loaded so with roundabout 50 players ur ram will start to burn :D

so set active only for instances` so erasing that lines will possibly fix the memory usage problem. but i do not have the tools for testing it. but that lines was a hack, never merged into TC, due to bad memory management.

**Comment by FrancescoBorzi** [comment] 2019-06-28 23:35
>  i have observed that when some player logs in, there is a tiny memory increase, but when the player logs out, that tiny space remains forever until server restart

Look, I haven't investigated the issue myself, but this is a good example of what **should not taken for granted as a memory leak**. It could be, for example, that the core stores this data about the player in the memory **on purpose** and then **it keeps it there** so when the player comes back the core doesn't have to reload the data from the database (which would instead be slower). Resulting in a overall performance increase at the price of more memory usage (that is fine since we have plenty of memory nowadays).

Of course, without an actual investigation we cannot exclude that it could just be that this memory is kept for no reason and it's just a programming mistake, thus a memory leak that should be indeed fixed.

What I'm trying to say here is just don't take for guaranteed that there is a problem when you see more memory used. Do investigate the code and the behaviour of the core before coming to a conclusion (being positive or negative).

**Comment by fmrmx** [comment] 2019-06-28 23:43
> 
> 
> > i have observed that when some player logs in, there is a tiny memory increase, but when the player logs out, that tiny space remains forever until server restart
> 
> Look, I haven't investigated the issue myself, but this is a good example of what **should not taken for granted as a memory leak**. It could be, for example, that the core stores this data about the player in the memory **on purpose** and then **it keeps it there** so when the player comes back the core doesn't have to reload the data from the database (which would instead be slower). Resulting in a overall performance increase at the price of more memory usage (that is fine since we have plenty of memory nowadays).
> 
> Of course, without an actual investigation we cannot exclude that it could just be that this memory is kept for no reason and it's just a programming mistake, thus a memory leak that should be indeed fixed.
> 
> What I'm trying to say here is just don't take for guaranteed that there is a problem when you see more memory used. Do investigate the code and the behaviour of the core before coming to a conclusion (being positive or negative).

Please read before answering, the core is not storing anythinh in database, but in memory, and if you are talking about performance, then it is not correct to store every player data until relog, because this itself is a huge performance impact, also as i said before and as stated by professional developers in the trinity comunity, they all came to the conclusion that that was not a correct way of managing memory, and also regardless of memory availability nowadays, the problem is that the core is not managing memory correctly, now , if you all decide that is correct, well then it is "correct", i do not use your core anyways, and idk if it gets fixed or not, but for the good trust the communit have in your hands, you shall must do something. not try to hide the sun with a finger.

**Comment by FrancescoBorzi** [comment] 2019-06-28 23:50
I don't know what you mean by "storing in the memory" but whatever is not in the database will be lost at server reload. 

> then it is not correct to store every player data until relog

> i have observed that when some player logs in, there is a tiny memory increase, but when the player logs out, that tiny space remains forever until server restart

If you log in and out **the same character** does the memory keep increasing? In that case there would be an issue for sure, otherwise we cannot determine whether it's a memory leak or not without additional context.

**Comment by FrancescoBorzi** [comment] 2019-06-28 23:53
Also, just to remove any doubts (if any) this comment is clearly referring to "Azeroth" as the continent and not AzerothCore since the comment is from 2012 and we created AzerothCore only in mid 2016

![image](https://user-images.githubusercontent.com/75517/60376606-6ec3f100-9a10-11e9-902d-5f3da5fa5888.png)

**Comment by fmrmx** [comment] 2019-06-28 23:56
Nevermind guys, i will not bother anymore. good luck.

**Comment by FrancescoBorzi** [comment] 2019-06-28 23:56
@fmrmx no bothering at all, any technical discussion is always welcome

**Comment by fmrmx** [comment] 2019-06-28 23:59
AzerothCore is based in SunwellCore, wich is based in TrinityCore, the lines i found, are found on your core too, that lines was a "hack" never merged to TC because of bad memory management, azeroth is the "world" of course.

**Comment by FrancescoBorzi** [comment] 2019-06-29 00:05
@fmrmx sure. I've also noticed that we have those lines while TC hasn't. Still we couldn't reproduce the issue mentioned in that discussion which sounds quite critical:

>  so with roundabout 50 players ur ram will start to burn

But still, if you have investigated it and think that those lines should be removed, it would be nice if you could come up with a PR that implements the needed changes and explain what would be impacted by them so we can test it accordingly.

**Comment by fmrmx** [comment] 2019-06-29 01:00
> 
> 
> @fmrmx sure. I've also noticed that we have those lines while TC hasn't. Still we couldn't reproduce the issue mentioned in that discussion which sounds quite critical:
> 
> > so with roundabout 50 players ur ram will start to burn
> 
> But still, if you have investigated it and think that those lines should be removed, it would be nice if you could come up with a PR that implements the needed changes and explain what would be impacted by them so we can test it accordingly.

I am too lazy to do that. really lazy, especially now. well i am too lazy to write...

**Comment by Selyria** [comment] 2019-06-29 20:14
> > @fmrmx sure. I've also noticed that we have those lines while TC hasn't. Still we couldn't reproduce the issue mentioned in that discussion which sounds quite critical:
> > > so with roundabout 50 players ur ram will start to burn
> > 
> > 
> > But still, if you have investigated it and think that those lines should be removed, it would be nice if you could come up with a PR that implements the needed changes and explain what would be impacted by them so we can test it accordingly.
> 
> I am too lazy to do that. really lazy, especially now. well i am too lazy to write...

oh, man, this is supposed to be a joke, right?

They are too lazy to fix it but they can write very well see above.

**Comment by fmrmx** [comment] 2019-06-30 17:26
> 
> 
> > > @fmrmx sure. I've also noticed that we have those lines while TC hasn't. Still we couldn't reproduce the issue mentioned in that discussion which sounds quite critical:
> > > > so with roundabout 50 players ur ram will start to burn
> > > 
> > > 
> > > But still, if you have investigated it and think that those lines should be removed, it would be nice if you could come up with a PR that implements the needed changes and explain what would be impacted by them so we can test it accordingly.
> > 
> > 
> > I am too lazy to do that. really lazy, especially now. well i am too lazy to write...
> 
> oh, man, this is supposed to be a joke, right?
> 
> They are too lazy to fix it but they can write very well see above.

it is your cores, not mine. as i said before, i am happy with my private core.

**Comment by FrancescoBorzi** [comment] 2019-06-30 17:45
I hope you wrote your "private core" from scratch instead of violating the GPL license of an existing project.
