### ISSUE TITLE
NPC "Colonel Jules" "Fly" after completing quest 10935.

### ISSUE THREAD

**Issue by MathematicalWTF** [azerothcore/azerothcore-wotlk#4993] opened 2021-03-25 00:57 UTC
##### CURRENT BEHAVIOUR:

The Colonel Jules: https://wowpedia.fandom.com/wiki/Colonel_Jules, after having "finished the excorcism", he allows you to finish the quest while he is in the air.
![WoWScrnShot_032221_183215](https://user-images.githubusercontent.com/79039973/112389520-da5cf000-8cc2-11eb-8c92-366571110ad2.jpg)

After a few seconds he returns to his bed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After having finished the excorcism, the npc Jules "already in bed" allows you to right click to finish the quest.

##### SOURCE:

https://www.youtube.com/watch?v=rl3eXf6WsKw

##### STEPS TO REPRODUCE THE PROBLEM:

1. Select the mission "The exorcism of Colonel Jules" ID 10935
2. Kill all spirits while Barada excorcises Jules and heals the anchorite with the "Ritual Prayer Beads".
3. When the necessary time has passed, you will see that Jules will let you finish the quest while he is flying.

##### EXTRA NOTES:

Apparently the error has always been in azerothcore.

##### AC HASH/COMMIT:

8bacb39 

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

None

##### CUSTOMIZATIONS:

None

**Comment by Si1ker** [comment] 2021-03-25 01:58
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/638

**Closed by Si1ker** 2021-03-25 01:58 UTC
Labels: Invalid - Duplicate
