### ISSUE TITLE
Imps on the mountains - Redridge Mountains

### ISSUE THREAD

**Issue by nolt** [azerothcore/azerothcore-wotlk#5101] opened 2021-04-01 22:36 UTC
## CURRENT BEHAVIOUR:

While looking wrong mineral vein spawn I meet those three little fella
https://imgur.com/zrDLxCz
https://imgur.com/2RXv2tE
https://imgur.com/e0sx12E

No GUID in creature table.

## EXPECTED BLIZZLIKE BEHAVIOUR:

They shouldn't be there.

## STEPS TO REPRODUCE THE PROBLEM:

1. .go xyz -8787 -2161 194
2. .go xyz -8754 -2191 229

## AC HASH/COMMIT:

Commit: https://github.com/azerothcore/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

## OPERATING SYSTEM:

Ubuntu 20.04

## MODULES:

None

## CUSTOMIZATIONS:

None

**Comment by jordigil** [comment] 2021-04-02 12:58
They looks like pets of the warlock orcs of stonewatch keep, maybe?

**Comment by Si1ker** [comment] 2021-04-04 17:22
They have no GUID because they're summoned by spell/SAI. Confirmed.
![image](https://user-images.githubusercontent.com/61223313/113516531-f7ea4f00-9537-11eb-8672-a4ed288ac7c2.png)

**Comment by claudiodfc** [comment] 2021-06-16 23:44
This bug doesn't belong to the 1-19 project, but to an overall rework to how the PetAI behaves.

**Comment by FrancescoBorzi** [comment] 2021-06-17 17:21
@claudiodfc updated

**Comment by UltraNix** [comment] 2021-08-28 19:23
Already fixed by 261d5c62

**Closed by UltraNix** 2021-08-28 19:23 UTC
Labels: DB, Confirmed, ChromieCraft Generic
