### ISSUE TITLE
ULDUAR Torim BUG

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#18966] opened 2024-05-28 11:54 UTC
### Current Behaviour

The two groups of monsters before Torim started, The IDs are 32882 and 32883 respectively, which are in a static state. This is incorrect

### Expected Blizzlike Behaviour

According to the situation of Blizzard's nostalgia suit, these two groups of monsters are in combat, not in a stationary state

### Steps to reproduce the problem

Enter Torim's room

### AC rev. hash/commit

AzerothCore rev. 46aed4dec768+ 2024-05-28 06:44:38 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 16 minute(s) 8 second(s)
Update time diff: 1ms. Last 500 diffs summary:
- Mean: 3ms
- Median: 2ms
- Percentiles (95, 99, max): 8ms, 9ms, 11ms
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.78.0
Using CMake version: 3.29.2
Using MySQL version: 80032
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.20348
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Bulid/bin/RelWithDebInfo/data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Bulid/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Bulid/bin/RelWithDebInfo/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: Skip_DK_Script.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

WINDOWS SERVER 2022

**Comment by heyitsbench** [comment] 2024-05-28 11:59
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15403.

**Closed by heyitsbench** 2024-05-28 11:59 UTC
