### ISSUE TITLE
[server]world server crash 1024

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13535] opened 2022-10-24 08:11 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/b502e0fa5730cb9ea1d0783516a8e5e9

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

77a52b8001ba6292b87138471deb7d8aa7b84e4b

### Operating system

Ubuntu20.04

**Comment by Kitzunu** [comment] 2022-10-30 20:41
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13172

**Closed by Kitzunu** 2022-10-30 20:41 UTC
