### ISSUE TITLE
Stackoverflow - Fel Soldier - Outland

### ISSUE THREAD

**Issue by SilentCLD** [azerothcore/azerothcore-wotlk#11203] opened 2022-03-28 13:24 UTC
### Current Behaviour

A stackoverflow occurs when the two packs of Fel Soldiers walking down the road towards the Dark Portal enter combat range with the faction specific (Horde/Alliance) NPCs standing at the top of the first set of stairs

https://gist.github.com/SilentCLD/62864d363b5742e0c26048f4f5e3d450

### Expected Blizzlike Behaviour

No crash

### Steps to reproduce the problem

1. `.go xyz -221.142731 1552.936646 47.970886 530 4.591798`
2. Follow the packs to the portal
3. Crash

### AC rev. hash/commit

AzerothCore rev. 9e7d1e2a3af7 2022-03-27 17:40:21 +0000 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.74.0
Using MySQL version: 50718
Using CMake version: 3.22.1
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in data/maps. Total size: 252191207 bytes
vmaps directory located in data/vmaps. Total size: 658130721 bytes
mmaps directory located in data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_03_27_22
Using Character DB Revision: 2022_03_01_00
Using Auth DB Revision: 2021_11_06_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Windows 10 x64 Professional

**Comment by UltraNix** [comment] 2023-01-07 09:45
Cannot reproduce it - closing.

**Closed by UltraNix** 2023-01-07 09:45 UTC
Labels: Priority-Critical, HasBacktrace
