### ISSUE TITLE
Quest Bear Druid

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5506] opened 2021-04-27 21:21 UTC
CURRENT BEHAVIOUR:

[Body and Heart] Quest

EXPECTED BLIZZLIKE BEHAVIOUR:

This is a bear bug quest
Must be after clicking
It completes but does not work

SOURCE:
![WoWScrnShot_042821_014647](https://user-images.githubusercontent.com/80007195/116314028-d4779480-a7c3-11eb-8060-2cfa5033ce9b.jpg)
![WoWScrnShot_042821_014659](https://user-images.githubusercontent.com/80007195/116314034-d6415800-a7c3-11eb-99f4-daca19bf21b1.jpg)
![WoWScrnShot_042821_014720](https://user-images.githubusercontent.com/80007195/116314037-d8a3b200-a7c3-11eb-97cb-b712e862a7ad.jpg)

STEPS TO REPRODUCE THE PROBLEM:

Entry NPC : 12144

EXTRA NOTES:
AC HASH/COMMIT:

rev. 26a477d 2021-04-24 10:42:48 +0000

OPERATING SYSTEM:
Ubuntu 20.10

MODULES:
N/A.

CUSTOMIZATIONS:
N/A.

**Comment by r-o-b-o-t-o** [comment] 2021-04-27 23:00
https://user-images.githubusercontent.com/24357633/116322631-b490a280-a7bc-11eb-99bc-7584c4fe978d.mp4

Working as intended, see this video (warning, loud music): 
https://www.youtube.com/watch?v=_IXoNvDHmtU&t=28s

I think we can close this one

**Comment by poryagholami1374** [comment] 2021-04-28 06:31
>  2021-04-28.00-55-24.mp4 
> Working as intended, see this video (warning, loud music):
> https://www.youtube.com/watch?v=_IXoNvDHmtU&t=28s
> 
> I think we can close this one

![WoWScrnShot_042821_105907](https://user-images.githubusercontent.com/80007195/116356817-02cf9100-a811-11eb-8b0d-f97483426f2f.jpg)
First I get the quest
It should be an exclamation mark
Not that it is a sign of completion

**Comment by poryagholami1374** [comment] 2021-04-28 06:33
>  2021-04-28.00-55-24.mp4 
> Working as intended, see this video (warning, loud music):
> https://www.youtube.com/watch?v=_IXoNvDHmtU&t=28s
> 
> I think we can close this one

Please sql this quest
You send me

**Comment by Sedatyf** [comment] 2021-04-28 07:14
As you can see on @r-o-b-o-t-o video everything just work fine. Maybe you just have to reload and you'll have your question mark to finish quest. But as he said, it's working as intended

**Comment by r-o-b-o-t-o** [comment] 2021-04-28 07:49
> First I get the quest
> It should be an exclamation mark
> Not that it is a sign of completion

Did you add the quest with GM commands? If so, could you try again by doing the whole questchain properly?

**Comment by poryagholami1374** [comment] 2021-04-28 08:12
> Did you add the quest with GM commands? If so, could you try again by doing the whole questchain properly?

If you have SQ, send me this quest, thank you

**Comment by Sedatyf** [comment] 2021-04-28 08:18
If you installed a server, you can look by yourself in the database for your quest. As we said, for us, there is no reason for this issue. So in my opinion, it's your work to investigate to confirm there is a bug or not. We gave you our proof, show us some proof that this bug is real

**Comment by r-o-b-o-t-o** [comment] 2021-04-28 08:22
> If you have SQ, send me this quest, thank you

This has nothing to do with the issue, and does not answer my question. If you are not able to reproduce this the way I asked you to, you can close this issue.
Also, we are not here to provide files to everyone that comes and ask, if you think there is a problem with your database, just drop your tables and reimport them from the SQL files in the repository.

**Closed** 2021-04-28 08:40 UTC
