### ISSUE TITLE
The boss of Naxamas cannot enter the battle.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#14373] opened 2022-12-26 09:10 UTC
### Current Behaviour

The boss of Naxamas cannot enter the battle.
BOSS name:Safiron
Hard:25 raid(not the hero)
issue:You briefly enter the battle when you attack the boss, but quickly leave the battle once the attack stops.

### Expected Blizzlike Behaviour

The boss should be able to be killed.

### Steps to reproduce the problem

1.Adjust the dungeon difficulty to 25 raid.
2.Enter the Naxamas dungeon.
3.Kill all the bosses before Safiron.
4.Fight with Safiron.

### AC rev. hash/commit

AzerothCore rev. c05c45c51d3d 2022-12-22 06:42:54 +0000 (master branch) (Win64, RelWithDebInfo, Static) 

### Operating system

Windows Server 2019 x64

### Custom changes or Modules

Use the autobalance module.

**Comment by 15877500030** [comment] 2022-12-26 09:17
Supplemental version number:AzerothCore rev. c05c45c51d3d 2022-12-22 06:42:54 +0000 (master branch) (Win64, RelWithDebInfo, Static)

**Comment by sogladev** [comment] 2024-11-28 23:24
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15043
fixed with: https://github.com/azerothcore/azerothcore-wotlk/pull/15048

**Closed by sogladev** 2024-11-28 23:24 UTC
