### ISSUE TITLE
Can't walk on water while in spirit mode after dying inside any dungeon/raid/instance

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2039] opened 2019-07-02 15:43 UTC
Can't walk on water while in spirit mode after dying inside any dungeon/raid/instance

##### SMALL DESCRIPTION:

Normally when you die, and you spirit walk to your body, you can walk on water. but if you die inside The Slave Pens dungeon it won't work. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to walk on water while in spirit mode after dying inside dungeon/raid/instance

##### CURRENT BEHAVIOUR:

Normally when you die, and you spirit walk to your body, you can walk on water. but if you die inside dungeon/raid/instance it won't work. 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Die inside any dungeon and release spirit
3.  Try to walk on water

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

031e0ae

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Selyria** [comment] 2019-07-06 13:14
so I just tested it ml once you die in an instance, you can't walk on water anymore. No matter in which instance you died.

**Comment by spinzaku** [comment] 2019-07-07 10:46
> so I just tested it ml once you die in an instance, you can't walk on water anymore. No matter in which instance you died.

Yes i have tested also recently. and my players also reported. will edit post

**Comment by locus313** [comment] 2020-11-28 05:56
confirmed on https://github.com/azerothcore/azerothcore-wotlk/commit/37d1f2be4729e4f9465a0591d451af4b8a945418

**Comment by buddiman** [comment] 2021-06-12 20:15
This seems to be fixed on https://github.com/azerothcore/azerothcore-wotlk/commit/dafef5bd7859b330cc5c835ee463107944cc915f

I went into the slave pens, .die on myself and released. I could walk on water like it's supposed to be.
![WoWScrnShot_061221_221315](https://user-images.githubusercontent.com/10009755/121788193-9d224300-cbcb-11eb-95a6-ae4c2b00a580.jpg)

**Comment by FrancescoBorzi** [comment] 2021-06-13 16:49
thank you @buddiman !

**Closed by FrancescoBorzi** 2021-06-13 16:49 UTC
Labels: CORE, Confirmed, Priority - Low
