### ISSUE TITLE
(Malygos/Razorscale): Flying bosses in the ground

### ISSUE THREAD

**Issue by iyasenai** [azerothcore/azerothcore-wotlk#4900] opened 2021-03-18 23:39 UTC
##### CURRENT BEHAVIOUR:

Bosses like Malygos and Razorscale literally fly on the ground.
Malygos:
![image](https://user-images.githubusercontent.com/37153212/111710437-b22f4600-8817-11eb-8398-d840d1ae3b2e.png)
Razorscale:
![image](https://user-images.githubusercontent.com/37153212/111710573-ed317980-8817-11eb-8492-6930f5e9aeb3.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The bosses must walk on the ground

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to any of the mentioned bosses and start the fight.

##### EXTRA NOTES:

In onyxia everything works correctly.

##### AC HASH/COMMIT:

9c6ede6

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No.

**Comment by Si1ker** [comment] 2021-03-19 21:52
I have tried

```cpp
me->SetCanFly(false);
me->SetDisableGravity(false);
me->SetHover(false);
me->SendMovementFlagUpdate();
```

But they are with the flying animation even though they are with those abilities disabled

![image](https://user-images.githubusercontent.com/61223313/111845727-12cb8b00-88cb-11eb-9ce7-2b431d20c85f.png)


I would say is another bug caused by vmaps as many others reported recently

**Comment by Mesielecat** [comment] 2021-09-10 14:38
Sindragosa have the same issue after  https://github.com/azerothcore/azerothcore-wotlk/commit/7965ea5aaab47a56291fcfca8ca2b384d81339bf

**Comment by laasker** [comment] 2021-09-10 23:11
> Sindragosa have the same issue after [7965ea5](https://github.com/azerothcore/azerothcore-wotlk/commit/7965ea5aaab47a56291fcfca8ca2b384d81339bf)

Im pretty sure sindragosa had still problem before this PR

I think this can be fixed by changing the inhabit type to 1, like this PR:
https://github.com/azerothcore/azerothcore-wotlk/pull/6661

**Comment by FrancescoBorzi** [comment] 2021-09-12 17:22
cc @UltraNix

**Closed** 2021-10-09 22:58 UTC
Labels: Confirmed, Instance - Raid - Northrend
