### ISSUE TITLE
"Of Nature's Wrath" Affix Does Not Provide Correct Bonus

### ISSUE THREAD

**Issue by ospie7** [azerothcore/azerothcore-wotlk#8147] opened 2021-09-29 04:14 UTC
**Current Behaviour**
Items with "Of Nature's Wrath" affix do not provide the bonus stated in the item description. Other affixes do not display this issue..

![image](https://user-images.githubusercontent.com/80938499/135202090-75368026-ce0b-4841-8a2e-8d8fa101b6a8.png)

**Expected Blizzlike Behaviour**

Items provide a bonus equal to that in the item description.

**AC rev. hash/commit**
chromiecraft/azerothcore-wotlk@b2f0893

**Comment by FrancescoBorzi** [comment] 2021-09-29 13:25
@ospie7 please add your AC version (commit hash)

**Comment by ospie7** [comment] 2021-09-29 13:42
> @ospie7 please add your AC version (commit hash)

I'm sorry, I'm new to github, how can I do that? This bug was from the chromiecraft build.

**Comment by ospie7** [comment] 2021-09-29 14:06
> @ospie7 please add your AC version (commit hash)

Hopefully this is correct.

**Comment by JamesGent** [comment] 2021-09-29 21:12
> 
> 
> > @ospie7 please add your AC version (commit hash)
> 
> Hopefully this is correct.

Can you clear WTF and retry this experiment?

Also can you equip a char in full nature damage bonus items and do DPS test on dummies then do same test naked?

I think it might be an interface only issue, so I want to rule that out.

**Comment by Shineslippers** [comment] 2021-12-02 16:17
That's duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/8606 was reported at the same day to CC https://github.com/chromiecraft/chromiecraft/issues/1890

**Closed by Shineslippers** 2021-12-02 16:17 UTC
Labels: Invalid-Duplicate
