### ISSUE TITLE
[server] world server crash 0609

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11987] opened 2022-06-09 06:52 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/bc0b183105eb6a7b451f02fa1ecc01b8

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

94e7338fe6a2f103fac4d3ad777b4592f9af7f81

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment] 2022-06-09 13:36
crash again:

https://gist.github.com/mpfans/59369a1d5201e7a9e97da749996e8a8e

**Comment by UltraNix** [comment] 2022-06-11 09:45
Duplicate of #11650

**Closed by UltraNix** 2022-06-11 09:45 UTC
Labels: Priority-Critical
