### ISSUE TITLE
(Quest/SQL) Emergency Protocol: Section 8.2, Paragraph D, one of the southern wrecks can't be burnt

### ISSUE THREAD

**Issue by YggdrasilWotLK** [azerothcore/azerothcore-wotlk#19117] opened 2024-06-21 22:34 UTC
### Current Behaviour

The southern wreck as marked on the map isn't burnable as the trigger object (GUID 188019) is missing. 

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/157967573/77d4062a-1930-4394-8af7-ac68e58cb516)

### Expected Blizzlike Behaviour

All wrecks in the area should be burnable

### Steps to reproduce the problem

1. Go to southern crashed flying  machine and see that it's not burnable

### Extra Notes

I spawned this object on my own server to rectify it :)

INSERT INTO gameobject(guid, id, map, zoneId, areaId, spawnMask, phaseMask, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state, ScriptName, VerifiedBuild, Comment) VALUES(2580373, 188019, 571, 0, 0, 1, 1, 3389.34, 5131.52, 13.0374, 0.839682, -0, -0, -0.407615, -0.913154, 300, 0, 1, ,' nill',' nill');

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/20ff8df91ca7f563246cd367894b111f067b532a

### Operating system

Ubuntu 22.04

### Custom changes or Modules

ELUNA module

**Comment by sudlud** [comment] 2024-10-15 19:22
can't reproduce on 998d548a3

`.quest add 11796`
`.go xyz 3389.34 5131.52 13.0374 571`

use `Emergency Torch` - wreck gets burned.

side note - gameobject `188019` has no spawns in any of my sniffs. at all wrecks there are actually trigger creatures that react to the `Emergency Torch` beeing used.

---

lol alright, this was fixed just yesterday with https://github.com/azerothcore/azerothcore-wotlk/pull/20197 closing the duplicate issue #20196.

so i'm closing this, too.

**Closed by sudlud** 2024-10-15 19:22 UTC
