### ISSUE TITLE
The translation of the guard's gossip menu overlaps

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#8041] opened 2021-09-23 07:34 UTC
### Current Behaviour

![QQ截图20210923144851](https://user-images.githubusercontent.com/18187177/134469888-6fe88b3c-2cda-4cb6-85d4-14e80a25df49.jpg)

### Expected Blizzlike Behaviour

The English client is displayed correctly!
![image](https://user-images.githubusercontent.com/18187177/134469861-21fa2685-e5a1-4831-9768-dd36caa91e31.png)

### Steps to reproduce the problem

none

### AC rev. hash/commit

bdcec84

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment] 2021-09-23 07:34
Maybe there's something wrong with localization?

**Comment by LukasVolgger** [comment] 2021-09-23 09:51
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7209

I am working on a fix for deDE locales. When it's ready you can add your locale too

**Closed** 2021-09-23 09:51 UTC
