### ISSUE TITLE
[WORLD] Burning Embers damage the player from a distance.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#588] opened 2017-08-29 05:22 UTC
**Description**: Burning Embers (small fires) damage the player from too far away. This is not a HUGE issue, but it seems that it's slightly bugged. Standing the same distance from other fire sources does not have the same effect.

**Expected behavior:** 
You should have to be touching the fire to get burned.

**Steps to reproduce the problem:**
Enter the warrior/hunter training hut on Hunter Rise in Thunder Bluff and stand near a burning ember pot.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by poszer** [comment] 2019-05-23 13:17
Closing, can't reproduce.

**Closed by poszer** 2019-05-23 13:17 UTC
Labels: Help wanted, Invalid - CannotReproduce, Priority - Low
