### ISSUE TITLE
Memory leak？

### ISSUE THREAD

**Issue by chendh123** [azerothcore/azerothcore-wotlk#1525] opened 2019-02-25 10:35 UTC
61032 cdh       20   0 3283568 2.624g  32224 S  51.5 33.6 225:35.47 worldserver  

SHA-1: 15622225d642d9db207ebacf920d30c061aaa57f

Running for 12 hours, res increase from 1.3G to 2.6G

modules: mod-transmog  mod-vas-autobalance

**Comment by FrancescoBorzi** [comment] 2019-02-25 12:40
I have the same behaviour and it then stabilizes at around 3-3.5 GB of memory.

Why do you think it's a leak? Does it keep growing or it stops at some point?

**Comment by BarbzYHOOL** [comment] 2019-02-25 14:06
it stops, people use the word "leak" wrongly

**Comment by Viste** [comment] 2019-02-25 17:32
It's okay, that's enough. 
If you need, read the kernel code, you may understand that certain things are loaded into RAM and remain there until the kernel finishes its work.

**Comment by FrancescoBorzi** [comment] 2019-02-25 17:40
> Running for 12 hours, res increase from 1.3G to 2.6G

closing since this does not mean that there is a memory leak, and it's the expected behaviour

**Closed by FrancescoBorzi** 2019-02-25 17:40 UTC

**Comment by FrancescoBorzi** [comment] 2019-09-15 09:56
## AzerothCore ram usage explanation

http://www.azerothcore.org/wiki/Memory-Usage
