### ISSUE TITLE
[STUCK] Lake Everstill

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1649] opened 2019-03-28 10:41 UTC
##### SMALL DESCRIPTION:

Sometimes and sometimes often, when I am in this area and I charge murlocs, I get stuck and I can't move. If I invoke my mount, it unlocks me.
![WoWScrnShot_032819_113606](https://user-images.githubusercontent.com/31663279/55151099-c753cb80-514d-11e9-9ad4-8ded270e00c0.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I must not be stuck

##### STEPS TO REPRODUCE THE PROBLEM:

1. create warrior (i don't know if work with other class)
2. charge and kill some murlocs
3. try several times until you get stuck

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

W10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by poszer** [comment] 2019-03-28 15:22
Tested and I can't reproduce this. I've tried many times, but without issue/stuck. 

Closing this, Thank you anyway for reports.

**Closed by poszer** 2019-03-28 15:22 UTC
Labels: Invalid - CannotReproduce
