### ISSUE TITLE
Dismounting from a flight (in SW and IF) can make players fall through the floor

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7742] opened 2021-09-06 10:57 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1625

Upon taking a flight from Westfall to Stormwind I found myself falling thru the floor and onto the ground underneath Stormwind 
![Screenshot_2](https://user-images.githubusercontent.com/89442337/132097901-c059cc2d-e78d-4ed2-84c5-e59990a8b9eb.png)

### Expected Blizzlike Behaviour

I expect not to fall thru the floor

### Steps to reproduce the problem

Take a flight from Westfall to Stormwind

### Extra Notes

I was playing on 4G mobile connection, there's a very slight possibility it might be related to that, but, I wasn't the only player that fell thru.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

It didn't happen to myself, because it happens so rarely, but I heard this now from multiple players. I'm not sure, if the flight from Sentinel Hill to Stormwind has anything to do with this issue, but it could be. I only ever heard of players falling through the floor upon dismounting from a flight in Stormwind and nowhere else. It is a rare bug.

Maybe related to: https://github.com/azerothcore/azerothcore-wotlk/issues/5765

**Comment by syssneck** [comment] 2021-09-06 11:25
I created something, that might be similar to the issue at hand. I turned fly on, flew a meter or so over the ground and turned it off again (at the position, where you dismount in sw). Sometimes my character still has the flying animation, despite having turned fly off:

https://user-images.githubusercontent.com/68868567/132210222-3c06eed7-7119-4fd3-8e91-08db16d27352.mp4

I didn't fell through the floor though.

**Comment by temperrr** [comment] 2021-09-08 07:18
It also happens in Undercity. Even on 1000/1000 connection with <-1 ms ping.

**Comment by UltraNix** [comment] 2021-09-17 19:19
Can't reproduce it both.

**Comment by FrancescoBorzi** [comment] 2021-09-29 12:50
@azerothcore/bug-triaging can anyone please have a look?

**Comment by Shineslippers** [comment] 2021-11-24 16:40
Since https://github.com/azerothcore/azerothcore-wotlk/issues/8963 clientside issue. I guess there is the same. Have to close it.

**Closed by Shineslippers** 2021-11-24 16:40 UTC
Labels: ChromieCraft Generic, Needs Feedback
