### ISSUE TITLE
AI Pathing Issue [$50]

### ISSUE THREAD

**Issue by Cinnamohn** [azerothcore/azerothcore-wotlk#4468] opened 2021-02-07 00:05 UTC
##### CURRENT BEHAVIOUR:

When you silence a spellcaster and move out of melee range, they will just stand in place and do nothing until they can cast again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you silence an npc, they should move towards you to auto attack until they can cast again.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Pick a class with mana
2. .go xyz -9224 -1006 71 0
3. Stand at a distance from a Defias Rogue Wizard
4. Interrupt it with Counterspell (.cast 2139)

##### EXTRA NOTES:

They respond to moving out of line of sight, moving out of range, running out of mana, and their target being immune correctly. This is the only condition in which they don't.

##### AC HASH/COMMIT:

924ca9f

##### OPERATING SYSTEM:

Windows 10

**Comment by FrancescoBorzi** [comment] 2021-02-08 10:59
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/4091 ?

**Comment by Cinnamohn** [comment] 2021-02-09 07:46
I believe so. Thought it was related to the movement update, otherwise I would've looked further back. One thing I can add that might help to resolve the issue is that the untalented Counterspell only locks a single spell school, whereas something like a priest's Silence is a true no-spells silence. The wizard in my report reacts correctly to Silence, but Arch Mage Xintor in the video of #4091 does not. The wizard uses 1 school of magic. Xintor uses 2.

**Comment by UltraNix** [comment] 2021-03-16 10:16
Missing `SMARTCAST_COMBAT_MOVE` in SAI scripts. I'm not sure if there is any coreside solution.

**Closed** 2021-03-21 14:19 UTC
Labels: Bounty
