### ISSUE TITLE
Crash/restart close various doors in Scholomance

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9422] opened 2021-11-30 12:25 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

1. Crash/restart close various not important `Iron Gate` doors in Scholomance: `43186 (Entry: 175617)`, `43189 (Entry: 175618)`, `43197 (Entry: 175615)`, `43190 (Entry: 175614) `, `43179 (Entry: 175613)`, `43199 (Entry: 175612)`, `43198 (Entry: 175611)`
2. `43208 (Entry: 175564) - Brazier of the Herald` available to use after crash/restart. Consume `blood of Innocent`, but doesn't call boss. Ideal way doesn't active at all. Waste of blood without boss summon isn't cool.
3.  `43192 (Entry: 175167) - Viewing Room Door` after crash/restart is also closed. Need key to open. So any wipe after this door will finish dungeon.

### Expected Blizzlike Behaviour

Those objects should not get reset after crash/restart

### Steps to reproduce the problem

.additem 13873
.go ga 43192
.ser res 1

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment] 2021-11-30 12:55
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/9414

**Comment by Nyeriah** [comment] 2021-11-30 12:58
Stratholme != scholomance

**Comment by Kitzunu** [comment] 2021-11-30 13:32
No but I bet it is a generic issue with either instances or gameobjects.

**Comment by Nyeriah** [comment] 2021-11-30 13:40
> No but I bet it is a generic issue with either instances or gameobjects.

The way that those "crash recovery" mechanisms work is that a variable is stored and saved to the database so those doors and objects are open in case the server crashes. For example: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp#L1587-L1619

But if we check the Scholomance file, there's nothing about any door being loaded: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/EasternKingdoms/Scholomance/instance_scholomance.cpp#L218-L235 Neither there is any door associated with any boss so they can be automatically opened on state set.

So we need to check each of those events (Ramstein's abomination death count, Scholo boss states?) and ensure the data we need is saved and loaded in case of crashes, so the instance is restored the exact way it was once the server starts again

**Comment by claudiodfc** [comment] 2021-11-30 14:01
I tested Blood of the Innocents the other day and it was fine and we fixed the issue with opening doors recently? Do you have a crash report?

**Comment by Nyeriah** [comment] 2021-11-30 14:04
> I tested Blood of the Innocents the other day and it was fine and we fixed the issue with opening doors recently? Do you have a crash report?

Hey Claudio, I think this is not about those objects crashing, but the fact they don't behave as expected after a crash happens.

**Comment by Shineslippers** [comment] 2021-11-30 14:07
@claudiodfc Yes, there is nothing bad about scripts, or blood, or instance. I'm forcing `.server restart 1`

**Closed** 2022-05-24 13:33 UTC
Labels: Confirmed, 50-59, Instance - Dungeon - Vanilla
