### ISSUE TITLE
Kaw the Mammoth Destroyer doesn´t mount the Moria mount - Borean Tundra

### ISSUE THREAD

**Issue by cyberpro98** [azerothcore/azerothcore-wotlk#18336] opened 2024-02-15 23:01 UTC
### Current Behaviour

I accept the quest and i ride a mammoth untill this npc where the Kaw the Mammoth Destroyer should jump/mount on the MORIA and so we go in fight. But he doesn´t mount it and it´s not possible to complete the quest.
![WoWScrnShot_021524_234428](https://github.com/azerothcore/azerothcore-wotlk/assets/11796196/7a76e256-50fc-43fb-8b6e-a70a53f2014b)

### Expected Blizzlike Behaviour

The Kaw the Mammoth Destroyer should jump on his mount and attack you when you approach. 

### Source

https://www.youtube.com/watch?v=oTwddbBZu3Q&t=95s&ab_channel=Bue

### Steps to reproduce the problem

Just add a quest  11879  and you will see it ... 

### AC rev. hash/commit

AzerothCore rev. cbb1defb8ee5+ 2024-02-12 11:18:12 +0000 (master branch) (Win64,
 RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 7.
Server uptime: 1 day(s) 23 hour(s) 43 minute(s) 15 second(s)
Update time diff: 1ms, average: 4ms.
Using SSL version: OpenSSL 1.1.1w  11 Sep 2023 (library: OpenSSL 1.1.1w  11 Sep
2023)
Using Boost version: 1.81.0
Using CMake version: 3.28.1
Using MySQL version: 80035
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 6.3.9600
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev

### Operating system

Windows 2012 

### Custom changes or Modules

 List enable modules:
 HardMode
 KillStreak-Module
 item_leveler
 mod-1v1-arena
 mod-ah-bot
 mod-anticheat
 mod-autobalance
 mod-cfbg
 mod-eluna
 mod-premium
 mod-pvp-titles
 mod-solo-lfg
 mod-transmog
 mod_world_chat
 vipCommands

**Comment by heyitsbench** [comment] 2024-02-15 23:15
Duplicate of #18181.

**Closed** 2024-02-15 23:15 UTC

**Comment by cyberpro98** [comment] 2024-02-15 23:17
Is it fixed or not ?
