### ISSUE TITLE
Client data v10 package is bugged

### ISSUE THREAD

**Issue by nolt** [azerothcore/azerothcore-wotlk#5183] opened 2021-04-07 22:48 UTC
## CURRENT BEHAVIOUR:

With recent commit https://github.com/azerothcore/azerothcore-wotlk/commit/91dfedd0801a8babdb07e1bd865d586096dbbd97
and using v10 client data I get those errors in Server.log:

```
2021-04-07 23:08:08 Using DataDir ../data/
2021-04-07 23:08:08 WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
2021-04-07 23:08:08 ERROR: VMap file '../data/vmaps/000.vmtree' is missing or points to wrong version of vmap file. Redo vmaps with latest version of vmap_assembler.exe.
```

## STEPS TO REPRODUCE THE PROBLEM:

1. pull recent AC sources
2. compile and use v10 client data

## AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/91dfedd0801a8babdb07e1bd865d586096dbbd97

## OPERATING SYSTEM:

Ubuntu 20.04

## MODULES:

- none

## CUSTOMIZATIONS:

- none

**Comment by nolt** [comment] 2021-04-07 22:49
I've compiled tools and extracted on clean client (ChromieClient btw). All works fine, here are extracted all files:
https://mega.nz/file/RRRyELIC#ewajM0i59llSr9pv-niehf0taGov3l-BFr1UVG9Rn5Y

Can someone else confirm this issue?

**Comment by Ramys** [comment] 2021-04-07 23:39
This version already exists.
https://github.com/wowgaming/client-data

**Comment by FrancescoBorzi** [comment] 2021-04-08 09:32
@nolt that's weird because I've updated my core, downloaded the v10  and it worked fine for me

**Comment by nolt** [comment] 2021-04-08 12:07
User Delcid from discord was affected with same issue on Windows.

**Comment by cirosantos0** [comment] 2021-04-08 14:47
Same problem for me on ubuntu using acore.sh to download the package.
Worked with the package Ramys shared above.
Acore Version: 1dd7d7514552919b9626ffa22ed4471224afe3c8

**Comment by nolt** [comment] 2021-04-08 15:47
> Same problem for me on ubuntu using acore.sh to download the package.
> Worked with the package Ramys shared above.
> Acore Version: [1dd7d75](https://github.com/azerothcore/azerothcore-wotlk/commit/1dd7d7514552919b9626ffa22ed4471224afe3c8)

Wait what? :)
We talking about v10, and Ramys provided link to v10 client data package which cause this issue :)

**Comment by Ramys** [comment] 2021-04-08 17:32
Anyway for me this package works perfectly.

**Comment by FrancescoBorzi** [comment] 2021-04-08 17:54
@Helias is working on this

**Comment by Delcidx** [comment] 2021-04-08 17:58
> User Delcid from discord was affected with same issue on Windows.

Yes, i had the issue but resolve it by extracting the data.zip again and compiling the solution.

**Comment by cirosantos0** [comment] 2021-04-08 19:48
> > Same problem for me on ubuntu using acore.sh to download the package.
> > Worked with the package Ramys shared above.
> > Acore Version: [1dd7d75](https://github.com/azerothcore/azerothcore-wotlk/commit/1dd7d7514552919b9626ffa22ed4471224afe3c8)
> 
> Wait what? :)
> We talking about v10, and Ramys provided link to v10 client data package which cause this issue :)

Sorry, I should have been clearer on my reply;

Using score.sh to download and extract the files leads to the error on topic.

Extracting it manually works.

**Comment by nolt** [comment] 2021-04-08 20:08
Well I used:
```
unzip data.zip
```
and downloaded using Google Chrome; nothing special but had that issue. Tried few times and same situation. We will wait for Helias reply.

**Comment by frytik** [comment] 2021-04-08 20:27
Can confirm, same issue for me, downloads clean source, compiled and works only with v9 data
Win x64

**Comment by eTzmNcbkrng** [comment] 2021-04-09 01:47
Same issue.
Windows 10 x64.
Worked fine after I manually downloaded and extracted v10 data.zip from https://github.com/wowgaming/client-data/releases

**Comment by FrancescoBorzi** [comment] 2021-04-09 08:17
it's not the same issue, some people are saying it works only with v9 while others say it works fine downloading v10.

honestly, I don't understand where the issue is

**Comment by Kitzunu** [comment] 2021-04-09 12:04
I can confirm.

I downloaded the v10 and everything worked perfectly.
I then reran CMake, rebuilt and now I get the same error in worldsevrer and can't get it to start
```
2021-04-09 14:02:34 ERROR: VMap file 'E:\build-azeroth\bin\RelWithDebInfo\data/vmaps/000.vmtree' is missing or points to wrong version of vmap file. Redo vmaps with latest version of vmap_assembler.exe.
```

**Comment by Helias** [comment] 2021-04-09 18:21
I will upload a new version soon

**Comment by Kitzunu** [comment] 2021-04-10 01:30
@nolt rerun cmake and rebuild and see if the issue still exists

**Comment by skxawng-cu** [comment] 2021-04-10 03:44
I have a problem with v10 data, all Workshop's NPCs in Winter Battlefield are underground. 

And Singragoza in ICC raid go underground too.

**Comment by skxawng-cu** [comment] 2021-04-10 03:46
I want to know what file permissions I have to give to data folder, now I am using 0777 because with default permissions the mage blink can cause that the player go underground. 
Any one can help?

**Comment by FrancescoBorzi** [comment] 2021-04-10 09:12
> I have a problem with v10 data, all Workshop's NPCs in Winter Battlefield are underground.
> 
> And Singragoza in ICC raid go underground too.

@UltraNix or anyone else: can you confirm this?

**Comment by UltraNix** [comment] 2021-04-10 09:18
Wintergrasp fixed by #5188.
Sindragosa - works okay for me.
@Helias Make sure that `vmap_magic` is updated.

**Comment by Helias** [comment] 2021-04-10 12:43
client data updated, try this
https://github.com/wowgaming/client-data/releases/tag/v10

@UltraNix what do you mean with vmap_magic?

**Comment by UltraNix** [comment] 2021-04-10 12:53
`VMAP_MAGIC`

**Comment by cirosantos0** [comment] 2021-04-10 15:51
> > I have a problem with v10 data, all Workshop's NPCs in Winter Battlefield are underground.
> > And Singragoza in ICC raid go underground too.
> 
> @UltraNix or anyone else: can you confirm this?

Sindragosa working without problems.
Can confirm Wintergrasp NPC under floor on c05fa1a0a915ab90e8d7731ad0f8f3b2ff2e7731.
#5188 fixes it.

**Comment by nolt** [comment] 2021-04-10 17:17
@Helias @Kitzunu 
Just finished testing new client data, all works without any problems.
Testing procedure:
- unziped new client_data on revision https://github.com/azerothcore/azerothcore-wotlk/commit/91dfedd0801a8babdb07e1bd865d586096dbbd97 without cmake/rebuild - no errors
- rerun cmake and rebuild with same rev as above - no errors
- pulled rev https://github.com/azerothcore/azerothcore-wotlk/commit/c05fa1a0a915ab90e8d7731ad0f8f3b2ff2e7731 and build - no errors

**Closed** 2021-04-10 21:05 UTC
Labels: Fix included, mmap/vmap

**Comment by Dude100** [comment] 2021-04-10 21:13
> I have a problem with v10 data, all Workshop's NPCs in Winter Battlefield are underground.
> 
> And Singragoza in ICC raid go underground too.

+1
