### ISSUE TITLE
Could not find text for creature

### ISSUE THREAD

**Issue by devfrom** [azerothcore/azerothcore-wotlk#980] opened 2018-07-18 15:19 UTC
PROBLEM

2018-07-17 06:42:51 CreatureTextMgr: Could not find Text for Creature(Disidra Stormglory) Entry 32718 in 'creature_text' table. Ignoring.
2018-07-17 06:43:55 CreatureTextMgr: Could not find Text for Creature(Moon Priestess Nici) Entry 32714 in 'creature_text' table. Ignoring.
2018-07-17 06:44:08 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-17 06:44:13 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.
2018-07-17 06:44:52 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-17 06:45:01 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-17 08:53:26 SmartScript::ProcessAction: Entry 20071 SourceType 0, Event 0, Link Event 1 not found or invalid, skipped.
2018-07-17 09:11:51 CreatureTextMgr: Could not find Text for Creature(Great Hexer Ohodo) Entry 32719 in 'creature_text' table. Ignoring.
2018-07-17 09:12:38 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.

Someone who can solve this problem? appears directly in worldserver.exe

AC HASH / COMMIT:
8767372

OPERATIONAL SYSTEM:
Windonws R2 2008

MODULES:
NO

**Comment by BarbzYHOOL** [comment] 2018-07-18 21:51
try this from knindza and report the result here https://pastebin.com/hF62Z6JC

**Comment by devfrom** [comment] 2018-07-19 13:44
@BarbzYHOOL  I ran still reporting the same db error in worldserver.exe

**Comment by dunjeon** [comment] 2018-07-19 14:36
The sql insert helps, but the creature text table doesn't have guid 27047 as the ss above shows.

**Comment by devfrom** [comment] 2018-07-19 14:42
@dunjeon Do you know how we can solve this situation?

**Comment by Knindzagxg** [comment] 2018-07-19 14:43
I haven't complete all off them - Will start working on creature text during weekend.

**Comment by dunjeon** [comment] 2018-07-19 20:20
TCs creature_texts has about ~2.5k additions that are likely usable.  (I use them)

**Comment by BarbzYHOOL** [comment] 2018-07-19 21:17
hmm that might be a good idea dunjeon, would you mind giving us the sql?

(And what about the accelerated daytime script/module on your repack? you could post the script if no module)

**Comment by dunjeon** [comment] 2018-07-20 00:08
Extracted 2.5k creature_texts from TC and knindza thta are missing from AC  (This won't fix all the problems, but it's a start.)
bcc08f682cb8b61109fbb6414f5cd51d778f89fb

@BarbzYHOOL 
TimeIsTimePlus is a core hack at the moment. I'm working on a module version =;

**Comment by vhipercode** [comment] 2018-07-20 00:19
@dunjeon  What is your discord or skype?

**Comment by dunjeon** [comment] 2018-07-20 02:15
Discord: Dunjeon

**Comment by dunjeon** [comment] 2018-07-20 17:08
@BarbzYHOOL 
https://github.com/dunjeon/azerothcore-wotlk/commit/bcc08f682cb8b61109fbb6414f5cd51d778f89fb

**Comment by devfrom** [comment] 2018-07-24 12:45
even running those texts the CreatureMgr error in the worldserver still continues.
@dunjeon 
2018-07-24 02:42:49 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-24 02:43:15 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:44:01 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-24 02:44:06 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:44:26 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-24 02:45:05 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.
2018-07-24 02:45:06 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:45:10 CreatureTextMgr: Could not find Text for Creature(Warp-Huntress Kula) Entry 32711 in 'creature_text' table. Ignoring.
2018-07-24 02:46:59 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:48:09 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.
2018-07-24 02:48:47 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:49:18 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:50:26 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:50:59 CreatureTextMgr: Could not find Text for Creature(Invisible Stalker (Floating Only)) Entry 27047 in 'creature_text' table. Ignoring.
2018-07-24 02:51:12 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.
2018-07-24 02:54:16 CreatureTextMgr: Could not find Text for Creature(Orland Schaeffer) Entry 29506 in 'creature_text' table. Ignoring.

**Comment by Hir0shi** [comment] 2018-07-24 12:51
Confirm!

**Comment by dunjeon** [comment] 2018-07-24 12:51
@devfrom correct.  it's ironic that out of the additional 2.5k Only ~2 of the ones you reported were corrected.  Getting a full working list will take some time, but the good news is that this is probably the simplest thing to work on in all of wow emu development.  if you would like to champion the task, I would be willing to teach you how to do it.

**Comment by dunjeon** [comment] 2018-07-24 12:54
I made sure to note in #984 that the commit could not close the issue.  I'm pretty sure this could be a near never ending search for completion and the errors don't hurt anything.
@BarbzYHOOL  Low priority perhaps?

**Comment by Knindzagxg** [comment] 2018-07-25 05:21
`INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `TextRange`, `comment`) VALUES (27047, 0, 0, '', 12, 0, -1, 0, 0, 0, 0, 0, 'Invis ');
`
`INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `TextRange`, `comment`) VALUES (32711, 0, 0, 'So peaceful...', 12, 0, 100, 0, 0, 0, 0, 0, 'Dala Hunter');
`
`INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `TextRange`, `comment`) VALUES (29506, 0, 0, 'Welcome traveler!', 12, 0, 100, 0, 0, 0, 0, 0, 'BS Trainer');
`
Dunno what you doing wrong tbh, fix for test is already there.
Tho, try adding 1 by 1 now.

**Comment by Swiftsmoke** [comment] 2018-07-25 06:01
27047 (Invisible Stalker) is due to smart_script in Dalaran Where the Stalker is moving close to her and triggering her Invoker script 

Aemara - OOC LOS - Say Line
entry 28989

**Comment by poszer** [comment] 2018-11-02 11:11
Confirmed on Win. Too much reports for these NPC's. I have investigating this issue, and it looks like these NPC, in my situatation Warp - Huntress Kula is kinda bugged, Actually he's pet. While walking around Dalaran, pet get stucked always, and can't continue to follow Warp. 
Here is picture : 
![pet](https://user-images.githubusercontent.com/41213210/47912260-48a57b80-de98-11e8-88e2-8d94bb735bbd.png)

This is also way to reproduce problem, and you will get Error in log. Just follow him until pet get stucked :stuck_out_tongue_winking_eye: 

Here is picture if if you kill he's pet what's happening.
![log](https://user-images.githubusercontent.com/41213210/47912238-34fa1500-de98-11e8-94e5-ad133674d58b.png)

**Comment by poszer** [comment] 2019-01-28 02:10
**Try this :**
```
UPDATE `creature_template` SET `AIName`= 'SmartAI',`ScriptName`= '' WHERE  `entry` IN(29491,28994,28721,28725,33027,28727,28715,28714,28726,29523,28989,28997,28723,28718);
 
DELETE FROM `smart_scripts` WHERE `entryorguid` IN(29491,28994,28721,28725,33027,28727,28715,28714,28726,29523,28989,28997,28723,28718) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `COMMENT`) VALUES
(29491, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Karandonna - OOC LOS - Say Line'),
(28994, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Abra Cadabra - OOC LOS - Say Line'),
(28721, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tiffany Cartier - OOC LOS - Say Line'),
(28727, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edward Egan - OOC LOS - Say Line'),
(33027, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Jessica Sellers - OOC LOS - Say Line'),
(28725, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Patricia Egan - OOC LOS - Say Line'),
(28715, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Endora Moorehead - OOC LOS - Say Line'),
(28714, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Ildine Sorrowspear - OOC LOS - Say Line'),
(28726, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Dominique Stefano - OOC LOS - Say Line'),
(29523, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Bragund Brightlink - OOC LOS - Say Line'),
(28989, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Aemara - OOC LOS - Say Line'),
(28997, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Griselda Hunderland - OOC LOS - Say Line'),
(28723, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Larana Drome - OOC LOS - Say Line'),
(28718, 0, 0, 0, 10, 0, 100, 0, 1, 20, 30000, 120000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Ranid Glowergold - OOC LOS - Say Line');
 
DELETE FROM `creature_text` WHERE `creatureid` IN(29491,28994,28721,28725,33027,28727,28715,28714,28726,29523,28989,28997,28723,28718);
INSERT INTO `creature_text` (`creatureid`, `groupid`, `id`, `text`, `TYPE`, `language`, `probability`, `emote`, `duration`, `sound`, `COMMENT`, `BroadcastTextID`) VALUES
(29491, 0, 0, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Karandonna', 32811),
(29491, 0, 1, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Karandonna',32936),
(28994, 0, 0, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Abra Cadabra',32935),
(28994, 0, 1, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Abra Cadabra',32811),
(28994, 0, 2, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Abra Cadabra',32936),
(28994, 0, 3, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Abra Cadabra',32810),
(28721, 0, 0, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Tiffany Cartier',32809),
(28721, 0, 1, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Tiffany Cartier',32808),
(28721, 0, 2, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Tiffany Cartier',32935),
(28721, 0, 3, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Tiffany Cartier',32810),
(28721, 0, 4, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Tiffany Cartier',32936),
(28721, 0, 5, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Tiffany Cartier',32811),
(28725, 0, 0, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Patricia Egan',32811),
(28725, 0, 1, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Patricia Egan',32936),
(28725, 0, 2, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Patricia Egan',32809),
(28725, 0, 3, 'Welcome!', 12, 0, 100, 3, 0, 0, 'Patricia Egan',32807),
(33027, 0, 0, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Jessica Sellers',32810),
(33027, 0, 1, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Jessica Sellers',32808),
(33027, 0, 2, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Jessica Sellers',32811),
(33027, 0, 3, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Jessica Sellers',32809),
(33027, 0, 4, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Jessica Sellers',32936),
(28727, 0, 0, 'Welcome!', 12, 0, 100, 3, 0, 0, 'Edward Egan',32807),
(28727, 0, 1, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Edward Egan',32935),
(28727, 0, 2, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Edward Egan',32811),
(28727, 0, 3, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Edward Egan', 32809),
(28715, 0, 0, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Endora Moorehead',32809),
(28715, 0, 1, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Endora Moorehead',32808),
(28715, 0, 2, 'Welcome!', 12, 0, 100, 3, 0, 0, 'Endora Moorehead',32807),
(28714, 0, 0, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Ildine Sorrowspear',32936),
(28714, 0, 1, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Ildine Sorrowspear',32935),
(28714, 0, 2, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Ildine Sorrowspear',32810),
(28726, 0, 0, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Dominique Stefano',32809),
(28726, 0, 1, 'Welcome!', 12, 0, 100, 3, 0, 0, 'Dominique Stefano',32807),
(28726, 0, 2, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Dominique Stefano',32808),
(28726, 0, 3, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Dominique Stefano',32811),
(28726, 0, 4, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Dominique Stefano',32935),
(28726, 0, 5, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Dominique Stefano',32810),
(29523, 0, 0, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Bragund Brightlink',32936),
(29523, 0, 1, 'Welcome!', 12, 0, 100, 3, 0, 0, 'Bragund Brightlink',32807),
(29523, 0, 2, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Bragund Brightlink',32809),
(29523, 0, 3, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Bragund Brightlink',32810),
(28989, 0, 0, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Aemara',32809),
(28989, 0, 1, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Aemara',32935),
(28989, 0, 2, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Aemara',32811),
(28989, 0, 3, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Aemara',32808),
(28989, 0, 4, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Aemara',32810),
(28989, 0, 5, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Aemara',32936),
(28997, 0, 0, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Griselda Hunderland',32808),
(28997, 0, 1, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Griselda Hunderland',32810),
(28997, 0, 2, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Griselda Hunderland',32935),
(28997, 0, 3, 'Welcome!', 12, 0, 100, 3, 0, 0, 'Griselda Hunderland',32807),
(28723, 0, 0, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Larana Drome',32808),
(28723, 0, 1, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Larana Drome',32935),
(28723, 0, 2, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Larana Drome',32936),
(28718, 0, 0, 'Welcome!', 12, 0, 100, 3, 0, 0, 'Ranid Glowergold',32807),
(28718, 0, 1, 'Greetings.', 12, 0, 100, 3, 0, 0, 'Ranid Glowergold',32935),
(28718, 0, 2, 'Welcome. May I help you find something?', 12, 0, 100, 3, 0, 0, 'Ranid Glowergold',32811),
(28718, 0, 3, 'Let me know if you need help finding anything, $c.', 12, 0, 100, 3, 0, 0, 'Ranid Glowergold',32810),
(28718, 0, 4, 'Greetings! Please have a look around.', 12, 0, 100, 3, 0, 0, 'Ranid Glowergold',32809),
(28718, 0, 5, 'Greetings, $c.', 12, 0, 100, 3, 0, 0, 'Ranid Glowergold',32808),
(28718, 0, 6, 'Welcome.', 12, 0, 100, 3, 0, 0, 'Ranid Glowergold',32936);
```

**Closed** 2019-02-04 21:44 UTC
Labels: Fix included, Priority - Low
