### ISSUE TITLE
UBRS skinning The Beast froze the game

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9088] opened 2021-11-09 13:22 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When you trying to skinning The Beast game froze and you have to do server restart.

https://user-images.githubusercontent.com/85256266/140931814-183e89d5-ea82-4e62-aff7-904987852c4d.mp4

### Expected Blizzlike Behaviour

X

### Source

X

### Steps to reproduce the problem

.additem 12709 - skining dagger
.setskill 173 400 - dagger skill if needed
.setskill 393 400 - skinning
.go c id 10430
.cast 10768

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-11-09 13:31
Confirmed. Followed test instruction above, and immediately disconnected when trying to skin the NPC:

https://user-images.githubusercontent.com/81782124/140932830-359d9f54-c16e-403c-9d10-e67aa645064b.mp4

**Comment by Shineslippers** [comment] 2021-11-09 13:33
Logs clear. There have to spawn NPC [Finkle Einhorn](https://wowgaming.altervista.org/aowow/?npc=10776) after skinning

**Comment by acidmanifesto** [comment] 2021-11-09 13:52
I had to modify the steps but i am getting no crash or segmentation fault and not breaks on debugger being hit.
**But im using a revision from 6 days ago.**https://github.com/azerothcore/azerothcore-wotlk/commit/f30725144dbc1b25be08591568b82076c19e60a5
So i will do a clean recompile with the current to check. But as of right now, the revision from 6 days ago  it is fine,
Had to modify the repo step though.
I will report back.

Repo steps i did:
.additem 12709 - skining dagger
.setskill 173 400 - dagger skill if needed
**.setskill 393 400 - skinning** had to do this for the skinning to work
.go c id 10430
.cast 10768
![image](https://user-images.githubusercontent.com/16887899/140935511-cae0f551-c812-43d3-8db2-ba8bf6b85a69.png)

**Comment by temperrr** [comment] 2021-11-09 14:00
Can't get it to crash server on latest ac.
@acidmanifesto there has been a fix for the beast a few days ago, so could be that you don't have that yet.

**Comment by acidmanifesto** [comment] 2021-11-09 14:03
> Can't get it to crash server on latest ac. @acidmanifesto there has been a fix for the beast a few days ago, so could be that you don't have that yet.

oh i didnt get a crash on my revision from 6 days ago. im pulling the latest now to retest with debugger attached. Currently compiling. so if i hit a break then i will see what the issue is, if it is current with the current revision as of 30 minutes ago.

**Comment by acidmanifesto** [comment] 2021-11-09 14:15
so i am getting the crash.
![image](https://user-images.githubusercontent.com/16887899/140939713-82dca16f-85e5-4ea7-aea8-9327ca307b6b.png)
which is caused by: https://github.com/azerothcore/azerothcore-wotlk/blob/540e8e92091626dc70d44908a0129a887002a04e/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_the_beast.cpp#L154
![image](https://user-images.githubusercontent.com/16887899/140939854-f6d7f121-de43-4b6f-9c3c-46e71e3c6553.png)
However, the only changes done with in the past 6 days was https://github.com/azerothcore/azerothcore-wotlk/commit/d80f7d467d475deafa867d474c18f1026bcfac62#diff-2541299a3a8045508d3da09728007c10e79af9dbf2de1546207e4b9e87ae5851
@Nyeriah any ideas?

**Comment by Kitzunu** [comment] 2021-11-09 14:25
is it trying to talk while dead?

**Comment by acidmanifesto** [comment] 2021-11-09 14:33
> is it trying to talk while dead?

i may of followed the wrong stack.  but updating per the convo in the discord.
![image](https://user-images.githubusercontent.com/16887899/140943246-1163bb33-6725-43e8-b22b-92eba14ceca4.png)
Seems to be the issue. maybe.

**Comment by Nyeriah** [comment] 2021-11-09 14:50
The callstack I read at discord is pointing to

 https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp#L171

It's a AI::Talk() crash caused right after a creature is added to the map by a summon spell. Seems to match the description of line 171: Talk() is being called before the creature's AI is initialized.

**Comment by patou01** [comment] 2021-11-09 16:12
But OnCreatureCreate should only be called after the AI is initialized, no? I'd assume nobody in a dungeon wants a "non-ready mob" when scripting.

Shouldn't then this be the fix? (Assuming that's where the crash happens)
![image](https://user-images.githubusercontent.com/2592673/140961142-239b734b-fe61-4c3c-aff0-09bcea6cc37e.png)


Else we need to make it clear to not use AI() in "OnCreatureCreate" which to me is not logical, but maybe it is to others.

**Comment by patou01** [comment] 2021-11-09 16:16
After making the above change:
![image](https://user-images.githubusercontent.com/2592673/140962158-a5e42766-d758-4080-9d3c-01d55a731f0f.png)

**Comment by patou01** [comment] 2021-11-09 16:22
``` 
void Creature::AddToWorld()
{
    ///- Register the creature for guid lookup
    if (!IsInWorld())
    {
        GetMap()->GetObjectsStore().Insert<Creature>(GetGUID(), this);
        if (m_spawnId)
            GetMap()->GetCreatureBySpawnIdStore().insert(std::make_pair(m_spawnId, this));

        TC_LOG_DEBUG("entities.unit", "Adding creature %s with DBGUID %u to world in map %u", GetGUID().ToString().c_str(), m_spawnId, GetMap()->GetId());

        Unit::AddToWorld();
        SearchFormation();
        AIM_Initialize();
        if (IsVehicle())
            GetVehicleKit()->Install();

        if (GetZoneScript())
            GetZoneScript()->OnCreatureCreate(this);
    }
}
```
This is from trinitycore, so they basically did exactly what I suggested... Whether they adjusted something else around it or if someone wants to check when that happened, that's up ot you guys :)

**Comment by Nyeriah** [comment] 2021-11-09 16:28
Bottom line is: if we had used Eluna, nothing of this would've happened.

But yes, feel free to PR that change, it makes sense and shouldn't affect anything. But I'd still avoid AI calls during creature spawns if possible

Thanks

**Comment by acidmanifesto** [comment] 2021-11-09 16:31
> ```
> void Creature::AddToWorld()
> {
>     ///- Register the creature for guid lookup
>     if (!IsInWorld())
>     {
>         GetMap()->GetObjectsStore().Insert<Creature>(GetGUID(), this);
>         if (m_spawnId)
>             GetMap()->GetCreatureBySpawnIdStore().insert(std::make_pair(m_spawnId, this));
> 
>         TC_LOG_DEBUG("entities.unit", "Adding creature %s with DBGUID %u to world in map %u", GetGUID().ToString().c_str(), m_spawnId, GetMap()->GetId());
> 
>         Unit::AddToWorld();
>         SearchFormation();
>         AIM_Initialize();
>         if (IsVehicle())
>             GetVehicleKit()->Install();
> 
>         if (GetZoneScript())
>             GetZoneScript()->OnCreatureCreate(this);
>     }
> }
> ```
> 
> This is from trinitycore, so they basically did exactly what I suggested... Whether they adjusted something else around it or if someone wants to check when that happened, that's up ot you guys :)
> 
> edit: Nicer with link to TC where it's done https://github.com/TrinityCore/TrinityCore/blob/04909bada85d4770a58a5b2b6f2180f5aacb1b81/src/server/game/Entities/Creature/Creature.cpp#L274

If you wish to open your own pr for the changes you suggested i would be happy to close this one. If not i will give your suggestion a go when im home and mark you appropiately as the solution provider.

**Comment by patou01** [comment] 2021-11-09 16:35
Since I have the code open I make the PR it's a matter of minutes https://github.com/azerothcore/azerothcore-wotlk/pull/9090

**Closed** 2022-11-01 15:34 UTC
Labels: Confirmed, 50-59, Instance - Dungeon - Vanilla, Priority-Critical
