### ISSUE TITLE
[Quest]: The Emissary

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2552] opened 2020-01-07 00:32 UTC
Ques The Emysary problem:
https://www.wowhead.com/quest=11626/the-emissary

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Trident of Naz'jan unsleep Leviroth and short combat complete quest

##### CURRENT BEHAVIOUR:
Trident of Naz'jan kill Leviroth and no can complete quest

##### STEPS TO REPRODUCE THE PROBLEM:
.go xyz 1598.75 5573.5 6.5 571 2.2
.quest add 11626

##### BRANCH(ES):
AzerothCore rev. cf33698040e6+ 2020-01-05 21:06:41 +0100 (master branch)

##### OPERATING SYSTEM:
Ubuntu 18

##### MODULES:
Transmorf
Boss announcer

**Comment by STARRHELD** [comment] 2020-01-20 13:38
Works as intended for me.

**Comment by Nefertumm** [comment] 2020-01-20 19:33
Can't confirm eadcb1a78208f1b777bbd847048f495128c84372

**Comment by FrancescoBorzi** [comment] 2020-01-20 19:40
2 people can't reproduce the issue, closing

**Closed by FrancescoBorzi** 2020-01-20 19:40 UTC
Labels: Invalid - CannotReproduce
