### ISSUE TITLE
(DB/Quest): A Spirit Guide

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2884] opened 2020-04-12 18:33 UTC
https://www.wowhead.com/quest=9410/a-spirit-guide 

**STEPS TO REPRODUCE THE PROBLEM**:

1. Take the quest
2. Install the body of Krun Spinebreaker. 
3. Follow the wolf

**EXPECTED BLIZZLIKE BEHAVIOUR**:
You must follow the wolf.

**CURRENT BEHAVIOUR:**
The wolf is following you

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 9c8c5ea+ 2020-04-08 23:45:58 +0000

**OPERATING SYSTEM**: Debian 9

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog

**Comment by wlasser** [comment] 2020-04-13 15:57
IN AZEROTHCORE YOU ARE NOT ESCORT SOMEBODY,
SOMEBODY ESCORT YOU.

**Comment by Hacaw** [comment] 2020-12-07 19:40
I **cannot** reproduce this issue, you can close this (but I found 1 minor issue).

TESTING
---
.q add 9410
Go to the quest location.
Summon wolf, he does both the emotes.
He starts to run and you have to follow him.

It behaves like here: https://www.youtube.com/watch?v=4BGlnjGieUk

Minor-issue: Since I am using the warmane client, and I am still a novice when it comes to extract dbc files from AC, I see that this icon is not displayed correctly. 
Check 3:04 of the above video.

SPEC
---
COMMIT: 920f19f
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by FrancescoBorzi** [comment] 2020-12-07 22:28
thanks @Hacaw !

**Closed** 2020-12-07 22:27 UTC
Labels: DB, Not confirmed
