### ISSUE TITLE
ERROR 1785 (HY000) at line 4 in file: '.\data\sql\updates\db_world\2022_08_21_15.sql'

### ISSUE THREAD

**Issue by Greyisttot** [azerothcore/azerothcore-wotlk#12866] opened 2022-08-27 13:04 UTC
### Current Behaviour

**Staff Edit by acidmanifesto for readbility**
```
2022-08-27 21:00:24 INFO  [server.worldserver] AzerothCore rev. 9b3082f99291+ 2022-08-27 12:48:41 +0000 (master branch) (Win64, Release, Static) (worldserver-daemon)
2022-08-27 21:00:24 INFO  [server.worldserver] <Ctrl-C> to stop.

2022-08-27 21:00:24 INFO  [server.worldserver]    █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
2022-08-27 21:00:24 INFO  [server.worldserver]   ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
2022-08-27 21:00:24 INFO  [server.worldserver]   ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
2022-08-27 21:00:24 INFO  [server.worldserver]   ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
2022-08-27 21:00:24 INFO  [server.worldserver]   ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
2022-08-27 21:00:24 INFO  [server.worldserver]   ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
2022-08-27 21:00:24 INFO  [server.worldserver]                                  ██████╗ ██████╗ ██████╗ ███████╗
2022-08-27 21:00:24 INFO  [server.worldserver]                                 ██╔════╝██╔═══██╗██╔══██╗██╔════╝
2022-08-27 21:00:24 INFO  [server.worldserver]                                 ██║     ██║   ██║██████╔╝█████╗
2022-08-27 21:00:24 INFO  [server.worldserver]                                 ██║     ██║   ██║██╔══██╗██╔══╝
2022-08-27 21:00:24 INFO  [server.worldserver]                                 ╚██████╗╚██████╔╝██║  ██║███████╗
2022-08-27 21:00:24 INFO  [server.worldserver]                                  ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

2022-08-27 21:00:24 INFO  [server.worldserver]      AzerothCore 3.3.5a  -  www.azerothcore.org

2022-08-27 21:00:24 INFO  [server.worldserver] > Using configuration file       configs/worldserver.conf
2022-08-27 21:00:24 INFO  [server.worldserver] > Using SSL version:             OpenSSL 1.1.1q  5 Jul 2022 (library: OpenSSL 1.1.1q  5 Jul 2022)
2022-08-27 21:00:24 INFO  [server.worldserver] > Using Boost version:           1.80.0
2022-08-27 21:00:24 INFO  [server.worldserver]  
2022-08-27 21:00:24 INFO  [server.worldserver] Process priority class set to HIGH
2022-08-27 21:00:24 INFO  [server.loading]  
2022-08-27 21:00:24 INFO  [server.loading] Loading modules configuration...
2022-08-27 21:00:24 INFO  [server.loading]  
2022-08-27 21:00:24 INFO  [server.loading] Using modules configuration:
2022-08-27 21:00:24 INFO  [server.loading] > Anticheat.conf
2022-08-27 21:00:24 INFO  [server.loading] > CFBG.conf
2022-08-27 21:00:24 INFO  [server.loading] > mod_LuaEngine.conf
2022-08-27 21:00:24 INFO  [server.loading] > reagent_bank.conf
2022-08-27 21:00:24 INFO  [server.loading] > who-logged.conf
2022-08-27 21:00:24 INFO  [server.loading]  
2022-08-27 21:00:24 INFO  [server.loading] Initializing Scripts...
2022-08-27 21:00:24 INFO  [server.loading] > Loading C++ scripts
2022-08-27 21:00:24 INFO  [server.loading]  
2022-08-27 21:00:24 INFO  [sql.driver] Opening DatabasePool '1_auth'. Asynchronous connections: 1, synchronous connections: 1.
2022-08-27 21:00:24 INFO  [sql.driver] DatabasePool '1_auth' opened successfully. 2 total connections running.
2022-08-27 21:00:24 INFO  [sql.driver]  
2022-08-27 21:00:24 INFO  [sql.driver] Opening DatabasePool '1_characters'. Asynchronous connections: 1, synchronous connections: 2.
2022-08-27 21:00:24 INFO  [sql.driver] DatabasePool '1_characters' opened successfully. 3 total connections running.
2022-08-27 21:00:24 INFO  [sql.driver]  
2022-08-27 21:00:24 INFO  [sql.driver] Opening DatabasePool '1_world'. Asynchronous connections: 1, synchronous connections: 1.
2022-08-27 21:00:24 INFO  [sql.driver] DatabasePool '1_world' opened successfully. 2 total connections running.
2022-08-27 21:00:24 INFO  [sql.driver]  
2022-08-27 21:00:24 INFO  [sql.updates] Updating Auth database...
2022-08-27 21:00:24 INFO  [sql.updates] >> Auth database is up-to-date! Containing 1 new and 31 archived updates.
2022-08-27 21:00:24 INFO  [sql.updates]  
2022-08-27 21:00:24 INFO  [sql.updates] Updating Character database...
2022-08-27 21:00:24 INFO  [sql.updates] >> Character database is up-to-date! Containing 1 new and 54 archived updates.
2022-08-27 21:00:24 INFO  [sql.updates]  
2022-08-27 21:00:24 INFO  [sql.updates] Updating World database...
2022-08-27 21:00:25 INFO  [sql.updates] >> Applying update "2022_08_21_15.sql" '1464284'...
2022-08-27 21:00:25 ERROR [sql.updates] mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1785 (HY000) at line 4 in file: '.\data\sql\updates\db_world\2022_08_21_15.sql': Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.


2022-08-27 21:00:25 FATAL [sql.updates] Applying of file './/data/sql/updates/db_world/2022_08_21_15.sql' to database '1_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
2022-08-27 21:00:25 ERROR [server.worldserver] Could not update the World database, see log for details.
2022-08-27 21:00:25 INFO  [sql.driver] Closing down DatabasePool '1_world'.
2022-08-27 21:00:25 INFO  [sql.driver] Asynchronous connections on DatabasePool '1_world' terminated. Proceeding with synchronous connections.
2022-08-27 21:00:25 INFO  [sql.driver] All connections on DatabasePool '1_world' closed.
2022-08-27 21:00:25 INFO  [sql.driver] Closing down DatabasePool '1_characters'.
2022-08-27 21:00:25 INFO  [sql.driver] Asynchronous connections on DatabasePool '1_characters' terminated. Proceeding with synchronous connections.
2022-08-27 21:00:25 INFO  [sql.driver] All connections on DatabasePool '1_characters' closed.
2022-08-27 21:00:25 INFO  [sql.driver] Closing down DatabasePool '1_auth'.
2022-08-27 21:00:25 INFO  [sql.driver] Asynchronous connections on DatabasePool '1_auth' terminated. Proceeding with synchronous connections.
2022-08-27 21:00:25 INFO  [sql.driver] All connections on DatabasePool '1_auth' closed.
```
### Expected Blizzlike Behaviour

Performing this update manually can work around the issue temporarily.

### Steps to reproduce the problem
```
ERROR 1785 (HY000) at line 4 in file: '.\data\sql\updates\db_world\2022_08_21_15.sql': Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.


2022-08-27 21:00:25 FATAL [sql.updates] Applying of file './/data/sql/updates/db_world/2022_08_21_15.sql' to database '1_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
2022-08-27 21:00:25 ERROR [server.worldserver] Could not update the World database, see log for details.
```

### AC rev. hash/commit

null

### Operating system

Windows 2019

**Comment by Nyeriah** [comment] 2022-08-27 13:11
I don't have such issue. What is your SQL server version?

**Comment by Greyisttot** [comment] 2022-08-27 15:55
> 我没有这样的问题。您的 SQL 服务器版本是多少？

mysql 8.0.29

**Comment by acidmanifesto** [comment] 2022-08-30 19:14
> > 我没有这样的问题。您的 SQL 服务器版本是多少？
> 
> mysql 8.0.29

Is the issue still occuring?

**Comment by Kitzunu** [comment] 2022-09-10 23:48
closing as no update and can't reproduce it myself

**Closed by Kitzunu** 2022-09-10 23:48 UTC
