### ISSUE TITLE
[Quest Bug] "Stinky" Ignatz ignores combat

### ISSUE THREAD

**Issue by scott-grimes** [azerothcore/azerothcore-wotlk#7945] opened 2021-09-18 00:15 UTC
### Current Behaviour

"Stinky" Ignatz (entry 4880 guid 68946) in Dustwallow starts escort quests (1222) and (1270) for alliance/horde respectively. He follows a path through the marsh near several mobs before he finally "disappears into the swamp" and the quest completes. 

Right now he does not enter combat at all. Things I've tried:
1) Attacking a monster near him, he will not assist but just keeps walking
2) Allowing him to be attacked. He continues walking w/o entering combat

See attached

### Expected Blizzlike Behaviour

I could find no reference on wowhead at https://classic.wowhead.com/npc=4880/stinky-ignatz#starts about him ignoring combat. Can't remember any escort quests off the top of my head where the escorted NPC doesn't help out when combat is entered. The only historic video I could find was from another pserver and this has the typical behavior of the escort assisting when combat is entered: https://youtu.be/ZA7Qx7WsYas?t=761

### Source

![brokenquest](https://user-images.githubusercontent.com/6396416/133865386-fac53ef9-9901-4694-b5c2-d7cd677bad64.jpeg)

### Steps to reproduce the problem

1) .go creature 68946
2) Accept escort quest 
3) Observe stinky commit suicide 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment] 2021-09-18 12:21
Seems to be a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7624 ?

**Comment by Kitzunu** [comment] 2021-09-18 17:14
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7624

**Closed by Kitzunu** 2021-09-18 17:14 UTC
Labels: Invalid-MissingHash/Commit
