### ISSUE TITLE
[server] world crash0417

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11427] opened 2022-04-18 00:26 UTC
### Current Behaviour

crash log:
https://gist.github.com/mpfans/5741574498613f0efa326d1d2dbb81b5

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a35e411fdd86f3b44e7b5f1a36b1ba2d43887a68 + PR (https://github.com/azerothcore/azerothcore-wotlk/pull/11346)

### Operating system

ubuntu 20.04

**Comment by Kitzunu** [comment] 2022-04-18 16:49
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/11331

**Closed by Kitzunu** 2022-04-18 16:49 UTC
