### ISSUE TITLE
(Crash) WorldServer.exe

### ISSUE THREAD

**Issue by gamabutara** [azerothcore/azerothcore-wotlk#17608] opened 2023-10-28 16:51 UTC
### Current Behaviour

https://gist.github.com/gamabutara/08dccd9f06851d86ac79180776e8f00a

### Expected Blizzlike Behaviour

N

### Steps to reproduce the problem

N

### AC rev. hash/commit

79b39f9655111088a741185c4dabd31dae7d85ea

### Operating system

Windows 10

**Comment by heyitsbench** [comment] 2023-10-28 17:12
Duplicate of #17575?

**Comment by It0w** [comment] 2023-10-28 22:37
During the quest "[A Job for an Intelligent Man](https://wotlk.evowow.com/?quest=9355)" on Hellfire Peninsula, the server crashes without an error appearing in the log file.

The crash happens within 5 minutes while killing monsters in the area. I can sit in Stormwind and play with my thumbs without any problems.
I am not sure if it is the same error as mentioned above.

**Comment by heyitsbench** [comment] 2023-10-28 22:50
@It0w, if you can produce a crash log, please feel free to post it in another issue.

**Closed** 2023-10-28 22:49 UTC

**Comment by It0w** [comment] 2023-10-29 05:48
@heyitsbench, I just wanted to check back in and let you know that I was able to resolve my issue.
Apparently the SQL entries for the RandomEnchants module were missing. Which led to server crash when looting.
