### ISSUE TITLE
Ruins Of AhnQiraj BOSS ayamiss crash

### ISSUE THREAD

**Issue by leewheel** [azerothcore/azerothcore-wotlk#20488] opened 2024-11-09 04:21 UTC
### Current Behaviour

The following code causes a crash:
`        ScheduleHealthCheckEvent(20, [&] {
            DoCastSelf(SPELL_FRENZY);
            Talk(EMOTE_FRENZY);
        });`
        
        
![Uploading image.png…]()

### Expected Blizzlike Behaviour

I finished beating the previous BOSS, started entering the area BOSS and started triggering events, and then it crashed

### Source

`    void Reset() override
    {
        BossAI::Reset();
        me->SetCombatMovement(false);
        me->SetReactState(REACT_AGGRESSIVE);

        ScheduleHealthCheckEvent(70, [&] {
            me->ClearUnitState(UNIT_STATE_ROOT);
            me->SetReactState(REACT_PASSIVE);
            me->SetCanFly(false);
            me->SetDisableGravity(false);
            me->GetMotionMaster()->MovePath(me->GetEntry() * 10, false);
            DoResetThreatList();
            scheduler.CancelGroup(GROUP_AIR);
        });

        ScheduleHealthCheckEvent(20, [&] {      //<--- This line crash
            DoCastSelf(SPELL_FRENZY);
            Talk(EMOTE_FRENZY);
        });
    }`

### Steps to reproduce the problem

Maybe can ---After killing the previous BOSS, I went up the slope and started attacking a slime monster, and then it collapsed.

### AC rev. hash/commit

.server debug
AzerothCore rev. 30500074a754+ 2024-11-09 07:34:07 +0800 (AshenOrderNpcBotsLFG branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.1.2 1 Aug 2023)
Using Boost version: 1.81.0
Using CMake version: 3.29.5
Using MySQL version: 80037
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8098
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in Data/maps. Total size: 467378196 bytes
vmaps directory located in Data/vmaps. Total size: 1190145929 bytes
mmaps directory located in Data/mmaps. Total size: 3397173168 bytes
Default DBC locale: enUS.
All available DBC locales: enUS koKR frFR deDE zhCN zhTW esES esMX
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: No updates found!
Latest CharacterDatabase update: No updates found!
Latest WorldDatabase update: 2024_07_17_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- DungeonRespawn
|- ReusablePotion
|- StatBooster
|- StatBoosterReroller
|- mod-absorb
|- mod-anticheat
|- mod-appreciation
|- mod-auctionator
|- mod-autobalance
|- mod-eluna
|- mod-emblem-transfer
|- mod-guildfunds
|- mod-individual-progression
|- mod-keep-out
|- mod-npc-beastmaster
|- mod-random-enchants
|- mod-reagent-bank-account
|- mod-reward-played-time
|- mod-starting-pet
|- mod-transmog
|- mod-war-effort

### Operating system

Windows 10

**Comment by sudlud** [comment] 2024-11-09 05:40
Please provide a crash log (via gist).

Also your image was not fully uploaded when you posted the issue.

**Comment by Grimdhex** [comment] 2024-11-09 05:42
We can't provide support for custom AC version. And as this raid was intensive play on CC, there are probably no regression on clean servers. 

Also, I already say it but please provide complete crash logs because we can't do anything without.

**Comment by Nyeriah** [comment] 2024-11-09 10:08
Can't possibly have a clue about what you have or haven't merged into your custom core, so cannot offer support to it. Chances are crash was addressed and you haven't merged the commit yet, as a crash for this was addressed already. That said, closing it.

**Closed by Nyeriah** 2024-11-09 10:08 UTC
Labels: Invalid-MissingHash/Commit/NotAC
