### ISSUE TITLE
Biology has incorrect spell damage

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#18248] opened 2024-02-01 02:54 UTC
### Current Behaviour

spell:37985  When the player is at level 70, the damage from each breath exhalation is 3300+
I have found that some spells cause incorrect damage when used by creatures
The damage is no longer acceptable to normal players

### Expected Blizzlike Behaviour

spell:37985
The normal damage caused by spells should be 600+

### Steps to reproduce the problem

1. leve 69  Set yourself to level 70
2. .go c 72576
3.  .modify hp 9000000
4. Waiting for creatures to cast spell: 37985

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b6c429c5a8c3c127d9a14eef72e5bfb1a796d6bf

### Operating system

debian 11

### Custom changes or Modules

no

**Comment by heyitsbench** [comment] 2024-02-01 22:24
Duplicate of #18042.

**Closed by heyitsbench** 2024-02-01 22:24 UTC
