### ISSUE TITLE
Compiling Error "Cannot start service OCI runtime failed"

### ISSUE THREAD

**Issue by hardin015** [azerothcore/azerothcore-wotlk#2338] opened 2019-10-08 03:40 UTC
##### SMALL DESCRIPTION:

 I gain an error which says that it cannot not start the containers authserver and worldserver unknown to me as for why it's doing this.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I run git-bash.exe
2. I enter the command docker-composed up according to the install docker guide wiki
3.  Error occurs

##### EXTRA NOTES:

I'm on Windows 10 Home Edition just for clarification, and I've been following the tutorial on the wiki for the install with docker guide. Here's my error text
> ERROR: For azerothcore-wotlk_ac-worldserver_1 Cannot start service ac-worldserver: OCI runtime failed: container_linux.go:345: starting container process caused "exec: \"/azeroth-server/bin/worldserver\": stat /azeroth-server/bin/woStarting azerothcore-wotlk_ac-authserver_1 ... error

> ERROR: for azerothcore-wotlk_ac-authserver_1 Cannot start service ac-authserver: OCI runtime failed: container_linux.go:345: starting container process caused "exec: \"/azeroth-server/bin/authserver\": stat /azeroth-server/bin/authserver: no such file or directory": unknown

> ERROR: for ac-worldserver Cannot start service ac-worldserver: OCI runtime failed: container_linux.go:345: starting container process caused "exec: \"/azeroth-server/bin/worldserver\": stat /azeroth-server/bin/worldserver: no such file or directory": unknown

> ERROR: for ac-authserver Cannot start service ac-authserver: OCI runtime failed: container_linux.go:345: starting container process caused "exec: \"/azeroth-server/bin/authserver\": stat /azeroth-server/bin/authserver: no such file or directory": unknown

Here's an Image [https://i.stack.imgur.com/bdNRj.png](url)
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

0a9202a82954e9458707e6e4c2b5370fb7d6a7ae

##### OPERATING SYSTEM:

Windows 10 Home Edition

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

None

**Comment by FrancescoBorzi** [comment] 2019-10-08 07:01
The error:

>  OCI runtime failed

is not a problem with AC but a generic error with Docker that probably depends on your system.

> Windows 10 Home Edition

it can also be because Docker doesn't work well in the Home edition of Windows

Closing because it's not a bug but a more of a support request, please read: https://www.azerothcore.org/wiki/How-to-ask-for-help

**Closed by FrancescoBorzi** 2019-10-08 07:01 UTC
