### ISSUE TITLE
Naxx 10 - Instructor Razuvious Encounter

### ISSUE THREAD

**Issue by NexusWoW** [azerothcore/azerothcore-wotlk#336] opened 2017-01-23 08:42 UTC
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
When using the Orb of Domination to control to the Death Knight Understudies, if understudy is dismissed (eg. because Forced Obediance is about to run out and you need to reinitiate it before it is your turn to tank) it will despawn. This effectively puts a 1:30 enrage timer on this encounter as that is the duration of a single Forced Obediance.

Expected behaviour: Tell us what should happen instead
Understudy should return to being hostile once dismissed from player control.

Steps to reproduce the problem:

At Instructor Razuvious, use an Orb of Domination to control a DK Understudy.

Right click and dismiss controlled understudy. It will despawn.

Include proofs for this behaviour
http://wowwiki.wikia.com/wiki/Instructor_Razuvious

**Comment by talamortis** [comment] 2017-01-23 11:08
I will test this later and will fix :)

**Comment by NexusWoW** [comment] 2017-01-23 12:23
I can no longer replicate it. Issue seems to be either intermittent or fixed. sorry!

**Comment by markvetwow** [comment] 2017-01-23 13:02
It happened to me too anyways. I checked the encounter three times,and every time Studies are dissapearing after canceling an orb MC.

**Comment by talamortis** [comment] 2017-01-23 21:31
i cant reproduce this issue :/

**Comment by markvetwow** [comment] 2017-01-24 11:59
There is a short movie with this issue. Hope this helps. [Link here!](https://www.youtube.com/watch?v=3BaGbbQ7XH8)

**Comment by talamortis** [comment] 2017-01-24 16:01
can you see if the problem is the same if there are 2 people in the raid/group

**Comment by markvetwow** [comment] 2017-01-24 17:15
So,there is a short movie with 2 players in a raid group. As you can see this issue still happening. At the end of movie i entered GM mode,so,studies wasn't just in invisible state. [Link.](https://www.youtube.com/watch?v=mwegrSu95pE)

**Comment by talamortis** [comment] 2017-01-24 20:14
@markvetwow thank you, does this issue only happen when you dismiss the creature and not when the spell runs out?

**Comment by markvetwow** [comment] 2017-01-24 20:22
Only when you dismiss it. Just disappearing and not visible in GM mode.

**Comment by talamortis** [comment] 2017-01-25 13:08
can you do be a favour, just to see if its an issue with the script or an issue with the pet handler, can you make a priest use mindcrontrol on a creature and then dismiss it? see if it disapears then

**Comment by markvetwow** [comment] 2017-01-25 13:10
Yea,sure. I'll report with video.

**Comment by markvetwow** [comment] 2017-01-25 13:18
So,creatures disappearing when i'm canceling MC by priest. It seems like it works like hunter pet abandon,or something like that. [Link on video.](https://youtu.be/5yODIVQOPTA)

**Comment by talamortis** [comment] 2017-01-25 13:38
thanks for testing, im testing a possible fix shortly :)

**Comment by talamortis** [comment] 2017-01-25 17:42
ok tested this issue and its a bit confusing :/ it only happens if the creature is spawned, if its already in the database and spawned without the script it works correctly.

**Comment by markvetwow** [comment] 2017-01-25 17:57
So,we need to set ScriptName string to (null) and they will not disappear?

**Comment by talamortis** [comment] 2017-01-26 19:14
@markvetwow no if u dont let the boss spawn them with the script but add them manually, they will work properly but the only downfall is u will only get 1 attempt.

**Comment by markvetwow** [comment] 2017-01-26 20:48
oh, i see. so,i need to replace them every pull?

**Comment by markvetwow** [comment] 2017-01-27 02:56
Checked that 3 times. So, if i add creature manually. I can use orb or even priest mc on them,and dismiss them. so,the strange thing is. if i spam right click on the orb. sometimes i can re-control a study. but without working one any random ability. i mean,after spamming a RMB on orb,study is under my control,but i can't use taunt for example(by mouse,or hotkey). after dismissing,and clicking on orb again,the same issue is happening,so,i can't use bone barrier for example(without any errors)

**Comment by Ercules76** [comment] 2017-08-18 21:42
News for this issue? I've tested a few time but the bug does not arise.

**Comment by poszer** [comment] 2019-02-06 11:51
Can't confirm. Closing

**Closed by poszer** 2019-02-06 11:51 UTC
Labels: Not confirmed
