### ISSUE TITLE
halls of reflection lich king starts by moving very fast and damaged to Sylvanas

### ISSUE THREAD

**Issue by fantomlancer** [azerothcore/azerothcore-wotlk#13121] opened 2022-09-24 13:34 UTC
### Current Behaviour

porblem for dungeons halls of reflection lastt boss the lich king
really problem is movement the lich king
He starts by moving very fast and damaged to Sylvanas
https://files.fm/f/mm5j97nvw
watch this video and you understand

### Expected Blizzlike Behaviour

Wrath of the Lich King is actually a gauntlet event where you must escape from the Lich King himself. It serves as the third boss encounter in the Halls of Reflection. It is tied to the achievement
We're Not Retreating; We're Advancing in a Different Direction

### Source

https://www.wowhead.com/wotlk/npc=36954/the-lich-king

### Steps to reproduce the problem

https://www.youtube.com/watch?v=QonHbWafJ5Q
time started 9:05 finished 9:25

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

windows 10

**Comment by LukasVolgger** [comment] 2022-09-24 14:36
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13080

**Closed** 2022-09-24 14:37 UTC
Labels: Invalid-Duplicate
