### ISSUE TITLE
Quest Buge  [That Which Creates Can Also Destroy]

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5856] opened 2021-05-15 08:47 UTC
## CURRENT BEHAVIOUR:
[That Which Creates Can Also Destroy]
When I shrink this npc
And if I kill it, the quest will not be solved

## EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.wowhead.com/quest=12459/that-which-creates-can-also-destroy

## SOURCE:
![WoWScrnShot_051521_130815](https://user-images.githubusercontent.com/80007195/118354221-44856900-b57f-11eb-8c35-58ff7fb8ae51.jpg)

## STEPS TO REPRODUCE THE PROBLEM:
.go cre 40504

## AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by Sedatyf** [comment] 2021-05-19 16:34
I tried this issue, and everything worked fine. I couldn't reproduce the issue. You'll have to give us more information otherwise I will close this issue

**Comment by poryagholami1374** [comment] 2021-05-19 16:37
> I tried this issue, and everything worked fine. I couldn't reproduce the issue. You'll have to give us more information otherwise I will close this issue

You have to test the hero with your spell
The quest is solved with the GM command when you kill
Try testing with a regular hero or with a spell

**Comment by Sedatyf** [comment] 2021-05-19 16:38
That's what I did. I killed all monsters with my spells and not with GM commands

**Comment by poryagholami1374** [comment] 2021-05-19 16:39
> That's what I did. I killed all monsters with my spells and not with GM commands

This is a drag quest
And killing this drag quest will not solve it
I tested with a few heroes

**Comment by tkn963** [comment] 2021-05-19 16:42
I tried this as well, several times as both Horde and Alliance, and it works as it should. I was using characters on accounts that are not set to be GMs.

**Comment by Sedatyf** [comment] 2021-05-19 16:42
I'm closing this then

**Closed by Sedatyf** 2021-05-19 16:42 UTC
Labels: Not confirmed

**Comment by poryagholami1374** [comment] 2021-05-19 16:45
> I'm closing this then

![Uploading WoWScrnShot_051921_211355.jpg…]()

**Comment by poryagholami1374** [comment] 2021-05-19 16:46
![WoWScrnShot_051921_211355](https://user-images.githubusercontent.com/80007195/118851858-741dd380-b8e7-11eb-94db-6e10109f299a.jpg)

**Comment by Sedatyf** [comment] 2021-05-19 16:46
Your revision (https://github.com/azerothcore/azerothcore-wotlk/commit/7fa1cb1c1ad24023a8f5f7e9ccc3f05f8ba80489) is way far behind the current head in master. Try to upgrade your server. But everything worked flawlessly on my side and on @tkn963 as well

**Comment by poryagholami1374** [comment] 2021-05-19 16:47
> Your revision ([7fa1cb1](https://github.com/azerothcore/azerothcore-wotlk/commit/7fa1cb1c1ad24023a8f5f7e9ccc3f05f8ba80489)) is way far behind the current head in master. Try to upgrade your server. But everything worked flawlessly on my side and on @tkn963 as well

Ok, I tested again
