### ISSUE TITLE
DB/InstanceTemplate: Icecrown RDF Reward

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#669] opened 2017-09-29 19:01 UTC
**Description**: at level 70 dongeons finder give wrong token

**Current behaviour**: Tell us what happens

at level 70 dongeons finder give wrong token

![wowscrnshot_092217_120551](https://user-images.githubusercontent.com/31663279/31031511-09733232-a559-11e7-9840-6f9c1eb36b08.jpg)

**Expected behaviour**: Tell us what should happen instead

give token for lvl 70

**Steps to reproduce the problem**:

1. character lvl 70
2. look dongeon finder
3. 

**Branch(es)**: Master 

**AC hash/commit**:  6b08fd2f6136

**Operating system**:  Win10 and ubuntu server 16.04

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Dilemmast** [comment] 2017-09-29 21:06
My bro When you are in level 70 You can Enter Normal of this instances : The Nexus - Utgarde Keep - Azjol-Nerub . And when you go to join random df you can get 2x EOT in a day . this is not issue . @ShinDarth  close it

**Comment by Maurowin** [comment] 2020-02-28 09:36
@talamortis its true issue. These token can be get at level 80. Article 2009 (sorry French site) https://worldofwarcraft.judgehype.com/news/ptr-3-3-recherche-de-groupes-et-recompenses-119139/10/

**Comment by Maurowin** [comment] 2020-02-28 12:56
When you are lvl 80 (ptr 3.3.) I can't found retail video 3.3.5
https://m.youtube.com/watch?v=cIUWlMAp-ck
I'm currently searching when you are not 80 but it's to hard. If someone has to play at this period comment to discover reality.

**Comment by Maurowin** [comment] 2020-02-28 13:29
On wowwiki.fandom.com/wiki/Dungeons_Finder :
- for wotlk normal dungeons, you receive 12 Justice Point, money and some experience.

**Comment by BarbzYHOOL** [comment] 2020-03-14 01:07
there is no justice point in wotlk

some info on dungeon finder:
https://wow.gamepedia.com/Patch_3.3.0

https://wow.gamepedia.com/Satchel_of_Helpful_Goods_(level_70)

https://www.engadget.com/2009/12/08/patch-3-3-the-dungeon-finder-guide/
https://www.engadget.com/2009/12/08/patch-3-3-the-dungeon-finder-guide-page-2/

**Comment by Kitzunu** [comment] 2020-07-22 10:01
(I don't know if this is what Barbz means) I do not think that you'd receive Justice Points for Dungeon finder in 3.3.5, seems very unlikely unless it was for the nth dungeon in NORMAL dungeon finder

**Comment by Si1ker** [comment] 2020-11-07 20:08
@Maurowin @BarbzYHOOL @Kitzunu 

![image](https://user-images.githubusercontent.com/61223313/98450486-a19cef80-2102-11eb-9c58-dc963d2f6782.png)

Source: https://www.wowhead.com/item=52005/satchel-of-helpful-goods#comments

Should we focus on the level requirement for the emblems then? 🤔

**Comment by Si1ker** [comment] 2020-11-07 20:24
A possible new issue 😹 , are we missing this in the ac ?

![image](https://user-images.githubusercontent.com/61223313/98450745-df027c80-2104-11eb-8af1-188ad667d110.png)

**Comment by BarbzYHOOL** [comment] 2020-11-07 20:56
i made a PR for that for the dungeon cooldown, we have it but not very well done, and i improved it and you even "plussed" it !

**Comment by Branel** [comment] 2021-04-20 15:14
> The Heroic Wrath of the Lich King Daily Random Dungeon option will award two [Emblems of Frost] no more than once a day.
> The normal Wrath of the Lich King Daily Random Dungeon option will award two [Emblems of Triumph] no more than once a day.
https://wowpedia.fandom.com/wiki/Emblem_of_Triumph

Dont know why you would get a lvl80 currency while doing normal dungeons, but not a bug.

**Closed** 2021-05-01 11:09 UTC
Labels: Confirmed, Instance - Dungeon - Northrend
