### ISSUE TITLE
Mad Alchemist's Potion not procing bonus buffs

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14726] opened 2023-01-21 12:19 UTC
https://github.com/chromiecraft/chromiecraft/issues/4842
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Mad Alchemist's Potion dosent give random alchemy buffs(mainly elixirs) at all 

### Expected Blizzlike Behaviour

Mad Alchemist's Potion should give elixirs buff at random

"Side effects appear randomly, and match the effects of known elixirs. The random effects will not overwrite existing flask/elixir buffs, so they do not appear if you are already under the effects of a flask or two elixirs."

### Source

https://www.wowhead.com/wotlk/item=34440/mad-alchemists-potion#comments
![image](https://user-images.githubusercontent.com/11332559/213866484-a214c008-c9ef-45c4-8cd4-ebb2fa840491.png)

### Steps to reproduce the problem

.additem 34440 
/use Mad Alchemist's Potion

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=34440

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment] 2023-01-21 17:55
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/14419

**Closed** 2023-01-21 17:58 UTC
Labels: Profession, Confirmed, ChromieCraft Generic
