### ISSUE TITLE
(dungeon) Halls of Reflection - Alliance group - Script issue

### ISSUE THREAD

**Issue by Ravenguard13** [azerothcore/azerothcore-wotlk#8989] opened 2021-11-05 21:59 UTC
### Current Behaviour

When Jaina approaches the Frostmourne stand and Uther spirit appears, the script goes all wild, they say their lines in wrong order, the timing is also wrong, when one line is still being said, the other goes too. 

Also, for some reason, Uther has lines from Quel'delar quest event even though noone in the group is doing it

### Expected Blizzlike Behaviour

The script shouldn't be broken, the timing and order of lines in dialogue between Jaina and Unther should be correct.
No Uther lines from Queldelar quest event should be said unless someone's doing the quest.

As shown in video below

### Source

https://youtu.be/U4gmguq4oHc

### Steps to reproduce the problem

1. Have a level 80 Alliance char/group
2. Enter Halls of Reflection dungeon
3. Talk to Jaina
4. Press "Can you remove the sword?"

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d35c6b602234dfc313066a2de9db74eb97798c75

### Operating system

Debian 10 x64

**Comment by avarishd** [comment] 2023-02-16 21:13
Duplicate of #773

**Closed** 2023-03-04 20:39 UTC
Labels: Instance - Dungeon - Northrend, temporary label
