### ISSUE TITLE
WaypointMovementGenerator::LoadPath: creature Eye of Dar'Khan

### ISSUE THREAD

**Issue by brunolopes1996** [azerothcore/azerothcore-wotlk#18577] opened 2024-03-18 10:42 UTC
### Current Behaviour

Red warning on worldserver console and on error log
WaypointMovementGenerator::LoadPath: creature Eye of Dar'Khan (GUID Full: 0xf130003fc0002edf Type: Creature Entry: 16320  Low: 11999) doesn't have waypoint path id: 0

### Expected Blizzlike Behaviour

Should have no error

### Steps to reproduce the problem

Run the server and start playing the game eventually it happens

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9616433b66096724177b723359ddb65b3345973c

### Operating system

windows 2022

### Custom changes or Modules

Clean Build
![clean zerothcore](https://github.com/azerothcore/azerothcore-wotlk/assets/12574972/afae3f95-1e93-4672-81b5-fc7a86e98e9b)

**Comment by sudlud** [comment] 2024-03-18 10:52
Thanks for the report!

Closing this as a duplicate of #17876

**Closed** 2024-03-18 10:52 UTC
Labels: Invalid-Duplicate
