### ISSUE TITLE
[DB]server loading warnings..

### ISSUE THREAD

**Issue by itwyceo** [azerothcore/azerothcore-wotlk#1057] opened 2018-10-20 02:49 UTC
##### SMALL DESCRIPTION:

DBerror log

##### CURRENT BEHAVIOUR:

from DBError.Log

2018-10-20 09:45:30 Table 'mail_loot_template' entry 90 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 119 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 124 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 140 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 180 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 183 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 216 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 217 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 218 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table 'mail_loot_template' entry 270 isn't mail template id and not referenced from loot, and then useless.
2018-10-20 09:45:30 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4989 Type: 19), ignored.
2018-10-20 09:45:30 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4988 Type: 19), ignored.
2018-10-20 09:45:30 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5620 Type: 73), ignored.
2018-10-20 09:45:30 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5632 Type: 73), ignored.
2018-10-20 09:45:30 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5619 Type: 73), ignored.
2018-10-20 09:45:30 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4987 Type: 19), ignored.

2018-10-20 09:45:29 No suitable start date found for holiday 321.
2018-10-20 09:45:29 No suitable start date found for holiday 283.
2018-10-20 09:45:29 No suitable start date found for holiday 284.
2018-10-20 09:45:29 No suitable start date found for holiday 285.
2018-10-20 09:45:29 No suitable start date found for holiday 353.
2018-10-20 09:45:29 No suitable start date found for holiday 400.
2018-10-20 09:45:29 No suitable start date found for holiday 420.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just see the DBerror log and console at start-up

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Windows 7

Windows server 2008 R2 enterprise

**Comment by poszer** [comment] 2018-10-22 20:04
Confirmed. Windows 7

```
2018-09-12 00:51:44 Table 'mail_loot_template' entry 90 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 119 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 124 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 140 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 180 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 183 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 216 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 217 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 218 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table 'mail_loot_template' entry 270 isn't mail template id and not referenced from loot, and then useless.
2018-09-12 00:51:44 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4989 Type: 19), ignored.
2018-09-12 00:51:44 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4988 Type: 19), ignored.
2018-09-12 00:51:44 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5620 Type: 73), ignored.
2018-09-12 00:51:44 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5632 Type: 73), ignored.
2018-09-12 00:51:44 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5619 Type: 73), ignored.
2018-09-12 00:51:44 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4987 Type: 19), ignored.
```

**Comment by BarbzYHOOL** [comment] 2018-10-22 20:17
I think all of this is because of the DBC but not sure

**Comment by StygianTheBest** [comment] 2018-12-15 05:12
I investigated this. Every one of the mail loot template errors point to quest-related mail items. You get mail once you've completed a quest trigger. The error points to the fact that they have no reference in the loot table and probably aren't linked to the quest properly. Here are the items:

`
90  - 21746 - lucky red envelope - lunar festival
119 - 15564 - rugged armor kit - ?
124 - 21746 - lucky red envelope - lunar festival
140 - 21746 - lucky red envelope - lunar festival
180 - 24132 - leter admiral - quest
183 - 31698 - letter shattrath - quest
216 - 37902 - springtime stout - brew of the month
217 - 37903 - blackrock lager - brew of the month
218 - 37904 - stranglethorn brew - brew of the month
270 - 46544, 46545 - curious wolvar pup, curious oracle hatchling - quest
`

**Comment by Kitzunu** [comment] 2021-01-16 02:57
closing as I cant confirm

**Closed by Kitzunu** 2021-01-16 02:57 UTC
Labels: Confirmed, Priority - Low
