### ISSUE TITLE
Kel'Thuzad Event

### ISSUE THREAD

**Issue by pe93** [azerothcore/azerothcore-wotlk#6862] opened 2021-07-10 09:50 UTC
### Current Behaviour

When the Event for Kel'Thuzad starts, the mobs that spawn are all targetable and a lot of them come at once at you.

### Expected Blizzlike Behaviour

The mobs should not be targetable when they are in their chambers. They should come with a certain delay one by one not all at once

### Source

Azeroth Core latest source

### Steps to reproduce the problem

1. Enter Naxxramas
2. Start the Kel'Thuzad Event after killing Sapphiron

### AC rev. hash/commit

734ac6c

### Operating system

Windows 10

### Custom changes or Modules

Noone

**Comment by Kitzunu** [comment] 2021-07-10 13:13
Add commit hash

**Comment by pe93** [comment] 2021-07-10 13:21
> Add commit hash

How do i create one, im pretty new here

**Comment by Kitzunu** [comment] 2021-07-10 13:22
.server debug

paste everything from there into AC rev. hash/commit

**Comment by FrancescoBorzi** [comment] 2021-07-12 13:42
> Running without GDB

@pe93 please run it with gdb and provide the crash dump

**Comment by pe93** [comment] 2021-07-13 08:09
so heres what i got out, no crash 

AC> AzerothCore rev. 734ac6cdd394 2021-07-01 11:39:17 +0000 (master branch) (Uni
x, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar
2020)
Using ACE version: 6.4.5
Using Boost version: 1.71.0
Using MySQL version: 80025
Using CMake version: 3.16.3
Compiled on: Linux 5.4.72-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207
 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 6581307
21 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365
052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_01_00
Using Character DB Revision: 2021_06_30_00
Using Auth DB Revision: 2021_06_17_00

**Comment by steenburgh** [comment] 2021-07-18 15:46
This is a duplicate of #6259

**Closed by steenburgh** 2021-07-18 15:46 UTC
