### ISSUE TITLE
Citizen of Havenshire behaviour bug

### ISSUE THREAD

**Issue by Bassaled** [azerothcore/azerothcore-wotlk#2918] opened 2020-04-22 00:32 UTC
##### SMALL DESCRIPTION:
Citizens of Havenshire do not flee, then after damage enrage like they should

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Citizens of Havenshire flee, then after damage enrage 

##### CURRENT BEHAVIOUR:
They just stand

##### STEPS TO REPRODUCE THE PROBLEM:

1. Fight a Citizen of Havenshire in New Avalon

##### EXTRA NOTES:
Video: https://youtu.be/b863yUtcCzM?t=1035

##### AC HASH/COMMIT:
Azeroth Core solo repack 1.3.10

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Azeroth Core solo repack 1.3.10

##### OTHER CUSTOMIZATIONS:
No

**Comment by Kitzunu** [comment] 2020-04-22 01:08
Pretty sure this is a dupe of https://github.com/azerothcore/azerothcore-wotlk/issues/2608

**Comment by Viste** [comment] 2020-04-22 06:30
send this to repack author. We don't manage this repack

**Closed** 2020-04-22 08:29 UTC
