### ISSUE TITLE
DB/Quest: Death Comes From On High script

### ISSUE THREAD

**Issue by Flerex** [azerothcore/azerothcore-wotlk#324] opened 2017-01-13 21:24 UTC
**Description**: When using the _Eye of Acherus_ in _Death Comes From On High_,  it doesn't let you move upwards or downwards and two of its abilities don't work either: _Summon Ghouls_ and _Recall Eye of Acherus_. As we can't move downwards, I don't know if it also gets the aggro from the NPCs in order to the usage of the _Summon Ghoul_ ability make sense.

I would also note that the first time I created a DK the speed of the eye was really slow but, somehow, now it seems okay. 

**Current behaviour**: 

- Two abilities don't work
- Doesn't allow you to move upwards and downwards

**Expected behaviour**:
I found a video that shows pretty much everything I'm saying:
https://www.youtube.com/watch?v=0QRxM5YeyEs

**Steps to reproduce the problem**:

1. Create a DK
2. Get to that mission
3. Use the orbs

**Branch(es)**: master

**AC hash/commit**:  e30ae1d4c329b8a203ed0d75b6eccccef30cba66

**Operating system**:  MacOS

**Modules**:  Nope

**Other Customizations**: AzerothCore straight out of the box

**Comment by talamortis** [comment] 2017-01-13 22:01
tested, and can confirm this doesnt allow me to move the creature at all

**Comment by talamortis** [comment] 2017-01-14 17:45
fixed 👍  will update later and push to branch

**Comment by Flerex** [comment] 2017-01-14 17:52
That was fast. Thanks!

**Comment by talamortis** [comment] 2017-01-14 17:53
could u please test for me though before i push?

**Comment by Flerex** [comment] 2017-01-14 17:53
Sure!

**Comment by talamortis** [comment] 2017-01-14 17:55
change this line https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L63

and change it to 

            if (type == ESCORT_MOTION_TYPE || point !=0)

**Comment by Flerex** [comment] 2017-01-14 18:09
It works now, but it does something weird. It still doesn't allow you to move upwards or downwards until you press the spacebar. Also, "Recall Eye of Acherus" still doesn't work (even tho this is not as important, as you can come back using the ability "cancel" over the action bar).

On the bright side, Summon Ghouls works perfectly and everything seems working as expected.

**Comment by talamortis** [comment] 2017-01-14 18:37
ok so can i close this issue?

**Comment by Flerex** [comment] 2017-01-14 18:39
Shouldn't those things be solved first?

**Comment by falzard** [comment] 2017-01-16 19:21
Why this is "high priority" o_0

**Comment by talamortis** [comment] 2017-01-16 19:25
because without completing this quest DK's can not go any further.

**Comment by falzard** [comment] 2017-01-16 19:43
Ok sorry, my bad.

**Comment by Voxstrasza** [comment] 2020-11-27 03:12
I cannot reproduce the bugs listed in the OP, I think it was fixed but this holds true:

>  It works now, but it does something weird. It still doesn't allow you to move upwards or downwards until you press the spacebar. Also, "Recall Eye of Acherus" still doesn't work (even tho this is not as important, as you can come back using the ability "cancel" over the action bar).
> 
> On the bright side, Summon Ghouls works perfectly and everything seems working as expected.

Gonna go ahead and close this because the original issue is fixed and the quests can be completed.  @Flerex please open a new issue to address the spacebar and recall bug.

**Closed by Voxstrasza** 2020-11-27 03:12 UTC
Labels: Confirmed
