### ISSUE TITLE
Faction and race change problem

### ISSUE THREAD

**Issue by KaloyanDDimitrov** [azerothcore/azerothcore-wotlk#12955] opened 2022-09-03 20:08 UTC
### Current Behaviour

When i change the faction from undead to gnom i cant talk in chat. I have to select manualy Gnimish to talk. And after that I get an server error.
Character GUID Full: 0x0000000000000002 Type: Player Low: 2 has skill 220 that does not exist.
Character GUID Full: 0x0000000000000002 Type: Player Low: 2 has skill 753 that does not exist.

### Expected Blizzlike Behaviour

Dont have to select manualy to talk.

### Steps to reproduce the problem

1. Change faction/race

### AC rev. hash/commit

AC> AzerothCore rev. 31892275b0aa 2022-09-03 10:32:30 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 100334
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-125-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-autobalance

### Operating system

Ubuntu 20

### Custom changes or Modules

Autobalance, Anticheat

**Comment by UltraNix** [comment] 2022-11-19 12:51
@KaloyanDDimitrov Cannot reproduce it.

**Comment by Kitzunu** [comment] 2023-04-08 19:40
so close it

**Closed by Kitzunu** 2023-04-08 19:40 UTC
Labels: ChromieCraft Generic, Unable to reproduce

**Comment by OlegVintaga** [comment] 2023-09-21 04:21
Still, there is an error; when you change the race, it appears in the logs

Character GUID Full: 0x0000000000000001 Type: Player Low: 1 has skill 754 that does not exist.

AzerothCore rev. b1c92f498a3b+ 2023-09-20 22:55:46 +0200 (master branch) (Win64, Release, Static)

**Comment by heyitsbench** [comment] 2023-09-21 04:22
> Still, there is an error

We need reproduction steps.

**Comment by brunolopes1996** [comment] 2024-05-16 19:27
Compile a clean core, create a character then race change or faction change and that issue, will happen, a easy combination to try is Tauren to Blood elf, you will not learn the new blood elf racial and have that log error just with a different spell ID, compiled a clean and updated source at 16/05/2024
