### ISSUE TITLE
Portal does not work

### ISSUE THREAD

**Issue by devfrom** [azerothcore/azerothcore-wotlk#971] opened 2018-07-12 22:47 UTC
Sholazar Basin's portal is not working.

How it should work: when passing by it should teleport the player to (Un"goro Crater)

![portal bug](https://user-images.githubusercontent.com/41171790/42666219-253385a6-861a-11e8-90eb-e39c403ad955.jpg)

Detalhes
Azerothcore Version

https://github.com/azerothcore/azerothcore-wotlk/commit/02d14df9b8d366ab4685442b4ececf5041c8f035

windows server 2008 32x

No Modules

**Comment by BarbzYHOOL** [comment] 2018-07-12 22:59
Give gameobject guid so we can teleport to it to confirm

**Comment by devfrom** [comment] 2018-07-13 02:07
@BarbzYHOOL Look

**Comment by BarbzYHOOL** [comment] 2018-07-13 16:06
Fill the template correctly to help us

**Comment by Heijex** [comment] 2018-07-15 14:47
Can confirm, also this is not a object, the 2 waygate locations are in un'goro crater & sholazar basin, you should be able to teleport from one to the other, currently you cannot.

**Comment by BarbzYHOOL** [comment] 2018-07-15 15:15
>also this is not a object,

then what is it? a mob? :D

We need "steps to reproduce the bug" with commands and stuff

**Comment by Heijex** [comment] 2018-07-15 15:30
It's missing in world DB areatrigger_teleport here you go

`INSERT INTO `areatrigger_teleport` (`ID`, `Name`, `target_map`, `target_position_x`, `target_position_y`, `target_position_z`, `target_orientation`) VALUES (5046, 'Sholazar Basin - (Waygate)', 1, -6175.67, -1318.19, -172.336, 5.50695);
INSERT INTO `areatrigger_teleport` (`ID`, `Name`, `target_map`, `target_position_x`, `target_position_y`, `target_position_z`, `target_orientation`) VALUES (5047, 'Un\'Goro Crater - (Waygate)', 571, 4913.76, 5188.3, -92.8283, 3.54975);
`

**Comment by vhipercode** [comment] 2018-07-15 16:10
Tested and fixed, thank you! @Heijex 
Closed Issues -> @BarbzYHOOL

**Comment by BarbzYHOOL** [comment] 2018-07-15 16:38
it's still a game object to teleport too

No, it's not fixed, we need a Pull Request for this :P

Thank you Heijex though

**Comment by Heijex** [comment] 2018-07-15 16:52
It's not a object, I'm going to assume it's a building with in the world, there are also no hidden creatures nearby however, you can literally find the exact locations in the DBC files. AreaTrigger.dbc & Maps.dbc

**Comment by BarbzYHOOL** [comment] 2018-07-15 17:15
hmm ok but just find a near NPC or game object to teleport to it when opening an issue, that's the idea

**Comment by Knindzagxg** [comment] 2018-07-20 18:22
Before posting something, pretty please MAKE SURE to check everything.
There's no need for fix at all, since Portal working perfect.

It's part of story lane quest, and before you can trigger it, you have to activate 2 objects which will let you teleport. You can't just add last quest and expect you will activate all triggers / procs or etc.

Full quest lane - http://www.wowhead.com/quest=12620/the-lifewardens-wrath

Here's video as well...

https://www.youtube.com/watch?v=95fk9sxWJQM&feature=youtu.be

**Comment by Nefertumm** [comment] 2018-08-07 14:29
Closing this due there's nothing to fix.

**Closed by Nefertumm** 2018-08-07 14:29 UTC
Labels: Fix included, Needs Testing/Feedback
