### ISSUE TITLE
Unable enter to The Wailing Caverns with levitate aura

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#10077] opened 2022-01-08 18:16 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2671

You cannot enter Wailing Caverns with Levitate buffed. You get immediately teleported out of the dungeon.

https://user-images.githubusercontent.com/62797536/147355220-63f58584-c3ed-4248-bec0-181cda3c7d2d.mp4

Tester:

The issue is confirmed. Unable enter to The Wailing Caverns with [Levitate](https://wowgaming.altervista.org/aowow/?spell=1706) aura. Is not affecting other insstances
 
https://user-images.githubusercontent.com/85256266/148655046-e689960e-a271-4d31-9e38-8c7a41702e77.mp4

### Expected Blizzlike Behaviour

You should be able to enter Wailing Caverns with Levitate buffed.

### Steps to reproduce the problem

.tele wailingcaverns
.aura 1706

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment] 2022-01-16 08:59
I can't reproduce it.

**Comment by Nefertumm** [comment] 2022-01-17 20:19
I can't reproduce it either, rev f5524677e1a81702ad80e763d656b1681af36739
I'm going to close it for now, if anyone can confirm it again, open it again.

**Closed by Nefertumm** 2022-01-17 20:19 UTC
Labels: ChromieCraft Generic, Unable to reproduce, Class - Priest
