### ISSUE TITLE
[DK Starting Area] These monsters will not approach players after being attacked

### ISSUE THREAD

**Issue by Doc-Huang** [azerothcore/azerothcore-wotlk#21036] opened 2024-12-24 15:49 UTC
### Current Behaviour

These monsters will not approach players after being attacked.
In the pre mission of the Death Knight, they were stunned in place after being subjected to Icy Touch.
Including but not limited to the following monsters：
28557  Scarlet Peasant
28577  Citizen of Havenshire
28576  Citizen of Havenshire
28611  Scarlet Captain
etc...
![image](https://github.com/user-attachments/assets/1397b609-41aa-4d3d-9006-2f13afc84c6e)

### Expected Blizzlike Behaviour

Attack the player normally, slowly approach the player

### Steps to reproduce the problem

Do not approach monsters, only use ranged skills.

### AC rev. hash/commit

02d5f705f349
![image](https://github.com/user-attachments/assets/00d58d72-753b-46f1-a7c9-de914f36b6b7)

### Operating system

win11 x64

**Comment by TheSCREWEDSoftware** [comment] 2024-12-24 22:59
For future reference do is told in the form relative to source and rev.

![image](https://github.com/user-attachments/assets/8866a0be-f2db-4830-9f6b-94bf362ab9dd)

And yes I'm aware that you've added the Keira Image. But there's a place for you to leave the exact `.server debug` information in.

To my understand and testing is that these NPCs in retail and in AC is that the peasent and the citizens (any npc that is not a soldier) should either fight or be afraid. Upon being afraid they may or not swing at you (in retail). And if you drop combat after moving them aroudn they dont seem to return to their position.

Resumed:

- Peasents and Citizens should either fight you (and get afraid of you after X amount of HP) or be afraid of you, upon being engage by the pilot.
- They don't seem to return to their original positions upon combat reset.

**Comment by Doc-Huang** [comment] 2024-12-25 09:16
> For future reference do is told in the form relative to source and rev.
> 
> ![image](https://private-user-images.githubusercontent.com/16946913/398487472-8866a0be-f2db-4830-9f6b-94bf362ab9dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTgxNDEsIm5iZiI6MTczNTExNzg0MSwicGF0aCI6Ii8xNjk0NjkxMy8zOTg0ODc0NzItODg2NmEwYmUtZjJkYi00ODMwLTlmNmItOTRiZjM2MmFiOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA5MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NTRjODJiOWRjNWM3MGY0OWNlZTdjZGM2NzJhZDM2NmQwYjBkMjBlNTE5ZjljNjllZjgyYTY5OTg2NThjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Eb5jTGFGL1oYMPJecjRJCSQGWNLlmgfA2uqFr0dSdPM)
> 
> And yes I'm aware that you've added the Keira Image. But there's a place for you to leave the exact `.server debug` information in.
> 
> To my understand and testing is that these NPCs in retail and in AC is that the peasent and the citizens (any npc that is not a soldier) should either fight or be afraid. Upon being afraid they may or not swing at you (in retail). And if you drop combat after moving them aroudn they dont seem to return to their position.
> 
> Resumed:
> 
> * Peasents and Citizens should either fight you (and get afraid of you after X amount of HP) or be afraid of you, upon being engage by the pilot.
> * They don't seem to return to their original positions upon combat reset.

Because this is the latest version downloaded from someone else, the hash value may not match, but I am well aware that this is a pure version without any kernel modifications. Please don't dwell on hash values. I am just an ordinary player and don't know much about building and modifying AC platforms. I just discovered problems.
In the game, it's not just a problem for the citizens. As I mentioned before, Scarlet Captain and Scarlet Peanut have also encountered this issue. This is an obvious bug that you can easily identify with a simple attempt.
Thank u.

**Comment by Rorschach91** [comment] 2024-12-25 20:40
Citizen of Havenshire should ignore the players and hostile npcs unless they attack them first.
When a player attacks a Citizen, it could have two different reactions:
1) Citizen says a dialogue line, stay in place in fear and don't attack.
2) Citizen says a dialogue line, casts a buff on itself (Cornered and Enraged) and attack the player.

In any case Citizen of Havenshire are related to another two issues: [Issue 1](https://github.com/azerothcore/azerothcore-wotlk/issues/20891) and [Issue 2](https://github.com/azerothcore/azerothcore-wotlk/issues/20148).

I'm already working to fix a part of the problem but I need time, because I'm sniffing all waypoints, groups etc.....

![cit pre](https://github.com/user-attachments/assets/007e465e-d6aa-4766-87a9-cffffa76704e)

In addition, some Citizens of Havenshire have frost fever and blood plague auras. This is probably caused by an old bad sniff.
This particular bug will be fixed soon.
![no auras](https://github.com/user-attachments/assets/602c934e-44bf-4d04-8260-383a534c175b)

**Closed** 2024-12-31 08:40 UTC
Labels: Confirmed, Class - Death Knight
