### ISSUE TITLE
Flying mount dismounts in shallow water

### ISSUE THREAD

**Issue by alecsci** [azerothcore/azerothcore-wotlk#19698] opened 2024-08-21 21:31 UTC
### Current Behaviour

Reported by: https://github.com/chromiecraft/chromiecraft/issues/5657

As soon as a flying mount even touches the edge of water it immediately gets dismounted. It doesn't behave like a normal ground mount when just crossing shallow water. You can mount in the shallow water, barely move or touch the water you get immediately dismounted

### Expected Blizzlike Behaviour

It should only dismount when you need swim, but stay mounted when just crossing shallow water.

### Source

Original Wrath video showing player running in shallow water while mounted on a gryphon
https://youtu.be/ieT1fBMalgI?t=120

TBC Classic video showing player running in shallow water while mounted on a windrider.
https://youtu.be/k7cnybarC8Y?t=276

### Steps to reproduce the problem

1. .setskill 762 300 300
2. learn 39803
3. .go xyz -1830 4957 -24 (go near a pool of shallow water)
4. mount in water, and try to move

### Extra Notes

[Video](https://www.youtube.com/watch?v=kLRoliaDWN0)
Some solution was tried here: https://github.com/azerothcore/azerothcore-wotlk/pull/16608

### AC rev. hash/commit

0f80a41cb64dea1b00c28a84e441503e179ea154

### Operating system

Windows 11 x64

### Custom changes or Modules

None

**Comment by alecsci** [comment] 2024-08-21 21:33
Some solution was tried here: https://github.com/azerothcore/azerothcore-wotlk/pull/16608

**Comment by Kitzunu** [comment] 2024-08-22 06:41
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/18316

**Closed by Kitzunu** 2024-08-22 06:41 UTC
Labels: Confirmed, 70
