### ISSUE TITLE
No loot if you kill neutral npc by meele weapon

### ISSUE THREAD

**Issue by skelUA** [azerothcore/azerothcore-wotlk#17598] opened 2023-10-27 07:42 UTC
### Current Behaviour

If you kill some npc (https://www.wowhead.com/wotlk/npc=23979/giant-marsh-frog) like  by meele weapon yo dont gane loot

### Expected Blizzlike Behaviour

 https://www.youtube.com/watch?v=3KIh0c4hveI&ab_channel=allOfWoW

### Steps to reproduce the problem

1. .quest add 1218
2. .go creature id 23979
3. Try to kill npc by meele weapon

### AC rev. hash/commit

AC> AzerothCore rev. 78ba9ff92e8f+ 2023-10-23 09:03:37 +0300 (TS branch) (Unix, Debug, Static)
Connected players: 22. Characters in world: 22.
Connection peak: 62.
Server uptime: 2 day(s) 3 hour(s) 1 minute(s) 37 second(s)
Update time diff: 1ms, average: 13ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80034
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-79-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS ruRU
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-transmog
- mod-weekend-xp

### Operating system

debian

**Comment by Kitzunu** [comment] 2023-10-27 23:42
I can actually confirm this on 79b39f9655111088a741185c4dabd31dae7d85ea

Killing the frog with a melee ability as a rogue will result in no loot
Killing the frog with a ranged ability as a mage will result in loot

**Comment by heyitsbench** [comment] 2023-10-27 23:47
Duplicate of #16374?

**Comment by Kitzunu** [comment] 2023-10-27 23:48
https://github.com/azerothcore/azerothcore-wotlk/issues/16374

**Closed by Kitzunu** 2023-10-27 23:48 UTC
Labels: Confirmed
