### ISSUE TITLE
[VS] Compilation warning

### ISSUE THREAD

**Issue by Mutevazi** [azerothcore/azerothcore-wotlk#1296] opened 2019-01-16 10:58 UTC
##### Warning:

C4715 WorldSocket :: ProcessIncoming: value is not returned for all execution paths  | game | d:\azerothcore\src\server\game\server\worldsocket.cpp 724

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Win 10 x64 MariaDB 10.1

##### MODULES:

Clear

**Comment by Mutevazi** [comment] 2019-01-16 16:39
Because of this warning, the server does not turn on. Help.

**Comment by FrancescoBorzi** [comment] 2019-01-16 16:44
@Mutevazi No worries, we will help you. Do you changed the code somehow ?

also please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/How-to-ask-for-help

I close this since it's not a bug but a support request.

**Closed by FrancescoBorzi** 2019-01-16 16:44 UTC

**Comment by Mutevazi** [comment] 2019-01-16 16:52
No, I did not touch anything. Today I downloaded the master branch again and tried to compile the core on MariaDB 10.1.
In the middle of the compile process, a warning was issued. After compilation, the server was not turned on. Old versions compile fine without problems.

**Comment by FrancescoBorzi** [comment] 2019-01-16 16:59
@Mutevazi  what error do you get when you try to RUN the server? (not during compilation)

**Comment by Mutevazi** [comment] 2019-01-16 17:14
The database is fine! Older versions work well.
Base rebooted, does not help.
(At the same time authserver works in normal mode.)

SQLDriver.log (serverworld) = 
```
Closing down DatabasePool 'characters'.
Asynchronous connections on DatabasePool 'characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'characters' closed.
Closing down DatabasePool 'world'.
Asynchronous connections on DatabasePool 'world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'world' closed.
Closing down DatabasePool 'auth'.
Asynchronous connections on DatabasePool 'auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'auth' closed.

```
Server.log
```
2019-01-16 20:10:44 ERROR: DatabasePool world NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors.
2019-01-16 20:10:44 ERROR: Cannot connect to world database 127.0.0.1;3306;root;root;world
```

**Comment by FrancescoBorzi** [comment] 2019-01-16 17:54
@Mutevazi let's discuss it in the chat: https://discord.gg/gkt4y2x

**Comment by Mutevazi** [comment] 2019-01-16 18:40
Unfortunately, this is not a solution to my problem.
Do not tell me how to solve the warning that comes out in new versions of AC on MariaDB 10.1?
Because of this warning, the server refuses to work with the database.

**Comment by Mutevazi** [comment] 2019-01-16 18:48
Oh great @Viste , could you help me with the solution of this warning? For heaven's sake

**Comment by Mutevazi** [comment] 2019-01-16 19:19
Warning also issued on MySQL 5.6

**Comment by Viste** [comment] 2019-01-16 19:21
@Mutevazi do you use mariadb lib with MySQL or change it to Mysql lib?
i think its related to https://github.com/azerothcore/azerothcore-wotlk/commit/27ea9c3f9558168d182f3dc28401e2d341a9ed81
but i dont test this commit with MariaDB for now, can do it tommorow i gues.
give me plz some time ) and  i try to help

**Comment by Mutevazi** [comment] 2019-01-16 19:23
@Viste Hey. No, I completely deleted MariaDB 10.1 and installed MySQL 5.6 (The computer rebooted). Thank you very much for the activity.

**Comment by Mutevazi** [comment] 2019-01-17 16:31
@Viste Any news? Day without a new revision :(

**Comment by Viste** [comment] 2019-01-18 13:15
I'm sorry a lot of work, so while I did not do anything
