### ISSUE TITLE
Bloodsail Warlock Succubus summon don't aggro unless attacked themselves

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6353] opened 2021-06-14 23:26 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

Original report:  https://github.com/chromiecraft/chromiecraft/issues/862

##### CURRENT BEHAVIOUR:

I don't know if its just me but i noticed the bloodsail warlock succubi don't aggro at all even if you attack her master. she only seems to attack when you attack her.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I assume all pets aggro once the master ai attacks or is being attacked.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to any bloosail warlock in stranglethorn vale and witness how she just stands there.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 5330cd983c19 ) :

![WoWScrnShot_061521_022134](https://user-images.githubusercontent.com/82579073/121971218-ec5da480-cd80-11eb-92c1-570eaa34cda2.jpg)

**Comment by mserajnik** [comment] 2021-06-15 00:24
Probably related to #6239?

**Comment by Kitzunu** [comment] 2021-06-15 00:36
duplicate of #6239

**Closed** 2022-11-01 15:24 UTC
Labels: Invalid-Duplicate, Confirmed, 40-49
