### ISSUE TITLE
Minions not engaging in combat, again [$20]

### ISSUE THREAD

**Issue by arielcami** [azerothcore/azerothcore-wotlk#6239] opened 2021-06-05 15:36 UTC
**CURRENT BEHAVIOUR:**
- Pet isn't engaging in combat.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
- Pets should rush right at it's master's attacker.

**STEPS TO REPRODUCE THE PROBLEM:**

1.   .go xyz -7702.6 -4217.43 9.76 1 5
2.   Stand 30 yards away.
3.  Attack Wastewander Shadow Mage, ignore his pet.

**EXTRA NOTES:**
-This issue has been addressed and merged in the past(#5166), but it's still not working in this particular case.
-Video:
https://user-images.githubusercontent.com/71854140/120896981-9e5ed900-c5e9-11eb-9cf5-c2ebb3444e6c.mp4

**AC HASH/COMMIT:**
- f819cf86fd7f

**OPERATING SYSTEM:**
-Win10 64bits

**MODULES:**
-No modules

<bountysource-plugin>

---
There is a [$20 open bounty](https://www.bountysource.com/issues/98988587-minions-not-engaging-in-combat-again) on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).

**Comment by Azcobu** [comment] 2021-06-05 15:56
Confirmed on rev. f819cf86fd7f

https://user-images.githubusercontent.com/81782124/120897603-2a164b00-c666-11eb-8fad-595f853f74f4.mp4

**Comment by Kitzunu** [comment] 2021-06-15 00:40
That PR looks very hacky. That should be handled by the core, imagine if you had to add that to all minions/guardians' SAI

**Comment by T1ti** [comment] 2021-06-15 03:57
yes this should obviously be a general core fix

**Comment by mserajnik** [comment] 2021-06-18 13:17
Corresponding ChromieCraft issue: https://github.com/chromiecraft/chromiecraft/issues/862 (the PR that closes this issue should close that one too)

**Comment by Kitzunu** [comment] 2021-06-18 14:11
Also the one who fixes this should remove the hack fixes from the DB

**Comment by syssneck** [comment] 2021-08-28 09:14
This is still an annoying bug and makes warlock mobs way too easy to kill. Is someone on this, or can we maybe add a bounty for this?

**Comment by Azcobu** [comment] 2021-08-28 09:21
Agreed, this is coming up rather a lot and it's affecting quite a lot of summoner mobs. Tag added.

**Comment by TheRiddermark** [comment] 2021-08-28 12:21
I just wanted to add that this doesn't seem to be limited to warlocks. Leveling a belf rogue atm, and while fighting [this NPC](https://wowgaming.altervista.org/aowow/?npc=16345) in the Ghostlands the same thing happens.

[Image attached.](https://i.imgur.com/79XVpV5.jpg)

Not only is the pet [Lynx](https://wowgaming.altervista.org/aowow/?npc=16348) not attacking but it also de-spawns when the Troll dies.

Cheers and keep up the good work!

**Comment by stoudtlr** [comment] 2021-09-01 21:11
same happens with the wolf pets of RazorMane Hunters in the Barrens as well.  They won't attack player.

**Comment by VincentVanclef** [comment] 2021-09-10 19:10
Why isnt this being prioritized?

**Comment by stoudtlr** [comment] 2021-09-10 19:34
https://www.bountysource.com/issues/98988587-minions-not-engaging-in-combat-again

**Comment by VincentVanclef** [comment] 2021-09-10 19:45
Possible fix:

bool Unit::Attack(Unit* victim, bool meleeAttack)

find:

if (creature && !IsControllableGuardian())
{
    ...
}

and replace that whole block with:

`if (creature/* && !IsControllableGuardian()*/)
    {
        // should not let player enter combat by right clicking target - doesn't helps
        SetInCombatWith(victim);
        if (victim->GetTypeId() == TYPEID_PLAYER)
            victim->SetInCombatWith(this);
        AddThreat(victim, 0.0f);

        if (!IsControllableGuardian())
        {
            creature->SendAIReaction(AI_REACTION_HOSTILE);
            creature->CallAssistance();
            creature->SetAssistanceTimer(sWorld->getIntConfig(CONFIG_CREATURE_FAMILY_ASSISTANCE_PERIOD));
        }
    }`

before:
https://drive.google.com/uc?id=15hVCviUp2XArP43zgRYZCm__jHc9a6ju

after:
https://drive.google.com/uc?id=1utBG82pKmpWyOK_JCiErak9DOKWLNJL-

I dont know the combat system in depth, was just debugging and checking why it wasnt updating its combat target, and found this check. Is there a reason for it?

**Comment by patou01** [comment] 2021-09-11 16:51
The bug is somewhat symmetric (pet doesn't set master in combat and vice-versa) after just having opened the code for the first time now, it seems to me the most logical place to do this is in void **Unit::CombatStart,** where the guardian should set all its minions in combat with the target and a minion should set his guardian in combat. It seems also that the calls for help don't include pets.

Video on commit aa115e767 

[https://drive.google.com/file/d/1U4ImqEw3hOMYzoXgJy_EU3BljvaWorCN/view?usp=sharing](https://drive.google.com/file/d/1U4ImqEw3hOMYzoXgJy_EU3BljvaWorCN/view?usp=sharing)

However, I have not yet managed to propose a fix.

**Comment by Xshade** [comment] 2021-09-13 18:33
With most recent update on ChromieCraft on 13th september, there was visible change regarding voidwalker minion in tanaris. The minion targets the player character and attempts only 1 attack against it. Once it's master dies the pet doesn't despawn (which is correct), have player as target and moves in melee range but doesn't attack and doesnt keep player in combat. Here is a clip of what's exactly happening: https://youtu.be/yCDRMhFjFE8 I guess you are close to fixing it :]

**Comment by patou01** [comment] 2021-09-13 19:04
I do not see any closed PR that should affect this behaviour, nor do I see any commit that suggests they affected it. Other than the open PR I have, I think nothing should affect their behaviour. 

Building latest PR it works on my side (ie current state of azerothcore + the proposed change). https://drive.google.com/file/d/1q2t9wFt7Zz5brje3n3i19DoURB1BcUYj/view?usp=sharing 

I suspect what is happening on your video is actually "the same as it was before" (but I'm too lazy to rebuild tonight and test again), except you aggro'd the pet due to being melee. 

Additionally, can confirm that after .die on the mage, the minion kept attacking me, though that's not recorded, because I only read it later and was not the goal of the PR so I hadn't looked into that behaviour. If it needs to be changed, let us know!

**Comment by Xshade** [comment] 2021-09-13 19:47
I wasn't able to play from last Wednesday till today but when i logged in today to farm rep for Steamwhedle Cartel (before the today's server update) voidwalkers disappeared once the mage is killed. After the server update i countinued from where i left and after i killed first Shadow Mage i saw the minion didn't despawn and i by instinct killed it. After few more i noticed that minions do only one attack and thats it. Considering that i started testing it. Some minions just do one attack at the start of the combat and then only follow you (this is what happens most of the time), on 2 or 3 occasions i noticed that they actually attack you but once the dmg is dealt from them to the player you get out of combat until their next attack. If you move some yards away they stop attacking. My testing so far are executed with imeadeatly killin the mage since their spells are bit powerful against my rogue. I noticed that you do only 1-2 spell casts so that could be why it doesn't have same effect to you or because you are using ranged/caster character (if you have time try to use melee class and be around their lvl just modify your health so you dont get killed and observe).

Sorry for this messed comment but in my defense i was trying to type it, watch twitch, test ingame (in chromiecraft server) and chat in discord :S

**Comment by stoudtlr** [comment] 2021-09-13 20:07
@Xshade 
There are two separate issues:
1. Minions/pets despawn when master dies - issue #6211
2.  Minions/pets not attacking - this one.

The first one was solved by @UltraNix with PR #7607 that was merged to master branch on 9/4, and @patou01 is trying to solve this one with his PR #7836

**Closed** 2021-09-16 08:27 UTC
Labels: Priority-High, Bounty, CORE, Confirmed

**Comment by BeefSteaker** [comment] 2022-11-25 18:38
Seems to still be happening for at least the two mobs linked above
