### ISSUE TITLE
Autoloot window dissapears too fast

### ISSUE THREAD

**Issue by Dezaimasu** [azerothcore/azerothcore-wotlk#14704] opened 2023-01-18 01:53 UTC
### Current Behaviour

When looting any lootable items (corpses, chests, quest objects, etc.) using autoloot, loot window only appears for a fraction of a second. 
In attached video it's only visible on a single frame, the video is 30fps, so the loot window is only visible for less then 33.33ms

[loot.webm](https://user-images.githubusercontent.com/1636242/213060763-ac17112a-8b1e-43fc-a9f2-1fe1df602ec9.webm)

### Expected Blizzlike Behaviour

Default tick rate for autoloot window is 150ms
The console command to change this behavior (/console autoLootRate) was only added in 6.0.2

### Source

https://wowpedia.fandom.com/wiki/Console_variables ctrl+f `autoLootRate`

### Steps to reproduce the problem

1. Kill any mob that drops any loot
2.  Loot its corpse with either Auto Loot setting enabled, or when holding Auto Loot Key

### Extra Notes

I thought it would be mentioned somewhere since virtually every single player is affected by it, but couldn't find anything in this repo. Not sure if this behavior not considered a bug or no one cared about it.

### AC rev. hash/commit

b3e37226745a

### Operating system

Windows 10 x64

### Custom changes or Modules

none

**Comment by heyitsbench** [comment] 2023-01-18 01:58
Is there any 3.3.5a source on the speed it's supposed to take? If it's a cvar introduced later, my inclination is that the speed is client-side and is somewhat inherently blizzlike.

**Comment by Dezaimasu** [comment] 2023-01-18 02:28
Here's some random WotLK video from 2009. You can clearly see the loot window takes longer to disappear on 1:51, 1:54, 3:04, 4:08
https://www.youtube.com/watch?v=ZHL0BaW3Ye8

Here's another one, 2:35, 3:38, etc.
https://www.youtube.com/watch?v=dwM5n3f5Nts

**Comment by Ovahlord** [comment] 2023-01-18 11:47
That's not really an issue lol. Retail takes longer because Blizzard sends packets in fixed intervals. any pserver emulator however processes packets and actions immediately which is why autoloot works much faster. That what you see is not a bug, but the result of way better performance.

**Comment by Dezaimasu** [comment] 2023-01-18 11:58
@Ovahlord yeah, I thought that might be the case.
Far reach, but is there any way I could emulate this behavior? Thanks in advance. There are few loot-related module hooks, but I'm not sure which one fits better. `OnBeforeOpenItem`?

**Comment by Ovahlord** [comment] 2023-01-18 14:58
there are ways but I heavily recommend not doing so. Artifically delaying stuff always comes crashing down on your eventually

**Comment by Kitzunu** [comment] 2023-01-18 15:28
Going to close this.

**Closed by Kitzunu** 2023-01-18 15:28 UTC
