### ISSUE TITLE
[server]world server crash 1028

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13571] opened 2022-10-28 02:58 UTC
### Current Behaviour

crash log:

https://gist.github.com/mpfans/e5bd87dcfaabc0792cde943c940ed4df

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/77a52b8001ba6292b87138471deb7d8aa7b84e4b

### Operating system

Ubuntu20.04

**Comment by acidmanifesto** [comment] 2022-10-28 11:20
Interesting

https://gist.github.com/mpfans/e5bd87dcfaabc0792cde943c940ed4df#file-crash20221028-L129

Issue with a prepared statement but doesnt show which one though.

**Comment by lykhouzov** [comment] 2022-10-28 12:13
i think it is because of following
```log
wow-worldserver-1  | In mysql_stmt_prepare() id: 55, sql: "SELECT mapId, zoneId, posX, posY, posZ, posO FROM character_homebind WHERE guid = ?"
wow-worldserver-1  | Unknown column 'posO' in 'field list'
wow-worldserver-1  | In mysql_stmt_prepare() id: 195, sql: "INSERT INTO character_homebind (guid, mapId, zoneId, posX, posY, posZ, posO) VALUES (?, ?, ?, ?, ?, ?, ?)"
wow-worldserver-1  | Unknown column 'posO' in 'field list'
wow-worldserver-1  | In mysql_stmt_prepare() id: 196, sql: "UPDATE character_homebind SET mapId = ?, zoneId = ?, posX = ?, posY = ?, posZ = ?, posO = ? WHERE guid = ?"
wow-worldserver-1  | Unknown column 'posO' in 'field list'

```
as I can see, in  `azerothcore-wotlk/src/server/database/Database/Implementation/CharacterDatabase.cpp` line 98, in the select the field `posO` is used , but it is not expists in base sql for `character_homebind` table

**Comment by Kitzunu** [comment] 2022-10-30 20:37
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13172 again...

**Closed by Kitzunu** 2022-10-30 20:37 UTC
