### ISSUE TITLE
[server]worldserver crash 0419

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11438] opened 2022-04-19 07:01 UTC
### Current Behaviour

crash log:

https://gist.github.com/mpfans/58af7808f90cccbf16648c70d34d5f4c

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a35e411fdd86f3b44e7b5f1a36b1ba2d43887a68 + PR (https://github.com/azerothcore/azerothcore-wotlk/pull/11346)

### Operating system

ubuntu 20.04

**Comment by Kitzunu** [comment] 2022-04-21 17:26
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/11296

**Closed by Kitzunu** 2022-04-21 17:26 UTC
Labels: Priority-Critical, HasBacktrace
