### ISSUE TITLE
Bug on boss hodir

### ISSUE THREAD

**Issue by blacknightt1** [azerothcore/azerothcore-wotlk#7429] opened 2021-08-18 15:30 UTC
### Current Behaviour

Hodir Bass and Hodir Flash Freeze

When you enter
evade
Is

### Expected Blizzlike Behaviour

Should not
evade
Be

### Source

https://youtu.be/jij25A-M55E

https://www.wowhead.com/npc=32845/hodir

### Steps to reproduce the problem

.

### Extra Notes

.

### AC rev. hash/commit

AzerothCore rev. c88e93fb5079+ 2021-08-17 22:49:17 +0000 (master branch) (Win64, RelWithDebInfo, Static) (authserver)
<Ctrl-C> to stop.

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-transmog
mod-duel-reset

**Comment by Dude100** [comment] 2021-08-19 09:54
I confirm [https://youtu.be/hAC7_Msvfrc](url)

**Comment by steenburgh** [comment] 2021-08-23 02:19
Duplicate of #5859

**Closed by steenburgh** 2021-08-23 02:19 UTC
Labels: Confirmed
