### ISSUE TITLE
Westfall mobs drop high level leather

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#7265] opened 2021-08-09 11:47 UTC
### Current Behaviour

Westfall beasts dropping high level leathers. Loot tables are bugged. Rugged leather.

### Expected Blizzlike Behaviour

They should have drop light leathers, light hides.

### Source

https://classic.wowhead.com/guides/classic-leather-farming-early-leather

Rugged leather is a 50+ drop.

### Steps to reproduce the problem

Steps to reproduce the problem

    get a skinning knife
    skin a mob in westfall
    get high level leather like thick or rugged

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/1369

### AC rev. hash/commit

chromiecraft/azerothcore-wotlk@36a1777

### Operating system

win10

### Custom changes or Modules

    mod-ah-bot
    mod-cfbg
    mod-chromie-xp
    mod-desertion-warnings
    mod-duel-reset
    mod-eluna-lua-engine
    mod-ip-tracker
    mod-low-level-arena
    mod-multi-client-check
    mod-pvp-titles
    mod-pvpstats-announcer
    mod-queue-list-cache
    mod-server-auto-shutdown
    lua-CarbonCopy
    lua-CustomWorldboss
    lua-LevelUpReward
    lua-send-and-bind
    lua-Zonecheck
    lua-TempAnnouncements

**Comment by Azcobu** [comment] 2021-08-10 04:52
This may be a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7253, but without any information about which Westfall mobs you're referring to here it's hard to say. The listing of affected mobs in #7253 does contain a few Westfall beasts (Goretusk, Young Goretusk, Coyote Packleader) - are they the ones displaying this error, or are there others? The rugged leather dropping certainly matches, however.

**Comment by patou01** [comment] 2021-09-17 18:08
```
DROP TEMPORARY TABLE IF EXISTS mobsSkinCheck;

CREATE TEMPORARY TABLE mobsSkinCheck AS
SELECT * FROM `creature_template` WHERE (`maxLevel` < 25);

SELECT * FROM `mobsSkinCheck` WHERE `skinloot` IN  (SELECT `Entry` FROM `skinning_loot_template` WHERE (`item` IN (4234, 4304, 8170)));
```
The above request does not give any significant result to me, so I expect this to be fixed.
The goal of the request was to find any mob of level < 25 which drops any of the following:
[heavy leather](https://classic.wowhead.com/item=4234/heavy-leather)
[thick leather](https://classic.wowhead.com/item=4304/thick-leather)
[rugged leather](https://classic.wowhead.com/item=8170/rugged-leather)

Please check the SQL code was correct before closing this.

 That's not to say the same issue might not be present in other mobs areas however, I have not looked into that.

**Comment by Azcobu** [comment] 2021-09-18 02:09
You're correct, this was fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/7254. If you run a query looking for NPCs under level 25 that still drop any of those 3 items, you will still find some that do still drop item 4234, Heavy Leather:

```SQL
SELECT ct.entry, ct.name, ct.maxlevel, slt.Item
FROM `creature_template` ct
JOIN `skinning_loot_template` slt ON ct.skinloot = slt.Entry
WHERE ct.maxlevel < 25 AND slt.Item IN (4234, 4304, 8170)
```

| entry | name | maxlevel | Item | 
| ---: | --- | ---: | ---: | 
| 3927 | Wolf Master Nandos | 21 | 4234 | 
| 4274 | Fenrus the Devourer | 21 | 4234 | 
| 4825 | Aku'mai Snapjaw | 23 | 4234 | 
| 4829 | Aku'mai | 24 | 4234 | 
| 4830 | Old Serra'kis | 24 | 4234 | 

However, if you then go and check these NPCs on Wowhead, they all do show Heavy Leather as being part of their correct drop tables. (3 are bosses, one is a mini-boss, and the Snapjaws are just an outlier I guess.)

Anyway, as we've both verified that there are no more incorrect skinning drops in the DB for this level range, I will close this issue accordingly.

**Closed by Azcobu** 2021-09-18 02:09 UTC
Labels: Priority-Medium, Confirmed, 1-19
