### ISSUE TITLE
[server]world crash 0516

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11782] opened 2022-05-16 15:48 UTC
### Current Behaviour

crash log:

https://gist.github.com/mpfans/760632733ae4f57b8fb637501e8024c8

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

822aff29e680d7ddce1064abf8a543999c914c98 + https://github.com/azerothcore/azerothcore-wotlk/pull/11740 + https://github.com/azerothcore/azerothcore-wotlk/pull/11741

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment] 2022-05-16 15:49
@UltraNix  Please

**Comment by UltraNix** [comment] 2022-05-16 20:39
Duplicate of #11650

**Closed by UltraNix** 2022-05-16 20:39 UTC
