### ISSUE TITLE
NPC Verog the Dervish despawns quickly

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#5941] opened 2021-05-19 04:41 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

NPC Verog the Dervish, target mob for [https://vanillawowdb.com/?quest=851](https://vanillawowdb.com/?quest=851) despawns in less than 60 seconds after spawning
![image](https://user-images.githubusercontent.com/68164076/118754550-2c7e4580-b81c-11eb-9db9-acee47946a32.png)
![image](https://user-images.githubusercontent.com/68164076/118754667-62232e80-b81c-11eb-9060-bdcbaf196553.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Considering how rare and a pain it is to get him to spawn, he should stick around at least long enough for players to get to him and kill him. I don't believe he should despawn at all.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .go object 13162
2. Kill Kolkar around the oasis until one of them says "I am slain. Summon Verog" 
3. head back to object 13162 he will have spawned at the bottom of the ramp
4. See how long he stays spawned 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by dreadfule** [comment] 2021-05-20 17:19
After thorough testing, on my side I replicated the issue and it seems to be working fine. Are you sure you don't have **.gm on** or anything else? I tested it countless times and he stays there for a long time. Perhaps you have missing files. Not sure though but I found no errors with this it seems to be working as intended.

**Comment by temperrr** [comment] 2022-06-12 07:56
@Stump876 

Do you have a source for this>?

**Comment by Stump876** [comment] 2022-06-12 15:08
https://classic.wowhead.com/quest=851/verog-the-dervish#comments:id=2941925
I have a comment from 2006. "You have a couple minutes to get to him and kill him before he disappears" 
How many mobs needed to kill to spawn him seems to be the major complaint. 

I have no idea if this is still valid. I thought this was closed ages ago.

**Comment by elthehablo** [comment] 2023-08-05 16:14
Confirmed by sniffs to be 5 mins instead of the 60s it was at. Fixed in my PR.

**Closed** 2023-08-06 01:15 UTC
Labels: Confirmed, 1-19, Good first issue
