### ISSUE TITLE
Warlock spell bar empties randomly once per pet [$35]

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5320] opened 2021-04-17 06:54 UTC
Originally reported https://github.com/chromiecraft/chromiecraft/issues/419

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Once for each pet so far, but seemingly random (cannot specify a possible trigger), the warlocks' pet abilities disappeared from the pet bar. So far happened only once for each warlock pet per character and was reported before (https://github.com/chromiecraft/chromiecraft/issues/341)

Affected pets and abilities
- [Summon Imp](https://db.rising-gods.de?spell=688)
  - [Abilities prior lvl 29 were affected](https://db.rising-gods.de/?spells=-3.188)
- [Summon Voidwalker](https://db.rising-gods.de/?spell=697)
  - [Abilities prior lvl 29 were affected](https://db.rising-gods.de/?spells=-3.204)

Other warlock pets likely also affected but not reported here as not experienced myself yet.
Unknown if hunter class is also affected.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Pet abilities shouldnt disappear from the pet bar. Abilities can be dragged back to the bar, but in general they shouldnt be affected by e.g. resummon, new ranks, ...

##### STEPS TO REPRODUCE THE PROBLEM:

Cannot force reproduction of the problem. happened occasionally for multiple people, but seems to be only once per pet per character.
trigger event unknown. potentially reproducible by leveling a warlock one level at a time, while summoning, learning abilities and possibly relogging.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment] 2021-04-17 06:58
I confirm the bug, it happened several times to me too..

**Comment by claudiodfc** [comment] 2021-06-20 15:15
Might be fixed with #6015 but needs further testing. With this PR I wasn't able to reproduce this bug

**Comment by necropola** [comment] 2021-07-04 09:58
To me it looks like the pet bar is messed up each time your demon leanrs a new spell or spell rank. Just got my Voidwalker's bar messed up at 40. Both skills which got a new rank (Torment and Sacrifice) got removed from the bar.

It's not fixed by #6015.

Why is the mention by the corresponding AC issue not displayed on teh corresponding CC issue https://github.com/chromiecraft/chromiecraft/issues/419?

**Comment by UltraNix** [comment] 2021-07-20 14:02
@necropola No problem with petbar/spells when leveled up or learn new rank/spell on my local server.

**Comment by necropola** [comment] 2021-07-20 18:00
@UltraNix Try the same when mounted while leveling up and/or check pets that weren't active when leveling up.

**Comment by UltraNix** [comment] 2021-07-20 18:47
@necropola Yep - that's the casue - pet offline while leveled up. Thanks.

**Closed** 2021-07-23 09:54 UTC
Labels: Bounty, ChromieCraft Generic, Class - Warlock, Confirmed, Priority - Low
