### ISSUE TITLE
Issue After Server Update - Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#19654] opened 2024-08-17 15:51 UTC
### Current Behaviour

I encountered an issue after performing an update on my AzerothCore server. Upon restarting the server, I received the following error message:

https://gist.github.com/kambire/b3bcfda0a30015c6c99ae2746150b6c7

java

Segmentation fault (core dumped)

Symptoms:

    There are no other visible error messages.
    The server logs do not show any additional information.
    I am unable to locate any core dump files or logs that might help diagnose the issue.

Request:

    Is there a specific location where the core dump file might be stored?
    If not, could you guide me on how to enable debug mode or any additional logging that might help me track down the root cause of this issue?
    
    

Thank you in advance for your assistance.

### Expected Blizzlike Behaviour

The server should start normally without crashing, allowing players to connect and interact with the world as expected.

### Steps to reproduce the problem

no steps

### Extra Notes

The issue does not occur consistently. It seems to be triggered when a player logs in, as sometimes the server runs for hours without crashing, but at other times, it crashes every 10 minutes.

### AC rev. hash/commit

AC> AzerothCore rev. 3c4086a5a069 2024-08-16 05:07:41 -0300 (master branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 1 minute(s) 3 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 1ms
|- Median: 1ms
|- Percentiles (95, 99, max): 3ms, 4ms, 4ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-118-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: npc_gambler.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg

### Operating system

Ubuntu 24.04 LTS

### Custom changes or Modules

mod-cfbg, mod-breaking-news-override, mod-anticheat

**Comment by Nyeriah** [comment] 2024-08-17 16:23
https://www.azerothcore.org/wiki/how-to-restart-and-debug

Please provide a crash log. We can't know what caused it and therefore can't fix it otherwise

**Comment by kambire** [comment] 2024-08-17 18:44
> https://www.azerothcore.org/wiki/how-to-restart-and-debug
> 
> Please provide a crash log. We can't know what caused it and therefore can't fix it otherwise

please help me 
root@wow:/azerothcore-wotlk/env/dist# gdb -x gdb.conf --batch ./worldserver
./worldserver: No such file or directory.
gdb.conf:3: Error in sourced command file:
No executable file specified.
Use the "file" or "exec-file" command.

**Comment by kambire** [comment] 2024-08-18 00:09
> https://www.azerothcore.org/wiki/how-to-restart-and-debug
> 
> Please provide a crash log. We can't know what caused it and therefore can't fix it otherwise

https://gist.github.com/kambire/b3bcfda0a30015c6c99ae2746150b6c7

**Comment by sudlud** [comment] 2024-08-19 18:18
On what machine / hardware are you running your server?
from your crash log it looks like it happens in a part where map files are beeing loaded, which leads to the assumption that you might have corrupted map files / issues reading from drive maybe?

Do you have any more information available?

**Comment by kambire** [comment] 2024-08-19 23:09
> On what machine / hardware are you running your server? from your crash log it looks like it happens in a part where map files are beeing loaded, which leads to the assumption that you might have corrupted map files / issues reading from drive maybe?
> 
> Do you have any more information available?
> 
> Please provide the full output of '.server debug'

Thinking it might be an issue with the operating system, I reinstalled everything from scratch on Ubuntu Server and set up the core again, but the problems persisted. The only debug data I have is the following:

`AC> AzerothCore rev. 3c4086a5a069+ 2024-08-16 05:07:41 -0300 (master branch) (Unix, Release, Static)
Connected players: 49. Characters in world: 48.
Connection peak: 49.
Server uptime: 35 minute(s) 23 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 4ms
|- Median: 1ms
|- Percentiles (95, 99, max): 11ms, 11ms, 16ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-118-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: npc_gambler.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg`

**Comment by kambire** [comment] 2024-08-19 23:09
AC> AzerothCore rev. 3c4086a5a069+ 2024-08-16 05:07:41 -0300 (master branch) (Unix, Release, Static)
Connected players: 49. Characters in world: 48.
Connection peak: 49.
Server uptime: 35 minute(s) 23 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 4ms
|- Median: 1ms
|- Percentiles (95, 99, max): 11ms, 11ms, 16ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-118-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: npc_gambler.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg

**Comment by Kitzunu** [comment] 2024-08-20 07:23
First of all that hash doesnt exist

Second of all, compile in RelWithDebInfo and provide a crashlog. Release logs are useless

**Comment by sudlud** [comment] 2024-08-20 07:38
3c4086a5a069fa73452e74801c8ed4faf6caeb05

the commit does exist, somehow there was an additional `+` at the end

**Comment by and-elf** [comment] 2024-09-01 05:14
Maybe reset local changes, then?

**Comment by Kitzunu** [comment] 2024-11-30 20:24
Closing as it isnt reproducable, and no more info from OP for 3 months

**Closed by Kitzunu** 2024-11-30 20:24 UTC
Labels: Waiting For More Info from Author
