### ISSUE TITLE
Missing/Wrong Models for "Shattered Sun Warriors" and "Shattered Sun Marksman"

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20089] opened 2024-09-29 12:13 UTC
### Current Behaviour

The NPCs are either missing their model or have the wrong model associated. Assumed has to due with the transaction to new modelid table.

<details>
  <summary>Images</summary>

![WoWScrnShot_092924_125753](https://github.com/user-attachments/assets/698e2938-e44c-4b28-a598-56dcdc4c8208)

![WoWScrnShot_092924_125826](https://github.com/user-attachments/assets/4df2f11a-0ef5-4726-b371-0a7017cc8e46)

</details>

### Expected Blizzlike Behaviour

<details>
  <summary>Images</summary>

Marksman
![image](https://github.com/user-attachments/assets/a143d129-b70f-4e8a-9d14-091c3a38a2a5)

Marksman
![image](https://github.com/user-attachments/assets/2a92dce1-27a0-459c-8250-6545c9440b0b)

Warrior
![image](https://github.com/user-attachments/assets/dfd80e9a-b092-4c6a-b067-9dc7490ca61c)

Warrior
![image](https://github.com/user-attachments/assets/eaa206ce-504e-49fe-9c23-88215a661980)

</details>

### Source

Wowhead: [Shattered Sun Warrior](https://www.wowhead.com/npc=55012/shattered-sun-warrior)

Wowhead: [Shattered Sun Warrior](https://www.wowhead.com/npc=25115/shattered-sun-warrior)

### Steps to reproduce the problem

.tele sunwell

Follow the road that goes north-east from the sunwell

You will see on that bridge the missing model / wrong model marksman

Continue following the bridge and go left, you will see the missing model / wrong model warrior

### Extra Notes

If someone tells me which commit the SQL before was changed from the old table creature_template with modelID in it I can probably check the modelid and add it to the new table 

### AC rev. hash/commit

<details>
<summary>Click me</summary>

```
AzerothCore rev. bb0d292e1c2b 2024-09-22 07:38:46 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 26 minute(s) 43 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 5ms, 6ms
Using SSL version: OpenSSL 3.1.5 30 Jan 2024 (library: OpenSSL 3.1.5 30 Jan 2024)
Using Boost version: 1.81.0
Using CMake version: 3.29.3
Using MySQL version: 80036
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 291014951 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: account_bound_mounts.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-chat-transmitter
|- mod-eluna
```
</details>

### Operating system

Windows 10 x64

### Custom changes or Modules

```
|- mod-chat-transmitter
|- mod-eluna
```

**Comment by heyitsbench** [comment] 2024-09-29 12:35
This is a duplicate of an already existing issue and has nothing to do with the swap to `creature_template_model`. These creatures are supposed to make use of transform auras to show their correct models, those auras are not applied on AC.

**Closed by heyitsbench** 2024-09-29 12:35 UTC
