### ISSUE TITLE
Maraudon Portal Unclickable

### ISSUE THREAD

**Issue by wackinwallaby** [azerothcore/azerothcore-wotlk#3036] opened 2020-05-14 13:47 UTC
Maraudon Portal Unclickable

##### SMALL DESCRIPTION:
The portal to inner maraudon(178404) is not clickable by players.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
should be able to click the portal and be teleported into earth song falls inside the maraudon instance

##### CURRENT BEHAVIOUR:
portal is in the correct location, but is not clickable object by players.  Only way I can use it is to activate GM mode on a GM account and the portal is usable at that point and works as intended with GM mode on.  
![WoWScrnShot_051320_214031](https://user-images.githubusercontent.com/65240021/81942073-a7889c80-95c7-11ea-92c0-dbd7808b174a.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to the portal location (maraudon entrance outside of the instance) is right behind spirit of kolk
2.  notice that the portal is unclickable unless gm mode is on
3. 

##### EXTRA NOTES:

I added another game object of the same type(the portal) and it behaved the same. 
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

f301d817e7d5 2020-05-12 06:08:54 +0000 (master branch) (Unix, Release)
commit f301d817e7d542929cb54a9c3b61e7a401c1a23a 

##### OPERATING SYSTEM:

Ubuntu 18.04

##### MODULES:

AHbot
Autobalance

##### OTHER CUSTOMIZATIONS:

None

**Comment by Devellopper** [comment] 2020-05-14 17:33
Try this 
```sql
UPDATE `gameobject_template_addon` SET `faction` = 0 WHERE `entry` = 178404;

**Comment by wackinwallaby** [comment] 2020-05-14 18:14
Thanks that did the trick!  Appreciate it!

**Comment by Kitzunu** [comment] 2020-05-14 19:51
I want to know if this is correct retail behavior, if it is, then pls PR the fix :)

**Comment by wackinwallaby** [comment] 2020-05-14 20:13
Ok sorry I closed I am not sure how this process works... I'm new to this... I think that this is retail behavior but I'm not 100 percent sure since I didn't play wow at this time but according to the patch here it looks likeit... https://wowwiki.fandom.com/wiki/Patch_3.0.8_(undocumented_changes)#Dungeons_and_Raids 

With that said I'll have to look up the PR process.  Thanks for your help.

**Comment by Meltie2013** [comment] 2020-05-15 21:18
@r0m1ntik94 I would make sure that fix is valid by sniffs before changing the faction on anything.
That can cause other issues to arise. Plus I believe the issue is somewhere else like a condition that has not been removed yet for that object.

**Comment by r0m1ntik94** [comment] 2020-05-15 21:39
@Meltie2013 I just suggested a fix so that the portal was available for both factions since from the initial it was available only for the horde. I do not know if it should be for both or not. These changes do not affect the rest I checked in the database everywhere where this portal is involved.

**Comment by Meltie2013** [comment] 2020-05-15 21:44
Let me check a few things here and get back to this issue.

**Comment by a20eac1d** [comment] 2020-05-16 12:11
@Meltie2013 Hey Meltie. Any chance I could contact you via email or Discord or anything? I'd love to help out on this project and am looking for the network packet sniffs.

Thank you!

**Comment by BarbzYHOOL** [comment] 2020-05-16 18:02
join our discord too a20

**Comment by Meltie2013** [comment] 2020-05-17 00:13
After doing some more research, the portal faction can be changed to 0. Still need sniff conformation on the true value.
You can have a look at other portals as reference.
```sql
select a.entry, a.name, b.faction, b.flags from gameobject_template as a 
	inner join gameobject_template_addon as b on a.entry = b.entry 
		left join gameobject as c on a.entry = c.id
			where a.type = 22 and c.id != 0 and a.name like '%Portal%'
				order by name asc;
```

**Closed** 2020-07-18 14:42 UTC
Labels: Fix included
