### ISSUE TITLE
GM Command .pdump not working properly

### ISSUE THREAD

**Issue by digsgg** [azerothcore/azerothcore-wotlk#7840] opened 2021-09-12 20:59 UTC
### Current Behaviour

The GM command `.pdump` is not working correctly, as it needs an update to reflect the current database structure (column positions specifically).

As an example, when executing `.pdump write test.txt Charname`, the server says it cannot dump deleted characters, even though the character to be dumped is not deleted at all.

When applying the possible fix presented as an extra note, executing `.pdump load` on the dump file then presents a MySQL error:
`[1366] Incorrect integer value: '' for column 'order' at row 1`

### Expected Blizzlike Behaviour

`.pdump` should correctly write and load dump files.

### Steps to reproduce the problem

1. Create any character in a GM account
2. Execute `.pdump write test.txt $Charname`

### Extra Notes

Possible fix for the `.pdump write` argument would be to change src/server/game/Tools/PlayerDump.cpp in the following lines:
-Line 329 to: `                        if (result->GetFieldCount() <= 76)          // avoid crashes on next check`
-Line 332 to: `                        if (result->Fetch()[76].GetUInt32())        // characters.deleteInfos_Account - if filled error`
-Line 559 to: `                    if (!changenth(line, 76, null))             // characters.deleteInfos_Account`
-Line 561 to: `                    if (!changenth(line, 77, null))             // characters.deleteInfos_Name`
-Line 563 to: `                    if (!changenth(line, 78, null))             // characters.deleteDate`

As for the `.pdump load` argument, the server then struggles to read the dump file generated after the fix. A possible fix was to manually define the value in column order as NULL (instead of '') on the generated text file, so maybe defining NAs as NULL instead of empty fields on the source code might fix it?

This allowed the server to correctly dump and load the file.

### AC rev. hash/commit

AzerothCore rev. c0bc20214f35+ 2021-09-12 10:20:50 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80026
Using CMake version: 3.16.3
Compiled on: Linux 5.10.16.3-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_09_12_00
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Windows 10

### Custom changes or Modules

Docker installation.

Installed Modules:
mod-account-achievements
mod-ah-bot
mod-autobalance
mod-learn-spells
mod-solocraft-master
mod-solo-lfg

**Comment by Kitzunu** [comment] 2021-09-13 00:05
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7346

**Closed by Kitzunu** 2021-09-13 00:05 UTC
Labels: GM commands

**Comment by acidmanifesto** [comment] 2022-01-25 01:18
https://github.com/azerothcore/azerothcore-wotlk/pull/10349
