### ISSUE TITLE
Dig rat looting issues

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#18046] opened 2023-12-24 05:18 UTC
Original Chromicraft report https://github.com/chromiecraft/chromiecraft/issues/6345 comfirmed on my local

### What client do you play on?

enGB

### Faction

Both

### Content Phase:

20-29

### Current Behaviour

Dig rats are not lootable when killed with melee. Tested on 10+ dig rats. They do drop when killed with a thrown weapon.

Quest Link: https://wowgaming.altervista.org/aowow/?quest=862
Item Link: https://wowgaming.altervista.org/aowow/?item=5051
Mob Link: https://wowgaming.altervista.org/aowow/?npc=3444

### Expected Blizzlike Behaviour

Dig rats should drop the Dig Rat item when killed with any weapon or spell.

### Source

![Dig Rat Before Thrown Kill](https://github.com/chromiecraft/chromiecraft/assets/11815278/239d6f7c-7372-4f7a-919b-8ecaf656d7fb)
![Dig Rat After Melee Kill](https://github.com/chromiecraft/chromiecraft/assets/11815278/058555ca-3fa6-4a34-9626-090dfb9d29c6)
![Dig Rat After Thrown Kill](https://github.com/chromiecraft/chromiecraft/assets/11815278/afdfc04b-ee51-4a9c-b195-f424d7645904)
![Dig Rat Before Melee Kill](https://github.com/chromiecraft/chromiecraft/assets/11815278/002fbeac-e444-40fb-a9b0-997ea281a101)

### Steps to reproduce the problem

1. I found this easier to be Alliance so you don't have to fight with the dwarves too. But the OP was horde. The issue effects both
2. `.go c 13984`
3. Kill Dig Rats with melee attacks.
4. Attempt to loot.
5. Try different skills, or ranks of skills. Some can loot some cannot. My details below.

### Extra Notes

**Tester notes:** At first i thought it was just white damage, But using `Charge` before attacking the rat on the warrior allowed me to loot it. With a warlock, DOT spells corruption and curse of agony also did not allow looting. Shadow bolt did allow me to loot. On a Rogue, simple melee will not allow me to loot, however a Sinester Strike would. Mage, rank 1 fireball would not let me loot, rank 16 fireball would. Rank 1 frost bolt allowed loot. I see no pattern. I can't put my finger on the cause here. but something is definitly wrong.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-12-24 05:22
Likely the same issue as the Marsh Frog one.

**Comment by Kitzunu** [comment] 2024-01-03 17:32
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/16374

**Closed by Kitzunu** 2024-01-03 17:32 UTC
Labels: Confirmed, 20-29
