### ISSUE TITLE
[server]world server crash 0929-2

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13172] opened 2022-09-29 15:38 UTC
### Current Behaviour

crash log:

https://gist.github.com/mpfans/872a5d7a5454821783ed63da81c432ae

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

6c3fc2603b46c84cd4334030f4bf7b57857e0241

### Operating system

Ubuntu20.04

**Comment by Winfidonarleyan** [comment] 2022-10-01 08:20
interesting, very

**Comment by UltraNix** [comment] 2022-10-01 09:13
@mpfans Looks like invalid query. Very weird.

**Comment by mpfans** [comment] 2022-10-01 15:11
@UltraNix  https://github.com/azerothcore/azerothcore-wotlk/issues/13189

I'm not sure if it's the same

**Comment by UltraNix** [comment] 2022-10-01 15:16
Different but looks again odd.

**Comment by mpfans** [comment] 2022-10-01 15:18
Recently updated the latest code several times, no custom code

**Comment by UltraNix** [comment] 2022-10-01 15:19
Testing some PRs?

**Comment by mpfans** [comment] 2022-10-01 15:21
> Testing some PRs?

no... on master branch

**Comment by mpfans** [comment] 2022-10-01 15:21
![image](https://user-images.githubusercontent.com/18187177/193416377-520cc485-d22f-40b7-ab96-9ba4aa5bd6c2.png)

**Comment by UltraNix** [comment] 2022-10-01 15:23
If it's something new, try to revert some recent commits (if possible) and test it.

**Comment by mpfans** [comment] 2022-10-01 15:26
About 5-6 crashes in the last week

I was wondering whether to test the PR submitted by Nefertum about fixing crashes

**Comment by UltraNix** [comment] 2022-10-01 15:30
They are okay, but these two crashes you linked here are odd. If it repeats often, then I suggest revert recent commits.

**Comment by Kitzunu** [comment] 2022-10-31 01:19
What does your DBError file say?

**Comment by Kitzunu** [comment] 2022-10-31 01:21
Found this in the crashlog
```
fmtMessage="Tried to access invalid prepared statement index 103680 (max index 455) on database `characters`, connection type: asynchronous")
```

So your DBErrors log would be helpful @mpfans

**Comment by mpfans** [comment] 2022-10-31 02:11
> Found this in the crashlog
> 
> ```
> fmtMessage="Tried to access invalid prepared statement index 103680 (max index 455) on database `characters`, connection type: asynchronous")
> ```
> 
> So your DBErrors log would be helpful @mpfans

sry... DBErrors.log not time stamp... How to add it?

**Comment by Kitzunu** [comment] 2022-11-01 21:01
I dont reslly know what you mean, but next crash, just post your entire DBErrors file @mpfans

**Comment by Kitzunu** [comment] 2022-11-06 18:05
Okay. I want you to do 3 things  @mpfans 

1. Post ALL your preparedstatements.
2. Post the entire output of `.server debug`
3. Next time you crash, post DBErrors.log file. We have asked several times but you never post it with your new issues.

Otherwise we need to close the issue, because only you are having these issues.

**Comment by mpfans** [comment] 2022-11-30 00:52
DBErrors.log
https://gist.github.com/mpfans/cf32ff835952d43e7ebe5f471954694e

@Kitzunu

**Comment by mpfans** [comment] 2022-11-30 00:53
AC> AzerothCore rev. 9bebd6a05e4a+ 2022-11-21 09:16:02 +0000 (master branch) (Unix, RELWITHDEBINFO, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80031
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-132-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/data/mmaps. Total size: 2320900676 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-multi-client-check

**Comment by Kitzunu** [comment] 2022-12-11 09:16
I am going to close this. Here are the reasons:

1. You are the only one having this issue, nobody else, which points to you having some custom code in the core or modules that is causing this.
2. As the information of the crashlog is pointing to a prepared statement that does not exist in the core, it points to custom modifications
3. As the DBErrors log and the Crashlog doesnt provide any additional data that can be used to debug, except the custom prepared statement there is no way to debug it.
4. As you don't know how to reproduce it, it will be impossible.

**Closed by Kitzunu** 2022-12-11 09:16 UTC
Labels: ChromieCraft Generic, Priority-Critical, HasBacktrace
