### ISSUE TITLE
Combat bug

### ISSUE THREAD

**Issue by pati3nc3** [azerothcore/azerothcore-wotlk#627] opened 2017-09-13 15:43 UTC
**Description**: Actions that will get you into combat:
Attacking
Casting an offensive Spell
Casting a Buff or Healing spell on a unit that is in combat
Getting on a mob's Aggro list
Certain bosses always put everyone in the group (or raid) in combat when engaged, regardless their distance from the boss

**Current behaviour**: When you cast a buff or healing spell on a unit that is in combat the caster doesen't enter in combat. The same bug occurs when the first unit enter in combat with his pet.

**Expected behaviour**:  When you cast a buff or healing spell on a unit that is in combat the caster HAVE to enter in combat.

**HOW TO TEST**:
1. Create 2 characters for example Priest and Mage ( same faction, Horde ) and 1 character (Ally)
2. Cast spells with mage on Ally and cast Heal or Buff on the mage while he's is in combat 
3. The Priest doesn't enter in combat

**Comment by talamortis** [comment] 2017-09-13 16:06
are you testing the source yourself? or are you a player on a server?

**Comment by pati3nc3** [comment] 2017-09-13 16:08
I personally tested it more then once.

**Comment by talamortis** [comment] 2017-09-13 16:09
yes but are you using azerothcore source code? as i dont get the issue

**Comment by BarbzYHOOL** [comment] 2017-09-13 16:45
AS = azerothshard (precise it next time)

I don't know if it uses the same source code but it's from Yehonal

**Comment by poszer** [comment] 2019-03-26 23:20
Can't reproduce this. Closing

**Comment by Motorheadx** [comment] 2019-04-28 18:49
There's a problem, I confirm.

**Comment by FrancescoBorzi** [comment] 2019-04-28 19:13
@Motorheadx can you please open a new report with your details?

**Comment by Motorheadx** [comment] 2019-04-28 19:35
did what pati3nc3 wrote

**Comment by FrancescoBorzi** [comment] 2019-04-28 19:44
@Motorheadx can you please your AC version (commit hash)?

**Comment by Motorheadx** [comment] 2019-04-28 19:48
https://github.com/azerothcore/azerothcore-wotlk/commit/5df63b86c2d3251f5f91a834653503c8c33d7a6b

**Comment by poszer** [comment] 2019-04-28 21:44
Again, can't reproduce :smiley:  
Screenshots as proof :+1: 
![casting buff](https://user-images.githubusercontent.com/41213210/56870423-6f8bd700-6a0f-11e9-83b2-ba0f6d579307.png)
![incombat](https://user-images.githubusercontent.com/41213210/56870424-74508b00-6a0f-11e9-89d2-9c1929b9b05c.png)
![casting flash heal](https://user-images.githubusercontent.com/41213210/56870425-774b7b80-6a0f-11e9-8a8a-414065317bd3.png)
![reapply](https://user-images.githubusercontent.com/41213210/56870427-7c102f80-6a0f-11e9-9214-ef49773988e7.png)
![outofparty](https://user-images.githubusercontent.com/41213210/56870429-7fa3b680-6a0f-11e9-88ae-62312349507d.png)

**Comment by Motorheadx** [comment] 2019-04-28 21:45
test caster class please

**Comment by poszer** [comment] 2019-04-28 21:47
> test caster class please and pvp combat

Okay

**Comment by poszer** [comment] 2019-04-28 22:16
Even with casters, i don't see any problem here
![refresh](https://user-images.githubusercontent.com/41213210/56870715-ecb94b00-6a13-11e9-9107-c3e90abea735.png)
![enter](https://user-images.githubusercontent.com/41213210/56870716-ecb94b00-6a13-11e9-997b-fecba99e37fa.png)
![taking](https://user-images.githubusercontent.com/41213210/56870717-ecb94b00-6a13-11e9-958e-2b01fc2a8a00.png)

**Comment by Motorheadx** [comment] 2019-04-28 22:19
pvp combat please and do not press the right mouse button when attacking another player and just shoot him with an frost bolt

**Comment by poszer** [comment] 2019-04-28 22:22
> pvp combat please and do not press the right mouse button when attacking another player and just shoot him with an frost bolt

Than give me instantly all details how to reproduce it. You have edited comment X times. And as you can se in this one, the creature is shooted with firebolt.
Also i'll test it as Player vs Player. But how i remember, there is no problem with this. Let's see

**Comment by Motorheadx** [comment] 2019-04-28 22:36
you can ignore me, I told you about the problem, do it or not, you decide and so the problem still have test more carefully

**Comment by poszer** [comment] 2019-04-28 22:37
> you can ignore me, I told you about the problem, do it or not, you decide and so the problem still have test more carefully

Did i ignore you? Or i'm only here who's trying to see where is problem?

**Comment by poszer** [comment] 2019-04-28 23:30
Tested, now can confirm. The only problem is with casters.
How to reproduce this : 
1. Create 2 characters for example Priest and Mage ( same faction, Horde ) and 1 character (Ally)
2. Cast spells with mage on Ally and cast Heal or Buff on the mage while he's is in combat 
3. The Priest doesn't enter in combat

This is how you should report issues. So we can know how to reproduce it @Motorheadx

**Comment by FrancescoBorzi** [comment] 2019-04-29 07:59
@Motorheadx it's not that we don't believe you. Just it's impossible for developers to fix a bug without being able to reproduce it first. That's why @poszer tried very hard to do it and finally came up with the exact steps to reproduce the problem

**Comment by BarbzYHOOL** [comment] 2019-05-01 22:02
Big issue

**Comment by poszer** [comment] 2019-05-17 00:52
@Motorheadx Can you try the fix?

**Closed** 2019-05-21 00:43 UTC
Labels: Help wanted, Needs Developer, Priority - High

**Comment by Motorheadx** [comment] 2019-05-29 17:55
combat also doesn't work properly

**Comment by BarbzYHOOL** [comment] 2019-05-29 17:59
too late

**Comment by poszer** [comment] 2019-05-29 18:39
> combat also doesn't work properly

You dont learn anything from what i write you. Be precise,  explain everything. I can't reproduce anything, if you just write "combat doesnt work properly ".  Also, since you  reporting issues, and since we fix it, atleast test it when I ask you! Don't be lazy and just wait for fix. If you know to apply fix, than you know also how to test PR. Thanks

**Comment by Viste** [comment] 2019-05-29 21:01
Нормально ты с ними общаешься ))), но вообще оно правы, в том случае если ты никогогда не играл в wow, )), судя по всему что я вижу, мало кто тут дейтвительно ИГРАЛ в ВоВ, а не просто заходил под пиво с кентами побегать ) ну и да, если впаду переводить напиши просто на русском в deepl и закидывай им пусть дальше сами эти сканворды разгадывают ))))))
don't push on him, he's not very good with English, explained to you how he could. In general, if you play WoW, everything is clear from his explanations.

**Comment by BarbzYHOOL** [comment] 2019-05-30 15:31
@Motorheadx use this translator then https://www.deepl.com/translator#en/ru/
