### ISSUE TITLE
Pathing/Aggro issue in Deadmines [$50]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4405] opened 2021-02-01 11:42 UTC
Pathing issue in Deadmines

##### CURRENT BEHAVIOUR:

Inside the Deadmines dungeon at the boat section the pathing/aggro is very strange. You can pull Captain Greenskin from the lower ship decks.

This means you can pull the 2nd to last boss by accident when ascending the ramps to get to the top deck, it also means you can pull Greenskin on purpose from the bottom deck.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Greenskin should be the 2nd to last boss to fight, not aggroable from the bottom deck of the ship.

##### STEPS TO REPRODUCE THE PROBLEM:

This is very hard to reproduce. Yehonal has video somewhere pls upload Yehonal.

1. Go to Deadmines
2. Get to the lower deck area of wooden scaffolding and stand near the Captain Greenskin path rotation (or taunt him)
3. Watch as you can aggro Greenskin by standing/taunting from the bottom deck.

##### EXTRA NOTES:

Not entirely sure if this is a bug but it feels very off to me.

##### AC HASH/COMMIT:

ChromieCraft latest (and 2-3 versions before that).

**Comment by Kitzunu** [comment] 2021-02-01 12:33
Please reproduce this on latest Azerothcore, as Yehonal's PR was just merged.

**Comment by Yehonal** [comment] 2021-02-01 12:58
@Kitzunu tested on my PR, the issue is still there, it's related to aggro radius and condition.

I'll take a look asap. Thanks for the feedback @JamesGent

**Comment by JamesGent** [comment] 2021-02-01 16:13
![WoWScrnShot_020121_160814](https://user-images.githubusercontent.com/61194190/106485374-6f542180-64a8-11eb-90ff-e9b2c8bed1d2.jpg)

**Comment by T1ti** [comment] 2021-02-16 20:56
This is blizzlike, Classic has this issue as well, maybe they fixed it in a later version tho.

**Comment by T1ti** [comment] 2021-02-16 20:59
https://youtu.be/j01MfraN6b0?t=2999
You can see it happening here

**Comment by UltraNix** [comment] 2021-03-16 10:25
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/4397-deadmines-vc-guide.html
`Before we proceed I must warn you that on the ship there is not much room and it's quite packed. I suggest you have your puller always pull way back to your group. Tell him to do it carefully, especially when reaching the 2nd floor of wooden boards, on the right-hand side of the ship, because Captain Greenskin roams right above it. It is very easy to agro the captain and cause a party wipe. Try to have someone keep a watch on the Captain for early warning if he does agros`
+ video above.
No bug?

**Comment by T1ti** [comment] 2021-03-19 04:58
I also think it's not a bug. or a least a blizzlike bug.

**Comment by Yehonal** [comment] 2021-03-19 07:16
the vmaps generated do not have any obstructions there, so the captain can clearly see you and aggro.

The only way to "disable" this behaviour would be to add a further check to the aggro system which includes the Pathgeneration: the idea is to generate the path that is needed to reach you and if it's higher than the max aggro distance, we could avoid the creature to engage you.

**Closed by Yehonal** 2021-03-19 07:16 UTC
Labels: 1-19, Bounty, Priority - High
