### ISSUE TITLE
[Achievements] dual talent

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2076] opened 2019-07-08 08:43 UTC
Description: bug learn dual talent achievement.

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/6db0a438d9dff3d1fab5f904657ed281f5dee6c7

OS: windows 2017

MODULES:
Anticheat

@Winfidonarleyan 

https://github.com/azerothcore/azerothcore-wotlk/pull/1218

**Comment by FrancescoBorzi** [comment] 2019-07-08 17:31
Can you please be more descriptive? It is not clear to me what the problem is

**Comment by wowmane** [comment] 2019-07-08 17:47
if give dual talent, dont give achievement!

**Comment by Selyria** [comment] 2019-07-09 07:09
So I just tested it and didn't have any problems. 
![Duall Spell](https://user-images.githubusercontent.com/179698/60866684-49618f00-a229-11e9-8deb-11a0d2b94910.jpg)

**Comment by poszer** [comment] 2019-07-09 07:19
Thank you @Selyria . Closing this issue

**Closed by poszer** 2019-07-09 07:19 UTC
Labels: Invalid - CannotReproduce

**Comment by wowmane** [comment] 2019-07-09 10:08
@Selyria 

WTF? 

What is your version :))?

**Comment by Selyria** [comment] 2019-07-09 18:53
AzerothCore rev. ac8b20922bea+ 2019-07-08 11:27:52 +0200 (master branch) (Win64, Release)
