### ISSUE TITLE
Command .send mail triggers a warning about transaction

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1884] opened 2019-05-25 11:08 UTC
##### SMALL DESCRIPTION:

Command .send mail triggers a warning showing that there is superfluous code

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No warning

##### CURRENT BEHAVIOUR:

`.send mail your_character "hello" "butch"` => warning in the console: `Warning: Transaction only holds 1 query, consider removing Transaction context in code.`

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.send mail your_character "hello" "butch"`
2. Check console

##### EXTRA NOTES:

~~ALSO, you need to log off to receive the mail and log back. If you use `.send items`, you send a mail but you don't need to log off (I didn't check the console for `.send items` though, sorry no time atm). Apparently it requires a /reload~~

I'm on an OLD core and many things have been cleaned recently by Shin, maybe he fixed it (but I doubt it).

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

e8aff9feac0fdcce5591b9c6e5e1eb1f77d57bc7

**Comment by Selyria** [comment] 2019-05-25 22:25
So I just tested it I do not get any errors in the console and the mail is also sent and can be retrieved in the mailbox 

AzerothCore rev. 6131c9d789bd+ 2019-05-18 21:10:42 +0000 (master branch) (Win64, Release)

**Comment by BarbzYHOOL** [comment] 2019-05-26 09:43
And you didn't have to log out and log in to view the mail in the mailbox ? or type /reload ?

**Comment by poszer** [comment] 2019-05-27 12:03
> And you didn't have to log out and log in to view the mail in the mailbox ? or type /reload ?

Need rework

**Comment by BarbzYHOOL** [comment] 2019-05-27 14:20
@poszer do you get warning like me or not?

**Comment by poszer** [comment] 2019-05-27 14:36
> @poszer do you get warning like me or not?

yes, ofc

**Comment by BarbzYHOOL** [comment] 2019-05-27 14:46
but selyria said "no error" in console

@Selyria I was speaking of the console (the worldserver.exe), and it might require to set it to log debug messages too

**Comment by Selyria** [comment] 2019-05-27 16:04
Yes I also get errors sry had my worldconfig replace my fail

**Comment by Kitzunu** [comment] 2020-07-26 15:33
```cpp
void DatabaseWorkerPool<T>::CommitTransaction(SQLTransaction transaction)
{
    #ifdef ACORE_DEBUG
    //! Only analyze transaction weaknesses in Debug mode.
    //! Ideally we catch the faults in Debug mode and then correct them,
    //! so there's no need to waste these CPU cycles in Release mode.
    switch (transaction->GetSize())
    {
        case 0:
            sLog->outSQLDriver("Transaction contains 0 queries. Not executing.");
            return;
        case 1:
            sLog->outSQLDriver("Warning: Transaction only holds 1 query, consider removing Transaction context in code.");
            break;
        default:
            break;
    }
    #endif // ACORE_DEBUG

    Enqueue(new TransactionTask(transaction));
}

**Comment by Voxstrasza** [comment] 2020-11-27 18:27
I cannot reproduce on `f6d4ceeebc62+`.  Here is my worldserver:

```

Command: .send mail idiot "hello" "poop" [Player: Idiot (13l) (Account: 11) X: -2552.814209 Y: -4817.844238 Z: 119.127335 Map: 1 (Kalimdor) Area: 2079 (Alcaz Island) Zone: Dustwallow Marsh Selected:  (0l)]
Average update time diff: 38. Players online: 1.
Command: .send mail idiot "hello" "poop" [Player: Idiot (13l) (Account: 11) X: -2552.814209 Y: -4817.844238 Z: 119.127335 Map: 1 (Kalimdor) Area: 2079 (Alcaz Island) Zone: Dustwallow Marsh Selected:  (0l)]
Command: .send mail idiot "hello" "butch" [Player: Idiot (13l) (Account: 11) X: -2552.814209 Y: -4817.844238 Z: 119.127335 Map: 1 (Kalimdor) Area: 2079 (Alcaz Island) Zone: Dustwallow Marsh Selected:  (0l)]
```

Must've been fixed in the last year and a half - closing.

**Closed by Voxstrasza** 2020-11-27 18:27 UTC
Labels: CORE, DB, Priority - Low
