### ISSUE TITLE
Wrong model for Shattered Sun Warrior and Shattered Sun Marksman

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#15293] opened 2023-03-06 20:49 UTC
### Current Behaviour

**perhaps someone else! IDK**

![WoWScrnShot_030623_234701](https://user-images.githubusercontent.com/21084600/223227110-573f834d-e548-4ffd-a607-66468bdd3eb1.jpg)

![WoWScrnShot_030623_235904](https://user-images.githubusercontent.com/21084600/223229236-ac96feec-fb68-4822-b36a-dfe3e1e86903.jpg)

### Expected Blizzlike Behaviour

https://www.wowhead.com/wotlk/npc=37512/shattered-sun-warrior
https://www.wowhead.com/wotlk/npc=25142/shattered-sun-marksman

### Steps to reproduce the problem

.tele shattr

### AC rev. hash/commit

850dfb93203ba80ae66deb597abd612c61878777

### Operating system

Putin OS

**Comment by Mitradis** [comment] 2023-03-06 20:50
and they have wrong position in Shattrath.

**Comment by Mitradis** [comment] 2023-03-06 20:56
```
REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(24938, 0, 0, 0, 0, 0, 22752, 22757, 22753, 22763, 'Shattered Sun Marksman', '', '', 0, 70, 70, 1, 1957, 0, 1, 1.14286, 1, 1, 20, 1, 0, 0, 1, 2000, 2000, 1, 1, 1, 33536, 2048, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'SmartAI', 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, '', 0),
(25115, 0, 0, 0, 0, 0, 22910, 22914, 22918, 22922, 'Shattered Sun Warrior', '', '', 0, 70, 70, 1, 1960, 0, 1, 1.14286, 1, 1, 20, 1, 0, 0, 1, 2000, 2000, 1, 1, 1, 33536, 2048, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 1, 1.5, 1, 1, 1, 0, 0, 1, 0, 0, 0, '', 0);
```

**Comment by avarishd** [comment] 2023-03-15 14:25
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/10795. More info there.

**Closed** 2023-03-15 14:26 UTC
Labels: Invalid-Duplicate
