### ISSUE TITLE
[WORLD] Dragons flying in Blackrock Mountain are slow and have bad waypoints

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#547] opened 2017-08-12 12:08 UTC
**Description:** 
The dragons that fly above the centrail are of Blackrock Mountain do not move as they should. Both of them should be flying a specific route at a normal speed. Instead, they are slow and seem to stay in place.

**Expected behavior:** 
They should mimic the flight pattern and speed of the original game.

**Steps to reproduce the problem:**
Visit the central are of Blackrock Mountain and look up!

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by poszer** [comment] 2019-07-16 16:08
Missing informations. Idk what dragons, what is that creature ID, we can't reproduce this without informations. Closing this

**Closed by poszer** 2019-07-16 16:08 UTC
Labels: Good first issue, Invalid - Missing information, Priority - Trivial
