### ISSUE TITLE
[DK-Quest #12679] - Tonight We Dine In Havenshire

### ISSUE THREAD

**Issue by iThorgrim-Hub** [azerothcore/azerothcore-wotlk#2609] opened 2020-01-23 14:57 UTC
[DK-Quest #12679] - Tonight We Dine In Havenshire

SMALL DESCRIPTION:
* No arrows are fired on the area, they are all already on the ground, therefore, no pnj is hit by an arrow.

EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.youtube.com/watch?v=KlTDzmnnQ70

https://www.wowhead.com/quest=12679/tonight-we-dine-in-havenshire
https://wowgaming.altervista.org/aowow/?quest=12679

BRANCH(ES):
master

AC HASH/COMMIT:
9f690a3

OPERATING SYSTEM:
Ubuntu 18.04

MODULES:
mod_eluna
mod_transmo

OTHER CUSTOMIZATIONS:
No custom

**Comment by Hacaw** [comment] 2020-12-09 20:36
CONCLUSION
---
I can not reproduce this issue.
@iThorgrim-Hub I don't understand what is the issue. Saronite arrows are spawned on the ground and you can easily loot them.
What do you mean by pnj ?  I watched the retail video and the arrows were also on the ground.

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Kitzunu** [comment] 2021-04-25 00:29
Will close this as there are no updates since it wasn't reproduced

**Closed by Kitzunu** 2021-04-25 00:29 UTC
Labels: Not confirmed
