### ISSUE TITLE
UDK gargoyle

### ISSUE THREAD

**Issue by Felcaster** [azerothcore/azerothcore-wotlk#16958] opened 2023-08-08 13:22 UTC
### Current Behaviour

Hello
https://github.com/azerothcore/azerothcore-wotlk/issues/3053
Gargoyle still have not enough dmg. I create full pvp DK 6651 gears score with Shadowmourne and two best trinkets.
Dr.Damage shows that strike must be ~2684 and total lifetime dmg ~38525 (with all procs around 80000).
But recount shows 1595-1614 strike dmg and 36071 total dmg (gargoyle called with all procs). So it miss ~ 50%dmg.
![WoWScrnShot_080823_155109](https://github.com/azerothcore/azerothcore-wotlk/assets/141717213/69022421-ffad-4551-b9ee-b9ef276441dd)
Screen with procs ~83657 lifetime dmg
![WoWScrnShot_080823_160419](https://github.com/azerothcore/azerothcore-wotlk/assets/141717213/9d1872bf-3d1f-4265-9091-0897ad4a3f4d)

### Expected Blizzlike Behaviour

 with procs ~83657 lifetime dmg

### Steps to reproduce the problem

Summon gargoyle.

### AC rev. hash/commit

.server debug
AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Rel
ease, Static)
Using SSL version: OpenSSL 3.0.9 30 May 2023 (library: OpenSSL 3.0.9 30 May 2023
)
Using Boost version: 1.81.0
Using MySQL version: 80033
Using CMake version: 3.26.4
Compiled on: Windows 6.1.7601
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 557561268 bytes
vmaps directory located in ./data/vmaps. Total size: 1330813631 bytes
mmaps directory located in ./data/mmaps. Total size: 2270339876 bytes
Using ruRU DBC Locale as default. All available DBC locales: ruRU
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- DungeonRespawn
- StatBooster
- mod-TimeIsTime
- mod-account-achievements
- mod-accountbound
- mod-ah-bot
- mod-autobalance (disabled)
- mod-eluna
- mod-gain-honor-guard
- mod-guildfunds
- mod-individual-xp
- mod-learn-spells
- mod-npc-all-mounts
- mod-npc-free-professions
- mod-skip-dk-starting-area
- mod-solo-lfg
- mod-transmog

### Operating system

windows 7 x64

**Comment by heyitsbench** [comment] 2023-08-08 17:38
Duplicate of #16420 and missing revision hash.

**Closed by heyitsbench** 2023-08-08 17:38 UTC
Labels: Invalid-MissingHash/Commit
