### ISSUE TITLE
2 mining nodes inside/on top of eachother in Plaguelands

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#4770] opened 2021-03-09 11:36 UTC
2 mining nodes inside/on top of eachother in Plaguelands

2 locations.

##### CURRENT BEHAVIOUR:

![WoWScrnShot_030921_113450](https://user-images.githubusercontent.com/61194190/110464810-84d1f200-80cb-11eb-9690-68c42ae4d120.jpg)

![WoWScrnShot_030921_113420](https://user-images.githubusercontent.com/61194190/110464816-87cce280-80cb-11eb-8c3e-bd508e4f402f.jpg)

Found another here.

![WoWScrnShot_030921_113842](https://user-images.githubusercontent.com/61194190/110465191-03c72a80-80cc-11eb-84cb-ff4a5c5f34a1.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only 1 at a time

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the shown location in screenshot/map
2. Use Find Minerals
3. Show 2x nodes in same spot

##### AC HASH/COMMIT:

AzerothCore rev. 6a7155eb7e82 2021-03-07 12:37:07 +0000 (master branch)

**Comment by celestinmetral** [comment] 2021-03-09 23:35
Hello, if possible, I would like to try to resolve this issue for my first one. Please don't hesitate to tell me if I'm doing wrong!

I can confirm that there are two nodes at X=1238 and Y=-1780 (see picture). I found the line in `gameobject` table, and to try I moved the Mithril one at Z=73 for visibility (and to confirm I've got the correct one!).

![image](https://user-images.githubusercontent.com/13820293/110552109-027f1780-8137-11eb-8fb3-2ae57f20648e.png)

To check if we should keep the gold or mithril one, I looked at WotlkDB : [gold vein](https://wotlkdb.com/?object=1734) and [mithril deposit](https://wotlkdb.com/?object=2040) (see "Western plaguelands" map). The problem is that for both objects, there is a spawn node at (51.1, 74.3). Which one should we keep? Where can I can find better info ? Youtube videos ?

Let say we decide to remove the mithril one, the query would be something like `DELETE FROM gameobject WHERE guid=7193;`, right ?

From know, I've got to learn how to make a correct pull request, and understand how the `INSERT INTO `version_db_world` (`sql_rev`) VALUES ('xx');` I saw in other PR works.

Thanks !

**Comment by Zoidwaffle** [comment] 2021-03-10 07:35
I haven't checked out Plaguelands, so what I'm saying here is general info as I understand it.

You can add objects into a `pool_template` - by doing that, you could make a pool with for example 3 nodes. 1 Gold, 1 Mithril and 1 Iron. Then make only 1 object from the pool spawn at once with a lower chance for gold than the others.

Perhaps not the best example in the world, but maybe you can get some inspiration here:

https://github.com/azerothcore/azerothcore-wotlk/pull/4690/files

As an alternative, you could delete one of the nodes to prevent them being too close.

**Comment by JamesGent** [comment] 2021-03-11 02:04
@celestinmetral 

Related but a separate issue: If you get a chance, use Find Minerals and fly around Searing Gorge (starting from Thorium Point and go north). I found 10+ stacks of double, triple, and even quintuple nodes in Searing Gorge.

**Comment by celestinmetral** [comment] 2021-03-11 21:00
Ok thanks, the idea I got was to make a query to find ALL nodes on the map that are very close to each other and be sure they are in a pool, if the `pool_template` is the solution ! Thanks

**Comment by Andrei-UPB** [comment] 2021-03-15 23:06
Haven't been around AC lately, but speaking from experience, all the old world mines are lacking pool templates but have the proper coordinates, some of them spawn inside mountains and other terrain and can be fixed on a case-by-case basis.

In northrend the mines were grouped into pools across the entire continent, with cobalt being very, very scarce. Once chromiecraft reaches 71+ bracket this will be one of the first issues that will pop up.

Celestin, your idea is the way I thought about doing it back in 2019 as well, getting pools going for every Kalimdor/EasternKingdoms zone and not the entire continent, but I abandoned it in favor of learning SAI.

Good luck with this, it's not a hard issue.

**Comment by celestinmetral** [comment] 2021-03-16 23:03
Okay so while this issue had me dive into the database structure which is a good thing, I think it's related to issues  #2510 and #2211 for exemple, so it's a more complex problem

**Closed** 2022-11-01 15:58 UTC
Labels: 60, Good first issue, temporary label
