### ISSUE TITLE
Quest #12027 Bug/Script Problem: Mr. Floppy's Perilous Adventure

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1310] opened 2019-01-17 15:45 UTC
##### SMALL DESCRIPTION:
This is an escort quest, towards the end of the quest, a final creature spawns which the player is supposed to kill: Ravenous Worg (id=26590), it spawns but it just stands there and does nothing. Then after about 20 seconds, the quest completes successfully with the creature still standing there doing nothing. I have noticed earlier in the dberrors.log when world server starts, it throws the following

ERROR: Script named 'npc_ravenous_worg' is assigned in database, but has no code!

even when the script is actually there in src/server/scripts/Northrend/zone_grizzly_hills.cpp Line 326 as pointed out by Poszer.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The ravenous worg is supposed to attack floppy, throw it away, and then attack player. But after attacking Floppy, it just stands there and does nothing. Even when the player attack it, it still does nothing, no fighting back.

##### CURRENT BEHAVIOUR:

The ravenous worg just stands there after attacking Floppy, and does nothing even if the player attacks it.
https://wowgaming.altervista.org/aowow/?quest=12027
https://wowgaming.altervista.org/aowow/?npc=26590
![wowscrnshot_011719_231714](https://user-images.githubusercontent.com/35093669/51330182-f5fc5880-1ab1-11e9-8424-26a20ab9f9db.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept Quest #12027 from Emily at Northrend Grizzly Hills (map coord 49,34), no prequests required, anyone can do as long as they are level 63 or above. And then just follow through it.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

b578bce
https://github.com/azerothcore/azerothcore-wotlk/commit/b578bce1d1b7de2254ec2aacb19bed40a0732997

##### OPERATING SYSTEM:

Win 7/10

##### MODULES:

no

##### OTHER CUSTOMIZATIONS:

no

**Comment by poszer** [comment] 2019-01-17 16:21
Follow the quest normally. Gona post Video soon ( Just to show you that NPC Ravenous Worg is attacking Pet )

**Comment by poszer** [comment] 2019-01-17 16:34
> I just followed it normally, I saw it chew the pet and throw it away, but then it just stays there and does nothing, even if i proactively attack it, it still does nothing. 5 seconds later the quest says complete.... it is supposed to attack the player after throwing away the pet?

Ok, found some video on youtube, while my is uploading, take a look :
[Mr. Floppy's Perilous Adventure](https://www.youtube.com/watch?v=FnHXYNYKMjA)

**Comment by gtao725** [comment] 2019-01-17 16:41
saw them both, compared to mine, all is same except the very end, I attack it after it throws away Floppy, but it doesn't attack back.

**Comment by poszer** [comment] 2019-01-17 16:50
> saw them both, compared to mine, all is same except the very end, I attack it after it throws away Floppy, but it doesn't attack back.

Hmm interesting, i can't reproduce it, you will see in video in max 5 min that NPC Ravenous Worg attack pet

**Comment by gtao725** [comment] 2019-01-17 16:55
Poszer, I know the Worg attacks the pet, I am saying that the Ravenous Worg does not attack the player after attacking the pet. I am uploading my video now.

**Comment by poszer** [comment] 2019-01-17 17:06
> Poszer, I know the Worg attacks the pet, I am saying that the Ravenous Worg does not attack the player after attacking the pet. I am uploading my video now. Srry I wasn't very clear about it in the initial post (edited it now), video still uploading.

Yeah, didn't understand you best. I'll test it now

**Comment by Stoabrogga** [comment] 2019-01-17 17:21
@poszer 
The object instantiation for "npc_ravenous_worg" is missing. Just add
```
new npc_ravenous_worg();
```
under
```
new npc_mrfloppy();
```
in function "AddSC_grizzly_hills()" (zone_grizzly_hills.cpp).

**Comment by poszer** [comment] 2019-01-17 17:25
> new npc_ravenous_worg();

Thank you lol

**Comment by poszer** [comment] 2019-01-17 17:30
> My video to illustrate problem: https://youtu.be/bx_V3o8CqEg
> 
> Thx Stoabrogga and poszer! I will test it tmr after recompiling.

Yeah, i'll update it soon

**Comment by gtao725** [comment] 2019-01-18 02:19
I confirm this quest is perfect now, thx so much guys!

**Comment by BarbzYHOOL** [comment] 2019-01-18 11:49
@gtao725 please, say it on the pull request (PR)'s page https://github.com/azerothcore/azerothcore-wotlk/pull/1314 and don't close until it's merged

**Comment by gtao725** [comment] 2019-01-18 12:45
got it, srry still new to github, slowly learning all the rules. Thx for the reminder.

**Closed** 2019-01-19 11:07 UTC
Labels: CORE, General - Quests
