### ISSUE TITLE
[quest] `At The Enemy's Gates`

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13905] opened 2022-11-22 03:53 UTC
### Current Behaviour

`At The Enemy's Gates` quest ,Kill the monster required by the quest. The quest target has not been increased,not mount `Stabled Campaign Warhorse`,Kill the monster required by the quest, and the quest target will increase

### Expected Blizzlike Behaviour

mount `Stabled Campaign Warhorse`,Kill the monster required by the quest, and the quest target will increase

### Steps to reproduce the problem

1. .q a 13847(.q a 13856)
2. .additem  46106
3.  `.go xyz 6421.782715 2368.399414 466.919586 571`
4. mount a `Stabled Campaign Warhorse`
5. Kill the monster required by the quest. The quest target has not been increased

### AC rev. hash/commit

9bebd6a05e4a251a87a1d22b347da2e0a6a13336

### Operating system

Ubuntu20.04

**Comment by heyitsbench** [comment] 2022-11-22 03:54
Duplicate of #12849.

**Closed by heyitsbench** 2022-11-22 03:54 UTC
