### ISSUE TITLE
BRD respawntime is too high in The Lyceum

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1773] opened 2019-04-25 18:19 UTC
SMALL DESCRIPTION:

The Lyceum is a place in FRG where many non-elite run around that's also okay you have to collect 2 torches from the Shadowforge Flame Keepers the challenge is that the creatures respawn very fast. that happens but only the respawn is much too long.

EXPECTED BLIZZLIKE BEHAVIOUR:
Link: https://wowwiki.fandom.com/wiki/Lyceum
https://de.wowhead.com/npc=9956/flammenbewahrer-der-schattenschmiede#english-comments

according to this link and my memories of that time, the mobs respawned after 30 seconds.

Shadowforge Flame Keeper Respawn 10min ID 9956
Request Reservist Respawn 30 sec ID 8901

CURRENT BEHAVIOUR:
currently the respawn is 11 min at the Shadowforge Flame Keeper and the Anvilrage Reservist have 6 min respawn.

STEPS TO REPRODUCE THE PROBLEM:
.go creature 88904
kill the creature and make .npc info and look at the respawntime I measured it with stopwatch.

BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod transmog
mod_world_chat

**Comment by Pondaveia** [comment] 2019-05-02 14:51
## Here's the explanation to the re spawn being 30 seconds.

In theory It's impossible to set their re spawn rate to 30 seconds without touching the configuration files for the server.

Rank | Name | Default Respawn time | corpse decay time (worldserver.conf) | Spawntimesecs + worldserver.conf
-- | -- | -- | -- | --
0 | Normal | 5 min | 60 sec | 6 min
1 | Elite | 5 min | 5 min | 10 min
2 | Rare Elite | 5 min | 5 min | 10 min
3 | Boss | 5 min | 1 hour | 1 hour, 5 min
4 | Rare | 5 min | 5 min | 10 min


Respawn times can be modified in two other places: Creature.spawntimesecs (only for that single GUID of the creature) and in the worldserver.conf file under the "Corpse.Decay" settings (for ALL creatures of the same rank). The default `spawntimesecs` for all spawned creatures is 300 seconds (5 minutes). For example, using the ".npc add" command to spawn a "Normal" NPC will give it a default respawn time of 6 minutes (spawntimesecs + Corpse.Decay time). Also, the creature must decay first before it can respawn. For this reason, the Corpse Decay Time of the creature is also it's minimum respawn time, since setting the creature's Creature.spawntimesecs = 0 will remove the Default Respawn Time. In the example above, setting our Normal NPC's spawntimesecs = 0 will mean the creature's respawn time decreases from 6 minutes to 60 seconds.

[Click me to read trinity core documentation about respawn](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130008/creature+template)

So this means that we can set it at least to 60 seconds by running this query:

``` SQL
UPDATE `creature` SET `spawntimesecs` = 0 WHERE `id` IN (8901);
UPDATE `creature` SET `spawntimesecs` = 300 WHERE `id` IN (9956);
```

**Comment by Pondaveia** [comment] 2019-05-17 10:42
@Selyria Can you try the query above?

**Comment by Selyria** [comment] 2019-05-18 18:45
> @Selyria Can you try the query above?

So under 60 seconds, I can't get the spawn time right.

**Comment by JamesGent** [comment] 2020-11-27 17:22
Can confirm the issue is still live in master, however I can also confirm that the partial fix provided works. Recommended to integrate the partial fix into master branch and settle for 60 secs which isn't the blizzlike 30 secs but is better than 6 minutes.

![Desktop 27-11-2020 17-18-00-499](https://user-images.githubusercontent.com/61194190/100472852-f5cd3b00-30d4-11eb-91e3-a9ab9d1551b8.png)

**Comment by Zoidwaffle** [comment] 2021-02-20 22:59
I can confirm this has been merged as suggested above - so shouldn't this be closed, even though the fix isn't totally Bliz-like?

**Closed** 2021-02-21 00:40 UTC
Labels: Confirmed, Fix included, Instance - Dungeon - Classic, Priority - Low
