### ISSUE TITLE
[Achievement] Medium Rare 1311

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#19717] opened 2024-08-24 09:02 UTC
### Current Behaviour

![image](https://github.com/user-attachments/assets/d4d82caf-0f07-4bd9-9fb1-d0c7dbbcf4a8)

Killing elite mobs doesn't count!

### Expected Blizzlike Behaviour

Count elite mobs!

### Source

Achievement description

### Steps to reproduce the problem

Kill any elite mobs from the list, ex:
.go creature name Okrek
.go creature name Goretooth
.go creature name Fulgorge

### Extra Notes

https://www.wowhead.com/achievement=1311/medium-rare

### AC rev. hash/commit

AzerothCore rev. 337135bf9e40 2024-08-19

### Operating system

Debian 12

**Comment by sudlud** [comment] 2024-09-01 20:08
can't reproduce on 888aa00cfb51bbce968674a806a6beb02bdfd184

- ensure you have `.gm off`
- ensure you're on map `530`

with GM active or beeing on the wrong map, the achievement will not trigger.

If you still encounter this issue, please provide updated reproduction steps.

**Comment by TheSCREWEDSoftware** [comment] 2024-11-13 13:07
On `faea1c0735f1` can't reproduce this. Closing this

**Closed by TheSCREWEDSoftware** 2024-11-13 13:07 UTC
Labels: Invalid-Can't reproduce
