### ISSUE TITLE
Twillight mobs in The Master's Glaive [$15]

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4806] opened 2021-03-12 03:33 UTC
Originally reported https://github.com/chromiecraft/chromiecraft/issues/168

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

10-19

##### SMALL DESCRIPTION:

[Twilight Thugs](https://classic.wowhead.com/npc=2339/twilight-thug) and [Twilight Disciples](https://classic.wowhead.com/npc=2338/twilight-disciple) in The Master's Glaive zone tend to [disappear under textures](https://www.youtube.com/watch?v=vZtM6iM7vqs). 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should walk over the ground.

##### CURRENT BEHAVIOUR:

Mobs sometimes burrow beneath the textures, making them unlootable when killed.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Go to the Master's Glaive in Darkshore
Step 2 Pull some mobs, preferably those in water when You stand on slightly higher ground
Step 3 OR just watch them clip in the textures during their patrol routes.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment] 2021-03-27 10:59
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by Stifler82** [comment] 2021-03-27 11:35
Same problem: https://github.com/chromiecraft/chromiecraft/issues/215

**Comment by UltraNix** [comment] 2021-03-29 19:26
I believe it's fixed already by #4909. @Stifler82 could you retest? I cannot reproduce it.

**Comment by UltraNix** [comment] 2021-03-29 19:50
I cannot reproduce it - might be fixed by #4909.
@Stifler82 Could you retest it?

**Closed** 2021-04-01 15:37 UTC
Labels: 1-19, Bounty, CORE, ChromieCraft Generic, Confirmed, Priority - High, Priority - Medium, mmap/vmap
