### ISSUE TITLE
[server] world server crash 1003

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13254] opened 2022-10-03 14:59 UTC
### Current Behaviour

crash log:

https://gist.github.com/mpfans/6c804fd1e708f0d8a96a7f4274b433d8

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

6c3fc2603b46c84cd4334030f4bf7b57857e0241

### Operating system

Ubuntu20.04

**Comment by UltraNix** [comment] 2022-10-22 07:52
Duplicate of #13172

**Closed by UltraNix** 2022-10-22 07:52 UTC
Labels: Invalid-Duplicate, Priority-Critical, HasBacktrace
