### ISSUE TITLE
auth.account_banned bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6934] opened 2021-07-14 07:19 UTC
### Current Behaviour

ban an account to login for a period of time,during the ban period, it works normally
![20210714150912](https://user-images.githubusercontent.com/18187177/125579774-46de3cfc-3800-41e0-97c2-5b497176b49e.jpg)
After the ban time has expired, the player login ,after selecting the server list,will show the disconnection
![20210714151514](https://user-images.githubusercontent.com/18187177/125579532-a5ede6cd-c72f-45fc-95da-03d4a338e360.jpg)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1.For example, 10 minutes

> INSERT INTO `account_banned` (`id`, `bandate`, `unbandate`, `bannedby`, `banreason`, `active`) VALUES ('5', '1626246825', '1626247425', 'GM', 'test', '1'); 

 (This is based on the current time, the test needs to change the time)
2.Wait for the ban time, login to the game

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment] 2021-07-14 09:06
this bug is that when the  banned exceed the time limit, active is not changed to 0
if active =0  not disconnection

**Comment by r-o-b-o-t-o** [comment] 2021-07-14 09:17
Hello, this is a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6205
This should be fixed when the ACE dependency is removed

**Comment by mpfans** [comment] 2021-07-14 09:28
> Hello, this is a duplicate of #6205
> This should be fixed when the ACE dependency is removed

ok,tyvm!

**Closed** 2021-07-14 09:28 UTC
Labels: Invalid - Duplicate
