### ISSUE TITLE
Muradin incorrect dialogue

### ISSUE THREAD

**Issue by AldebaraanMKII** [azerothcore/azerothcore-wotlk#16752] opened 2023-07-14 02:37 UTC
### Current Behaviour

After the ship battle in icecrown citadel (which is not possible to complete without console commands btw) Muradin recites the Horde`s speech to the player as if he was Overlord Saurfang.
https://i.imgur.com/9ElhfIa.png

### Expected Blizzlike Behaviour

That he makes the Alliance speech.

### Steps to reproduce the problem

1. Finish the ship battle
2. Talk to Muradin in the ledge.

### AC rev. hash/commit

c843af3

### Operating system

Windows 10

**Comment by heyitsbench** [comment] 2023-07-14 02:42
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15132.

**Closed by heyitsbench** 2023-07-14 02:42 UTC
