### ISSUE TITLE
spell Insanity Boss Herald Volazj dungeons Ahn Kahel The Old Kingdom

### ISSUE THREAD

**Issue by fantomlancer** [azerothcore/azerothcore-wotlk#13116] opened 2022-09-24 13:23 UTC
### Current Behaviour

problem for spell Insanity Boss Herald Volazj dungeons Ahn Kahel The Old Kingdom its not working

### Expected Blizzlike Behaviour

Drive all players in the room to Insanity. During this time, players are phased and can't attack the Herald, but will be forced to fight 4 Twisted Visages. Used at 66% and 33% of Volazj's health left

### Source

https://www.wowhead.com/npc=29311/herald-volazj#abilities-normal-5-player

### Steps to reproduce the problem

Drive all players in the room to Insanity. During this time, players are phased and can't attack the Herald, but will be forced to fight 4 Twisted Visages. Used at 66% and 33% of Volazj's health left

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

windows 10

**Comment by LukasVolgger** [comment] 2022-09-24 14:41
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13068

**Closed** 2022-09-24 14:41 UTC
Labels: Invalid-Duplicate
