### ISSUE TITLE
Battleground Queue Announcer Spam

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#2220] opened 2019-08-17 14:56 UTC
Battleground Queue Announcer Spam

##### SMALL DESCRIPTION:

Battleground Queue Announcer Spam is very annoying, yet the best option to have enabled for small servers. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

<this is not a blizzard feature>

##### CURRENT BEHAVIOUR:

If someone spams the "join bg" button this can quickly occur:
https://cdn.discordapp.com/attachments/284323424032129024/612297498899382299/unknown.png

##### STEPS TO REPRODUCE THE PROBLEM:
 

1. Queue BG
2. Queue BG Again (spam the join bg button)
3. Watch this occur: https://cdn.discordapp.com/attachments/284323424032129024/612297498899382299/unknown.png

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

1d838ad78449+

**Comment by disclosurez** [comment] 2019-08-17 14:57
Suggested fix: 
Put a limit on this, so only sends message once per player in 30 seconds? (if someone try to spam it)

**Comment by FrancescoBorzi** [comment] 2019-08-17 14:58
tagging @Winfidonarleyan and @mik1893 , since they worked recently with BGs.

**Comment by disclosurez** [comment] 2019-08-21 19:18
Not sure if this code is working properly?



```
 else if (!bg->isArena()) // Show queue status to server (when joining battleground queue)
    {
        if (BGSpamProtection[leader->GetGUID()].last_queue == 0)
        {
            BGSpamProtection[leader->GetGUID()].last_queue = sWorld->GetGameTime();
            sWorld->SendWorldText(LANG_BG_QUEUE_ANNOUNCE_WORLD, bgName, q_min_level, q_max_level,
                qAlliance + qHorde, MaxPlayers);
        }
        else if (sWorld->GetGameTime() - BGSpamProtection[leader->GetGUID()].last_queue >= 30)
        {
            BGSpamProtection[leader->GetGUID()].last_queue = 0;
            sWorld->SendWorldText(LANG_BG_QUEUE_ANNOUNCE_WORLD, bgName, q_min_level, q_max_level,
                qAlliance + qHorde, MaxPlayers);
        }
    }
```

**Comment by milestorme** [comment] 2019-08-21 20:34
This was spamming before cfbg on que . I disabled it

**Comment by wizzymore** [comment] 2019-09-21 22:37
Hi, i can confirm that this is a bug.

But it occurs only two times(two texts every 30 seconds) if the button is spammed and the BG icon is not assigned to the respective BG

**Closed** 2019-10-06 17:34 UTC
