### ISSUE TITLE
Rest not triggering in Honor Hold Inn (and other inns)

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4090] opened 2020-12-29 07:36 UTC
.go -702 2721 94 530 

Check your state

![20201229153315](https://user-images.githubusercontent.com/18187177/103266929-98861b80-49eb-11eb-912d-f8f4e4079fb2.png)

**Comment by FrancescoBorzi** [comment] 2020-12-29 09:47
@mpfans please include your AC version (commit hash) when reporting an issue

**Comment by mpfans** [comment] 2020-12-29 09:51
> @mpfans please include your AC version (commit hash) when reporting an issue

sry... i forgot

 AzerothCore revision            : 96c7d423806c+ 2020-12-24 02:48:51 +0000 (master branch)
OS:ubuntu 18.04

**Comment by Kitzunu** [comment] 2020-12-29 12:45
@Meltie2013

**Comment by Meltie2013** [comment] 2020-12-29 13:09
@mpfans I checked the inn and it seems the area trigger id might not be correct. I checked the inn over at Thrallmar and its working just fine.

**Comment by mpfans** [comment] 2020-12-29 14:08
supplement:
When you use the hearthstone to return to the Honor Hold Inn, you can get a rest
When you walk into Honor Hold Inn, you don't get any

**Comment by Meltie2013** [comment] 2020-12-29 14:09
@Kitzunu @BarbzYHOOL @FrancescoBorzi @mpfans 
Well found the problem, well a number of them. With how area triggers are handled in the project, no wonder most Inn are not working. One issue for Honor Hold Inn, it was no radius in the database as shown below.

![image](https://user-images.githubusercontent.com/5354732/103289345-95b80600-49ac-11eb-806e-e2ad5ab81f4f.png)

Second, hard coding values for area triggers isn't the most bright idea. Values should be taken from the DBCs, not placed in a database.

**Comment by Meltie2013** [comment] 2020-12-29 14:19
Changing the radius value to 35, flag is applied in the Inn as shown below. Found over 30+ Inns affected by this.
![WoWScrnShot_122920_081822](https://user-images.githubusercontent.com/5354732/103290189-8df96100-49ae-11eb-9b10-8d7d1c5d263c.jpg)

**Comment by BarbzYHOOL** [comment] 2020-12-30 00:36
very interesting, have u compared the values to the dbc ones Meltie?

**Comment by BarbzYHOOL** [comment] 2020-12-30 01:13
so maybe need to fix all the 37 inns listed above with a "custom" radius value?
However Meltie told me the DBC have same value for the inn radius and that it works fine on his TC based core... so that might not be the best method to follow

@Yehonal  here are the PRs that lead to this (in order to fix another bug ofc):
- https://github.com/azerothcore/azerothcore-wotlk/pull/3985

**Comment by FrancescoBorzi** [comment] 2021-01-30 15:37
@BarbzYHOOL @Meltie2013 what's the status of this? should we revert the changes that broke it? We can't just leave this broken. Also why assigned to Yehonal?

**Comment by Kitzunu** [comment] 2021-01-30 15:41
There are two ways to quickly solve this.
1. Revert and go back to the other bugs
2. Hackfix it with radius

**Comment by Meltie2013** [comment] 2021-01-30 15:59
@FrancescoBorzi @Kitzunu Since the radius check is ignoring DBC values, you kind of have to add the radius into the database for it to work as I stated above. The current system is just garbage on how its done honestly.

**Comment by Yehonal** [comment] 2021-01-30 16:03
I'm going to debug it a little bit and reading your posts, since I noticed the issue is larger than I thought. Looks like that a lot of areas around the world are broken, and even some bosses in end-game raids are having issues with the areas.

But I've a question: @Meltie2013 if you know that the current system is a garbage as you said, and that your changes impact on it. Shouldn't they be still in WIP?

**Comment by Meltie2013** [comment] 2021-01-30 16:09
@Yehonal Was fixing the Inn Flag issues at the time, which shouldn't affect the radius checks and some how did. After the issue was brought up, I started looking into the radius system and found more issues. I didn't start working on another PR, just don't have the time for it currently.

About the PRs I made, they were being pushed to fast to my knowledge. At the time, this issue was being found during the WIP stage.

**Comment by Yehonal** [comment] 2021-01-30 16:20
I'm here: .go -702 2721 94 530 and I have the rest/inn flag.

I cannot reproduce this issue, can you test this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/4220 ?

Or giving me more info on how to test it?

**Comment by BarbzYHOOL** [comment] 2021-01-30 17:33
> @BarbzYHOOL @Meltie2013 what's the status of this? should we revert the changes that broke it? We can't just leave this broken. Also why assigned to Yehonal?

cause yehonal asked me in staff for the pr, i linked it 2 times and he said thanks, then he had no time so i reminded him here ^^



> There are two ways to quickly solve this.
> 
>     1. Revert and go back to the other bugs
> 
>     2. Hackfix it with radius

yeah if we can't find better, also, the initial bug was trivial 

> and even some bosses in end-game raids are having issues with the areas.

which issues??

---

@mpfans can you test what yehonal said above?

**Comment by mpfans** [comment] 2021-01-31 15:06
AC commit : c9b46beae276d8990cea7935609d4a8461d40bf3

This bug has been fixed, but I don't know which commit fixed it

**Comment by FrancescoBorzi** [comment] 2021-01-31 15:48
that's good news! thanks for letting us know @mpfans

**Closed by FrancescoBorzi** 2021-01-31 15:48 UTC
Labels: CORE, Priority - High

**Comment by BarbzYHOOL** [comment] 2021-02-01 20:16
@FrancescoBorzi @mpfans @Yehonal seems like Yehonal's PR has been merged and may be related as he pointed it out

**Comment by FrancescoBorzi** [comment] 2021-02-01 23:31
no, it was merged after mpfans' comment. But maybe he already had the PR running

**Comment by BarbzYHOOL** [comment] 2021-02-02 00:20
@FrancescoBorzi hmm ok weird... i fear that will be reopened later :D
