### ISSUE TITLE
Hanging Head of Nefarian in Orgrimmar/Stormwind Disappears after 2 Min !!!

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1728] opened 2019-04-18 14:00 UTC
##### SMALL DESCRIPTION:

The hanging head of Nefarian in Stormwind disappears after about 2 min of player handing in the quest and getting the buff.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The head should display for 2 hours as agreed in https://github.com/azerothcore/azerothcore-wotlk/pull/1662.

##### CURRENT BEHAVIOUR:

The head disappears after hanging/on spike for 2min from BOTH Stormwind & Orgrimmar.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .use an Alliance character and then .additem 19003 or Horde character and then .additem 19002
2. start the quest from the item
3. follow the quest through
4. by the end you will see the head disappears after about 2 min of displaying.

##### EXTRA NOTES:

This had no issues during the PR, but after merging, both Horde and Alliance version of the head on display disappear after about 2 min. The timer should be 7200000 from memory. Was it somehow incorrectly set ?

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

7eb703e

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by Pondaveia** [comment] 2019-04-18 14:22
Now that this was merged and there are no differences, [the issue is here](https://github.com/azerothcore/azerothcore-wotlk/pull/1711/commits/0eb7c925304f5bc35804b487c867b575db50adeb#diff-cf39a49f4983fdb205b45e0e58d66247R7).

As you can see it has been merged with 2 minutes because this that Falstring said is wrong:

> This is wrong. It is measured in seconds. Feel free to test yourself. Documentation says seconds and I also tested this. It despawned after 2 hours.
> 
> I also removed a line from the original that you made, which wasn't necessary

On SAI everything you set is in **Milliseconds** and not **seconds**.

FIX:

```
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `id`=3;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,3,0,0,0,100,0,3000,3000,0,0,50,179882,7200000,1,0,0,0,8,0,0,0,-8925.57,496.042,103.767,2.42801,'Field Marshal Afrasiabi - On Script - Summon Gameobject The Severed Head of Nefarian and despawn after 2 hours');
```

If you can't do the math, this website will convert milliseconds to hours:
https://www.timecalculator.net/milliseconds-to-hours

**Comment by poszer** [comment] 2019-04-18 14:24
> Now that this was merged and there are no differences, [the issue is here](https://github.com/azerothcore/azerothcore-wotlk/pull/1711/commits/0eb7c925304f5bc35804b487c867b575db50adeb#diff-cf39a49f4983fdb205b45e0e58d66247R7).
> 
> As you can see it has been merged with 2 minutes because this that Falstring said is wrong:
> 
> > This is wrong. It is measured in seconds. Feel free to test yourself. Documentation says seconds and I also tested this. It despawned after 2 hours.
> 
> On SAI everything you set is in **Milliseconds** and not **seconds**.
> 
> FIX:
> 
> ```
> DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `id`=3;
> INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
> (@ENTRY,9,3,0,0,0,100,0,3000,3000,0,0,50,179882,7200000,1,0,0,0,8,0,0,0,-8925.57,496.042,103.767,2.42801,'Field Marshal Afrasiabi - On Script - Summon Gameobject The Severed Head of Nefarian and despawn after 2 hours');
> ```
> If you can't do the math, this website will convert milliseconds to hours:
> https://www.timecalculator.net/milliseconds-to-hours

Nope, he's right. It's summoned go ( it's use seconds as timing for despawn ). 
Force despawn is in miliseconds. I'll fix this in some minutes

**Closed** 2019-04-22 01:06 UTC
