### ISSUE TITLE
[ICC]: LK does not reset event

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15388] opened 2023-03-14 21:16 UTC
### Current Behaviour

When you get to the encounter with the LK and die in any of its phases, it does not restart the event. For example, some things that happen when the event is not restarted are:

- Tirion Vadin, remains frozen in the grave.
- Lk sometimes doesn't show up again and when he shows up he stands on the throne and if you get close he fights you immediately.
- The platform columns that disappear in the 2nd phase do not reappear.
- The floor that spawns between stages does not spawn again.
- In the 3rd phase it does not fit for the sword.

### Expected Blizzlike Behaviour

when you die it should reset the event normally.
Tyrion should unfreeze and be able to talk to him again to start the event, the event platform must be restored, arthas must appear frozen on the throne, if you approach arthas the fight should not start, in the 3rd phase the sword must enter the game

### Steps to reproduce the problem

1. Go ICC
2. Go LK
3. start combat and die in one of its phases
4. revive and see how the event was again

### Extra Notes

@Nyeriah This happened to me after I updated with the Pr https://github.com/azerothcore/azerothcore-wotlk/pull/14789

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6a66b36a5d5cba8bab9fb62e0e0680cd5c94c4ab

### Operating system

Ubuntu 20.04

**Comment by boom8866** [comment] 2023-03-16 05:39
The problem exists

**Comment by Kitzunu** [comment] 2023-03-16 09:40
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15379

**Closed by Kitzunu** 2023-03-16 09:40 UTC
