### ISSUE TITLE
Not working cfg with GridUnload

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2069] opened 2019-07-07 05:53 UTC
Description: Unload grids to save memory. Can be disabled if enough memory
set GridUnload = 0 but change does not apply !

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/6db0a438d9dff3d1fab5f904657ed281f5dee6c7

OS: windows 2017

MODULES:
Anticheat

**Comment by poszer** [comment] 2019-07-11 18:33
@Winfidonarleyan :eyes:

**Comment by wowmane** [comment] 2019-07-11 22:12
For test

1. set to GridUnload = 0
2. gm, mod speed and fly on and move to maps
3. memory will to leak for enter character to the maps, "Grids"

disable, does not work.

**Comment by Stoabrogga** [comment] 2019-07-11 22:59
GridUnload = 0 means that the grids will **not** unload, so it is normal to increase memory usage. You have to set GridUnload = 1 in order to decrease memory usage.

**Comment by milestorme** [comment] 2019-07-12 02:50
This system works been playing with it disabled and enabled to test all these so called memory leaks, you should make sure you have no custom modifications to your core that are causing all these unrepeatable issues

**Comment by wowmane** [comment] 2019-07-12 06:08
#
#    GridUnload
#        Description: Unload grids to save memory. "Can be disabled if enough memory" is available
#                     to speed up moving players to new grids.
#        Default:     1 - (enable, Unload grids)
#                     0 - (disable, Do not unload grids)

GridUnload = 0

**Comment by wowmane** [comment] 2019-07-12 06:13
@Stoabrogga 

I think this bug is not for this, GridUnload changed to 1 but again tested and move to maps memory leak For each map!

**Comment by Stoabrogga** [comment] 2019-07-12 07:42
I think the error is on your side. I tested this for months and have no issues, the parameter is working as intended. @milestorme and many others told the same.

You have to take into account that it takes 5 minutes (default value) to unload grids once they were visited by a player, and there are a few grids which never unload, like transports or grids with NPC activity which has to take place even if no player is near.

**Comment by wowmane** [comment] 2019-07-12 07:59
@Stoabrogga , Thank You.

But this is fixed on the Trinitycore!

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L1292

Can you create a part to reduce memory?

**Comment by Stoabrogga** [comment] 2019-07-12 08:41
This has nothing to do with AC. As far as I know TC uses another technology for communication. Although AC and TC were the same years ago we are now talking about two different projects here, with each one taking a different way concerning conception and further development. Is this really so hard to understand?

**Comment by wowmane** [comment] 2019-07-12 09:10
@Stoabrogga 

Action must be taken to reduce memory.
Is this wrong? Is not it possible?

For better quality. AC

**Comment by milestorme** [comment] 2019-07-12 09:26
Memory works well you making up issues that don’t exist azerothcore is super stable has no memory leaks , ( many of us have tested) trinitycore is where I came from, in my personal experience it was unstable and under developed (not point fingers it’s just a fact I my experienced) since transferring here I notice half the issues I had before have been sorted or don’t exist and can’t be repeated in an Un modified azerothcore, I get no crash’s and absolutely no memory leaks , the way the cores are utilised for larger server performance is really amazing. I suggest removing any custom content , using only tested azerothcore moduless and enjoying the great performance from this core

**Comment by BarbzYHOOL** [comment] 2019-08-04 23:29
wowmane i think you should upgrade your server, economize 10$ per month and upgrade your server so you will stop worrying about your 256mb ram

**Closed** 2019-08-04 23:29 UTC
Labels: Not confirmed
