### ISSUE TITLE
Pit of Saron - Trash mobs problem

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#862] opened 2018-05-11 05:22 UTC
**Description**: Mobs after second boss, that come for event to 'block' free passage, drop under ground every single time.

**Current behaviour**: For some reason, they drop under texture, and keep agrro players from there.

**Expected behaviour**: They should stay at the top, so they can attack and kill them. Unable due LoS.

**Steps to reproduce the problem**: Not sure.

**Hash**: 7696bd3

**Operating system**:  Linux, Debian 9

**Modules**:  Premium, Congrats on level.

**Other Customizations**: No.

Pic: https://i.imgur.com/fD27U9Z.jpg

**Comment by Motorheadx** [comment] 2018-05-11 11:52
Steps to reproduce the problem: just enter the battle from far away and they fall when they go down

**Comment by Deku** [comment] 2018-05-11 12:09
Can confirm. That said, you still can walk down the ramp and get them from bellow the road

PD: for clarity, these ones 
![pit-of-saron-dungeon-map](https://user-images.githubusercontent.com/800655/39923625-77d03b46-54f2-11e8-9b07-8ef9a2c4d0a1.jpg)

**Comment by sucofog** [comment] 2018-05-11 12:49
Confirmed

**Comment by Motorheadx** [comment] 2018-05-11 13:13
I think this is some global problem

**Comment by Viste** [comment] 2018-05-13 07:59
Confirmed

**Comment by talamortis** [comment] 2018-05-13 09:48
This didnt happen before the maps,mmaps and vmaps got reworked

**Comment by Motorheadx** [comment] 2018-05-13 10:06
it's in the original sunwellcore

**Comment by BarbzYHOOL** [comment] 2018-05-13 11:14
And original sunwellcore has no mmaps reworked

**Comment by Motorheadx** [comment] 2018-05-13 11:33
Yes, this problem is not due to mmaps rework, this something else=)

**Comment by sucofog** [comment] 2018-05-14 18:31
The problem is not on the maps/vmaps/mmaps rework, not related

**Comment by Viste** [comment] 2018-05-16 22:56
@talamortis its sunwell global problem
and @Motorheadx right i agree it somewhere in Movespline

**Comment by sucofog** [comment] 2018-05-17 09:25
Yes, the problem is on MoveSpline, same happens when you charge with warriors against any mob, this is fixed on TC master

**Comment by Motorheadx** [comment] 2018-05-17 13:42
I ran some tests and realized that the problem is really npc 36892.In the file pit_of_saron for fun, I changed the npc to another 36830 it no longer fell.Then I tried to create my monster and just put it in the code and it worked fine, maybe where the error is with npc 36892 but I can't figure out where exactly I tried to disable SmartAI all the same it fell after that

**Comment by pondaveia** [comment] 2018-05-24 09:55
I've seen this happen when I scripted waypoints for any npc. If the waypoint was too long the mob simply calculated the closest path to the next point which made him clip with textures. Also on climbs this usually happens aswell so got to use more points to avoid this. It's almost as if the diff variable blew up.

This can probably be hotfixed/hacked with simply using more waypoints even though it isn't an optimal fix.

Note: In some textures we can also find pets clipping with terrain or standing way above it when they should just be standing on them.

**Comment by Motorheadx** [comment] 2018-05-24 10:28
it's not about waypoints, it's a great way to move around on points, it starts to fall during the battle when it stops to cast a spell

**Comment by Nefertumm** [comment] 2018-06-12 20:29
https://github.com/TrinityCore/TrinityCore/pull/5649/files this may help with this problem?

**Comment by BarbzYHOOL** [comment] 2018-06-12 20:39
We already have it https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Object/Object.cpp

**Comment by BarbzYHOOL** [comment] 2018-07-18 21:36
Can someone confirm with the newest commit and mmaps? 8e9faf848865769d8e1d851889f04eae07fb976a

**Comment by Motorheadx** [comment] 2018-08-11 16:01
I checked the new mmaps do not fix this problem

**Comment by mynew4** [comment] 2019-01-04 13:52
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp#L101
I think the problem is from here.

**Closed** 2020-12-01 16:58 UTC
Labels: Confirmed, Priority - High
