### ISSUE TITLE
Things that should still be fixed Deadmines

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1809] opened 2019-05-07 10:03 UTC
SMALL DESCRIPTION:

I still have the memory of classic that when you kill the first 3 bosses in the deadmines spawn behind you and patrol back and forth who still has it right in his head from 1 boss after the door to 2 boss behind the door so always run from boss to boss this 

After looting the Defias Gunpowder an npc should appear that doesn't happen

Captain Greenskin walks alone the two npc just stand around

EXPECTED BLIZZLIKE BEHAVIOR:

Note: Every time you kill a boss (up to Gilnid|Boss), the door he was guarding opens up, and a patrol respawns behind you and heads down towards you. After every boss fight this will happen, and the further you go down in the Deadmines, the bigger the patrols will be. So be on your guard and look behind you every now and then. The patrols are a mix of melee and spellcasters.

Example 1: Between the entrance and Rhahk'zor, there is a Devias Evoker and Devias Overseer that patrol to the boss room and into the previous caves (unsynced). These two patrollers are probably intended to spawn with the ogre's death. I think these patrols should be removed and set to spawn and patrol after the ogre's death.

Example 2: Between Sneeds room and Ogre's room. There is one Defias Overseer and Evoker that pat unsynced to sneed's room and back. As seen in the video above (3:14), these patrols should spawn with sneed's death, and patrol synchronously.

Example 3: The goblin foundry and after sneeds room. There are quite a few human elites in the goblin foundry, many of which are patroling through 2-3 goblin packs. This is obviously not correct, as a level appropriate group would be pulling 5-6 elites at once. Two defias taskmasters and a defias wizard are patrolling here, they should be spawned on gilnid's death and patrol from after sneed until gilnid's door. 

Defias Gunpowder

Looting the Defias Gunpowder should spawn a Defias Taskmaster behind the party, and aggro onto the player who looted the powder. Proof: http://wowpedia.org/Deadmines_walkthrough "the [Defias Gunpowder] as shown on the map above, and have someone loot it, but be aware that looting it causes a Defias Taskmaster to spawn in the corridor."

Captain Greenskin

The Defias Pirate and Defias Squallshaper should patrol in sync with Greenskin (see https://www.youtube.com/watch?v=bbh54CIGCj8 @ 1:35). They currently do not. Side note: In this video, VC's portrait is Rare?

https://vanilla-wow.fandom.com/wiki/Deadmines_walkthrough
https://classic.wowhead.com/guides/deadmines-classic-dungeon See here under Dungeon Patrols
https://vanilla-twinhead.twinstar.cz/?issue=3119 Should be correct is a long time ago but seems familiar to me

CURRENT BEHAVIOUR:
After looting the Defias Gunpowder an npc should appear that doesn't happen
Nothing comes there are also no spawn set or other it is missing completely
Captain Greenskin walks alone the two npc just stand around

STEPS TO REPRODUCE THE PROBLEM:
.go creature 79168

BRANCH(ES):
AzerothCore rev. 7188fa0f68f4+ 2019-05-04 06:58:25 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod transmog
mod_world_chat

**Comment by poszer** [comment] 2019-05-07 14:25
> EXPECTED BLIZZLIKE BEHAVIOR:
> 
> Note: Every time you kill a boss (up to Gilnid|Boss), the door he was guarding opens up, and a patrol respawns behind you and heads down towards you

Actually this isn't blizzlike for Gilnid. As you can see on this video everything:
https://www.youtube.com/watch?v=U9jeFJkenX0

Van Cleef

VC comes with two blackguards, which is correct. He summons two blackguards at 50% which is also correct. However, at around 25% he summons an additional two blackguards. Evidence suggests he should only spawn one set of guards at 50%.   - This is correct on AC

Also for Defias Gunpowder, while looting it it say this : 

> Loot the gunpowder from a small Defias Gunpowder barrel. This allows you to fire the cannon which eliminates the door and spawns an elite patrol (which can take a group by surprise if not careful) to investigate the noise from beyond the door.
And i have tested this, after you eliminate the door, there is some text, and creatures are going at the door to investigate the noise. So, this working fine.


As you can see on this video also: While looting this gunpoweder there isn't nothing spawned behind player https://youtu.be/rCmsbgZIKLA?t=176


For this Captain Greenskin, i can confirm this creature patrol solo. Will check it later 

> Captain Greenskin
> 
> The Defias Pirate and Defias Squallshaper should patrol in sync with Greenskin (see https://www.youtube.com/watch?v=bbh54CIGCj8 @ 1:35). They currently do not. Side note: In this video, VC's portrait is Rare?

So, how i can see from everything, this should be checked, and imported 2 more creatures to patrol with him:

- [ ] Captain Greenskin should patron with The Defias Pirate and Defias Squallshaper
 
P.S Any information about this is welcome. So, go on and write/report :smiley:

**Comment by Seebaby** [comment] 2019-05-11 13:59
So Nostralius has been a very good blizzlike server 

I've looked around a little bit again and will post the posts times where you can see my stuff I meant

https://youtu.be/zPJJ8GpIiEM?t=491 The Pat which appear after killing the bosses from behind it takes of course until they are there because they usually run a long way these spawnen not right behind the player but run through the cleaned rooms where you had fought through. That was the first 3 bosses so I'm really sure.

Here the one with the watch at the powder looten was not to be seen with her video because there is only run through.

https://youtu.be/zPJJ8GpIiEM?t=1960 There you see the Pat which appears after you have soldered the powder.

**Comment by Seebaby** [comment] 2019-05-11 23:06
So I searched deep on the internet and found old excerpts from the World of Warcraft books of Classic and your instances.

At the Deadmines I found a contribution that there are the PATROLS after the bosskills I will post the left times here it is a Pdf document.

Page 6 and 7 are the decisive ones 

http://ptgmedia.pearsoncmg.com/imprint_downloads/brady/wow/deadmines/Deadmines%20HRBW.pdf

**Comment by Viste** [comment] 2019-05-12 05:08
nostalrius video like a proof for wotlk gameplay perfect!

**Comment by Seebaby** [comment] 2019-05-12 16:14
> https://wowwiki.fandom.com/wiki/Patches/1.x
> search video from retail WOTLK or BC or Vanila(when you sure with patches nothing changes)?

I think you can never be sure I can just say I'm sure nothing has happened up to Cata in the Deadmines. Would also be a bit stupid of Blizzard to just take the PATROLS out of play.

**Comment by poszer** [comment] 2019-06-14 13:38
Left to close issue :

- [ ] The Defias Pirate and Defias Squallshaper should patrol in sync with Greenskin (see https://www.youtube.com/watch?v=bbh54CIGCj8 @ 1:35). They currently do not. Side note: In this video, VC's portrait is Rare?

**Comment by Selyria** [comment] 2019-06-15 13:29
> Left to close issue :
> 
> * [ ]  The Defias Pirate and Defias Squallshaper should patrol in sync with Greenskin (see https://www.youtube.com/watch?v=bbh54CIGCj8 @ 1:35). They currently do not. Side note: In this video, VC's portrait is Rare?

I don't remember ever seeing an endboss rare or finding any information on the internet that vancleep was ever rare.

**Comment by Voxstrasza** [comment] 2020-11-28 04:50
I went in and tested this on `37d1f2be4729` and the Taskmaster spawns when clicking on the gunpowder, and the NPCs patrol with Captain Greenskin in sync.  Closing this issue as the OP's problems have been fixed, although Sneed's door doesn't open after he dies - should be an easy fix by replicating the first bosses code.

**Closed by Voxstrasza** 2020-11-28 04:50 UTC
Labels: Instance - Dungeon - Classic, Priority - Low
