### ISSUE TITLE
Multiples Compilation Bug!

### ISSUE THREAD

**Issue by Open-Wow** [azerothcore/azerothcore-wotlk#2471] opened 2019-11-27 22:39 UTC
Multiples Compilation Bug!

##### SMALL DESCRIPTION:

I tried to compile the latest version of AC with the Eluna module, it's not the first time I've done it but it's the first time I've had so many mistakes

##### CURRENT BEHAVIOUR:

https://cdn.discordapp.com/attachments/625589186958852096/649378461902831647/unknown.png
https://cdn.discordapp.com/attachments/625589186958852096/649378489228853258/unknown.png

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just install mod-eluna
2. Visual Studio 2019 Community
3. MariaDB ?

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

71f5c96

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

mod-eluna

**Comment by Viste** [comment] 2019-11-28 00:52
for success build you need https://github.com/azerothcore/azerothcore-wotlk/pull/2454 and https://github.com/azerothcore/azerothcore-wotlk/pull/2455

**Comment by FrancescoBorzi** [comment] 2019-11-28 08:52
@Open-Wow please let us know if those PRs work for you so we can merge them

**Comment by Open-Wow** [comment] 2019-11-28 09:19
So this is the first time I've done this, sorry I didn't do the right thing.

So to test the PR's I made the order:
git fetch upstream pull/2454/head:Viste-rename
git checkout Viste-rename

git fetch upstream pull/2455/head:Viste-strings
git checkout Viste-strings

Apparently during the generation it improved the mistakes but I still have some, but much less.

https://zupimages.net/up/19/48/kpiu.png

**Comment by Stoabrogga** [comment] 2019-12-02 10:43
The issue is resolved now as these PRs got merged:
https://github.com/azerothcore/azerothcore-wotlk/pull/2454
https://github.com/azerothcore/azerothcore-wotlk/pull/2455
https://github.com/azerothcore/mod-eluna-lua-engine/pull/21

**Closed by Stoabrogga** 2019-12-02 10:43 UTC
