### ISSUE TITLE
[Raid] Karazhan - Prince Malchezaar infernal spawn

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#2635] opened 2020-02-02 21:28 UTC
##### SMALL DESCRIPTION:

There is a little bug with infernal spawner in script, sometimes it spawns infernals outside the combat area (outside map)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Infernals should be spawned in combat area available to players.

##### CURRENT BEHAVIOUR:

Basically described in small description.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .go c prince_malchezaar
2.  Pull the boss
3.  Wait for several Netherspite Infernal spawns

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

8cfdfd0

##### OPERATING SYSTEM:

Win 10 x64

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by gengarshadowball** [comment] 2020-02-03 19:47
Sorry I couldn't reproduce this bug. I fought him for a solid 10 minutes hugging the walls and in the middle and all of them spawned correctly. Can you maybe be more specific with the spots?

**Comment by markvetwow** [comment] 2020-02-04 18:16
Hmm, i'm sorry, it's kinda strange. Checked it again solo, and it's working correctly now.

When this "bug" appeared the first time, there was a 3 players -> Shaman, Paladin and Mage. So, basically what happened is that infernals was landing just outside the borders, so the aoe couldn't make any dmg to us. I don't really know how to reproduce this, but somehow it happened, if only i had a video..

**Comment by gengarshadowball** [comment] 2020-02-04 21:05
I'll try to reproduce with a group!

**Comment by Si1ker** [comment] 2020-02-19 21:13
Tested, not confirmed.

* 5 accounts for 10 minutes against him = Unable to reproduce the issue
* Only me against him for 10 minutes = Unable to reproduce the issue
* 3-4 infernals at the same time in both fights

![2020-02-19 15_05_46-Window](https://user-images.githubusercontent.com/61223313/74876741-d6c1a180-5329-11ea-9cb5-a30772c7445f.png)
![2020-02-19 15_06_42-Window](https://user-images.githubusercontent.com/61223313/74876744-d75a3800-5329-11ea-92ce-4ca757aee2a7.png)

The rarest I found was still inside the area, in the border:
![2020-02-19 15_07_57-Window](https://user-images.githubusercontent.com/61223313/74876745-d7f2ce80-5329-11ea-8894-2fa5d18d92b6.png)

**Comment by Helias** [comment] 2020-02-20 06:42
I am closing this issue until anyine reproduce that.
Be sure to have extracted the vmaps and mmpas correctly.

**Closed by Helias** 2020-02-20 06:42 UTC
Labels: Not confirmed
