### ISSUE TITLE
DBERRORS

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1214] opened 2019-01-01 17:23 UTC
##### SMALL DESCRIPTION:

There are several problems related to the database, the loading of the server but also during the use.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

no database errors

##### CURRENT BEHAVIOUR:

> 2019-01-01 16:35:09 Table 'mail_loot_template' Entry 90 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 119 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 124 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 140 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 180 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 183 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 216 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 217 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 218 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table 'mail_loot_template' Entry 270 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 16:35:09 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4989 Type: 19), ignored.
2019-01-01 16:35:09 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4988 Type: 19), ignored.
2019-01-01 16:35:09 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5620 Type: 73), ignored.
2019-01-01 16:35:09 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5632 Type: 73), ignored.
2019-01-01 16:35:09 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5619 Type: 73), ignored.
2019-01-01 16:35:09 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4987 Type: 19), ignored.
2019-01-01 16:35:11 Table `spell_scripts` using non-existent spell (id: 0) in SCRIPT_COMMAND_CAST_SPELL for script id 16805948
2019-01-01 16:35:11 Table `spell_scripts` using non-existent spell (id: 0) in SCRIPT_COMMAND_CAST_SPELL for script id 16831313
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 90 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 119 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 124 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 140 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 180 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 183 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 216 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 217 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 218 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:38 Table 'mail_loot_template' Entry 270 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:12:39 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4989 Type: 19), ignored.
2019-01-01 17:12:39 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4988 Type: 19), ignored.
2019-01-01 17:12:39 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5620 Type: 73), ignored.
2019-01-01 17:12:39 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5632 Type: 73), ignored.
2019-01-01 17:12:39 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5619 Type: 73), ignored.
2019-01-01 17:12:39 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4987 Type: 19), ignored.
2019-01-01 17:12:41 Table `spell_scripts` using non-existent spell (id: 0) in SCRIPT_COMMAND_CAST_SPELL for script id 16805948
2019-01-01 17:12:41 Table `spell_scripts` using non-existent spell (id: 0) in SCRIPT_COMMAND_CAST_SPELL for script id 16831313
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 90 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 119 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 124 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 140 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 180 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 183 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 216 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 217 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 218 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:35 Table 'mail_loot_template' Entry 270 isn't mail template id and not referenced from loot, and thus useless.
2019-01-01 17:21:36 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4989 Type: 19), ignored.
2019-01-01 17:21:36 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4988 Type: 19), ignored.
2019-01-01 17:21:36 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5620 Type: 73), ignored.
2019-01-01 17:21:36 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5632 Type: 73), ignored.
2019-01-01 17:21:36 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5619 Type: 73), ignored.
2019-01-01 17:21:36 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4987 Type: 19), ignored.
2019-01-01 17:21:38 Table `spell_scripts` using non-existent spell (id: 0) in SCRIPT_COMMAND_CAST_SPELL for script id 16805948
2019-01-01 17:21:38 Table `spell_scripts` using non-existent spell (id: 0) in SCRIPT_COMMAND_CAST_SPELL for script id 16831313
> 

##### STEPS TO REPRODUCE THE PROBLEM:

1. lunch the server
2. see dberror.log
3. play
4. see dberror.log

##### BRANCH(ES):

master

**Comment by wetbrownsauce** [comment] 2019-01-01 19:42
Duplicate of:
#1156 
#1155 
#1154 
#1152

**Comment by FrancescoBorzi** [comment] 2019-01-01 20:13
@wetbrownsauce when duplicate you can close it ;)

**Comment by wetbrownsauce** [comment] 2019-01-01 20:13
I didn't know I was able lmao

**Closed by FrancescoBorzi** 2019-01-01 20:13 UTC

**Comment by BarbzYHOOL** [comment] 2019-01-01 20:40
haha apparently now you can
