### ISSUE TITLE
Suggestion: GM Command to modify unit_flags of a particular creature while worldserver is running and not save to DB

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#15198] opened 2023-02-25 16:44 UTC
### Describe your feature request or suggestion in detail

On runtime it could be useful while debugging to be able to add and remove unit_flags by command.

### Describe a possible solution to your feature or suggestion in detail

.npc set flags temp add XXXX
.npc set flags temp remove XXXX

Since it's bitmask it'd be useful to modify multiple flags at once.
.npc set flags temp remove 768 would remove 512 and 256

Maybe another command for flags2 as well?

**Comment by Nyeriah** [comment] 2023-02-27 02:09
Apparently `debug update` already does this

![image](https://user-images.githubusercontent.com/47818697/221455556-98ea4ea8-f1c0-4616-985c-958c0886430d.png)

Or at least was intended to. We just need to supply the field index for the unit_flags, which is 59

```.debug update 59 #flag```

**Comment by Nyeriah** [comment] 2023-02-28 01:22
Just confirmed that the above works, gonna close this seeing how it is already implemented. Perhaps better documentation is needed

**Closed by Nyeriah** 2023-02-28 01:22 UTC
Labels: Suggestion
