### ISSUE TITLE
(DB/Creature): Doras <Wind Rider Master>

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2872] opened 2020-04-11 09:16 UTC
https://www.wowhead.com/npc=156845/ 
There are two of them, not one. 

STEPS TO REPRODUCE THE PROBLEM:
Teleport to Doras.
BRANCH(ES): master

AC HASH/COMMIT: AzerothCore rev. 9c8c5ea8ff43+ 2020-04-08 23:45:58 +0000
OPERATING SYSTEM: Debian 9
MODULES: Anticheat, ResetDuel

**Comment by Maurowin** [comment] 2020-04-11 09:23
Can u respect theses rules http://www.azerothcore.org/wiki/How-to-ask-for-help
And not delete issue form :

`








##### SMALL DESCRIPTION:




##### EXPECTED BLIZZLIKE BEHAVIOUR:




##### CURRENT BEHAVIOUR:




##### STEPS TO REPRODUCE THE PROBLEM:


1. 
2. 
3. 

##### EXTRA NOTES:


##### BRANCH(ES):


master


##### AC HASH/COMMIT:




##### OPERATING SYSTEM:




##### MODULES:




##### OTHER CUSTOMIZATIONS:









`

**Comment by Kitzunu** [comment] 2020-04-11 09:39
It is because they are in two different phases.
One is in phase 1 and one in phase 192

Turn off GM mode and one will disappear for you :)

**Comment by wowissues** [comment] 2020-04-11 09:40
> It is because they are in two different phases.
> One is in phase 1 and one in phase 192
> 
> Turn off GM mode and one will disappear for you :)


It has not disappeared, and even a simple player sees it.

**Comment by Kitzunu** [comment] 2020-04-11 09:41
I cannot reproduce that.

do 
`.mod phase 192` `.mod phase 1` with gm off

**Comment by wowissues** [comment] 2020-04-11 09:42
> I cannot reproduce that.
> ![image](https://user-images.githubusercontent.com/24550914/79040522-62003a80-7be9-11ea-96aa-e05823de36b1.png)
> 
> do
> `.mod phase 192` `.mod phase 1` with gm off

Yes, it's work. Buts how a simple player can see it? Phase too?

**Comment by Kitzunu** [comment] 2020-04-11 09:44
I dont know, do .pinfo to see the players phase

**Comment by wowissues** [comment] 2020-04-11 09:45
> I dont know, do .pinfo to see the players phase

Phase 4294967295

**Comment by Kitzunu** [comment] 2020-04-11 09:48
Hmm... I wonder how they land in that phase, because then both are shown

**Comment by wowissues** [comment] 2020-04-12 19:07
> Hmm... I wonder how they land in that phase, because then both are shown

hm, i have bug with phase with this quest https://www.wowhead.com/quest=12779/an-end-to-all-things too , after reconnect it works fine, hm idk

**Comment by Hacaw** [comment] 2020-12-08 19:20
I can reproduce this, but it's not an issue. 
Let's close it.

without .gm on
![image](https://user-images.githubusercontent.com/6963500/101530593-cce15b80-399a-11eb-94e4-8479570b202f.png)

with .gm on
![image](https://user-images.githubusercontent.com/6963500/101530630-d79bf080-399a-11eb-883e-d7d2c0b9dcfa.png)

TESTING
---
Used testing steps mentioned by author.

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment] 2020-12-08 20:32
The same happens with auctioneers at GM ON. There is a reason for it, not an issue.

**Closed by LukasVolgger** 2020-12-08 20:32 UTC
