### ISSUE TITLE
Rev: 6414b40518da (abort() has been called)

### ISSUE THREAD

**Issue by triggytag** [azerothcore/azerothcore-wotlk#4118] opened 2020-12-31 12:52 UTC
**Rev:**
6414b40518da

**Last info Console:**
2020-12-31 16:23:38 Starting up Auction House Listing thread...
2020-12-31 16:23:38 worldserver process priority class set to HIGH
2020-12-31 16:23:38 Max allowed socket connections 1024
2020-12-31 16:23:38 AzerothCore rev. 6414b40518da 2020-12-31 01:07:35 +0000 (master branch) (Win32, Debug) (worldserver-daemon) ready...
2020-12-31 16:24:40 Command: .save [Player: Владислав (1l) (Account: 11) X: -8949.950195 Y: -132.492996 Z: 83.531197 Map: 0 (Eastern Kingdoms) Area: 9 (Northshire Valley) Zone: Elwynn Forest Selected:  (0l)]

**Problem:**
Server worked 2-5 minutes and closed.
Last msg in console "worldserver.exe" - abort() has been called

**OS:**
Win7 32bit

Compile not Errors and Warnings

Maybe problem this 2GB RAM, but 1 year ago this core worked 24/7, and over 8 online), but worked stable.

**Comment by wizzymore** [comment] 2020-12-31 14:57
Hi,

Please use the proper template and also include the hash/commit of your core, this is very important.

Also, please include your crashlog by posting it to a third party app like pastebin and adding here the link

**Comment by Kitzunu** [comment] 2021-01-01 21:11
abort() is called here:
https://github.com/azerothcore/azerothcore-wotlk/blob/9be41ff4e628e1f6c3bc92a8140a9f8139c89ff5/src/common/Debugging/Errors.cpp#L111-L126
and here
https://github.com/azerothcore/azerothcore-wotlk/blob/9be41ff4e628e1f6c3bc92a8140a9f8139c89ff5/src/common/Database/MySQLConnection.cpp#L548-L557
But it can't be this because this is only SQL

But also in a hand full of deps:
g3dlite
jemalloc
mysqllite

Can you reproduce this issue? Do you have any way for us to reproduce it because currently, I can't.
Could it have to do with 32bit and 2gb ram?

Summoning @Helias and @Yehonal

**Comment by Winfidonarleyan** [comment] 2021-01-01 21:29
1. Use `RelWithDebInfo` build type for windows.
2. Check `Crash` folder
3. Try debug `worldserver.exe` with `Visual Studio`
- Example
![image](https://user-images.githubusercontent.com/18329778/103446525-129bf600-4cb3-11eb-8bd6-347682fdbfcc.png)

**Comment by triggytag** [comment] 2021-01-03 06:59
I started AC on another PC, which is more powerful and the server did not turn off. But, when the server is running on an old PC, in addition to the fact that it was turned off, it took a long time to load (5 minutes minimum), the client connects to the server for a long time, game chat (as if the ping rises).

**Comment by triggytag** [comment] 2021-01-03 07:24
+ maybe this 
MSVCP140D.dll
VCRUNTIME140D.dll
ucrtbased.dll

I took these dll files from another pc. And for some reason I don't have them on the server pc. I installed all the necessary packages to avoid these errors with the absence of these files, but for some reason it did not help.

**Comment by Kitzunu** [comment] 2021-01-03 11:27
I stil believe it has typ so with w32

**Comment by Kitzunu** [comment] 2021-04-17 00:09
As it hasn't had any activity for 4 months, and no other reports of this, I will close this issue.

If it still persists, please make a comment

**Closed by Kitzunu** 2021-04-17 00:09 UTC
Labels: Help wanted, Not confirmed, Priority - High
