### ISSUE TITLE
Professions learn

### ISSUE THREAD

**Issue by Rassd** [azerothcore/azerothcore-wotlk#478] opened 2017-05-01 09:23 UTC
**Description**:
works unlearn when im logged on but gets back after reloge so i can learn all works from npc

**Steps to reproduce the problem**:

1. Create Hero 80
2. .learn All rec Jew And .Learn all rec Al
3. Unlearn Jewelcrafting
4. .learn all rec eng
5. Relog
6. Login
7. You Have 3 work:|

**Branch(es)**: Master

**AC hash/commit**:  Last Rev

**Operating system**:  Windows 64

**Modules**: Transmog Anticheat

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Viste** [comment] 2017-06-12 20:20
Confrim!

**Comment by Yehonal** [comment] 2017-06-12 20:31
Could you test it with normal procedure (from trainers) instead of .learn commands please?

**Comment by Viste** [comment] 2017-06-12 20:51
@Yehonal i test it in few days when have free time

**Comment by Viste** [comment] 2017-06-13 08:16
@Yehonal i check and it only .learn command bug

**Comment by Viste** [comment] 2017-07-11 13:26
need help when i can find place where professions handle(all places)

**Comment by Viste** [comment] 2017-07-11 13:37
This bug also can be repeat when you use character migration web tool

**Comment by poszer** [comment] 2019-04-16 17:10
It's just an issue with learn commands. As the player in normal way, you can't reproduce this issue. I'm closing this

**Comment by vhiperdev** [comment] 2019-10-17 01:07
This problem has been closed, but the error still exists it would be good to reopen it, I tried to check more I have not found a solution.

**Comment by V3nomAnc3r** [comment] 2020-01-26 08:26
can someone fix this problem please!

**Comment by V3nomAnc3r** [comment] 2020-01-26 13:10
https://github.com/azerothcore/azerothcore-wotlk/issues/2330

**Comment by Kitzunu** [comment] 2020-04-23 16:16
I will close this in favor of https://github.com/azerothcore/azerothcore-wotlk/issues/2330 as it is the same issue, but more detailed.

Thank you for your report :)

**Closed by Kitzunu** 2020-04-23 16:16 UTC
Labels: Confirmed, Priority - Low
