### ISSUE TITLE
Holy wrath

### ISSUE THREAD

**Issue by deadmanevil** [azerothcore/azerothcore-wotlk#2020] opened 2019-06-27 01:09 UTC
Description:

Holy wrath does no damage.

Current behaviour:

Holy wrath does no damage.

Expected behaviour:

Holy wrath should do damage to all types, only stun certain types.

Steps to reproduce the problem:

Cast holy wrath.

Branch(es):

3.3.5
AC rev. hash/commit: 261fc79
Os: linux debian 9

**Comment by GMKyle** [comment] 2019-06-27 15:50
@deadmanevil 
I think this is not a bug on 3.3.5a(wotlk), the description of the spell is very clear, also his spellinfo shows **Creature Type Mask = 0x00000024 (DEMON, UNDEAD)** , the same as Turn evil for example.
The spell has the behavior that you are describing in 4.3.4(CATA), i din't checked more resettle versions.

**Comment by poszer** [comment] 2019-06-30 00:00
Checked vs Death Knight pet's (undead) and Warlock pet's (demons), it's working correctly.  It is an AoE ability that also stuns demons and undead for a short period of time. This cannot damage Forsaken NPCs or players, as they are classified as Humanoid. Closing this issue

**Closed by poszer** 2019-06-30 00:00 UTC
