### ISSUE TITLE
Revelosh (Uldaman) does not drop The Shaft of Tsol

### ISSUE THREAD

**Issue by copernicuschromie** [azerothcore/azerothcore-wotlk#5909] opened 2021-05-17 13:55 UTC
**CURRENT BEHAVIOUR:**
After killing Revelosh in Uldaman, he does not drop The Shaft of Tsol.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
The Shaft of Tsol should have 100% drop rate so it can be combined with the Gni'kiv Medallion for summoning Ironaya and completing The Hidden Chamber quest. 

**SOURCE:**
https://classic.wowhead.com/item=7741/the-shaft-of-tsol

**STEPS TO REPRODUCE THE PROBLEM:**

1. Enter Uldaman using Random Dungeon Finder
2. Defeat Revelosh

**EXTRA NOTES:**
The issue appears to be new as of approximately 15 May 2021. 

**AC HASH/COMMIT:**
N/A 

**OPERATING SYSTEM:**
Windows 10 Pro

**MODULES:**
N/A

**CUSTOMIZATIONS:**
N/A

**Comment by anguaive** [comment] 2021-05-18 16:43
Hi and thanks for the report! 

According to the source you linked, The Shaft of Tsol has a 41% drop chance, which matches the drop chance I dug up from the database. Here's the entire Revelosh loot table for completeness' sake:

```
SELECT clt.*
FROM
    `creature_template` ct
    JOIN `creature_loot_template` clt ON clt.Entry = ct.entry
WHERE ct.name = "Revelosh";

+-------+------+-----------+--------+---------------+----------+---------+----------+----------+---------------------------------+
| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment                         |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+---------------------------------+
|  6910 | 1708 |         0 |      2 |             0 |        1 |       0 |        1 |        1 | Revelosh - Sweet Nectar         |
|  6910 | 3771 |         0 |      2 |             0 |        1 |       0 |        1 |        1 | Revelosh - Wild Hog Shank       |
|  6910 | 4306 |         0 |     13 |             0 |        1 |       0 |        1 |        4 | Revelosh - Silk Cloth           |
|  6910 | 4338 |         0 |      2 |             0 |        1 |       0 |        1 |        3 | Revelosh - Mageweave Cloth      |
|  6910 | 7741 |         0 |     41 |             0 |        1 |       0 |        1 |        1 | Revelosh - The Shaft of Tsol    | <----
|  6910 | 9387 |         0 |     23 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Boots     |
|  6910 | 9388 |         0 |     21 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Armguards |
|  6910 | 9389 |         0 |     23 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Spaulders |
|  6910 | 9390 |         0 |     21 |             0 |        1 |       1 |        1 |        1 | Revelosh - Revelosh's Gloves    |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+---------------------------------+
```

Unless wowhead is wrong (which is always a possibility), everything is working as intended.

**Comment by Kitzunu** [comment] 2021-05-19 23:34
Dont ignore the template. add your rev

**Comment by anguaive** [comment] 2021-05-23 11:02
Working as intended. Closing

**Closed by anguaive** 2021-05-23 11:02 UTC
Labels: 30-39, Instance - Dungeon - Classic, Invalid - Intended/WontFix/Blizzlike, Invalid-MissingHash/Commit, Loot
