### ISSUE TITLE
Feature: There should be a min and max for respawn instead of a static number

### ISSUE THREAD

**Issue by neifion-00000000** [azerothcore/azerothcore-wotlk#13015] opened 2022-09-12 07:38 UTC
### Describe your feature request or suggestion in detail

Note:  This is a separate issue from the dynamic spawning system which has to do with spawning more to make up for population.    

I have proven fairly extensively spawn timers should not be static and there is always a range by finding an adequately fast enough spawning one and hammering it to some length (I also used to farm lotus on retail, it also follows this behavior).  This is something I've experienced everywhere in my sniffing  In my opinion the system is weighted to pick faster respawns less often but that is less proven.

imo respawn should be changed to min and max should be added (if 0 then max=min) 

Nyeriah mentioned it and I cofirmed vmangos has this feature already

**Comment by Ovahlord** [comment] 2022-09-12 09:40
What you observed is called dynamic respawning. The respawn timer scales with the amount of triggered respawn timers. In some other cases Blizzard just uses pools with a min-pool size, meaning that they enforce respawns to maintain a minimum number of active objects.

dynamic respawning is already implemented in TC.

**Comment by neifion-00000000** [comment] 2022-09-12 17:41
> What you observed is called dynamic respawning. The respawn timer scales with the amount of triggered respawn timers. In some other cases Blizzard just uses pools with a min-pool size, meaning that they enforce respawns to maintain a minimum number of active objects.
> 
> dynamic respawning is already implemented in TC.

this is simply not the case

I have done this on the both live and the PTR, when I am often the only active player on the entire server

**Comment by malcrom** [comment] 2022-09-15 17:59
Some npcs have quicker respawn timers, like quest bosses. This can be handled in SAI. Most have the same unless properly pooled to lessen respawn time.

**Comment by neifion-00000000** [comment] 2022-09-16 09:45
I mean I already have a concrete example of this, the snapper quest in Draenei start zone has this behavior, and its fairly widespread in general.  

https://www.youtube.com/watch?v=1cNUYTV_Ss4  56:05, respawn 56:35 (30 seconds)
57:38, respawns at 58:03 (25 seconds)
00:32, respawns at 01:00 (28 seconds)
01:31, respawns at some point in the low :50s (under 25 seconds)
02:06, respawns at 02:36 (30 seconds)
02:36, respawns at 03:00 (24 seconds)


Black Lotus spawns before they were changed were on timers ranging from 45m to 1hr15m

creatures also show this behavior but I have a lot less data on them due to the length it takes on them to respawn, but one thing I remember is that wildlife mobs in Teldrassil had a decent sized variation and before I decided it was impossible to account for properly I was tracking it

**Comment by heyitsbench** [comment] 2022-10-28 19:19
Might be a duplicate of #7592.

**Comment by Gultask** [comment] 2022-10-31 21:25
Closing due to duplicate

**Closed by Gultask** 2022-10-31 21:25 UTC
Labels: Suggestion
