### ISSUE TITLE
Reanne Wolfrunner - Wrong Dialogue

### ISSUE THREAD

**Issue by CyberFoxHax** [azerothcore/azerothcore-wotlk#6265] opened 2021-06-08 06:15 UTC
After completing the quest [[Raene's Cleansing]](https://classic.wowhead.com/quest=1028/raenes-cleansing), [[Raenne Wolfrunner]](https://classic.wowhead.com/npc=3691) should get an option to get [[Dartol's Rod of Transformation]](https://classic.wowhead.com/item=5462) in case you destroy it.

Conversation option is available before completing the quests. For observation, the option is still there even on a completely new character.

Clicking the option "Raene, I lost Dartol's Rod of Transformation" will spin into a different dialogue i recognize as [[Mountaineer Pebblebitty]](https://www.wowhead.com/npc=3836)

<img width="308" alt="1" src="https://user-images.githubusercontent.com/7734690/121132020-2dc2f100-c863-11eb-9e2e-be89bbb388ba.png">
<img width="306" alt="2" src="https://user-images.githubusercontent.com/7734690/121132029-30bde180-c863-11eb-82b3-dfd18c0237db.png">

___________
AzerothCore rev. 6f4f0043c2ab+ 2021-05-18 02:16:59 +0200 (master branch) (Win64, RelWithDebInfo) (worldserver-daemon)

**Comment by mserajnik** [comment] 2021-06-08 07:20
The dialogue part is a duplicate of #4905.

**Comment by mserajnik** [comment] 2021-06-08 15:08
Actually, #4905 also already mentions:

> Raene Wolfrunner (ID: 3691) has a gossip option "Raene, I lost Dartol's Rod of Transformation". After selecting this (I haven't completed the chain yet either.. not sure why this showed from the start)

In 1.), I was thrown of by your phrasing _She's offering_, but you likely also mean the availability of that dialogue option prior to completing the chain (as seen in your first screenshot too)?

If so, then the _whole_ issue is a duplicate of #4905.

**Comment by CyberFoxHax** [comment] 2021-06-09 01:49
@mserajnik Suppose i should correct that.

**Comment by mserajnik** [comment] 2021-06-09 12:17
Thanks for clarifying!

@FrancescoBorzi This can be closed as duplicate of #4905.

**Closed** 2021-06-09 16:13 UTC

**Comment by CyberFoxHax** [comment] 2021-06-10 03:28
great work guys!
