### ISSUE TITLE
Stacked buffs and not updates

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#16538] opened 2023-06-15 10:45 UTC
### Current Behaviour

some buffs can stack  [Drums of Forgotten Kings] (possibly the same with [Drums of the Wild] not check)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/136082219/6656ca6c-ecb8-4709-a2fa-74c4f799133a)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/136082219/c1acc57f-30b9-436e-a048-0e34057e7e15)

and when use  [Runescroll of Fortitude] priest buff not update but **ITEM consumed without effect or error** (you lost 1 [Runescroll of Fortitude] item but not have update Fortitude buff)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/136082219/74456594-000f-420f-8aad-266218bcc76e)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/136082219/f51351a7-c605-4fda-a593-517b8d3589d2)

### Expected Blizzlike Behaviour

not stucks and correctly update buff

### Steps to reproduce the problem

see screens

### AC rev. hash/commit

a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Windows 11 x64

**Comment by heyitsbench** [comment] 2024-07-06 19:30
For the part of the Drums, closing in favor of https://github.com/azerothcore/azerothcore-wotlk/issues/19324 as more recent revision and added source.

For the Runescroll, I cannot reproduce on f85d8433a66e98a97e0969182ecc5a1429a838b6.

**Closed by heyitsbench** 2024-07-06 19:30 UTC
