### ISSUE TITLE
Shadowmourne: Soul Fragment Proc

### ISSUE THREAD

**Issue by Irome** [azerothcore/azerothcore-wotlk#314] opened 2017-01-05 10:30 UTC
**Description**: The effect Soul Fragment (http://www.wowhead.com/spell=71905/soul-fragment) of Shadowmourne (http://www.wowhead.com/spell=71903/item-shadowmourne-legendary) not it's correct. The aura of the spell proc chance is 100%.

**Current behaviour**: The proc of the Soul Fragment increases with each melee ability.

**Expected behaviour**: It is a touchy subject. There are many theories about it. However, the issue was discussed and solved on TC: https://github.com/TrinityCore/TrinityCore/issues/1619

I quote here the proper functioning of Shadowmourne:
http://www.wowpedia.org/Shadowmourne

THE PROBLEM HAS BEEN SOLVED ON TC, SUFFICIENT TO IMPLEMENT THE COMMENTS: https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686

**Branch(es)**: Master

**AC hash/commit**:  f549a25501a12291af77f5d7f59ba69a4fc4a956

**Comment by Inifield** [comment] 2017-01-05 12:44
I did a quick look and the only thing I that found is 

INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(71903,   0,  0, 0x00000000, 0x00000000, 0x00000000,       0, 0x0, 0x2,     0, 0x0, 12,   0,      0, 0), -- Item - Shadowmourne Legendary

i'm not honestly sure this is it, to be honest I don't even understand what the problem is. ( you might need to adjust the SQL request, I took it from the commit you gave above)

**Comment by talamortis** [comment] 2017-01-07 08:02
the spell is not 100% proc chance if you read the tool tip it says your melee attacks have a chance

**Comment by talamortis** [comment] 2017-04-16 00:04
why is this issue closed?

**Comment by Nefertumm** [comment] 2017-06-29 20:39
This can be dangerous to import from TC, because it can break more stuff than fix... We should look at another option to fix this (not sure).

**Comment by Viste** [comment] 2017-07-01 01:51
@Nefertumm fixes for many staff that broken after ariel commit in tc repo ))) so we can import them to

**Comment by Pondaveia** [comment] 2019-05-06 13:56
Closing this issue due to missing evidence of the issue.

**Comment by Viste** [comment] 2019-05-06 15:06
stop close issues when problem are STILL NOT FIXED

**Comment by Axaxxax** [comment] 2020-02-12 16:46
Has anyone found a way to resolve this issue?

**Comment by gengarshadowball** [comment] 2020-05-23 09:28
Honestly, I don't see a problem in here. I made a video and what I did notice is the Chaos Bane doing less damage than it should.

https://www.youtube.com/watch?v=8vySPCAm_Pg

**Comment by Helias** [comment] 2020-05-23 14:08
I am closing this. If anyone can confirm this bug the issue can be re-opened

**Closed by Helias** 2020-05-23 14:08 UTC
Labels: Priority - Low
