### ISSUE TITLE
Hunter's auto attack does not stop for bandaging [$30]

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#5734] opened 2021-05-09 01:50 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Hunter's auto-shot will continue to tick and interrupt bandaging 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Bandage should stop all actions when activated. It is considered a channeled spell.
[https://wowwiki-archive.fandom.com/wiki/Channeling](https://wowwiki-archive.fandom.com/wiki/Channeling)
Testing with wand's auto-shoot works properly

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a hunter
2. Proceed to a training dummy
3. Range attack, and try to bandage
4.

##### EXTRA NOTES:

Original issue from Chiromicraft 
[https://github.com/chromiecraft/chromiecraft/issues/454](https://github.com/chromiecraft/chromiecraft/issues/454)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment] 2021-05-23 08:27
@Stump876 @torrenteeselkmanda
Cannot reproduce it.
https://imgur.com/a/EV2r2B7

**Comment by Stump876** [comment] 2021-05-23 16:27
That is odd. The first is on horde from Chromiecraft about 30 minutes ago. Took a screen shot of the text, I wasn't sure how well it would show up in the video. Double checked on test server on alliance. It's still doing it for me.

https://user-images.githubusercontent.com/68164076/119268714-115b5f00-bba9-11eb-9cab-edb0a017aab9.mp4


![image](https://user-images.githubusercontent.com/68164076/119268701-01dc1600-bba9-11eb-83c0-0d5f96d1b424.png)

https://user-images.githubusercontent.com/68164076/119268644-bb86b700-bba8-11eb-8aff-9f2602103d7d.mp4

**Comment by UltraNix** [comment] 2021-05-28 16:38
@Stump876 How did you attack these dummies - by right click on it or click on action bar?

**Comment by Stump876** [comment] 2021-05-28 23:57
Right click in the videos above. Testing with action bar click and key press all give the same result.

**Comment by UltraNix** [comment] 2021-05-30 14:36
Still I can't reproduce it. I tried many times, in many ways.

**Comment by UltraNix** [comment] 2021-05-31 09:49
Still I can't reproduce it. I tried many times, in many ways.
Maybe someone else could tell me exactly how to bug this.

**Comment by necropola** [comment] 2021-06-01 06:08
Confirmed on my local AC.
You need to have **Auto Attack /Auto Shot** enabled!

**Comment by UltraNix** [comment] 2021-06-01 08:12
@necropola You are right - that option was missing.

**Comment by necropola** [comment] 2021-06-09 17:46
@FrancescoBorzi 
With what we know now (https://github.com/azerothcore/azerothcore-wotlk/pull/6267#issuecomment-856975180), shouldn't this be reopened?
>I've tested the same on current TC-3.3.5 and there Bandaging **does not cancel Auto Shot** it just pauses it just like Auto Attack (action bar icons stay blinking). Which basically means that the **Bandaging Fix wasn't and still isn't a proper fix for the bandaging issue**.

**Comment by UltraNix** [comment] 2021-06-11 07:59
@FrancescoBorzi Please, close this one as I will make a proper fix in the new PR (#6267).

**Comment by FrancescoBorzi** [comment] 2021-06-11 17:22
@UltraNix just add `- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5734` in your PR

**Closed** 2021-06-13 17:27 UTC
Labels: Bounty, ChromieCraft Generic, Class - Hunter, Confirmed
