### ISSUE TITLE
Odur Algalon Major BUG

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15382] opened 2023-03-14 14:25 UTC
### Current Behaviour

Odur BUG: If Ogalon destroys the group, the BOSS will not be refreshed, but can only stay in a daze

### Expected Blizzlike Behaviour

When the group is destroyed, the player's running corpse BOSS is refreshed normally and can rejoin the battle

### Steps to reproduce the problem

There are no steps, because BOSS will no longer appear after the group is destroyed

### AC rev. hash/commit

AZEROTHCORE REV.4134C2DADA78+ 2023-03-14 06:35:16 +0000 (MASTER BRANCH) (WIN64.RELWITHDEBINFO,STATIC)

### Operating system

WINDOW SERVER 2019

**Comment by heyitsbench** [comment] 2023-03-16 03:37
Confirmed on a1c644fd3971085d25d16700384110feda6bfdab. Seems if Algalon is despawned for any reason, there is no way to restart the fight. This includes not only a wipe of the raid, but also the black hole phasing effect, and likely the phase punch effect as well.

**Comment by yukijean** [comment] 2023-03-16 09:01
@heyitsbench Can this problem be solved?

**Comment by Maelthyrr** [comment] 2023-03-16 09:16
> @heyitsbench Can this problem be solved?

Yes, but we have many issues. We can't said  when it will be fix.

**Comment by Kitzunu** [comment] 2023-03-16 09:40
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15379

**Closed by Kitzunu** 2023-03-16 09:40 UTC
