### ISSUE TITLE
(Spell) Focused Assault buff not being removed after WSG.

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#9724] opened 2021-12-15 17:17 UTC
### Current Behaviour

Try to carry flag for >5 mins in WSG and get debuff Focused Assault, either win or lose the BG, and notice the buff is still applied. 
Issue is first reported once and only onced on CC https://github.com/chromiecraft/chromiecraft/issues/738 and  https://github.com/chromiecraft/chromiecraft/issues/1732

### Expected Blizzlike Behaviour

When WSG is completed, Focused Assault should be removed from the player.

### Steps to reproduce the problem

Try to carry flag for >5 mins in WSG and get debuff Focused Assault
Win/Lose that BG while having debuff
Check if debuff persists on character upon leaving BG or entering new BG

also mentioned in the comments of the first issue:
![image](https://user-images.githubusercontent.com/16887899/146234102-65bc660b-2de3-4ed9-9843-10b4ec7af196.png)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/086b20edbcc76bb6b80ef4fe2845d1f4e4087bd9

### Operating system

Windows 10 x64 Pro

**Comment by Kitzunu** [comment] 2021-12-18 23:59
should be easy enough

**Comment by Kitzunu** [comment] 2021-12-19 00:00
Just throw a RemoveAurasDueToSpell() somewhere

**Comment by Shineslippers** [comment] 2021-12-20 17:02
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6195
Anyway it's rare bug. Almost unable to reproduce. Still is missing some command to end bgs.

**Closed** 2022-01-28 19:06 UTC
Labels: ChromieCraft Generic, Help Wanted, Battlegrounds
