### ISSUE TITLE
Hand of Reckoning

### ISSUE THREAD

**Issue by pati3nc3** [azerothcore/azerothcore-wotlk#626] opened 2017-09-13 09:55 UTC
**Description**: t's a very useful spell in PvP with a lot of uses. There's countless uses for a free 30yd spell that does small damage. To list a few... 

killing totems. 
Vindication procs. 
Vengeance procs. 
spending charges on dk bone shield and other similar shields. 
getting into combat (immunity to sap) 
putting someone into combat. (prevents out of combat spells) 
interrupting bandage and mount. 

**Current behaviour**: When you will use the spell, it doesen't put you and the target in combat and dont destroy totems.

**Expected behaviour**: The spell have to put the player and the target in combat and destroy totems.

**Commit hash**: d0af1c812bf4ea15204cad37b39ff27ff6bae339

**Branch**: master

**Mods/Patches**: Yes, official AC modules

**Comment by ShinDarth** [comment] 2017-09-13 13:21
missing commit hash, can you please edit your report and add it?

**Comment by pati3nc3** [comment] 2017-09-13 13:37
Atm i dont have the hash because i'm an AS player. So, the bug probably is confirmed because no modify was applied ( yehonal message)

Il giorno 13 set 2017, alle ore 15:22, Francesco Borzì <notifications@github.com<mailto:notifications@github.com>> ha scritto:


missing commit hash, can you please edit your report and add it?

**Comment by Yehonal** [comment] 2017-10-22 09:46
I've updated information about commit hash etc. He missed the steps however the bug is confirmed

I think we've just to remove the taunt immune flag from totem creature IMHO

**Comment by lineagedr** [comment] 2017-10-22 12:10
Are you sure it's supposed to be able to kill totems?

**Comment by lineagedr** [comment] 2017-10-22 12:17
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/game/Spells/SpellEffects.cpp#L3221

Change to:

`if (m_spellInfo->Id == 62124 && unitTarget->GetVictim() != m_caster)
{
	m_caster->CastSpell(unitTarget, 67485, true);
	unitTarget->CombatStart(m_caster);
}`

**Comment by Yehonal** [comment] 2017-10-22 12:29
I was debugging exactly that part before read your comment.

However there's an official macro for wrath that uses Hand of Reckoning to destroy shaman totem before Hoj, so i think totem must be damaged by this spell

**Comment by Yehonal** [comment] 2017-10-22 12:30
moreover there's nothing on the web that says the countrary

**Comment by Nefertumm** [comment] 2018-01-11 03:27
I think this should be closed by 5ad0bd21340612ffc567a40979cc1da738aac97c.

**Comment by poszer** [comment] 2018-12-12 12:22
HOR on totems work fine, it destroy them, and also deal damage ( Entering in combat ) on some with higher Hp.
![handofrecog](https://user-images.githubusercontent.com/41213210/49869426-a53d7400-fe10-11e8-8a9a-55aa625430e0.png)

While using on players, there is issue, saying the target is Immune ( Insted of that, it should enter the characters in combat).
![charimune](https://user-images.githubusercontent.com/41213210/49869472-c1411580-fe10-11e8-9d60-78cecf40df2a.png)

**Comment by BarbzYHOOL** [comment] 2018-12-16 19:48
@poszer did you test the fix included?

**Comment by poszer** [comment] 2018-12-16 22:15
> @poszer did you test the fix included?

Yes, the pictures are with fix included. It have issue whipe using it on player, saying the player is immune. But, thats wrong. If you use it on player, it should do damage on player

**Comment by BarbzYHOOL** [comment] 2018-12-18 20:46
the fix is half working apparently

**Comment by poszer** [comment] 2018-12-19 08:34
> 
> 
> the fix is half working apparently

It more looks like players are immune to taunt

**Comment by wetbrownsauce** [comment] 2018-12-19 15:31
I'm not sure about this, players are meant to be immune to taunt, including the effects of HoR. 
See 2009-08-08 hotfix by Blizzard (4 days after release of patch 3.2.0) which states:

"Hand of Reckoning is no longer able to be used on targets that are immune to taunt, including players"

via: [Saturday, August 8th Hotfixes WoW Wiki](https://wowwiki.wikia.com/wiki/Hotfixes/2009_Archive#August_2009)

**Comment by poszer** [comment] 2018-12-19 23:53
> @poszer
> I'm not sure about this, players are meant to be immune to taunt, including the effects of HoR.
> See 2009-08-08 hotfix by Blizzard (4 days after release of patch 3.2.0) which states:
> 
> "Hand of Reckoning is no longer able to be used on targets that are immune to taunt, including players"
> 
> via: [Saturday, August 8th Hotfixes WoW Wiki](https://wowwiki.wikia.com/wiki/Hotfixes/2009_Archive#August_2009)

Look this picture:
https://user-images.githubusercontent.com/41213210/49869472-c1411580-fe10-11e8-9d60-78cecf40df2a.png
It say for every class that is immune, but i remember the HoR was doing damage on every target, and was ideal to use it vs rogues, since it hold you in combat. Dunno whats changed, since i didnt saw that change on any server. HoR working like before. Will need confirmation about it from the people

**Comment by poszer** [comment] 2018-12-23 17:31
If the players should be immune on taunt  like @wetbrownsauce said, than its almost fixed. The only problem for now is ( Entering in combat ) while using HOR on players even the players are immune on it

**Comment by wetbrownsauce** [comment] 2018-12-23 17:32
Yes that is correct, it still needs to enter combat, just not deal damage to players

**Comment by poszer** [comment] 2018-12-24 12:05
> 
> 
> also need to open the PR with the fix

Done

**Comment by BarbzYHOOL** [comment] 2018-12-25 16:53
@poszer so what is the last issue to open about Hand of reckoning??

**Comment by poszer** [comment] 2018-12-25 17:49
> 
> 
> @poszer so what is the last issue to open about Hand of reckoning??

It was with players are immune, but like @wetbrownsauce said, it's okay since it's added in patch. It will just enter in combat now. So everything is fine with this

**Comment by BarbzYHOOL** [comment] 2018-12-25 18:36
Ah ok nice

**Closed** 2018-12-25 18:39 UTC
Labels: CORE, Class - Paladin, Fix included, Good first issue, Priority - High
