### ISSUE TITLE
Death Knight Cavalier (entry: 35451) boss final (TOC 5) is BUG - disappear

### ISSUE THREAD

**Issue by njmain** [azerothcore/azerothcore-wotlk#12857] opened 2022-08-26 16:08 UTC
### Current Behaviour

The final bos of toc 5 disappears and it is not possible to complete the dungeon.
![1](https://user-images.githubusercontent.com/5303854/186944801-b06a38d9-f112-40e6-9f96-896d13368168.png)
![2](https://user-images.githubusercontent.com/5303854/186944833-c9d988c0-3393-4c37-8889-81363f37bf38.png)

### Expected Blizzlike Behaviour

When you start the fight with the final boss of toc 5, he comes flying in and says "You ruined my grand entrance, rat", gets off his mount, kills the npc that started the battle, then disappears, and the dungeon can no longer be completed .

### Source

Death Knight Cavalier
entry: 3545
![npc1](https://user-images.githubusercontent.com/5303854/186946143-d469eb86-a494-41d6-bbbb-2121e80e817c.png)
![npc2](https://user-images.githubusercontent.com/5303854/186946157-62f3c281-9558-4061-8e66-9c151731db37.png)
![npc3](https://user-images.githubusercontent.com/5303854/186946167-d670feda-9932-4658-8434-537e642cd374.png)
1

### Steps to reproduce the problem

-Raise character to level 80
-Go to TrialOfTheChampion 5n or 5h
-complete first encounters
-confront the final boss

### AC rev. hash/commit

[2ed6848d6a98](url)

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-transmog
mod-solo-lfg
mod-learnspells
mod-instance-reset
mod-individual-xp
mod-eluna
mod-cfbg
mod-autobalance
mod-1v1-arena

**Comment by Tony931023** [comment] 2022-08-27 04:53
This problem was solved thanks to @UltraNix  , it is waiting for it to be worked in the core pr https://github.com/azerothcore/azerothcore-wotlk/pull/12807

**Comment by UltraNix** [comment] 2022-08-27 05:29
Duplicate of #12798

**Closed by UltraNix** 2022-08-27 05:29 UTC
