### ISSUE TITLE
Quest: A Blade Fit For A Champion

### ISSUE THREAD

**Issue by noisiver** [azerothcore/azerothcore-wotlk#6174] opened 2021-06-01 13:37 UTC
**CURRENT BEHAVIOUR:**

The creature Lake Frog for quest A Blade Fit For A Champion has a duplicate gossip option. The second one does not give the player the sword. The Warts-B-Gone Lip Balm buff stays active on the player after /kiss

**EXPECTED BLIZZLIKE BEHAVIOUR:**

There should be only one and it should give the player the sword. The Lip Balm buff should be removed after every /kiss

**SOURCE:**

https://imgur.com/3YdIlIh
The buff being removed after every /kiss is talked about on Wowhead in patch <= 3.3.5. I have no source from back then to link but just looking at the comments on Wowhead for the quest should confirm this
https://www.wowhead.com/quest=13666/a-blade-fit-for-a-champion#comments

**STEPS TO REPRODUCE THE PROBLEM:**

1. .quest add 13666 for alliance, .quest add 13673 for horde
2. .go xyz 3812.86 -4357.22 182.88 571
3. Apply the Warts-B-Gone Lip Balm
4. Use /kiss on the frogs until the NPC appears and check the buff every time /kiss is used
5. Speak to the NPC

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
1889fffbde6743379f8e720162f426cd7ccac28b

**OPERATING SYSTEM:**

Ubuntu 20.04

**MODULES:**

None

**CUSTOMIZATIONS:**

None

**Comment by poryagholami1374** [comment] 2021-06-03 12:24
![WoWScrnShot_060321_165324](https://user-images.githubusercontent.com/80007195/120644139-3d6dbe80-c48c-11eb-8ed2-7e4118c63d95.jpg)
I do not approve of this post
Quest completed

**Comment by tkn963** [comment] 2021-06-03 12:38
The quest can be completed, that's not the issue, the issue is duplicate options for the gossip and that the buff doesn't wear when using /kiss

**Comment by poryagholami1374** [comment] 2021-06-03 12:42
> The quest can be completed, that's not the issue, the issue is duplicate options for the gossip and that the buff doesn't wear when using /kiss

The second case does not give the sword to the player.

See the picture inside the bag

**Comment by poryagholami1374** [comment] 2021-06-03 12:45
> The quest can be completed, that's not the issue, the issue is duplicate options for the gossip and that the buff doesn't wear when using /kiss

I do not understand what you mean. Tell me the problem more accurately

**Comment by poryagholami1374** [comment] 2021-06-03 12:57
The Warts-B-Gone Lip Balm buff stays active on the player after /kiss
It stays on you but has no effect
Not a particular problem
Just to use this
The item should be left on for 5 minutes
To be like a Buff

**Comment by tkn963** [comment] 2021-06-03 13:04
Yes, the second option from the lake frog does nothing and should be removed - the option text is identical any way. The buff should be removed from the player after using /kiss so that you have to re-apply it with every /kiss - I have no footage of when I played back then but I remember it working this way, so looking at the wowhead comments confirmed my memory of the quest. If the comments are not enough to convince people, then fine. :P

https://www.wowhead.com/item=44986/warts-b-gone-lip-balm#comments

**Comment by tkn963** [comment] 2021-06-03 13:05
"The balm buff doesn't have a duration (kissing those quest frogs disspells it of course) so you can wear it all day long.

You know, in case you bump into more frogs."

**Comment by tkn963** [comment] 2021-06-03 13:09
This issue report is not like a 'fix asap' but rather an oddity that doesn't break anything but is not retail-like. The quest can be completed perfectly fine, so that was never the issue at all

**Comment by poryagholami1374** [comment] 2021-06-03 14:36
> This issue report is not like a 'fix asap' but rather an oddity that doesn't break anything but is not retail-like. The quest can be completed perfectly fine, so that was never the issue at all

This is not a problem of effort
You have to report the spell and I have no problem with Quest
And I confirmed that the quest problem report is incorrect

**Comment by Sedatyf** [comment] 2021-06-03 14:38
I'll take a look myself so we'll triage this

**Comment by tkn963** [comment] 2021-06-03 14:40
The quest itself works. The npc that you talk to has a duplicate of gossip option that is incorrect. When I get home I can show you a print of the npc_gossip_option of the menu id from that NPC

**Comment by poryagholami1374** [comment] 2021-06-03 14:41
> I'll take a look myself so we'll triage this

Quest has no problem

You must enter a title Spell persistence problem After the quest is completed

**Comment by tkn963** [comment] 2021-06-03 14:42
I mean if you find the MenuID of the npc you talk to to get the sword and look at the gossip options of that menu, the option 0 and 1 are both identical and option 1 does nothing

**Comment by tkn963** [comment] 2021-06-03 17:33
This is not simply a spell-related issue. I took some screenshots to show what the issues are.

https://imgur.com/a/kgzialB

The first image show that there are two of the gossip options and the second one is useless, doesn't function and should be removed.

The second image shows a part of the code for [zone_grizzly_hills.cpp](https://github.com/azerothcore/azerothcore-wotlk/blob/f4c226423dc0811efccf8135b46bc7ff46aab940/src/server/scripts/Northrend/zone_grizzly_hills.cpp#L823) that is implemented but does not remove the buff from the player as it **should**

**Closed** 2023-10-21 12:15 UTC
Labels: Confirmed, Quest, 75-79
