### ISSUE TITLE
[raid/Naxxramas] Kel'Thuzad bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6930] opened 2021-07-14 03:09 UTC
### Current Behaviour

After the battle begins, all monsters rush to the player

### Expected Blizzlike Behaviour

After the battle begins, monsters should be activated in batches and attack players

### Source

https://www.youtube.com/watch?v=1t8uk9qFSPg&t=23s

### Steps to reproduce the problem

1.attack Kel'Thuzad
2.Look at the monster

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc

### Operating system

ubuntu 20.04

**Comment by steenburgh** [comment] 2021-07-18 15:49
This is a duplicate of #6259

**Closed by steenburgh** 2021-07-18 15:49 UTC
