### ISSUE TITLE
Ulduar 25 Hodir boss fight wont start

### ISSUE THREAD

**Issue by pe93** [azerothcore/azerothcore-wotlk#6917] opened 2021-07-13 11:47 UTC
### Current Behaviour

Hodir fight in 25m Ulduar ist nor starting. You dont see the npc´s in ice tombs.
He isnt attacking or attackable. You can target him but the attacks wont work.
When u kill the boss the Npc´s in the frosttombs appear.
Also the Lootchests for normal mode and hardmode are alqays visible. They should appear after the fight.
When u kill hodir u dont get his sigil for the quest at the archivarium.

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=XQ_dLRQ3z3g&ab_channel=ashdragon1

### Source

https://www.youtube.com/watch?v=XQ_dLRQ3z3g&ab_channel=ashdragon1

### Steps to reproduce the problem

Enter Ulduar 25 man
Start Bossfight agains Hodir

### AC rev. hash/commit

AC> AzerothCore rev. 734ac6cdd394 2021-07-01 11:39:17 +0000 (master branch) (Uni
x, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar
2020)
Using ACE version: 6.4.5
Using Boost version: 1.71.0
Using MySQL version: 80025
Using CMake version: 3.16.3
Compiled on: Linux 5.4.72-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207
 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 6581307
21 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365
052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_01_00
Using Character DB Revision: 2021_06_30_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

win 10

### Custom changes or Modules

compiled using docker

**Comment by steenburgh** [comment] 2021-08-23 02:20
Duplicate of #5859

**Closed by steenburgh** 2021-08-23 02:20 UTC
