### ISSUE TITLE
Crash server for hacking or attack

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#2406] opened 2019-11-05 08:52 UTC
Hi

2019-11-05 01:18:44 ERROR: Player::Create: Possible hacking-attempt: Account 50 tried creating a character named 'Poll' with an invalid race/class pair (7/7) - refusing to do so.
2019-11-05 01:18:46 ERROR: Player::Create: Possible hacking-attempt: Account 50 tried creating a character named 'Bria' with an invalid race/class pair (7/7) - refusing to do so.

![IMG-20191105-WA0000](https://user-images.githubusercontent.com/52524476/68192675-ef9a8700-ffc6-11e9-8a84-6d2cd1614942.jpeg)

**Comment by Helias** [comment] 2019-11-05 09:34
How can I reproduce the bug?

**Comment by poryagholami** [comment] 2019-11-05 09:39
I don't know what to do with a different hacking program if I knew I was solving the problem myself

**Comment by Krath** [comment] 2019-11-05 18:50
> I don't know what to do with a different hacking program if I knew I was solving the problem myself
You should be less cocky since you're asking for help.
Also,  please include your AC version (commit hash).

**Comment by Krath** [comment] 2019-11-05 18:50
@poryagholami You should be less cocky since you're asking for help.
Also, please include your AC version (commit hash).

**Comment by Shard-MW** [comment] 2019-11-08 17:14
@Helias 
This is not a bug, this is a normal behaviour, but server shouldn't crash.
The player is trying to create a character with an invalid race/class pair, that means he's using a modified client (which have probably all class/race patch), in this case he tried to create a Gnome Shaman

http://www.ac-web.org/forums/showthread.php?135978-TrinityCore-All-Race-All-Class-3-3-5a

@poryagholami 
We really need your commit hash for this :)

**Comment by Helias** [comment] 2019-11-08 18:08
Hence,  it isn't a real issue.

We can make a module all-race-all-class to handle this.

But if the server does not crash, this is a normal behaviour so we can close the issue, agree?

**Comment by Shard-MW** [comment] 2019-11-08 18:20
@Helias 
Nope, his screen shows that his server crashes and it's not normal.
I remember working on custom races/classes and getting this error but server never crashed.

It was on old commit, so I think we need to try to reproduce it on the current commit (e83169d715904d4cd79bb8ee12db11018ec3c726).
I can't do it right now even if it takes not a lot of time, but to try to reproduce it we need : 
1. Download this patch : (found on http://www.ac-web.org/forums/showthread.php?135978-TrinityCore-All-Race-All-Class-3-3-5a)
> https://mega.nz/#!00sABRjK!zSKVa5NXt6r3kfeMKAmq8uOASOwTqxN4dX2LBRbEgNM
2. Put the patch in WoW/Data/ folder
3. Run WoW
4. Try to make a Gnome Shaman on a non-modded server

**Comment by Helias** [comment] 2019-11-08 21:32
Importing the sql file I got the following error:
`ERROR 1264 (22003) at line 10612: Out of range value for column 'amount' at row 1`
I fixed it converting `tinyint(3)` with `int(3)` in creating `playercreateinfo_item` table.

I'm testing this issue :wink:

**Comment by Helias** [comment] 2019-11-08 21:34
I didn't get any errors after creating a Gnome Shaman.

![immagine](https://user-images.githubusercontent.com/519778/68512160-dec46c80-0277-11ea-83a0-66f99380ef04.png)

![immagine](https://user-images.githubusercontent.com/519778/68512165-e7b53e00-0277-11ea-80f8-bd5a1f818718.png)

**Comment by Helias** [comment] 2019-11-08 21:43
Ok, without importing the sql file I got some errors :sweat_smile:, but still the server does not crash.

![immagine](https://user-images.githubusercontent.com/519778/68512520-f05a4400-0278-11ea-9257-f1a0ebd398fd.png)


I got this in console:
![immagine](https://user-images.githubusercontent.com/519778/68512583-1aac0180-0279-11ea-8bd4-788322d4e05f.png)


I think that this is not a problem, the server does not crash or takes any damage, so we can close this issue.

**Comment by LichKing255** [comment] 2019-11-08 21:45
he must send crash log for check it. i think crash is not for this error .

**Comment by Helias** [comment] 2019-11-11 11:08
I think we can close this.

**Closed by Helias** 2019-11-11 11:08 UTC
