### ISSUE TITLE
Rune of the Dawn doesn't grant the equipping player Argent Dawn Commission buff.

### ISSUE THREAD

**Issue by Thatharis** [azerothcore/azerothcore-wotlk#20116] opened 2024-10-01 08:41 UTC
### Current Behaviour

Rune of the Dawn doesn't grant the equipping player Argent Dawn Commission buff.
Seal of the Dawn still does grant the equipping player Argent Dawn Commission buff, however.

### Expected Blizzlike Behaviour

Rune of the Dawn should grant the player Argent Dawn Commission buff. Without the buff, collection of Scourgestones is impossible.

### Source

https://www.classicdb.ch/?item=19812

### Steps to reproduce the problem

Equip the Rune of the Dawn and not get any Scourgestones.

### AC rev. hash/commit

AzerothCore rev. 9ebdbd84593a

### Operating system

Debian 10 x64

### Custom changes or Modules

playerbots
individual-progression
dungeonrespawn
ah-bot
assistant
bg-reward
dynamic-loot-rates
reusablepotion
transmog

**Comment by TheSCREWEDSoftware** [comment] 2024-10-01 10:06
On: AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/bb0d292e1c2bb5619fbc3105e7cd919b45268748 2024-09-22 07:38:46 +0000 (master branch) (Win64, RelWithDebInfo, Static)

Couldn't replicate the said above.

Both the Rune (19812) and the Seal (13209) granted me the "Argent Dawn Commision"

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/321cb4a2-b842-40f0-af41-e1f7af42f57b)

![image](https://github.com/user-attachments/assets/c8f5fb98-ada8-4f32-9f30-047876bdebab)

</details>

**Comment by heyitsbench** [comment] 2024-10-01 11:52
Closing as cannot reproduce. If you are able to mimic the behavior you observed on a clean AC revision, feel free to comment as such.

**Closed by heyitsbench** 2024-10-01 11:52 UTC
