### ISSUE TITLE
enter dungeon Dismount

### ISSUE THREAD

**Issue by catontheway** [azerothcore/azerothcore-wotlk#7928] opened 2021-09-16 16:09 UTC
### Current Behaviour

//enter instance_zulfarrak dismount
        
void OnPlayerEnter(Player* player) override
        {
            //player->Dismount();
            player->RemoveAurasByType(SPELL_AURA_MOUNTED);
        }

it's not working.
![nnnnnn](https://user-images.githubusercontent.com/6520412/133646358-939e4081-290d-411c-b9e6-399820dd3e67.jpg)

### Expected Blizzlike Behaviour

When the player rides into the dungeon on a mount, I hope he can dismount 

### Steps to reproduce the problem

1、Ride into the zulfarrak

### AC rev. hash/commit

AzerothCore rev. 92acf6feb88a+ 2021-08-24 09:38:01 +0000 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1h  22 Sep 2020 (library: OpenSSL 1.1.1h  22 Sep 2020)
Using Boost version: 1.72.0
Using MySQL version: 50731
Using CMake version: 3.18.4
Compiled on: Windows 10.0.19041
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in Data/maps. Total size: 252190595 bytes
vmaps directory located in Data/vmaps. Total size: 658130553 bytes
mmaps directory located in Data/mmaps. Total size: 2196364992 bytes
Using zhCN DBC Locale as default. All available DBC locales: enUS frFR deDE zhCN esES esMX ruRU
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_08_24_00
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

windows 10 x64

**Comment by patou01** [comment] 2021-09-17 16:02
Based on classic, it shouldn't dismount:
https://youtu.be/I9dOA-PktnM?t=37

ZF is outdoors, I'm not sure why it should dismount since a mount is allowed inside.

I feel it being in code is wrong and it not working is bad, though I would expect that what was needed was the call to dismount(). 

Do you have a source that entering should dismount?

**Comment by catontheway** [comment] 2021-09-18 13:36
@patou01 thanks for your reply.
yes,it shuldn't dismount.But I want to figure out the reason, why it‘s not working.
dismount() and player->RemoveAurasByType(SPELL_AURA_MOUNTED) ，I have tried both of these two methods，but none of them work。if you have good idea,pls tell me.thank you very much

**Comment by Ragelezz** [comment] 2021-09-21 17:06
You get dismount at the moment when you get into a dungeon or raid. Tested: zul'farak and zul'gurub both are outdoor dungeons. So, how it should be ? If you enter an outdoor dungeon you SHOULD or NOT be dismounted ?

**Comment by catontheway** [comment] 2021-09-22 08:38
@Ragelezz thanks for your reply.
As you said，enter an outdoor dungeon,it shoule be not dismount. it‘s ’normal.
but i want to know..........
Is there any solution to complete this function(enter zul'farak dismount)？
thanks again..

**Comment by Ragelezz** [comment] 2021-09-22 17:50
So.. what is your question or issue exactly ? Why that function is not working or ? It is, you get dismounted on outdoor dungeons. Tell the exact issue if it is one ingame.

**Comment by patou01** [comment] 2021-09-22 17:59
@Ragelezz, for some reason, he's trying to dismount people in ZF (custom event?). It seems calling player->dismount() doesn't actually dismount them, that's quite interesting.

**Comment by Ragelezz** [comment] 2021-09-22 18:02
On my local (update to this repo) it does dismount players upon entering.

**Comment by Ragelezz** [comment] 2021-09-22 18:23
Hmm, yea, it seems to be mount specific issue; for example on Invincible and Black Qiraji Battle Tank I get dismounted but while on Kodo and Skeletal Warhorse I'm not. Will have a look either tonight or tomorrow after work on this.

**Comment by catontheway** [comment] 2021-09-22 20:24
@patou01 @Ragelezz thanks guys.
as patou said,this is my  custom modoule,i hope people goto the zf and dismount.

**Comment by patou01** [comment] 2021-09-24 15:52
So I think there's a hack that has been made somewhere, I'm not able to find it yet.
When you enter ZF, you get dismounted and remounted **if** your mount was a certain value. So a mammoth gets remounted, but not a qiraji battle tank.

**Comment by patou01** [comment] 2021-09-24 19:25
@catontheway , a temporary solution seems to be: 
````
        void OnPlayerEnter(Player* player) override
        {
            player->RemoveAurasByType(SPELL_AURA_MOUNTED);
            player->SetMountBlockId(0);
            player->Dismount();
        }
````
However, I have a feeling that you should be using some kind of module and hook instead of modifying in ZF.cpp, but that's ok as long as azerothcore doesn't get modifications in that file.

Let me know if that fits your needs, note that maybe this could create issues so don't just throw it in a server with too many people initially. Do some testing.

**Comment by patou01** [comment] 2021-10-31 19:08
We're usually reachable on discord or here on github :) I'll close the issue as it's not an issue in the sense of azerothcore (we don't need to dismount in ZF so the server is working as intended). Good luck!

**Closed by patou01** 2021-10-31 19:08 UTC
Labels: Instance - Dungeon - Vanilla, Not confirmed
