### ISSUE TITLE
[server] world server crash 0524-2

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11865] opened 2022-05-25 00:50 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/a9cdd1b116686c1d6173da291e4ab2f9

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/324112ff4fcb52416dea7444c9c80a7781b57ebf

### Operating system

Ubuntu20.04

**Comment by UltraNix** [comment] 2022-05-28 09:11
Duplicate of #11650

**Closed by UltraNix** 2022-05-28 09:11 UTC
