### ISSUE TITLE
Bug CorpoReality boss Healion raid wip, not removed in restart  

### ISSUE THREAD

**Issue by NordiKi** [azerothcore/azerothcore-wotlk#7485] opened 2021-08-21 16:10 UTC
### Current Behaviour

We came across a bug,
When Wiping the raid in Phase 3... when Buff Corporeality starts,
As soon as the Wipa raid, and everyone returning to the boss, it was transparent and with the Corporeality Buff activated... even so we started the boss again... and so repeatedly in the 3rd phase it duplicates the Corporeality buff

The correct thing would be for the boss to restart without the buff and it is not happening
The boss is not resetting the Coporeality

![WoWScrnShot_081721_232132](https://user-images.githubusercontent.com/89305735/130327847-340d93b1-3708-4af4-a1bc-3b59019a5c63.jpg)

### Expected Blizzlike Behaviour

The correct thing is when everyone in the raid (Wipar) the boss is reset (remove) without the corporeality buff

### Steps to reproduce the problem

we don't have a problem in the raid except this problem with the buff of not resetting when the raid wipes

### Extra Notes

Spell buff: https://www.wowhead.com/spell=74826/corporeality#comments
Npc boss: https://www.wowhead.com/npc=39863/halion

### AC rev. hash/commit

to be able to remove the Corporeality buff just executing the command .die and .respaw

### Operating system

win 10

**Comment by Kitzunu** [comment] 2021-08-21 19:06
Add hash/commit revision

**Comment by steenburgh** [comment] 2021-08-23 02:56
Duplicate of #7496

**Closed by steenburgh** 2021-08-23 02:56 UTC
Labels: Invalid-MissingHash/Commit
