### ISSUE TITLE
Loading Transports... Segmentation fault 

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2268] opened 2019-09-06 05:43 UTC
Loading Transports... Segmentation fault 

I updated my server to the latest commit and i suddenly get this when i start worldserver:

> Battlefield : Wintergrasp successfully initiated.
> Loading Transports...
> Segmentation fault (core dumped)

I also tried a fresh git clone https://github.com/azerothcore/azerothcore-wotlk.git
and produce same one.

I tried searching on discord @masterking32  and @ArashGorge  had the same issue before? But i am unsure how did they fix it. Maybe someone has any ideas here.

![master](https://user-images.githubusercontent.com/18629476/64403790-7b1d9780-d0ac-11e9-96e1-f7e5096a4424.png)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

3aeb2e564d43a3be06e4cc8bec9de7841a111f0e

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by ArashGorge** [comment] 2019-09-06 05:56
Did you update your database to the latest version? ,
In fact the server I was using was weak, I changed my server, tried again with the new kernel and database version, my problem was solved!

**Comment by andoys** [comment] 2019-09-06 06:01
@ArashGorge  yes i updated via sql please check discord

**Comment by Viste** [comment] 2019-09-06 20:34
any custom patches? modules? etc?

**Comment by poszer** [comment] 2019-09-06 21:52
Revert some days (3-5) and you'll fix problem ;) @andoys

**Comment by funar** [comment] 2019-09-07 01:45
I had the same issue, but did a fresh checkout and all was well again.  I'm not running any mods or local changes, either.  Odd issue, for sure, but _something_ must have been hanging in there that shouldn't have.

**Comment by Stoabrogga** [comment] 2019-09-07 06:03
I'm currently on f876cdda718f2e41fb7ae41215c824ca2ce2e8d7 with clean build (deleted my build directory) and fresh DB, no issues so far.

**Comment by brussens** [comment] 2019-09-07 14:49
@poszer Why are you laughing? A man has created a theme on a certain problem and, apparently, understands what he is doing. @Viste also asked a quite adequate and specific question, what is shitty about the fact that he decided to help the author? Or is it better in your understanding to offend the author, we will offer him to come back here in a week? Is it OpenSource or what? I don't understand why this reaction to this Issue? Please, if you don't have anything to say about the topic, don't strain your fingertips trying to write useless senseless shit.

**Comment by FrancescoBorzi** [comment] 2019-09-07 15:34
When you say:

> Revert some days (3-5) and you'll fix problem

you are implicitly saying that there is some issue in one of the commits of the last 3-5 days.

Of course that's always possible, but one should not limit to say that but instead report which commit is suspected to be faulty so it can be fixed or reverted.

**Comment by poszer** [comment] 2019-09-07 22:21
> I don't understand why this reaction to this Issue?

I think you re blind :D
Where you see reaction on Issue ?

**Comment by poszer** [comment] 2019-09-07 22:24
> When you say:
> 
> > Revert some days (3-5) and you'll fix problem
> 
> you are implicitly saying that there is some issue in one of the commits of the last 3-5 days.
> 
> Of course that's always possible, but one should not limit to say that but instead report which commit is suspected to be faulty so it can be fixed or reverted.

Yes ofc there is issue :)

**Comment by poszer** [comment] 2019-09-07 22:33
Delete more comments which you don't like :) Ac Logic haha

**Comment by poszer** [comment] 2019-09-07 22:42
> @poszer Why are you laughing? A man has created a theme on a certain problem and, apparently, understands what he is doing. @Viste also asked a quite adequate and specific question, what is shitty about the fact that he decided to help the author? Or is it better in your understanding to offend the author, we will offer him to come back here in a week? Is it OpenSource or what? I don't understand why this reaction to this Issue? Please, if you don't have anything to say about the topic, don't strain your fingertips trying to write useless senseless shit.

See , i replied to you. But they deleted my comment. Sad AC logic :)

**Comment by andoys** [comment] 2019-09-09 03:00
currently out of town. i reverted back to and older commit and worked

**Comment by Nefertumm** [comment] 2020-01-19 10:14
Still valid?

**Comment by Endeffect-AT** [comment] 2020-01-19 10:38
Can't confirm on commit bb42c7c+ 

Win 10 pro 64 bit

![](https://i.imgur.com/5ZVF61W.jpg)

**Comment by FrancescoBorzi** [comment] 2020-01-19 16:06
Closing as unable to reproduce.

If you know how to reproduce this issue, please open a new one and **include the reproduction steps**.

**Closed by FrancescoBorzi** 2020-01-19 16:06 UTC
