### ISSUE TITLE
[Warrings] in to build

### ISSUE THREAD

**Issue by tatense** [azerothcore/azerothcore-wotlk#3148] opened 2020-06-21 10:15 UTC
last version have warrings in to build

![Untitled](https://user-images.githubusercontent.com/47708113/85222029-c6036400-b3cd-11ea-8a8b-5a13701d4db3.png)

Os: linux ubt 20
version: https://github.com/azerothcore/azerothcore-wotlk/commit/139743004bd28fb046d5637bd0dac98b3caa73c6

**Comment by FrancescoBorzi** [comment] 2020-06-21 10:23
duplicate of: https://github.com/azerothcore/azerothcore-wotlk/issues/3108

also please, for future, include your errors **as text** (you can also add images but we need the text)

**Closed by FrancescoBorzi** 2020-06-21 10:23 UTC
