### ISSUE TITLE
achivement glory Boss Jedoga Shadowseeker Dungeon Ahn Kahel The Old Kingdom

### ISSUE THREAD

**Issue by fantomlancer** [azerothcore/azerothcore-wotlk#13117] opened 2022-09-24 13:26 UTC
### Current Behaviour

problem for take achivement glory Boss Jedoga Shadowseeker Dungeon Ahn Kahel The Old Kingdom boss not started for glory

### Expected Blizzlike Behaviour

Defeat Jedoga Shadowseeker in Ahn'kahet on Heroic Difficulty without killing any Twilight Volunteers
https://www.youtube.com/watch?v=5JsA-jhisRY
time video 1:04 started 1:27 Finish

### Source

https://www.wowhead.com/achievement=2056/volunteer-work

### Steps to reproduce the problem

Defeat Jedoga Shadowseeker in Ahn'kahet on Heroic Difficulty without killing any Twilight Volunteers

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

windows 10

**Comment by LukasVolgger** [comment] 2022-09-24 14:40
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13071

**Closed** 2022-09-24 14:40 UTC
Labels: Invalid-Duplicate
