### ISSUE TITLE
Are default users, like test1, test2 neccessary?

### ISSUE THREAD

**Issue by arenacraftwow** [azerothcore/azerothcore-wotlk#2760] opened 2020-03-14 11:42 UTC
Hi, I booted up a basic AzerothCore install and I noticed that by default I get some accounts with hashed passwords, and more importantly GM privileges. 

![image](https://user-images.githubusercontent.com/61932925/76681176-63414600-65f0-11ea-9a58-b480eb7e311f.png)

I couldn't find any references to those account names in the code, are those necessary? Is it safe to delete them? 

https://github.com/azerothcore/azerothcore-wotlk/search?q=test1&type=Code
https://github.com/azerothcore/azerothcore-wotlk/search?q=test10&unscoped_q=test10&type=Code

As you can see, other than their creation there are no references to them. If they serve some purpose I suggest documenting it and making it explicit.

**Comment by FrancescoBorzi** [comment] 2020-03-14 12:08
@arenacraftwow welcome here.

To answer your question: no they are not necessary and you can safely delete them.

However, this issue is not a bug report bug a support question so it should not belong to the github report. So I'll close it. Please read:

https://www.azerothcore.org/wiki/How-to-ask-for-help

if you have more questions, feel free to ask them in stackoverflow and we will help you

**Closed by FrancescoBorzi** 2020-03-14 12:08 UTC

**Comment by BarbzYHOOL** [comment] 2020-03-14 18:36
if i recall they are written in the wiki, but not sure, you should add a line about it in installation if missing
