### ISSUE TITLE
Core/BossAI: Bosses do not reset on wipes

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15379] opened 2023-03-14 03:48 UTC
### Current Behaviour

When you are in the encounter with Halion and you reach the third phase and receive more damage from the players of any of the two kingdoms, for example you bring the corporability to 20%/80% and all the players die when they revive and go from Back to the fight with Halion it stays as if you were in 3rd phase with the corporality that stayed in the previous event and it does more damage to you and it starts to heal itself and it starts to spam every x seconds "Your (or your companion's) efforts have forced Halion further <into/out of> the <Twilight/Physical> realm!"

### Expected Blizzlike Behaviour

when dying and starting the event again, it must start normal without maintaining any corporeality from the previous event

### Source

https://wowwiki-archive.fandom.com/wiki/Halion

### Steps to reproduce the problem

1. Go Halion
2. Enter combat and dies in 3rd phase when the corporatability is different from 50/50
3. revive 
4. enter combat again, lower his health a bit and wait until he starts to regenerate

### Extra Notes

This I think gets corrupted when after applying this change #14789 by @Nyeriah

### AC rev. hash/commit

6a66b36a5d5cba8bab9fb62e0e0680cd5c94c4ab

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment] 2023-03-16 09:39
Can you test the issue by removing commits until you find the faulty one? I have high doubts that https://github.com/azerothcore/azerothcore-wotlk/commit/bf30c66ba48cede909a98cb132959c979c032b3b is the culprit as the bosses themselves are not touched by these changes

**Comment by Kitzunu** [comment] 2023-03-17 01:35
@UltraNix perhaps you want to take a look?

**Comment by UltraNix** [comment] 2023-03-18 07:57
Perhpas it's not a generic problem, but it's something within the scripts.

**Comment by Kitzunu** [comment] 2023-03-18 08:49
Could be. At first it looked generic though.

**Comment by UltraNix** [comment] 2023-03-18 09:06
f59ee4ef7cc455fc300ed0741ac635c8e1f03fe3
Check this one

**Comment by Tony931023** [comment] 2023-03-18 15:04
@Kitzunu @UltraNix confirmed, this is corrupted by applying this https://github.com/azerothcore/azerothcore-wotlk/commit/f59ee4ef7cc455fc300ed0741ac635c8e1f03fe3 by  @Nyeriah 

tested on some bosses:

Halion -> what is said in this issue happens #15379
Lich King-> what is said in this issue happens  #15388
Sindagosa ->  what is said in this issue happens  #15410

**Comment by yukijean** [comment] 2023-03-19 17:27
@Tony931023 Hey buddy, did you miss out on my # 15382 question?

**Comment by Tony931023** [comment] 2023-03-19 17:34
> @Tony931023 Hey buddy, did you miss out on my # 15382 question?

Update https://github.com/azerothcore/azerothcore-wotlk/issues/15379#issuecomment-1474873514

**Comment by yukijean** [comment] 2023-03-20 13:28
@Kitzunu @UltraNix @Tony931023 Three brothers, please tell me when the bug in LK Algalon and Cindagosa is expected to be repaired. Thank you.

**Comment by Nyeriah** [comment] 2023-03-20 13:50
@yukijean Please don't ping random people and don't ask thigns to be fixed. If you'd like to see something fixed without contributing, you may place a bounty on it.

As for this issue, I will address it when I find the time.

**Comment by yukijean** [comment] 2023-03-20 14:24
@Nyeriah OK， THANK YOU

**Comment by Nyeriah** [comment] 2023-03-21 18:06
https://github.com/azerothcore/azerothcore-wotlk/pull/15507

**Closed by Nyeriah** 2023-03-21 18:06 UTC
Labels: Confirmed, Priority-High

**Comment by yukijean** [comment] 2023-03-22 04:25
Hello, I'm not trying to urge you, but seeing that you have fixed two boss issues that are very serious, I still want to ask, Olgaren, has the issue of not refreshing been resolved in this update? Thank you very much


---Original---
From: ***@***.***&gt;
Date: Wed, Mar 22, 2023 02:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [azerothcore/azerothcore-wotlk] Core/BossAI: Bosses do not reseton wipes (Issue #15379)




 
#15507

**Comment by heyitsbench** [comment] 2023-03-22 04:54
> Hello, I'm not trying to urge you, but seeing that you have fixed two boss issues that are very serious, I still want to ask, Olgaren, has the issue of not refreshing been resolved in this update?

Doesn't look like it. [That issue](https://github.com/azerothcore/azerothcore-wotlk/issues/15382) does need to be reopened, as it was closed for being a duplicate of this one.

**Comment by yukijean** [comment] 2023-03-22 05:02
Could you tell me how to reopen it


---Original---
From: "Benjamin ***@***.***&gt;
Date: Wed, Mar 22, 2023 12:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [azerothcore/azerothcore-wotlk] Core/BossAI: Bosses do not reseton wipes (Issue #15379)




  
Hello, I'm not trying to urge you, but seeing that you have fixed two boss issues that are very serious, I still want to ask, Olgaren, has the issue of not refreshing been resolved in this update?
  
Doesn't look like it. That issue does need to be reopened, as it was closed for being a duplicate of this one.

**Comment by yukijean** [comment] 2023-03-22 14:04
@Tony931023 Hello, did you see the last 10% or so of the time when you tested the Lich King again, and the NPC disappeared without triggering the plot. In P3, the previously disappeared floor was restored~~

**Comment by Tony931023** [comment] 2023-03-22 14:12
> Hello, did you see the last 10% or so of the time when you tested the Lich King again, and the NPC disappeared without triggering the plot. In P3, the previously disappeared floor was restored~~

I'll try that later now

**Comment by yukijean** [comment] 2023-03-22 14:39
Thank you very much. If the test is complete and convenient, you can reply and observe that the terrain lost on P2 will be restored on P3, and then 10% NPC will disappear.

**Comment by yukijean** [comment] 2023-03-23 03:45
@Tony931023 #15542 15542，Hello, you have time to watch. Someone uploaded a video and encountered the same problem.

**Comment by yukijean** [comment] 2023-03-23 03:46
@Tony931023 #15542 15542，Hello, you have time to watch. Someone uploaded a video and encountered the same problem.
