### ISSUE TITLE
[server]world server crash 1103

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#13666] opened 2022-11-03 12:07 UTC
### Current Behaviour

crash log :

https://gist.github.com/mpfans/89f1b78ce529c8bfb0f4e823a762a433

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

77a52b8

### Operating system

Ubuntu20.04

**Comment by Kitzunu** [comment] 2022-11-06 17:57
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13172

**Closed by Kitzunu** 2022-11-06 17:57 UTC
