### ISSUE TITLE
quest:The Drakkensryd (id 12886) can't completed

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5929] opened 2021-05-18 03:31 UTC
**CURRENT BEHAVIOUR:**
get quest:The Drakkensryd (id 12886) ,riding drake,can't attack Hyldsmeet Drakerider,tip: too far away
**EXPECTED BLIZZLIKE BEHAVIOUR:**
get quest:The Drakkensryd (id 12886) ,riding drake,attack Hyldsmeet Drakerider,complete this quest 

**STEPS TO REPRODUCE THE PROBLEM:**

1. get quest:The Drakkensryd (id 12886)
2. riding a drake
3. attack Hyldsmeet Drakerider

**AC HASH/COMMIT:**
681c3237dfaf46bcad02f00ce717b97bdd899f40
**OPERATING SYSTEM:**
ubuntu 20.04
**MODULES:**
none

**Comment by Eldarix** [comment] 2021-05-18 04:03
Can you please not delete the necessary categories that have to be filled in? Thank you

**Comment by mpfans** [comment] 2021-05-18 04:05
> Can you please not delete the necessary categories that have to be filled in? Thank you

What are the necessary categories?

**Comment by Eldarix** [comment] 2021-05-18 04:11
Everything you have preset at the initial template when you open a new issue.

**Comment by mpfans** [comment] 2021-05-18 04:28
> Everything you have preset at the initial template when you open a new issue.

Sorry, I think I've provided all the information

**Comment by Maurowin** [comment] 2021-05-18 08:09
i can confirm, we are far away to attack. And we don't aggro PNJ too
b2ab5dba79c1

**Comment by Eldarix** [comment] 2021-05-18 09:16
> 
> 
> > Everything you have preset at the initial template when you open a new issue.
> 
> Sorry, I think I've provided all the information

No problem at all mate, just for helping the devs with the organizing ;)

**Comment by UltraNix** [comment] 2021-06-16 14:34
63a273507c753e6d130e8ae2dd7d9d15bf2dd02b is the cause.
The problem here is the order of processed packets. It should be like this:
launching spline (entering vehicle) --> triggerring CMSG_MOVE_CHNG_TRANSPORT --> serverside spline finished --> triigering CMSG_SPLINE_DONE. But now its: launching spline --> serverside spline finished --> CMSG_MOVE_CHNG_TRANSPORT --> CMSG_SPLINE_DONE. It's something that packets received from client are delayed.

**Comment by Azcobu** [comment] 2021-06-16 14:52
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5891
@UltraNix copying your comment to that ticket too as it looks to be important.

**Closed** 2021-06-16 17:37 UTC
Labels: Confirmed, Invalid - Duplicate, Quest
