### ISSUE TITLE
[RAID] UBRS Orc mobs don't always attack

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#606] opened 2017-09-07 13:32 UTC
**Description**:  Several of the groups in the starting area do not attack. Some will reset and then attack after, and some just sit there idle while you're killing the others in the group. This was most noticeable with the Dreadweaver and Summoners, but also occurred with the warriors.

You can be inside one of the room with the runes and killing the warriors and a few of the spellcasters will just sit there.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by poszer** [comment] 2019-02-07 08:00
Can't reproduce. Closing

**Closed by poszer** 2019-02-07 08:00 UTC
Labels: Instance - Raid - Vanilla, Priority - Low
