### ISSUE TITLE
dungeons Halls of Stone The main problem is the bronze beard He disappears after the boss starts

### ISSUE THREAD

**Issue by fantomlancer** [azerothcore/azerothcore-wotlk#13120] opened 2022-09-24 13:33 UTC
### Current Behaviour

Problem for dungeons Halls of Stone last boss Sjonnir The Ironshaper
The main problem is the bronze beard He disappears after the boss starts
He must be alive until the last moment when the boss is killed to finish the quest

### Expected Blizzlike Behaviour

Bronzebeard must survive until the last moment when the boss is killed to complete the quest

### Source

https://www.wowhead.com/wotlk/npc=27978/sjonnir-the-ironshaper
https://www.wowhead.com/wotlk/achievement=2154/brann-spankin-new

### Steps to reproduce the problem

Bronzebeard must survive until the last moment when the boss is killed to complete the quest
https://www.youtube.com/watch?v=YR3ieuowaYQ
time started 20:22 finished 24:29

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

windows 10

**Comment by LukasVolgger** [comment] 2022-09-24 14:35
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/13079

**Closed** 2022-09-24 14:35 UTC
Labels: Invalid-Duplicate
