### ISSUE TITLE
Feature: Waypoint smooth node transition

### ISSUE THREAD

**Issue by aleigood** [azerothcore/azerothcore-wotlk#14523] opened 2023-01-06 10:35 UTC
### Describe your feature request or suggestion in detail

This commit allows NPC to walk more smoothly between waypoint, rather than playing animation from scratch at each waypoint. hope it can be backport.

```
Transition to next node should be now more smooth without letting the client start playing animation mode.
This should also slightly improve follower movements.

Idea is to send next waypoint node path to client before the reach of


```
https://github.com/cmangos/mangos-tbc/commit/bff8238b90485ebb4d810802b992443a99f47cde

**Comment by Kitzunu** [comment] 2023-01-06 11:18
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/10096

**Closed by Kitzunu** 2023-01-06 11:18 UTC
Labels: Suggestion, Invalid-MissingHash/Commit
