### ISSUE TITLE
[Area] Kirin'var Village in Netherstorm. Collisions Mess. Quest items inaccessible.

### ISSUE THREAD

**Issue by CyberFoxHax** [azerothcore/azerothcore-wotlk#3818] opened 2020-12-01 09:02 UTC
![image](https://user-images.githubusercontent.com/7734690/100718614-81590b80-33f6-11eb-8fdb-084c9964889f.png)
![image](https://user-images.githubusercontent.com/7734690/100718649-8ae27380-33f6-11eb-849d-c8c3ec8bdc19.png)

There are a few quest items that and bosses in the houses that you can't access because the doors are blocked. Almost all houses have this issue. I managed to complete the quest by using Blink to get past the invisible walls.

##### OPERATING SYSTEM:
Server: Debian 10
Client: Windows 10

##### AC HASH/COMMIT:
e1bf18374124ff05ab41f8014f001d27af1ab865

**Comment by LukasVolgger** [comment] 2020-12-01 10:10
Hello @CyberFoxHax. 

Could you please add more information about which quests it depends? So it's hard to reproduce.

Note: I did every quest in this area and noticed no bug as you describe.

**Comment by CyberFoxHax** [comment] 2020-12-01 11:43
https://wow.gamepedia.com/Destroy_Naberius! is one
there also another quest where you need to pick up books in the houses. Which i can't enter.

Just try to enter a few houses. If you have no problem i think it's just me. I don't know how the collision data looks, whether or not it's even part of AzerothCore.

**Comment by LukasVolgger** [comment] 2020-12-01 12:18
Tested Quest 10320 https://www.wowhead.com/quest=10320/destroy-naberius and i cannot reproduce this issue. 

I also entered every house in that zone without any problems. 

Closing this as there is no issue.

**Closed by LukasVolgger** 2020-12-01 12:18 UTC
Labels: Invalid - CannotReproduce, Not confirmed
