### ISSUE TITLE
Undertaker Mordo/Megelon wrong coordinates

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4512] opened 2021-02-09 02:32 UTC
Originally reported https://github.com/chromiecraft/chromiecraft/issues/62

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
Undead starting zone: Undertaker Mordo was moved to in front of the spawn point in 3.3

Draenei starting zone:  Megelon was moved to just next to the spawn point in 3.3.5

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Both NPCs should be right next to the spawn point.

##### CURRENT BEHAVIOUR:
As above

##### STEPS TO REPRODUCE THE PROBLEM:
1. Start fresh UD character
2. Run out of the tomb and at the top
3. Talk to Undertaker Mordo / Read "rude awakening".

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment] 2021-02-09 02:33
I confirm, the NPC [Undertaker Mordo](https://wotlkdb.com/?npc=1568) 

who gives the Undead Starter quest [Rude Awakening](https://wotlkdb.com/?quest=363)
 **is in the wrong coordinate.**
 **Video** of my **Test**: [Undertaker Mordo](https://youtu.be/touQVsCOIXg)

**Comment by Voxstrasza** [comment] 2021-02-09 02:40
Confirmed, this NPC was moved right in front of the spawn point for new Undead characters some time in WotLK

https://wow.gamepedia.com/Talk:Undertaker_Mordo

**Comment by Voxstrasza** [comment] 2021-02-09 02:49
@Stifler82 can you add this NPC to your issue, too?  he's in the wrong place as well https://www.wowhead.com/npc=16475/megelon#comments

In 3.3 they moved some starter NPCs closer to the spawn.  Undertaker Mordo and Megelon are two of them

**Comment by Stifler82** [comment] 2021-02-09 03:14
> @Stifler82 can you add this NPC to your issue, too? he's in the wrong place as well https://www.wowhead.com/npc=16475/megelon#comments
> 
> In 3.3 they moved some starter NPCs closer to the spawn. Undertaker Mordo and Megelon are two of them

Sorry, what do you mean "to your issue"?
Inside the forum of **Chromiecraft**? or **here** in this forum? or in **this post**? or **something else**?

**Comment by Voxstrasza** [comment] 2021-02-09 03:17
Nevermind, i did it.  :)

**Comment by Zoidwaffle** [comment] 2021-02-11 13:00
Hm, I tried to find out where Undertaker Mordo should be.

But are we sure he he should be moved? According to this, from Cata, he has indeed moved: https://www.youtube.com/watch?v=CZqW3u0mQk4

However, you don't spawn in the crypt in the video... And last I checked, you still spawn down in the crypt and not outside in the GY.

So if he's moved, I guess the starting spawn point should be moved as well? Could the issue be whatever addon you are using is based on too new data? (I forgot if it's Questie or whatever that has those arrows).

**Comment by Zoidwaffle** [comment] 2021-02-11 13:20
And rambling on here...

Megelon was also moved in later expansions. From Warlords: https://www.youtube.com/watch?v=T_N08d9wvzY

But moving him doesn't seem to "break" things, so let me make a PR for that one.

**Comment by Voxstrasza** [comment] 2021-02-11 14:02
> 
> 
> And rambling on here...
> 
> Megelon was also moved in later expansions. From Warlords: https://www.youtube.com/watch?v=T_N08d9wvzY
> 
> But moving him doesn't seem to "break" things, so let me make a PR for that one.

There was no official documentation on this, but they were moved in 3.3 and 3.3.5 (undertaker, megelon respectively).  Multiple wowhead comments from the era confirm this.

**Comment by Zoidwaffle** [comment] 2021-02-11 14:41
@Voxstrasza - OK, I can move the Undertaker guy as well. But I assume not to touch the spawning location for undeads then.

I might need to remove a grave or two, from the video it seems like he stands where there's one now at least.

**Comment by Voxstrasza** [comment] 2021-02-11 15:13
> 
> 
> @Voxstrasza - OK, I can move the Undertaker guy as well. But I assume not to touch the spawning location for undeads then.
> 
> I might need to remove a grave or two, from the video it seems like he stands where there's one now at least.

I don't think the grave is relevant.  Undertaker simply spawns right in front of the player spawn.  https://youtu.be/ShNqq9BnNsw?t=276 <- this is a TC video, but the correct area.

**Comment by Zoidwaffle** [comment] 2021-02-11 15:53
Ah, yeah, that's a totally different place than the one in the cata video I found. Seeing that, I misunderstood @Stifler82 I think... I will update the PR later!

**Comment by Zoidwaffle** [comment] 2021-02-11 19:37
OK, I made another PR since the old one was already marked as ready to merge.

So all should be good regarding this now!

**Closed** 2021-02-12 14:19 UTC
Labels: 1-19, Confirmed
