### ISSUE TITLE
Demolitionist Legoso incorrect texts & timings during quest "Ending Their World" [$5]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4580] opened 2021-02-15 16:58 UTC
Demolitionist Legoso incorrect texts & timings during quest "Ending Their World"

##### CURRENT BEHAVIOUR:

He speaks too early, and counts down "3, 2," fights for 15 mins, reaches the top "1, boom". 

The last fight contains a $N instead of a name.

Last fight a bit buggy / weird.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://www.wowhead.com/npc=17982/demolitionist-legoso

https://www.wowhead.com/quest=9759/ending-their-world#

https://www.youtube.com/watch?v=lARzK9CLu24

##### STEPS TO REPRODUCE THE PROBLEM:

1. Begin quest Ending Their World
2. Observe dialogue/triggered events.
3. Drink water and stay healthy.

##### AC HASH/COMMIT:

ChromieCraft latest.

AzerothCore rev. 21f828847f42 2021-02-14 

##### MODULES:

CFBG

**Comment by cjb3768** [comment] 2021-02-15 17:33
Can confirm presence of bug

**Comment by branel** [comment] 2021-04-14 17:18
This quest works fully as intended, I am not sure what has changed since you first posted it but I just completed it just like it was shown in the video you linked.
AC rev c49f687668a1

**Comment by Branel** [comment] 2021-04-29 14:17
please close this @FrancescoBorzi @Kitzunu

**Closed** 2021-04-29 16:24 UTC
Labels: 1-19, Bounty, Confirmed, Good first issue, Priority - Low
