### ISSUE TITLE
How do you restart/reset an arena season properly?

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2372] opened 2019-10-22 06:58 UTC
Server was up with this setting.
Arena.ArenaSeason.InProgress = 1

i changed it to
Arena.ArenaSeason.InProgress = 0

restarted server

then i set it to
Arena.ArenaSeason.InProgress = 1 

again restarted server

Tema ratings still there
Do i delete the team ratings manually? or ?
Also after a season ends, people should get titles,rewards. so far nothing

**Comment by smansesdottk** [comment] 2019-10-22 09:11
I think you should delete team ratings manually, and give rewards, titles to player before activate new season.

**Comment by andoys** [comment] 2019-10-22 09:27
Ah so it's not automatic? :( darn

**Comment by Malow** [comment] 2019-10-27 17:53
There's a game_event table which has arena seasons in it, I'm not sure if changing their start/end times makes some automatic things happen though.

**Comment by Kitzunu** [comment] 2020-04-23 12:41
You link it from game_event to game_event_arena_season

I would believe you would need to manually reset the ratings, or delete all existing teams.

I will close this as it is not a bug, this is more a conversation for Stackoverflow or the [forum](https://github.com/azerothcore/forum)

**Closed by Kitzunu** 2020-04-23 12:41 UTC
