### ISSUE TITLE
DB/Misc: Grimtotem Naturalist

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#540] opened 2017-08-05 20:00 UTC
**Description**: This mob in feralas is scripted in SAI (smart_scripts table)
when he's in tauren form he acts like he's a bear in melee but when he's in bear form he acts like he's tauren and casts from distance. That's why they don't move when you go a bit far from them.

**Current behaviour**: 
He doesn't shift in bear form while having the bear form buff. He uses bear attacks
If you die or flee or put gm on, he goes into bear form but casts spells...

**Expected behaviour**: The opposite

**Steps to reproduce the problem**:

1. .npc add 7726
2. he has bear form and doesn't shift into bear
3. flee or die and see him transforming into bear but then he casts tauren form spells -__-

**Branch(es)**: master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  from july 2017

**Comment by d3tr0l** [comment] 2017-11-12 20:47
I have tested the SAI fix for this from TC, it is not working either.

`
-- Grimtotem Naturalist SAI
SET @ENTRY := 7726;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,4,0,100,1,0,0,0,0,22,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - On Aggro - Set Event Phase 1 (No Repeat)"),
(@ENTRY,0,1,0,4,1,100,1,0,0,0,0,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - On Aggro - Disable Combat Movement (Phase 1) (No Repeat)"),
(@ENTRY,0,2,0,4,1,100,1,0,0,0,0,11,9739,0,0,0,0,0,2,0,0,0,0,0,0,0,"Grimtotem Naturalist - On Aggro - Cast 'Wrath' (Phase 1) (No Repeat)"),
(@ENTRY,0,3,0,9,1,100,0,0,40,3400,4700,11,9739,0,0,0,0,0,2,0,0,0,0,0,0,0,"Grimtotem Naturalist - Within 0-40 Range - Cast 'Wrath' (Phase 1)"),
(@ENTRY,0,4,0,9,1,100,0,40,100,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Within 40-100 Range - Enable Combat Movement (Phase 1)"),
(@ENTRY,0,5,0,9,1,100,0,10,15,0,0,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Within 10-15 Range - Disable Combat Movement (Phase 1)"),
(@ENTRY,0,6,0,9,1,100,0,0,40,0,0,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Within 0-40 Range - Disable Combat Movement (Phase 1)"),
(@ENTRY,0,7,0,3,1,100,0,0,15,0,0,22,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 0-15% Mana - Set Event Phase 2 (Phase 1)"),
(@ENTRY,0,8,0,3,2,100,0,0,15,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 0-15% Mana - Enable Combat Movement (Phase 2)"),
(@ENTRY,0,9,0,3,2,100,0,30,100,100,100,22,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 30-100% Mana - Set Event Phase 1 (Phase 2)"),
(@ENTRY,0,10,0,7,1,100,1,0,0,0,0,22,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - On Evade - Set Event Phase 0 (Phase 1) (No Repeat)"),
(@ENTRY,0,11,12,2,1,100,1,0,50,0,0,22,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 0-50% Health - Set Event Phase 3 (Phase 1) (No Repeat)"),
(@ENTRY,0,12,13,61,1,100,1,0,50,0,0,11,19030,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 0-50% Health - Cast 'Bear Form' (Phase 1) (No Repeat)"),
(@ENTRY,0,13,0,61,1,100,1,0,50,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 0-50% Health - Enable Combat Movement (Phase 1) (No Repeat)"),
(@ENTRY,0,14,0,0,4,100,0,3000,4500,12000,13000,11,12161,0,0,0,0,0,2,0,0,0,0,0,0,0,"Grimtotem Naturalist - In Combat - Cast 'Maul' (Phase 4)"),
(@ENTRY,0,15,0,0,4,100,0,8000,9000,25000,26000,11,15727,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - In Combat - Cast 'Demoralizing Roar' (Phase 4)"),
(@ENTRY,0,16,0,7,4,100,1,0,0,0,0,28,19030,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - On Evade - Remove Aura 'Bear Form' (Phase 4) (No Repeat)"),
(@ENTRY,0,17,0,7,4,100,1,0,0,0,0,22,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - On Evade - Set Event Phase 0 (Phase 4) (No Repeat)");
`

Above, from TC official repo, not working, it should work on TC, but i have not tested it yet, mybe the DB is not the issue?

**Comment by BarbzYHOOL** [comment] 2017-11-14 17:40
Yeah we tested this with talamortis long ago too and it didn't work. I didn't want to spend time on that single mob though, sorry but from what I described something was clearly wrong.

I guess you could try to find all druid like NPCs that shift maybe and compare ?

You can also try on our demo server on AC, there is a TC realm (join the discord)

**Comment by d3tr0l** [comment] 2017-11-14 17:47
I will have a look at this over weekend most likely, i am busy atm. There need to be confirmed these following things: 
1. If this is bugged really completely, i mean broken AI and scripting 
2. If the AI and scripting is working and actually it might be only phase model id's bug

But i am afraid the scripting is not working for this NPC completely... x( very strange.

**Comment by BarbzYHOOL** [comment] 2017-11-14 18:26
Maybe try this from today TC fixes

`
-- Grimtotem Naturalist
DELETE FROM `smart_scripts` WHERE `entryorguid`=7726 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(7726,0,0,0,4,0,100,1,0,0,0,0,22,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - On Aggro - Set Event Phase 1"),
(7726,0,1,0,0,1,100,0,0,0,3400,4700,11,9739,64,0,0,0,0,2,0,0,0,0,0,0,0,"Grimtotem Naturalist - In Combat (Phase 1) - Cast Wrath"),
(7726,0,2,0,2,0,100,1,0,50,0,0,22,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 0-50% Health - Set Event Phase 2"),
(7726,0,3,0,0,2,100,1,0,0,0,0,11,19030,1,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - In Combat (Phase 2) - Cast Bear Form"),
(7726,0,4,0,0,2,100,0,5000,7000,11000,13000,11,12161,2,0,0,0,0,2,0,0,0,0,0,0,0,"Grimtotem Naturalist - In Combat (Phase 2) - Cast Maul"),
(7726,0,5,0,0,2,100,0,8000,10000,24000,28000,11,15727,2,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - In Combat (Phase 2) - Cast Demoralizing Roar"),
(7726,0,6,0,0,2,100,1,0,0,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - In Combat (Phase 2) - Enable Combat Movement"),
(7726,0,7,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Grimtotem Naturalist - Between 0-15% Health - Flee For Assist (No Repeat)");
`

**Comment by d3tr0l** [comment] 2017-11-15 19:08
I am working on this, got him rid of the aura before entering combat. Got him go into bear form while below 50% hp or with not enough mana to cast Wrath spell. Having issue with movements while he is in the bear form. Another thing i noticed, the buff itself is ONLY VISUAL, but it should add armor and hp to the caster and it does not. So even when i am done with this fix, the buff itself is bugged and someone should propably open bug report or i will do it myself.

**Comment by d3tr0l** [comment] 2017-11-17 15:20
Ok so i am stuck at this:

https://gist.github.com/d3tr0l/364749964997a9a95a54c54f5afa2739

Do not mind the missing start of phase 2 triggered by low mana, atm the issue is...that the NPC simply would not move CLOSE ENOUGH to engage melee combat...my addon is showing 5y-8y range...if i get little bit closer the NPC starts fighting me as supposed....btw the NPC is finally following the player when engaged in combat...but it is broken. The NPC should not move while in phase 1.

My conclusion is there are 2 ANOTHER BUGS.
First one is, that the core is not handling the smart script AI phasing correctly
Second one is this: https://github.com/TrinityCore/TrinityCore/pull/18128 and the fact that Azeroth Core does not have this implemented ( propably) thus the melee range is not engaging at 5y but instead on 4,5y and that is causing the smart scripts useless, my opinion.

Any reply is welcomed.

**Comment by pondaveia** [comment] 2018-03-08 22:47
These guys are not supposed to run away, other than that the gist fixes this bug! Good job.

**Comment by BarbzYHOOL** [comment] 2018-09-24 19:06
It fixes it for me.

**Closed** 2018-09-24 19:13 UTC
Labels: Area - Classic, DB, Fix included, Good first issue, Needs Testing/Feedback, Priority - Low

**Comment by d3tr0l** [comment] 2018-10-06 14:51
Yes sorry, i tested it again and i must had screwed tables somehow. It is finally working really nice ! :D
