### ISSUE TITLE
[BUG] Core/Class: Agility no added critical chance in char info

### ISSUE THREAD

**Issue by Wowkasu** [azerothcore/azerothcore-wotlk#3198] opened 2020-07-17 20:06 UTC
##### CURRENT BEHAVIOUR:
- A warrior's agility(1) does not add a chance of a critical strike(3)

In the pictures the character has items with agility, when you hover the cursor, we see in the hint (6.81% white arrow number 1) (7.48% red arrow number 1) the chance to make a critical blow due to agility. 
But in general, the chance of a critical strike does not add up (arrow number 3 is red and white).

<details>
<summary>Show screenshots</summary>

![2020-07-18_02-30-48](https://user-images.githubusercontent.com/68443208/87825310-18d31d00-c8a1-11ea-8a6e-0bce62eff9cf.png)
![2020-07-18_02-30-04](https://user-images.githubusercontent.com/68443208/87825318-1bce0d80-c8a1-11ea-96fe-05044960cbb4.png)

</details>
<summary>Show screenshots</summary>

the problem was confirmed in the collection of statistics the estimate should be 50% and we have a lot less critical hits.

<details>
<summary>Show screenshots</summary>

![WoWScrnShot_071720_222557](https://user-images.githubusercontent.com/68443208/87826979-12927000-c8a4-11ea-9036-abf68ed29b00.jpg)
![WoWScrnShot_071720_222601](https://user-images.githubusercontent.com/68443208/87826986-158d6080-c8a4-11ea-8445-229b105706fe.jpg)
![WoWScrnShot_071720_222606](https://user-images.githubusercontent.com/68443208/87826992-17572400-c8a4-11ea-876e-e64523f5c85a.jpg)

</details>

I can't tell you the exact time the problem occurred.
tried on the server updated a week ago (red arrows) and another server a month ago was updated (white arrows). Estimated time the problem appeared 1-2 months ago.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- The values of chance must add up to a chance of agility.

##### STEPS TO REPRODUCE THE PROBLEM:
1. create a warrior of level 80
2. put objects on it with dexterity, but no chance of a critical strike, for example. item id 47314
3. Move your cursor over the agility and look at the percentage of chance of a critical strike (blue arrow №4).

<details>
<summary>Show screenshots</summary>

![2020-07-18_02-57-38](https://user-images.githubusercontent.com/68443208/87826359-f4784000-c8a2-11ea-8ebf-f99ba3ea7362.png)
</details>

4. look at the chance of a critical strike (blue arrow №5).

<details>
<summary>Show screenshots</summary>

![2020-07-18_02-58-22](https://user-images.githubusercontent.com/68443208/87826484-2b4e5600-c8a3-11ea-847b-6ce2e4cb78da.png)
</details>

**Comment by BarbzYHOOL** [comment] 2020-07-17 20:41
not confirmed on an OLD commit (like 4 months ago)

**Comment by Knindzagxg** [comment] 2020-07-18 04:56
Did u max all your skills when you made new level 80?

Also, it required to do relog, to get save interval.
Sometimes, this weird visual bug happen for me as well, but clearing cache sorted it.

And last question - You maybe using any modules? Transmog module broke this visually as well.

**Comment by Wowkasu** [comment] 2020-07-18 05:09
> Вы максимизировали все свои навыки, когда сделали новый 80-й уровень?
> 
> Кроме того, он требовал сделать relog, чтобы получить интервал сохранения.
> Иногда эта странная визуальная ошибка случалась и со мной, но очистка кэша все уладила.
> 
> И последний вопрос - может быть, вы используете какие-то модули? Модуль Transmog сломал это визуально, а также.

it was tested by four different people on two different servers. 
with cleaning and restarting. 
The 4 images for example are original objects without transmogrification. You see that, right?

We also collected statistics to confirm that there is no stacking from agility, you have seen the images?

I wrote how to reproduce the problem. Check it on your server with the latest update and write the result here.

Translated with www.DeepL.com/Translator (free version)

**Comment by Wowkasu** [comment] 2020-07-18 05:28
there is another detail of this malfunction.
![2020-07-18_12-19-53](https://user-images.githubusercontent.com/68443208/87845478-0f25d580-c8f2-11ea-8b44-aeb704aefff6.png)
https://wotlkdb.com/?spell=29801

Warrior Rebel talent does not add a number for a chance of a critical strike.
![2020-07-18_12-23-26](https://user-images.githubusercontent.com/68443208/87845496-2cf33a80-c8f2-11ea-9293-055d8b7efa99.png)
![2020-07-18_12-24-39](https://user-images.githubusercontent.com/68443208/87845498-2ebcfe00-c8f2-11ea-9087-114fc03d9e3c.png)

**Comment by merdlin** [comment] 2020-07-19 00:47
Tested, confirmed.

**Comment by pklloveyou** [comment] 2020-07-19 07:05
![image](https://user-images.githubusercontent.com/18535853/87869294-330c1880-c9d1-11ea-8a59-291e0b2fc3c9.png)
![image](https://user-images.githubusercontent.com/18535853/87869303-4e772380-c9d1-11ea-9d2a-cc7cadcb2fc0.png)

**Comment by pklloveyou** [comment] 2020-07-19 07:08
rogue
![image](https://user-images.githubusercontent.com/18535853/87869351-aa41ac80-c9d1-11ea-8d9a-bcdb9f5e9c41.png)

**Comment by Winfidonarleyan** [comment] 2020-07-19 08:00
Add commit in general info

**Comment by Wowkasu** [comment] 2020-07-19 08:12
Yeah, well, I'll confirm the rogue not adding up either.
![2020-07-19_15-08-13](https://user-images.githubusercontent.com/68443208/87870428-276d2180-c9d2-11ea-86e2-17904e8b4d65.png)

**Comment by pklloveyou** [comment] 2020-07-19 08:39
All Class It's all 0
![image](https://user-images.githubusercontent.com/18535853/87870867-76b94f00-c9de-11ea-9c35-4309b5fd2cab.png)

**Comment by pklloveyou** [comment] 2020-07-19 10:07
As the level increases, it decreases. Is this normal?

**Comment by Knindzagxg** [comment] 2020-07-19 10:12
I still can't reproduce the problem.

Can you try those steps - Check video bellow.
There must be interval save after gaining skill and things like.

https://www.youtube.com/watch?v=M2ou2fWLtnA&feature=youtu.be

Lemme know if issue is still there after those steps.

Without 5% from talents.
![1](https://i.imgur.com/udC0WTg.jpg)

With talent.
![2](https://i.imgur.com/DEvBULK.jpg)

With Rampage.
![3](https://i.imgur.com/UsdW1Hi.jpg)

**Comment by Knindzagxg** [comment] 2020-07-19 10:17
Yes pk, at lower levels you have higher crit.
While leveling it will go down cause your damage and abilities will go up.

**Comment by Knindzagxg** [comment] 2020-07-19 10:34
@Wowkasu 

```the problem was confirmed in the collection of statistics the estimate should be 50% and we have a lot less critical hits.```

I really don't get you on this part btw.

Warrior's default crit chance is 34.85%.
On dummies (Which are boss level, which mean you will miss and things like) you got 31+% crit hit strikes from normal attacks.
With spells, it go higher, over 37,5% which is correct as well, due some of them proc a bit more from passive's.

There is no possible way to have 50% crit hits on boss targets with this chance - It would be just broken.
Specially because Fury specs would be insane, due all procs from Flurry (Increased attack speed after crit strike) which will get warriors on 85+% bonus attack speed all the time.

**Comment by Wowkasu** [comment] 2020-07-19 12:51
Knindzagxg 
I checked both your video, your ability study, and the restart. Yeah, it's becoming visible to the bandit.

But the warrior doesn't.
I got a complaint from players whose characters are older than two years "used to be, but now they're not." 

Still, for warriors, the problem remains.

**Comment by Knindzagxg** [comment] 2020-07-19 14:21
I tested fully warriors from scratch.

Even with pure Agility items and things like but wasn't able to reproduce.
Agility scaling on the other hand works as well - At start once u start getting it, it will go high (Lets say 150 Agi = 1.5% crit for example) but higher u go, crit will not work on same % due scaling.

It would be just broken. Imagine 60% warrior with Titan Grip that increase 2 hand damage and 100% Flurry uptime.
They would 1 shoot pretty much everything.

It's totally different when you test hunter, rogue or etc.
They scale pretty good cause agility not only increase their crit but ability damage as well.
For warriors it's different due stren giving best possible outcome and ofc hit, arp and etc.

**Comment by Wowkasu** [comment] 2020-07-19 14:55
the problem appeared 1-2 months ago, before that the warriors worked well, everything as you describe.

**Comment by Knindzagxg** [comment] 2020-07-19 14:59
Ill go trough each PR we had to see was there anything new towards it.
Will let you know in a day or two.

**Comment by Wowkasu** [comment] 2020-07-19 15:03
> Ill go trough each PR we had to see was there anything new towards it.
> Will let you know in a day or two.

Thank you very, very much!

**Comment by Chromie-WoW** [comment] 2020-07-19 18:14
After doing some troubleshooting here is what i came up with

Level 60 warrior
.max skill
AGI Buff DOES add crit chance but does NOT change mouse over crit rating.
Crit rating DOES add crit chance and DOES change mouse over crit rating

**Comment by Knindzagxg** [comment] 2020-07-19 18:16
For all interval updates you have to logout, after each commands Chromie.

Sometimes those take a bit more time and for some silly reason if server have Transmog module it's broken visually and nothing helps.

No worries Wowkasu, just need a bit more time.

**Comment by Chromie-WoW** [comment] 2020-07-19 18:22
> For all interval updates you have to logout, after each commands Chromie.
> 
> Sometimes those take a bit more time and for some silly reason if server have Transmog module it's broken visually and nothing helps.
> 
> No worries Wowkasu, just need a bit more time.

I understand on the interval updates, but its wierd it recalculates when you apply a crit item, it seems like it should always update stats on talent change, buff change, and worn change. But thats not for this thread lol

**Comment by BarbzYHOOL** [comment] 2020-07-19 18:27
the EASIEST way to find the issue (if we have noidea) and that ANYBODY can do, is to find a commit where it was not bugged example 2 months ago

you compile, you test, fine

then you take a commit 1 month ago, you compile, you test etc until you find the BUGGY commit

**Comment by Wowkasu** [comment] 2020-07-20 14:28
> No worries Wowkasu, just need a bit more time.
It's okay! I told the players, they understand that the project is free, and they do not complain. They put the warriors aside and started to play other classes well that there are 9 more )))).

**Comment by Cinnamohn** [comment] 2020-07-21 16:30
Is your weapon skill maxed for your character's level? Critical strike chance is reduced for every level below the maximum. That includes Unarmed without a weapon.

**Comment by CosmeF** [comment] 2020-07-22 21:41
This bug is not present on 257a530

**Comment by FrancescoBorzi** [comment] 2020-07-23 10:40
@CosmeF thanks a lot. It shouldn't be hard then to find which commit caused this issue.

Can anyone try commits between https://github.com/azerothcore/azerothcore-wotlk/commit/257a53085ede80703edd864f1386d133c0497b8f and https://github.com/azerothcore/azerothcore-wotlk/commit/0d9e52d812046ed1add8a0e81edcd017222bbce5 ?

No need to try commits one by one. You can use binary search: try the commit in the middle, is the bug there?
Yes -> look on older commits group
No -> look on newer commits group
Then repeat this until the faulty commit has been found

**Comment by pklloveyou** [comment] 2020-07-25 06:04
https://github.com/azerothcore/azerothcore-wotlk/commit/94e6ef17a2746fbac365934fc3e67593b221ad6e
https://github.com/azerothcore/azerothcore-wotlk/commit/ec806d6c605952993742cfda3aa5d567c9b41c04
Could it be a mistake here?

**Comment by CosmeF** [comment] 2020-07-25 06:20
Hello. I've started the binary search looking for the bug, but uppon setting up the base for the search, which is getting no error on 257a530 and getting it on 0d9e52d, I've failed the last part.

I can't reproduce the error on 0d9e52d following the steps on this issue, and thus cannot continue the search.

Lvl 80 troll warrior, **used maxskill and learn all my class commands**, equiped with item id 47314:

<details>
  <summary>Captured on 257a530 </summary>
  
![imagen](https://user-images.githubusercontent.com/57512214/88450352-5e04cb00-ce1c-11ea-9d53-1a53b1a77345.png)

</details>

<details>
  <summary>Captured on 0d9e52d </summary>
  
![imagen](https://user-images.githubusercontent.com/57512214/88450429-d4093200-ce1c-11ea-9b9c-bf1782f84d18.png)

</details>


I will continue testing more geared up characters, and keep you guys infomed.

**Comment by Wowkasu** [comment] 2020-08-03 06:33
This problem can be closed. It's solved this way.
https://github.com/azerothcore/azerothcore-wotlk/pull/3216

It's a good test.
![2020-08-03_01-11-05](https://user-images.githubusercontent.com/68443208/89152729-e22e1f80-d58d-11ea-888e-31d0e7f263a9.png)

**Comment by Kitzunu** [comment] 2020-08-03 12:47
It will be closed once the PR is merged

**Closed** 2020-08-09 14:10 UTC
Labels: CORE, Confirmed, Priority - High
