### ISSUE TITLE
BWL Broken

### ISSUE THREAD

**Issue by grabthar** [azerothcore/azerothcore-wotlk#5054] opened 2021-03-29 16:36 UTC
## CURRENT BEHAVIOUR:

Broken bwl.
All access to creature instance(boss) like:
`instance->GetCreature(DATA_RAZORGORE_THE_UNTAMED)`
return nothing

## EXPECTED BLIZZLIKE BEHAVIOUR:

fixed bwl boss / instance

## STEPS TO REPRODUCE THE PROBLEM:

1. Build from #3673 
2. go into bwl the razorgore orb doesn't cast mc
3. razorgore can't reach p2 can't stop casting mc aura and so on.

## EXTRA NOTES:

#3673 Introduce bugs.
I give some details here.
https://github.com/azerothcore/azerothcore-wotlk/commit/6ef73413131e58dddd45524d51b57015b0ca3b7b#commitcomment-48848790

Globally the bwl fix removed bosses guid because trinity does that, but they introduced code that replace the old way for finding boss creature instance.
You have 2 options to fix it:
- Introduce TC InstanceScript code then we could update all instances script.
- Reintroduce the removed guid

**Comment by Err0r1** [comment] 2021-03-29 18:51
Confirmed

**Comment by Si1ker** [comment] 2021-03-29 18:57
@FALL1N1 👀

**Comment by FALL1N1** [comment] 2021-03-29 18:59
Thanks for the report, I'm on it.

**Comment by grabthar** [comment] 2021-03-29 20:57
Also don't forget to re add nefarian->SetHomePosition(NefarianLoc[1]); otherwise he stay in the air until he reset

**Comment by Knindzagxg** [comment] 2021-03-30 15:17
Yeah, can confirm it.
For some reason Orb doesn't work now.

When it comes to Nefarian, it worked well for me.

PS. If you gonna solo test Nefarian,  .learn 47922 -> Will give you immunity trough phase 1, so you don't get mind control.

**Comment by T1ti** [comment] 2021-03-30 15:22
> Yeah, can confirm it.
> For some reason Orb doesn't work now.
> 
> When it comes to Nefarian, it worked well for me.
> 
> PS. If you gonna solo test Nefarian, .learn 47922 -> Will give you immunity trough phase 1, so you don't get mind control.

which orb, the teleport orb outside or the mind control orb ?

**Comment by Knindzagxg** [comment] 2021-03-30 15:56
Mind control one

**Comment by Knindzagxg** [comment] 2021-03-30 16:44
Nah mate, fresh build.
For some reason it doesn't start fight.

**Comment by FALL1N1** [comment] 2021-03-30 16:47
I see, I will test that as well, thanks!

**Comment by Pensukdeath** [comment] 2021-04-12 09:27
_Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)_

**This should work up to version 3.3.0, then Onyxia was remade for wotlk. And the presence of a raincoat is optional.**

Mind control doesn't work.

**Comment by Pensukdeath** [comment] 2021-04-19 17:07
> I see, I will test that as well, thanks!

Will you fix it?

**Comment by FALL1N1** [comment] 2021-04-19 18:49
@Pensukdeath yes, I'm halfway done with the PR and most of the issues, sadly I cannot work full time on the project, because I have IRL job as well as home repairs together with other web-based projects.
Hopefully I can finish it till the end of this week.

**Comment by Pensukdeath** [comment] 2021-04-19 19:49
> @Pensukdeath yes, I'm halfway done with the PR and most of the issues, sadly I cannot work full time on the project, because I have IRL job as well as home repairs together with other web-based projects.
> Hopefully I can finish it till the end of this week.
Know that everyone is looking forward to you)

**Comment by Pensukdeath** [comment] 2021-04-19 19:50
> @Pensukdeath yes, I'm halfway done with the PR and most of the issues, sadly I cannot work full time on the project, because I have IRL job as well as home repairs together with other web-based projects.
> Hopefully I can finish it till the end of this week.

Know that everyone is looking forward to you)

**Comment by Ragelezz** [comment] 2021-09-22 18:04
I don't see anyone assigned to this, any updates for this raid? Needs a fully rewrite or just some bugs here and there?

**Comment by Helias** [comment] 2021-09-23 07:05
@grabthar  @Err0r1  @FALL1N1

**Comment by Err0r1** [comment] 2021-09-23 08:52
Tested, works good now

**Comment by Knindzagxg** [comment] 2021-09-23 15:20
For me Orb still not working.
Maybe i missed update, pic with my curr version down.
![WoWScrnShot_092321_171942](https://user-images.githubusercontent.com/27079035/134535732-5e0bd488-f4fe-447f-bc64-205ff7f4dca9.jpg)

**Comment by Knindzagxg** [comment] 2021-09-23 17:47
Updated core and maps -> Orb working now, but there is a lot of issues with fight itself.
- Line of Sight should be sorted 
- Yells from boss it self when you destroy eggs doesn't appear
- Adds do not despawn once you finish / restart fight
- Channeled beam must be sorted, since there is not timer (U can keep boss forever)
- Exit btn doesn't work as well, only way to leave it is by dismissing boss (Like u do for the pet)

That's what i found after quick test, wonder is it same for everyone else?

**Comment by FALL1N1** [comment] 2021-09-23 18:11
Can you try it with 2 or 3 characters, please? @Knindzagxg

**Comment by Knindzagxg** [comment] 2021-09-23 18:44
Will do once i finish some papers.
If not tonight, i will tomorrow for sure.

**Closed** 2022-11-01 15:58 UTC
Labels: Confirmed, Priority-High, CORE, 60, Script, Instance - Raid - Vanilla, temporary label
