### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by LichKing255** [azerothcore/azerothcore-wotlk#2280] opened 2019-09-10 22:33 UTC
##### SMALL DESCRIPTION:
i find problem why vmaps not load #2215 .
worldserver start with 600 mb of memory, and after 2 hour when have 10x players in server , this used 90% of memory . when use 90% , vmaps not load.
In fact, the main problem is overuse of memory.

10 min uptime with 3x player :
https://mega.nz/#!W9UTEAZI!EWFDAaeK4qWOMPLHxTy8a9M7Yrmt5sS6yJBHKgvMMPg

15 min uptime with 5x player : 
https://mega.nz/#!qsNVhCwY!OnZ2iBjEikihbgB59oTXlOki6pfqIh16Dh7AiUo7O6k

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/67d180ea776a171c6d660d964d6454ea504ce55b

##### OPERATING SYSTEM:

Windows Server 2016 Ram 4

##### MODULES:

nothing

##### OTHER CUSTOMIZATIONS:

nothing

**Comment by Stoabrogga** [comment] 2019-09-11 06:01
This is normal behaviour. 4 GB RAM is not enough, in my opinion you need at least 6 GB for your case in order to have enough resources left for the OS. My own server installation uses ca. 1.8-2 GB with only 1 player (myself) on Ubuntu 16.04.

**Comment by FrancescoBorzi** [comment] 2019-09-11 07:17
And why exactly you think it's a memory leak?

**Comment by zabustak** [comment] 2019-09-11 09:24
Operating system | Debian Linux 9 @ 4.20GHz, 8 cores ~60GB ram
4 days uptime server pop low ~6 gb ram 
14 days uptime same pop ~10 gb ram
https://ibb.co/5TZS1M9

I recommend you switch to Linux with larger resources, the server uses about 4GB RAM even if no one is playing

**Comment by FrancescoBorzi** [comment] 2019-09-11 09:34
closing as there is no evidence of a real memory leak 

using much RAM != memory leak
improperly using RAM == memory leak

**Closed by FrancescoBorzi** 2019-09-11 09:34 UTC

**Comment by LichKing255** [comment] 2019-09-11 09:38
As you say, after a few days the memory must to be filled.
So every time the memory is full Vmaps will not load.

**Comment by wowmane** [comment] 2019-09-11 09:50
Ican, Confrim.

For test

1. set to GridUnload = 1 or 0
2. gm, mod speed + fly on and move to maps
3. memory will to leak for enter character to the maps, "Grids"

I tested:
If Memory is Usage 20%
I will to move and join maps, server/core unload grids "Cache"
This will increase memory, Changed to 58% Usage!

This will increase memory!
"disable, does not work"

**Comment by LichKing255** [comment] 2019-09-11 09:59
> Ican, Confrim.
> 
> For test
> 
> 1. set to GridUnload = 1 or 0
> 2. gm, mod speed + fly on and move to maps
> 3. memory will to leak for enter character to the maps, "Grids"
> 
> I tested:
> If Memory is Usage 20%
> I will to move and join maps, server/core unload grids "Cache"
> This will increase memory, Changed to 58% Usage!
> 
> This will increase memory!
> "disable, does not work"

Azeroth don't have GridUnload config.

**Comment by Stoabrogga** [comment] 2019-09-11 10:12
There is a parameter "GridUnload":
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L213

Default is "1", which means that grids which are not active anymore will unload after 5 minutes. As I see it there's no other option but to increase RAM @LichKing255 .

**Comment by LichKing255** [comment] 2019-09-11 10:15
> There is a parameter "GridUnload":
> https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L213
> 
> Default is "1", which means that grids which are not active anymore will unload after 5 minutes. As I see it there's no other option but to increase RAM @LichKing255 .

my friend,  this don't add on World.cpp. and don't use any where.

**Comment by FrancescoBorzi** [comment] 2019-09-11 10:49
@LichKing255 as mentioned before, for an AC production server you definitely need more RAM.

as written in the [FAQ](http://www.azerothcore.org/wiki/FAQ) 

> 2 - Why is AzerothCore using more ram than TrinityCore?
AzerothCore is based on SunwellCore (a fork from TC). SunwellCore was a public server with 4000 players online and they made sure their core could handle that amount of player easily. Reading data from the ram is much faster than reading from the hard disk (there are entire systems based on this principle). That’s one of the reason there is a bigger ram usage.

so AC uses more RAM in order to provide better performance

**Comment by Stoabrogga** [comment] 2019-09-11 10:51
@LichKing255 
You're right about the parameter, it is not used anywhere. That's interesting, never thought of this. Sorry, but then I have no idea why this parameter is even there, should be removed.

**Comment by LichKing255** [comment] 2019-09-11 10:54
> @LichKing255 as mentioned before, for an AC production server you definitely need more RAM.
> 
> as written in the [FAQ](http://www.azerothcore.org/wiki/FAQ)
> 
> > 2 - Why is AzerothCore using more ram than TrinityCore?
> > AzerothCore is based on SunwellCore (a fork from TC). SunwellCore was a public server with 4000 players online and they made sure their core could handle that amount of player easily. Reading data from the ram is much faster than reading from the hard disk (there are entire systems based on this principle). That’s one of the reason there is a bigger ram usage.
> 
> so AC uses more RAM in order to provide better performance

ok, but you say, after a few days the memory must to be filled even if I have 12 gigs of RAM
So every time the memory is full Vmaps will not load.

What solution do you suggest for when memory is full?
You can't always check the amount of RAM and restart the server.

**Comment by FrancescoBorzi** [comment] 2019-09-11 11:14
@LichKing255 at some point it will stop growing, otherwise we have a memory leak indeed :)

**Comment by LichKing255** [comment] 2019-09-11 11:20
> @LichKing255 at some point it will stop growing, otherwise we have a memory leak indeed :)

It stops for a few minutes, but continues again. So why closed this issue?

**Comment by FrancescoBorzi** [comment] 2019-09-11 11:26
@LichKing255 because it is expected to stop at some point. 4 GBs are not enough for sure.

**Comment by wowmane** [comment] 2019-09-11 11:33
My memory is 15G but AC / usage 60% of RAM , after 1day .

I think this problem should be check, There are many reports on this

Issuse , search "Memory Leaks"

**Comment by Viste** [comment] 2019-09-11 12:07
omg NO memory leaks in grids/maps/vmaps its normal behavior for ACE and current core design 
stop post this bullshit 
TC use boost ITS ANOTHER LIBRARY AND HANDLE OF MANY THINGS GOING IN ANOTHER WAY fucking idiots

**Comment by LichKing255** [comment] 2019-09-11 12:10
> @LichKing255 because it is expected to stop at some point. 4 GBs are not enough for sure.

@FrancescoBorzi reopen plz. @wowmane and #1887 #1525 #508 all have problem.

@wowmane have higher ram

**Comment by Viste** [comment] 2019-09-11 12:10
when using different libraries AC(ACE) TC(boost), the processes inside the core run differently
and we can't compare AC to TC for CPU/memory usage.

**Comment by Viste** [comment] 2019-09-11 12:11
STOP THIS INSANE SHIT PLEASE!!!!!111121

**Comment by FrancescoBorzi** [comment] 2019-09-11 12:11
@LichKing255 again, using higher RAM is NOT an issue (and not a memory leak indeed).

If the memory keeps growing ENDLESSLY then we have a problem. At the moment I don't see any report about it.

**Comment by Viste** [comment] 2019-09-11 12:12
@FrancescoBorzi just ban them they are idiots...

**Comment by LichKing255** [comment] 2019-09-11 12:13
> when using different libraries AC(ACE) TC(boost), the processes inside the core run differently
> and we can't compare AC to TC for CPU/memory usage.

i don't compare AC AND TC, if see task manager on windows you see every min use more memory. just stop for few minutes and again Continues.

**Comment by LichKing255** [comment] 2019-09-11 12:15
> @FrancescoBorzi just ban them they are idiots...

You have a conflict with yourself. Please exit this report.

**Comment by LichKing255** [comment] 2019-09-11 12:26
> @LichKing255 again, using higher RAM is NOT an issue (and not a memory leak indeed).
> 
> If the memory keeps growing ENDLESSLY then we have a problem. At the moment I don't see any report about it.

Okay, I'm upgrading Ram and reporting the result. But the result doesn't change because wowmane has higher RAM and still has trouble.

**Comment by FrancescoBorzi** [comment] 2019-09-11 12:49
@LichKing255 yes please. I don't see which "problem" wowmane has.  Using more ram is not necessarily a problem.

For the last time, the problem is when it increases endlessly.

**Comment by FrancescoBorzi** [comment] 2019-09-15 09:57
## AzerothCore ram usage explanation

http://www.azerothcore.org/wiki/Memory-Usage
