### ISSUE TITLE
ins Halls Of Stone The problem of reviving 

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5492] opened 2021-04-27 08:35 UTC
CURRENT BEHAVIOUR:
ins Halls Of Stone
Krystallus Boss

EXPECTED BLIZZLIKE BEHAVIOUR:

The problem of reviving After losing hands Boss

Please fix this, thank you

SOURCE:
![WoWScrnShot_042721_124624](https://user-images.githubusercontent.com/80007195/116209976-af4d3c80-a757-11eb-9032-af6924ab81fe.jpg)

STEPS TO REPRODUCE THE PROBLEM:

Entry NPC : 27977

EXTRA NOTES:
AC HASH/COMMIT:

rev. 26a477d 2021-04-24 10:42:48 +0000

OPERATING SYSTEM:
Ubuntu 20.10

MODULES:
N/A.

CUSTOMIZATIONS:
N/A.

**Comment by FrancescoBorzi** [comment] 2021-04-27 12:04
@poryagholami1374 it is not clear what the issue is, can you please give more details?

**Comment by poryagholami1374** [comment] 2021-04-27 12:15
> it is not clear what the issue is, can you please give more details?

When we die with this bOss
LEVEL
Revive
  It does not work

**Comment by poryagholami1374** [comment] 2021-04-27 12:18
> @poryagholami1374 it is not clear what the issue is, can you please give more details?

When everyone dies
LEVEL
Revive
It does not work

**Comment by Sedatyf** [comment] 2021-04-27 12:18
It's still not clear imo. I don't know what you describe. What is the expected behavior? What is the current behavior?

**Comment by poryagholami1374** [comment] 2021-04-27 12:21
> It's still not clear in my opinion. I don't know what you describe. What is the expected behavior? What is the current behavior?

Level Redemption And ...
Is out of work

**Comment by Sedatyf** [comment] 2021-04-27 12:25
What do you mean by level redemption? Like if you die, you can't revive? Or if you die, you're at the wrong graveyard?

**Comment by poryagholami1374** [comment] 2021-04-27 12:49
> What do you mean by level redemption? Like if you die, you can't revive? Or if you die, you're at the wrong graveyard?

I say level does not work
This level Redemption

**Comment by Sedatyf** [comment] 2021-04-27 15:30
Please, @poryagholami1374 or @FrancescoBorzi, can you close this issue? I made a new one with more details and description : https://github.com/azerothcore/azerothcore-wotlk/issues/5497

**Closed** 2021-04-27 15:46 UTC
Labels: Invalid - Missing information
