### ISSUE TITLE
Hunter's Mend Pet with Glyph of Mend Pet generates extreme amount of threat on the pet

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6190] opened 2021-06-02 09:09 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/761

##### CURRENT BEHAVIOUR:

Hunter's mend pet ability increases aggro towards the pet when Glyph of Mend Pet is slotted.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mend pet should increase aggro towards hunter

##### STEPS TO REPRODUCE THE PROBLEM:

1. Turn off all active ability on pet including growl
2. Use Mend pet
3. Engage in combat
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: beb4df9):

![WoWScrnShot_060221_124408](https://user-images.githubusercontent.com/82579073/120459054-7e88a480-c3a0-11eb-8367-f490452f3c2d.jpg)
![WoWScrnShot_060221_124501](https://user-images.githubusercontent.com/82579073/120459125-92cca180-c3a0-11eb-86e8-9f73003bfd76.jpg)
![WoWScrnShot_060221_124509](https://user-images.githubusercontent.com/82579073/120459215-a7a93500-c3a0-11eb-9c5e-93cb49267f67.jpg)

**Comment by rdallastra** [comment] 2021-06-29 23:58
As mentioned in my comment in [https://github.com/chromiecraft/chromiecraft/issues/761](https://github.com/chromiecraft/chromiecraft/issues/761), the Mend Pet skill does not actually remove aggro from hunter, it just generates a huge amount of threat. Take a look at the amount of threat generated by my pet (with Mend Pet ticking) and my hunter:

![Threat meter](https://user-images.githubusercontent.com/45319286/123882082-09af7880-d914-11eb-86fa-05aee443a941.jpg)

The Mend Pet ability generated 50x more threat than my hunter with auto-attack and arcane shot. The pet used is a bear (Tenacity) with BM [talent tree](https://wotlkdb.com/?talent#ctbMzxtRV:fZz) and pet [talent tree](https://wotlkdb.com/?petcalc#0Rd0b). Please note I'm using the mend pet minor glyph as per the talent tree, could be related to that.

**Comment by necropola** [comment] 2021-07-25 04:21
Duplicate of #6755

**Comment by temperrr** [comment] 2021-07-25 09:27
The most important part is its due to the glyph of mend pet which gives your pet happiness when using mend pet. This generates too much threat

**Comment by necropola** [comment] 2021-07-25 09:35
> The most important part is its due to the glyph of mend pet which gives your pet happiness when using mend pet. This generates too much threat

I've edited the title and the description slightly so that it's more clear what the actual issue is.

**Closed** 2021-08-04 14:56 UTC
Labels: ChromieCraft Generic, Class-Hunter, Confirmed, Priority-High
