### ISSUE TITLE
Underwater Combat Issues - Jumping Resetting Combat, and Auto-Attacks Occasionally Failing

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#8729] opened 2021-10-25 12:40 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1641

Dropping combat when jumping out of the water, also character does not autoattack while fighting under the water.

You can clearly see that in the video below:
https://www.youtube.com/watch?v=7gqEzOdHOH0

Tester: Both issues confirmed, with some caveats.
1. Jumping out of the water rests combat state pretty much instantly:

https://user-images.githubusercontent.com/81782124/138694063-84aacfc3-df29-47d7-8a78-468b98089a6f.mp4

2. Auto-attack *sometimes* fails to work on underwater creatures. This was harder to replicate, and I found that it failed only rarely. @VFaleiro comments:

>It happened to me before, but it doesn't always happen. I believe it has something to do with the mob being hit and its position on the ground underwater. I was actually hitting Murk Threshers and Elder Murk Threshers (trying to farm Big-mouth Clams).
>
>They have large hitboxes that are located below their ingame models, and are most of the time close to the ground underwater. Very likely their hitbox was partially inside the ground, so my character couldn't auto-attack them because of LoS? Just a theory though.

So tried on a Murk Thresher thanks to this tip, and after maneuvering it near the shoreline, was able to get auto-attacks to fail. However, pulling the same NPC a bit further out into the water made it work fine, so the theory of some interaction with the sloping shore causing the problem sounds plausible.

https://user-images.githubusercontent.com/81782124/138694439-bd01dad3-08ff-48b8-b2c1-50723925c363.mp4

### Expected Blizzlike Behaviour

Combat should not drop when you jump out of water (it's okay when it drops when you jump on the shore, but it drops when you jump above water surface, even if Im in the center of the river) and player character should autoattack monsters while combat under the water.

### Source

Sources for jumping out of the water resetting combat were very scarce. All I could find was this quote:

"In the event of an encounter where you do use the transition between land and sea to break a fight, the mob in question will evade **but remain in combat with you**. It should, in most cases, reset within a few seconds." - https://wowpedia.fandom.com/wiki/Swim?oldid=2300441. The behaviour described is clearly different to that on AC, where combat breaks instantly.

I don't think we need a source for being unable to auto-attack a mob you're in combat with being incorrect.

### Steps to reproduce the problem

1. .go c 18642 (murk thresher). It will engage you.
2. I found swimming west a bit to near the shoreline, even jumping out and back in again, and generally moving it around near the slope while trying to auto-attack would usually do the trick.
3. To test the other issue, simply swim up and jump.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment] 2021-12-16 22:27
@Azcobu I can't reproduce the 2nd issue. I need an exact coords (taken from `.gps`) where I should go with that mob to observe problems with melee attacks.

**Comment by Azcobu** [comment] 2021-12-17 13:42
Just had a look and can't reproduce it now either, apparently something's changed since October. 

I did find some pathing issues with some of the threshers - they swim over land when they reset, and this:

https://user-images.githubusercontent.com/81782124/146552534-2408f974-0106-4216-9571-96a62affa915.mp4

But it's unrelated so feel free to close this and do what you like with the info above. I should also mention I'm no longer working on the project, so might not be available to answer queries in future.

**Comment by UltraNix** [comment] 2021-12-17 14:52
This one is fixed by #9740

**Closed** 2021-12-28 12:34 UTC
Labels: Confirmed, ChromieCraft Generic
