### ISSUE TITLE
The server eats a lot of RAM 

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#508] opened 2017-06-08 12:20 UTC
The server eats a lot of RAM with 0 online 3 gigabytes, and when online in 20 people all 6 gigabytes
Features of the server machine: 6 GB of RAM os Debian 8

**Comment by Yehonal** [comment] 2017-06-08 12:25
Is it a dedicated server or a container/VPS? could you send the output of
your "top" commands to get the real ram usage of worldserver process?

However enabling mmap, vmap and disabling grid cleanup can cause it.
Normally a server with full features enabled consume about 2GB of ram, of
course it grow up if people login since it have to load maps in ram.



2017-06-08 14:20 GMT+02:00 avatar789 <notifications@github.com>:

**Comment by avatar789** [comment] 2017-06-08 12:42
I rent VDS. Here is screenshot http://screenshot.ru/upload/image/SN3O

**Comment by Inifield** [comment] 2017-06-08 12:55
Can't confirm on windows, I use 2GB with 10 online

**Comment by avatar789** [comment] 2017-06-08 13:02
I thought that because of a rented vds, but already changed the vds and still the same way

**Comment by Debilushka** [comment] 2017-06-12 06:54
Guys, your help is very necessary. On the core, as I understand it, the cumulative effect works. The player goes into memory and grows up. It turns out that memory does not fall. What is the trouble (

**Comment by Viste** [comment] 2017-06-12 20:18
@Debilushka what you do in core mods, on clean AC i don't have that.
Что ты модифицировал, на чистом АЗ такого нет, чтобы тебе помогли дай больше инфы.

**Comment by Debilushka** [comment] 2017-06-13 05:09
Можем дать доступ к сорцам проекта, но они находятся на бибакете. там указаны все комиты.
#Can give access to the source project, but they are on bitbucket. There are all comity.

**Comment by Debilushka** [comment] 2017-06-13 06:40
Good afternoon. I want to ask for help, can't find what's the jamb. As previously wrote on the issue tracker that we ship - lot and falls of RAM.
Contacts Skype Debilushka1992
VK https://vk.com/devcores

Please help in this matter.
________________________________________________________________________________________
Добрый день.
Хочу попросить помощи, не можем найти в чем косяк.
Как ранее писал на гитхабе что у нас грузит ядро очень много и не спадает ОЗУ.
Контакты
Скайп Debilushka1992
VK https://vk.com/devcores

Очень прошу помочь в данном вопросе.

**Comment by Debilushka** [comment] 2017-06-13 12:05
Странно конечно, но скачал ваше ядро нулевое и та же система. Нарастает, но не падает ОЗУ. Понять не могу в чем беда( Может оптимизация необходима чего либо?

Strangely of course, but your kernel has downloaded the zero and the same system. Increases, but does not drop RAM. I can not understand what the trouble is (Can optimization be necessary for anything?

**Comment by HeartWell** [comment] 2017-06-13 14:03
Ас слишком много чего применила не нужного, мой тебе совет используй чистый санвел, возьми нужные коммиты и все.

**Comment by Debilushka** [comment] 2017-06-13 14:09
случаем базы от санвела нету?

**Comment by HeartWell** [comment] 2017-06-13 15:03
Она идет вместе с сорцами. https://github.com/Kittnz/Sunwell

**Comment by avatar789** [comment] 2017-06-20 14:05
There is a suspicion that this is due to saving reports for players. Since this report goes with an interval of 10-15 seconds, at this moment it rises RAM

**Comment by avatar789** [comment] 2017-06-20 14:06
http://screenshot.ru/upload/image/SaRz

**Comment by Debilushka** [comment] 2017-06-23 10:48
Warning: Transaction only holds 1 query, consider removing Transaction context in code.
Warning: GetUInt32() on non-(medium)int field. Using type: SHORT.
Что это за ошибки я чет понять не могу. Помогите пожалуйста.

**Comment by avatar789** [comment] 2017-06-27 09:40
We checked already on all operating systems including windows RAM still grows but does not fall. Grows when the player runs around the locations after the player leaves nothing. Just everything was tested on 2 different server machines. Is there no such problem for anyone?

**Comment by BarbzYHOOL** [comment] 2017-06-29 16:37
I think I can also confirm that.

However : 
`There is a suspicion that this is due to saving reports for players.`

If this is true, it means it's related to the anticheat module. And the issue you opened didn't mention that because you opened an incomplete issue.

**Comment by avatar789** [comment] 2017-06-29 17:59
I tried to use the stock kernel without mods, the ozu grows but does not fall, the problem is not in anticht

**Comment by avatar789** [comment] 2017-07-05 08:43
I do not know how to deal with this problem. I tried everything I knew and different ones, and the clean kernel was still growing RAM

**Comment by sucofog** [comment] 2017-07-09 18:36
No problems of RAM for me, i have mod anticheat, mod duelreset, mod transmog, and many other custom things.

**Comment by avatar789** [comment] 2017-07-10 02:01
I think that something is missing in the database, you could not throw it off database for last source

**Comment by Kizarr** [comment] 2017-07-29 19:40
I have same issue with ram here your not the only one here.

**Comment by Dragnell87** [comment] 2017-08-07 15:05
We usually have 600 to 1500 player ram goes from 6G to 8 depending how many user are connected, using AntiCheat, Transmog and Dualmod-reset, Server ubuntu 16.04, AzerothCore rev 7577792f4bc9 2017-05-08

**Comment by Viste** [comment] 2017-08-07 20:52
That ram can be taken by compile on Linux based OS try to do this:
sync; echo 1 > /proc/sys/vm/drop_caches
sync; echo 2 > /proc/sys/vm/drop_caches
sync; echo 3 > /proc/sys/vm/drop_caches

It  also can help to unload ram taken by server. In my case its help

**Comment by Viste** [comment] 2017-08-07 23:36
![default](https://user-images.githubusercontent.com/281977/29050087-6aebcb78-7be2-11e7-81af-da286629869d.png)

**Comment by avatar789** [comment] 2017-09-16 09:31
@Viste It did not help, RAM it is still growing

**Comment by avatar789** [comment] 2017-09-16 09:33
@Yehonal help me please!

**Comment by avatar789** [comment] 2017-09-16 09:33
perhaps because I compile in the release? tell me the correct configurator for debugging

**Comment by Yehonal** [comment] 2017-09-16 22:54
@avatar789 sorry but we don't have such issue, so i would suggest you to test the same OS configuration on another machine/vps (best on local physical hardware, but you can even use a virtualbox/wmware on your pc without buy any hosting, just to test).

I had similar issue with a low cost host that used ram ballooning technique, but as other user said, on bare metal server / good vps the worldserver can't consume 3GB. 

Moreover:

1) following issue guidelines specifying if you are using modules, customizations etc..

2) try to send a pastebin of your worldserver conf

**Comment by Viste** [comment] 2017-09-17 09:01
@Yehonal  the issue that have @avatar789 in machine or software configuration, becouse all who report me about my post what i made 7 Aug. say its help. And btw in QEMU KVM + Debian 8 all other standart  i don't have this shit

**Comment by avatar789** [comment] 2017-09-26 06:15
@Yehonal @Viste I rented a dedicated server, still growing RAM that I do not know.
Ram 32 GB
Debian 8.9
I used modules transmog
Mod-premium
Mod-anticheat
Duelreset
Use config cmake ../ -DCMAKE_INSTALL_PREFIX=/home/youruser/azeroth-server/ -DTOOLS=0 -DSCRIPTS=1
Latest AC master

**Comment by avatar789** [comment] 2017-09-26 06:19
player leaves the game RAM does not fall

**Comment by Dilemmast** [comment] 2017-09-28 07:02
Confirm it . after player leave the game amount of worldserver ram usage not decrease.

**Comment by Szone** [comment] 2018-01-16 13:16
Confirm it.

**Comment by ShinDarth** [comment] 2018-01-16 14:34
it would be nice to attach your version (commit hash) when you confirm, however thanks for your feedback

**Comment by Viste** [comment] 2018-01-20 10:56
sync; echo 1 > /proc/sys/vm/drop_caches
sync; echo 2 > /proc/sys/vm/drop_caches
sync; echo 3 > /proc/sys/vm/drop_caches

It can help to unload ram taken by server. In my case its help

**Comment by FALL1N1** [comment] 2018-06-12 22:54
https://github.com/azerothcore/azerothcore-wotlk/pull/924

**Comment by BarbzYHOOL** [comment] 2018-07-25 15:05
Another option to consider:

DontCacheRandomMovementPaths = 1

**Comment by Fiver** [comment] 2018-08-01 06:56
DontCacheRandomMovementPaths = 1 only save a little RAM.
and disable mmaps and vmaps. memory still grow up.... 6G+ with 20player..

GridUnload = 1 unused in core. maybe in this case!

**Comment by TrekPL** [comment] 2018-11-20 14:22
Confirmed on Ubuntu 18.04 (dedicated machine).
On startup worldserver eats up 1GB. I can see that random maps are being loaded and there is interaction between NPCs (killing others, most some common like critters) and it is going and going even without any player on server. Going to those areas and logging out does not unload them after a while. Is option GridUnload even used?
Compilation tested on:
cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/azerothcore -DTOOLS=0 -DSCRIPTS=1 -DENABLE_EXTRAS=1 -DENABLE_EXTRA_LOGS=1
and:
cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/azerothcore -DTOOLS=0 -DSCRIPTS=1
Current AC revision (fc4b52b036a33f1207acca8c93a4c9ef3f9baa10), no mods or modifications.

**Comment by Rochet2** [comment] 2019-01-21 22:09
If someone is on linux they could run valgrind to try detect memory leaks. `valgrind --log-file="valgrindlog.log" ./worldserver`.

The Windows task manager does not report the memory that is packed, so do keep that in mind if trying to use it to gauge the amount of memory used. For example this TC is using over 1GB memory in reality: https://imgur.com/UrBGLio
Instead of task manager I used visual studio to track memory usage on windows.
https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage-without-debugging2?view=vs-2017
For me I detected TC taking 1.7GB and AC 2.3GB RAM idle after startup. No players.
For me TC seemed to keep at a steady count, but AC keeps climbing in memory usage slowly. After some time its already at 3 GB idle.

https://i.imgur.com/uNVYDUm.png
This image has a graph of the memory consumption as well as few snapshots.
The first snapshot is from when server started up and the second snapshot is after idling for a bit without anyone connecting.
The line that slices the graph to two parts is the estimated startup finish time.
From what I see the memory being consumed after startup when idling is being mostly used by Creature constructor.  So it is possible that after startup something is creating more and more creatures.

From what I see, creatures being created is related to transports moving from map to another.
I tried seeing where the NPCs are at that were using memory and they seemed to be near orgrimmar zeppeling for example. However this may require more inspection.
It seems that after a while the memory consumption seems to stabilize (I assume once the transports have made a round through their normal route).
From the memory debugging I could see that the creature constructor was taking most of the memory after startup in my tests.

**Comment by Nephelion** [comment] 2019-01-26 16:09
Rochet2 Confirm
https://github.com/azerothcore/azerothcore-wotlk/commits/master
clean

After 2h with 0~10 player +3G Ram Used . . . 
and growing . . .

**Comment by BarbzYHOOL** [comment] 2019-01-26 18:54
nobody ever got his server down because it kept growing until saturation @Nephelion

**Comment by Pondaveia** [comment] 2019-05-06 14:57
Many people tried reproducing this issue but without success. Needs further re-search on the topic.

**Comment by Viste** [comment] 2019-05-07 09:47
for what? just close it like you always do )

**Comment by Pondaveia** [comment] 2019-05-15 11:33
@poszer has been investigating and what's happening is due to poor SAI scripting. Many events, quests and creatures are being spawned without being reset and this accumulates memory overtime. I do believe that if we focus on snipping these bad scripts that the server performance will stabilize, however it takes quite the effort to find those broken scripts.

**Comment by FrancescoBorzi** [comment] 2019-05-15 20:25
> @poszer has been investigating and what's happening is due to poor SAI scripting. Many events, quests and creatures are being spawned without being reset and this accumulates memory overtime. I do believe that if we focus on snipping these bad scripts that the server performance will stabilize, however it takes quite the effort to find those broken scripts.

I haven't investigated this yet, but according to what you're saying we should find a way to solve the issue at a generic level. So the SAI system should prevent poorly written SAI scripts to cause memory issues.

**Comment by Hir0shi** [comment] 2019-06-22 20:07
RAM: 15G
usage of : RAM 52%
usage of CPU: 50%
0 online players!
Test OS: Linux

IMAGE:
https://pasteboard.co/IkDFROZ.png

WHAT !?!

**Comment by Hir0shi** [comment] 2019-06-23 11:42
Confirm

https://github.com/azerothcore/azerothcore-wotlk/issues/1997

**Comment by Viste** [comment] 2019-06-24 04:32
@Hir0shi lol in your closed issue your worldserver eat only 3GB of real ram and you panic haha lol !

**Comment by Hir0shi** [comment] 2019-06-24 06:16
iKNOW, You are very Amateur!
yes ram get use 3G But enable 15G!
Over time, Azcore using get more RAM!

and np, i will to Test and use Trinitycore, there was no problem!

This is great for you, left of Contributor! The Azcore is corrupted...

**Comment by Viste** [comment] 2019-06-24 06:35
OMG RTFM then say shit: https://www.tldp.org/LDP/sag/html/vm-intro.html
YOU REAL RAM usage is 3GB so keep calm and masturbate on porn or  smoke weed )))
and i know about shit in AZ core more then you ))))
TC use another base for communicate with CPU and etc so again stop say shit :)
For AZ ACE base and some code stuff in core 3G of ram is mormal

**Comment by Hir0shi** [comment] 2019-06-24 06:37
are you drunk!

GG

**Comment by Viste** [comment] 2019-06-24 06:39
Almost all you issues closed in all of project you try to make you little private server more work full, and guess why?  because you an idiot )

**Comment by Hir0shi** [comment] 2019-06-24 06:42
This is great for you, You will soon understand! In the next reports!

and save my reports. BB

**Comment by Viste** [comment] 2019-06-24 07:16
good night sweet prince

**Comment by Hir0shi** [comment] 2019-06-24 20:10
54x post report ! are they wrong?


AzCore Ram and Cpu Usag after 5hours 
https://pasteboard.co/IkMP5K4.png


TrinityCore Ram and Cpu usage after 12hours:
https://pasteboard.co/IkRczgj.png

**Comment by FrancescoBorzi** [comment] 2019-06-24 20:13
@Hir0shi repeating the same message everywhere is NOT helping. Providing more details that can help the developers to spot any memory issue would help.

Do you understand? Please stop spamming

**Comment by Hir0shi** [comment] 2019-06-24 20:14
Hi @FrancescoBorzi 

Iknow, sry but!

see @viste posts..

**Comment by Viste** [comment] 2019-06-24 20:33
this is will help a bit https://github.com/azerothcore/azerothcore-wotlk/pull/1724

**Comment by FrancescoBorzi** [comment] 2019-06-24 20:38
@Viste it would be great if we could complete and merge that one...

**Comment by Viste** [comment] 2019-06-24 21:49
@FrancescoBorzi sorry but for now dont have time, a lot of work, I don't sleep all the time, and I'm also fixing the house.

**Comment by FrancescoBorzi** [comment] 2019-06-24 21:51
@Viste sure mate, take your time!

**Comment by Hir0shi** [comment] 2019-06-25 10:33
@FrancescoBorzi 

I did a test, think!
This problem increases the RAM by moves in the maps!

example:

I see Azcore usage ram: 40% and
i will to set gm mod speed and fly to 15 get move in the maps ... For 20 to 30 minutes
Ram usage changed to 58% !

Power Ram: 15G
OS: linux

There are no players on the server / just for test by gm rank

Can this be?!

**Comment by milestorme** [comment] 2019-06-25 10:43
its a single core thing he needs to do a top -H -p <pid>

eg
`top - 20:41:11 up 155 days, 23:35,  1 user,  load average: 0.67, 0.81, 0.95
Threads:  12 total,   1 running,  11 sleeping,   0 stopped,   0 zombie
%Cpu(s):  7.4 us,  2.5 sy,  0.0 ni, 89.9 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 32727944 total,  5122104 free,  8342228 used, 19263612 buff/cache
KiB Swap:  1046520 total,  1046520 free,        0 used. 23523320 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
17500 torn      20   0 7465516 4.777g  27012 S 28.7 15.3   2351:40 worldserver
17507 torn       5 -15 7465516 4.777g  27012 R  6.7 15.3 785:01.11 worldserver
17506 torn       5 -15 7465516 4.777g  27012 S  6.3 15.3 781:41.87 worldserver
17501 torn      20   0 7465516 4.777g  27012 S  6.0 15.3 595:34.72 worldserver
17504 torn      20   0 7465516 4.777g  27012 S  2.0 15.3 201:11.31 worldserver
17503 torn      20   0 7465516 4.777g  27012 S  0.7 15.3  79:14.48 worldserver
17492 torn       5 -15 7465516 4.777g  27012 S  0.0 15.3   0:02.68 worldserver
17493 torn      20   0 7465516 4.777g  27012 S  0.0 15.3   0:00.04 worldserver
17494 torn      20   0 7465516 4.777g  27012 S  0.0 15.3   7:10.40 worldserver
17495 torn      20   0 7465516 4.777g  27012 S  0.0 15.3   0:06.35 worldserver
17502 torn      20   0 7465516 4.777g  27012 S  0.0 15.3   3:46.90 worldserver
17505 torn       5 -15 7465516 4.777g  27012 S  0.0 15.3   0:19.94 worldserver

i see no mem leaks 8.5 days uptime averaging 20-25 players

`

**Comment by FALL1N1** [comment] 2019-06-25 10:55
Most eventually the grids are not unloaded if there are no players nearby, for example the dark portal, the npcs there fight 24/7, if there are no players they should stop their events.

**Comment by Hir0shi** [comment] 2019-06-25 13:01
@FALL1N1 

Only you can solve the problem ;d

**Comment by Stoabrogga** [comment] 2019-06-25 13:21
@FALL1N1 
> Most eventually the grids are not unloaded if there are no players nearby, for example the dark portal, the npcs there fight 24/7, if there are no players they should stop their events.

That's true, but the event only starts if at least one player enters the area (because otherwise the NPCs are not set to active). Also, this is not a memory leak (taking constantly more and more RAM) and only consumes a little more memory after the event is triggered for the first time.

**Comment by FrancescoBorzi** [comment] 2019-06-25 16:36
it's always good to improve the RAM usage but **please**, please please please do not abuse of the term [memory leak](https://en.wikipedia.org/wiki/Memory_leak) and avoid spreading myths about it

**Comment by Hir0shi** [comment] 2019-06-25 19:12
Yes  and Azerothcore project Much needs to be optimized...

example:
TrinityCore 3.3.5 last,rev after 24hours uptime ram and cpu % usage
RAM: 17.6%
CPU: 8.6%
Power RAM 15G But core just usage RES 1G!
https://pasteboard.co/IkRczgj.png
------------
AzerothCore 3.3.5 last,rev after 5hours uptime ram and cpu % usage
RAM: 61.0%
CPU: 59.2%
https://pasteboard.co/IkMP5K4.png
Power RAM 15G But core just usage RES 3.548G!

**Comment by FrancescoBorzi** [comment] 2019-06-25 20:01
@Hir0shi using more ram doesn't necessarily mean that it is less optimised. 

Please read: http://www.azerothcore.org/wiki/FAQ

![image](https://user-images.githubusercontent.com/75517/60129201-c0604780-9794-11e9-8828-b2f4ae67bc80.png)

So please STOP just comparing the RAM usage with TC without analyzing what is really happening.

**Comment by Stoabrogga** [comment] 2019-07-01 08:11
Closing this, as there's no prove about memory leaks. Enough people tried to reproduce this behaviour, checked their own server and commented on the issue that everything is ok, even after days of server uptime, e.g.:
https://github.com/azerothcore/azerothcore-wotlk/issues/1887#issuecomment-495946651
https://github.com/azerothcore/azerothcore-wotlk/issues/1887#issuecomment-506558222
https://github.com/azerothcore/azerothcore-wotlk/issues/1887#issuecomment-506649011

I also use AC for many months now without any issues.

**Closed by Stoabrogga** 2019-07-01 08:11 UTC
Labels: Priority - High

**Comment by FrancescoBorzi** [comment] 2019-09-15 09:58
## AzerothCore RAM usage explanation

http://www.azerothcore.org/wiki/Memory-Usage
