### ISSUE TITLE
(Creature) Michael Belfast must speak with you when you enter in the zone

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#16435] opened 2023-06-01 18:08 UTC
### Current Behaviour

Michael Belfast https://wowclassicdb.com/wotlk/npc/30571 not speak with you when you enter in the zone

### Expected Blizzlike Behaviour

This NPC must speak with you when you enter in the zone

### Steps to reproduce the problem

1. Go to dungeon
2.  Enter in the zone
3. Watch if NPC is talking

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/96a5224d927fde51860619abfe32e2fa5b3f14fa+ 2023-04-22 07:25:31 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

x64

**Comment by heyitsbench** [comment] 2023-06-01 19:02
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15611.

**Closed by heyitsbench** 2023-06-01 19:02 UTC
