### ISSUE TITLE
Certain Special Characters in SQL Password Cause DB Connection Failure

### ISSUE THREAD

**Issue by pillbug22** [azerothcore/azerothcore-wotlk#15415] opened 2023-03-16 18:38 UTC
### Discussed in https://github.com/azerothcore/azerothcore-wotlk/discussions/14600

<div type='discussions-op-text'>

<sup>Originally posted by **pillbug22** January  9, 2023</sup>
Greetings everyone - 

Have tried a few different cores over the years and this time around going with AC for the first time (Ubuntu-based). Have everything cloned, built, extracted, configured, etc. but running into something I haven't seen before.

The default "acore" database user has been given a new password in MySQL, and can successfully login manually with the new password using

`mysql -u acore -p`

authserver.conf and worldserver.conf are updated with the new password:

`LoginDatabaseInfo = "127.0.0.1;3306;acore;<updated password>;acore_auth"`

However, when launching ./authserver or ./worldserver  (still first time), it errors with

```
AzerothCore 3.3.5a  -  www.azerothcore.org

> Using configuration file       /home/<my local linux user>/azeroth-server/etc/worldserver.conf
> Using SSL version:             OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
> Using Boost version:           1.74.0
 
Can't set process priority class, error: Permission denied
Initializing Scripts...
> Loading C++ scripts
 
Opening DatabasePool ''. Asynchronous connections: 1, synchronous connections: 1.
Could not connect to MySQL database at : Access denied for user '<my local linux user>'@'localhost' (using password: NO)
DatabasePool Login NOT opened. There were errors opening the MySQL connections. Check your log file for specific errors
```

indicating it is trying to login to MySQL as my linux console user, not the "acore" database user as defined in the .conf files. Is there a setting I missed somewhere that tells the startup scripts to use the DB user instead of local console user?

The above output is on console, then also the same message is in the Auth.log. I do also have a DBErrors.log file generated, but it is empty (no info is written to it).

Thanks in advance!

Edit: Also confirmed it wasn't something weird about MySQL thinking it was a remote connection rather than local. Configured the bind-address on MySQL to allow all local connections, and I can connect OK to the DB from another PC using MySQL Workbench and the "acore" user. Even after allowing remote connections to MySQL, the authserver and worldserver still are attempting to use the local linux console user to login instead of the values in the .conf files.</div>

**Comment by pillbug22** [comment] 2023-03-16 18:40
Original discussion thread here with extra troubleshooting: https://github.com/azerothcore/azerothcore-wotlk/discussions/14600

**Cause:** Special characters in the MySQL user account password.

**Workaround:** Change the special characters being used in the MySQL account password.

I originally had a "#" and a "&" in the MySQL user account being used. This account would login OK from the command line and even MySQL Workbench.

Replacing the # and & with ? and ^, now authserver and worldserver launch correctly. Seems to be something with how ACore is pulling in those SQL connection strings from the .conf file so they are not being passed to MySQL correctly (since the characters themselves appear to be valid as password characters within MySQL itself).

Not sure if a fix can be applied or there is already a known issue for certain special characters being used by ACore (I haven't been able to find reference to this yet).

**Comment by Kitzunu** [comment] 2023-03-16 19:10
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/4781

**Comment by Kitzunu** [comment] 2023-03-16 19:10
Also next time you open an issue. Use the bug template.

**Closed by Kitzunu** 2023-03-16 19:10 UTC
Labels: Invalid-MissingHash/Commit
