### ISSUE TITLE
Core/Pet - Player pets have stopped following them a few times

### ISSUE THREAD

**Issue by diluh** [azerothcore/azerothcore-wotlk#2399] opened 2019-11-03 00:17 UTC
**Description:**

Players' pet is buggy

**Current Behavior:**

After some testing I found that the pet's of players of all classes at certain times stop moving as follows in the video below:

https://www.youtube.com/watch?v=XBJ0_tDMyV0&feature=youtu.be

But this bug does not happen every time, I tested on a server with clean database and did not reproduce the problem.

I tested it on a live server and the error happens.

**Expected Behavior:** Pet's Must Follow Players

**Steps to reproduce the problem:** Player pets must follow them

of the mission
Branch (s): Master

Hash / CA Confirmation: https://github.com/azerothcore/azerothcore-wotlk/commit/8a3a7295a40de873ba5c59d50ace5fb4b9f429ea

Operating System: Windows Server 2008 R2

**Comment by diluh** [comment] 2019-11-03 00:19
Also related to this Bug.

https://github.com/azerothcore/azerothcore-wotlk/issues/2390

**Comment by Stoabrogga** [comment] 2019-11-03 00:27
Just like I wrote in #2390, cannot confirm those issues on my server. Never happened to me once, and I play very much on my server.

> I tested on a server with clean database and did not reproduce the problem.
>
> I tested it on a live server and the error happens.

Perhaps there's something wrong with this live server if it works on another one with a clean DB.

**Comment by diluh** [comment] 2019-11-03 00:31
@Stoabrogga 
Tell me which database manager I can run the database on and which version of Mysql to use for further testing.

Navicat - HeidSql - SqlYog?

**Comment by pklloveyou** [comment] 2019-11-03 03:13
I also can't reproduce the problem

**Comment by Stoabrogga** [comment] 2019-11-03 09:20
@diluh 
I'm only using MySQL 5.7.27-0ubuntu0.16.04.1, no other tools.

**Comment by solidmaxtor** [comment] 2019-11-03 09:49
have same problem:
Ubuntu 16, mysql 5.7,  no modules, new maps download
https://www.youtube.com/watch?v=iNc_9AjyhEU

This happen in pets and all world creatures

**Comment by brussens** [comment] 2019-11-06 04:50
Sustained. There is indeed a problem. For example, in the cloak in the dalaran, the mage pet refuses to move. I'd like to note that this is not the only problem that appeared after updating the C++ version support commit.

**Comment by Stoabrogga** [comment] 2019-11-06 07:00
Ok, tested this myself with a mage. Ran around Dalaran for a while including the Underbelly and the Water Elemental never got stuck.

**Comment by brussens** [comment] 2019-11-06 11:31
Dear, if you don't have a problem, it doesn't mean you don't have one. Or do you want to say now that a few people simply confirm its presence on their "combat" servers? There is a problem, even on a clean database with the latest commit on Debian 9 x64, if that's important. If the staff doesn't want to admit the problem exists, just say so, and don't make users look like idiots. Thanks.

**Comment by Stoabrogga** [comment] 2019-11-06 11:48
Perhaps you should stop your aggressive attitude. I'm just trying to help by reproducing the issue. I have not yet tried running around Dalaran / Underbelly and when you mentioned it I did test it and provided my test results, that's all. I can also stop helping, solve this yourself.

**Comment by FrancescoBorzi** [comment] 2019-11-06 12:01
@brussens no one said that the problem does not exist. It's just we (as developers) can't fix it until we are able to reproduce it.

I think you misunderstood what @Stoabrogga said

**Comment by brussens** [comment] 2019-11-06 12:06
@Stoabrogga I don't understand what aggression is all about. There is a real fact that there is a problem with a few people on fresh assemblies. The problem appears randomly, not just in one place. I just can't understand why if there is a problem, then the staff can't admit it. No need to be offended, we are adults.

As for commits, I can only share sample information based on auth,uptime table data:
The last commit that didn't have a problem was 03864eea587f61cff66968aeee8b294247842ce1

Commit, after the upgrade, there was a problem: 0651e771231ca2a3ccf23cb141cb51ddf5152667

I'll note that the problem could have been between these commits.

**Comment by brussens** [comment] 2019-11-06 12:10
Also, I would like to draw your attention to the fact that the database has nothing to do with this in our case. The problem is only inside the code itself

**Comment by Stoabrogga** [comment] 2019-11-06 12:15
It's not about admitting that there are errors. It's great to find errors, because then they can be solved. But as long as I'm not able to reproduce it I have no idea where to look or how to solve this, sorry.

But I'll stop testing nevertheless, as obviously my server is not affected. Perhaps another developer can reliably reproduce the issue.

**Comment by FrancescoBorzi** [comment] 2019-11-06 12:43
@brussens all software can have bugs and we are well aware of it. No problems at all in "admitting" the existence of a bug. Never.

You confused "I can't reproduce the bug" with "there is no bug. They are two different things and @Stoabrogga clearly meant the first one.

That said, if anyone can help us to reproduce the issue, it would be great so we can fix it.

**Comment by Stoabrogga** [comment] 2019-11-06 13:04
@brussens 
Could you please post which cmake version and which compiler (incl. version) you are using to build the core?

**Comment by brussens** [comment] 2019-11-06 13:05
@FrancescoBorzi I wasn't trying to offend or be rude. It's just a fact that the 2 issue is open with this problem. My players also complained about hanging pets and pussies. I wrote down the approximate amount of commits above. If you hurt anyone, I'm sorry.

**Comment by brussens** [comment] 2019-11-06 13:13
@Stoabrogga By the way, I was just thinking that I was restoring the server image from the backup. This image, I probably did before the clang update.

**Comment by brussens** [comment] 2019-11-06 13:14
@Stoabrogga I'm gonna go in and check out the clang version

**Comment by brussens** [comment] 2019-11-06 13:24
@Stoabrogga Yes, indeed, I had a rollback to clang 3.8.1. CMake 3.15.4.

I will be upgrading my machine to Debian 10 today, so I will be able to test the updated components on a production server if necessary. However, it is certain that this is the problem since debian clang 6+ is not installed by default.

**Comment by BarbzYHOOL** [comment] 2019-11-06 15:47
> The last commit that didn't have a problem was 03864ee
> 
> Commit, after the upgrade, there was a problem: 0651e77
> 
> I'll note that the problem could have been between these commits.
> 

test all commits before and after  and find the exact commit then -__-'

**Comment by solidmaxtor** [comment] 2019-11-07 01:09
I mi case continue the problem, not know how can reproduce, only compile As I have always done.
Use ubuntu 16.04 with the udates required to compile Acore.
I only need test for install ubuntu 18 and see if the error persists.
I hope I can do it soon.

**Comment by diluh** [comment] 2019-11-07 01:37
I use have server on windows.  VS 2017 32x OpenSSL 1.0.2n MySQL 5.6 and still continue with the error.  not only affects housekeeping animals but affects some spells with infinite delay and not.

**Comment by Stoabrogga** [comment] 2019-11-07 07:15
I think after this commit you have to use at least clang 6 and cmake 3.8:
https://github.com/azerothcore/azerothcore-wotlk/commit/3a43e8c415cee4041f2a59e9ebc8af721a49be23
Also mentioned here:
http://www.azerothcore.org/wiki/Requirements

I'm currently using MySQL 5.7, clang 7.1.0, cmake 3.15.4 to build the core on Ubuntu 16.04 64-bit. Don't know if it's better for Windows to use VS 2019 as I don't use Windows and have no experience building the core there.

**Comment by pklloveyou** [comment] 2019-11-07 10:16
So far, none of the above errors have occurred. VS2019 Win10X64

**Comment by brussens** [comment] 2019-11-07 10:30
Yesterday I upgraded my server machine to Debian 10.1. I keep watching, I've already asked players to join in. But I think it's obvious. The problem is the software used to compile. I'm sure the problem may be with the outdated clang.

And yes, there's no problem yet. Please do not close the issue yet, at least for a couple of days.

P.S.: no problems are observed on Win10x64 VS2019 (last release).

**Comment by diluh** [comment] 2019-11-07 10:36
I will be upgrading to VS 2019 and will give me a 32x or 64x recommended feedback?

**Comment by brussens** [comment] 2019-11-07 11:53
@diluh VS 2019 x64 works perfectly)))

**Comment by brussens** [comment] 2019-11-07 18:00
Friends, having looked a little bit behind the recompiled core on the new software, I can say that the problem is kind of gone. Apparently, the problem was with the clang version.

**Comment by BarbzYHOOL** [comment] 2019-11-07 18:01
you were using clang 3.8?

**Comment by brussens** [comment] 2019-11-07 20:40
Yeah (3.8.1), I forgot to update it after the server was restored after the crash OS.

**Comment by diluh** [comment] 2019-11-08 05:52
This problem should not be closed yet I updated to VISUAL STUDIO 2019 X64 and still the error

**Comment by diluh** [comment] 2019-11-08 09:42
Can anyone help me solve this problem?

I installed VS 2019 Community Windows Server 2008 R2 x64

Mysql 5.7 - Lib
MariaDB as a data manager.
OpenSSL 1.0.2t 64x
All 32x / 64x c ++ packages
Cmake 3.16.0-rc3

I downloaded the updated AzerothCore Wiki [Date] maps again

HeidSql - Navicat - Sqlyog.

Nucleo AzerothCore updated on the latest commit.

And even with all this I still get errors in pets.

**Comment by diluh** [comment] 2019-11-08 11:03
I can only reproduce the bug with people active on the server alone it seems to have no errors.

**Comment by FrancescoBorzi** [comment] 2019-11-08 14:13
@brussens perfect, thanks for letting us know

@diluh try to use a newer version of cmake, preferrably 3.8 or higher

**Comment by diluh** [comment] 2019-11-08 15:22
@FrancescoBorzi I am using 3.16 latest and have errors, me and several other people who have server.

**Comment by FrancescoBorzi** [comment] 2019-11-08 15:25
@diluh what errors?

**Comment by BarbzYHOOL** [comment] 2019-11-08 18:45
it's probably still a compilation thing but different issue for windows (mvs)

**Comment by brussens** [comment] 2019-11-10 13:07
Friends, after a few days of watching the production server, I can say that the problem manifests itself. What a mistake, unfortunately, I could not catch.

**Comment by diluh** [comment] 2019-11-10 15:38
Friends this problem is very serious could you mark this issues as a high priority please?

**Comment by BarbzYHOOL** [comment] 2019-11-10 20:07
also the pet does not regen HP, like it stays in combat forever

**Comment by brussens** [comment] 2019-11-12 14:26
Yes, indeed, even with the freshest software there are problems of hanging up of the pets, npc at death return to the place of the spawn, some players have strong friezes when ping about 25 and disconnects them from the server.
This problem is very critical and I still can't understand the reason for this behavior.

**Comment by Stoabrogga** [comment] 2019-11-12 14:44
@brussens 
Do you see any heavy load on your server? Taking much CPU or I/O? Or bad internet connection? Perhaps a DoS attack? I still don't have the slightest idea what could cause this. This looks like a massive server lag.

**Comment by vhiperdev** [comment] 2019-11-12 14:53
I checked and there really is this problem, can not reproduce is something relative.

It looks like a delay that causes creatures like Waypoints - pet movement - to stall in some debuff cast spells.

I have outdated the core and will be monitoring the changes to identify what is causing it.

**Comment by BarbzYHOOL** [comment] 2019-11-12 15:02
@vhiperdev tell us at which commit it starts to happen if you can :(

**Comment by Knindzagxg** [comment] 2019-11-12 17:08
Mostly it seems like server resources issues.
Tested on my previous commit (With 45 days uptime) no issues.

Re-compiled with latest, and still no issues at all.
Problem can be RAM memory if you have to low (I suppose server is running on VPS)

Will keep eye on this, but none of players or devs that work with me were able to confirm issue sadly.

PS. Check if this happening with regular pets, cause i assume people taking free exotic one from NPC. Sometimes, there were issues, so make sure to check with regular pets.

https://www.youtube.com/watch?v=ORYAZNkhmmA&feature=youtu.be

**Comment by Knindzagxg** [comment] 2019-11-12 17:17
Also, wierd thing i noticed is that your pet doesn't appear after u dismount - Should be instant.
There was PR few months ago for it, and it works perfectly.

**Comment by vhiperdev** [comment] 2019-11-18 06:50
@Stoabrogga @brussens @diluh @solidmaxtor

After some tests on an online server I verified that this error is related in this commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9ea9329285e5eeb27b2f096dba69d4fea0f3d9cb

**Comment by Stoabrogga** [comment] 2019-11-18 07:30
@vhiperdev 
Thanks for nailing this down to this commit. I'll look into this and try to figure out what could cause the issue there.

**Comment by Stoabrogga** [comment] 2019-11-18 12:52
Ok, now that I know where to look for the error I finally was able to reproduce the issue on my server using 2 accounts:
- Create 2 hunters, put their pets in "defensive" mode
- `.go 7343.97 -896.434 915.94 571`
- Attack one of the rhinos there with the pet of the first hunter
- Attack the same rhino with the pet of the second hunter
- Run away with the second hunter, constantly attacking the rhino with the pet, so it keeps following
- One of the pets will show the bug

I'm already working on a solution and will create a PR once finished.

**Comment by Stoabrogga** [comment] 2019-11-18 22:52
Could you please test PR #2457 and provide feedback?

**Closed** 2019-11-26 08:49 UTC
Labels: Confirmed
