### ISSUE TITLE
The CPU usage rate of the worldserver process is 105%

### ISSUE THREAD

**Issue by moncat2005** [azerothcore/azerothcore-wotlk#17439] opened 2023-10-07 08:50 UTC
### Current Behaviour

The CPU usage of the worldserver process compiled by the acore version submitted before September 28, 2023 is approximately 30%.
The CPU usage of the worldserver process compiled by the acore version submitted after September 29, 2023 has increased to 105%.
It may be related to the introduction of grid functionality.
The configuration parameters of worldserverconf have also been typeset and sorted between these two progressive versions.
minworldupdatetime parameter in the configuration file has been reset to the same 10
In addition, the three parameters of visibility.distance remain consistent with the previous version.

### Expected Blizzlike Behaviour

Resolve abnormal CPU usage issues

### Steps to reproduce the problem

At present, it has been found that the version rolled back to September 28th has returned to normal.

### AC rev. hash/commit

AzerothCore rev. a2c6af4c5683+ 2023-10-01 07:26:31 +0000 (master branch)

### Operating system

Ubuntu 18.04

### Custom changes or Modules

Eluna module

**Comment by Kitzunu** [comment] 2023-10-07 11:17
@AGandrup Could you take a look, I think it all is surrounding the visibility change. I can't pin point the actual issue myself atm... and if we don't get it fixed within the next few days we need to revert it for the time being

**Comment by kissingers** [comment] 2023-10-09 14:32
Yes , https://github.com/azerothcore/azerothcore-wotlk/pull/15919  this only fix a very little problem, but case the server 300% CPU usage

**Comment by kissingers** [comment] 2023-10-09 14:36
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/5612b07f-6def-4cad-9af6-3f116f0f0e9a)
first is update the https://github.com/azerothcore/azerothcore-wotlk/pull/15919
second is npcbots with 200 npc and without update the patch
third is clear server without update the patch

**Comment by avarishd** [comment] 2023-10-09 14:38
That explains why AC has been so hard to run.

**Comment by mpfans** [comment] 2023-10-14 03:20
Encountered the same issue after updating this PR https://github.com/azerothcore/azerothcore-wotlk/pull/15919

**Comment by heyitsbench** [comment] 2023-10-14 03:21
@mpfans, would you be able to test #17480?

**Comment by mpfans** [comment] 2023-10-14 14:10
> @mpfans, would you be able to test #17480?

Tested without improvement

**Comment by AGandrup** [comment] 2023-10-14 14:53
> > @mpfans, would you be able to test #17480?
> 
> Tested without improvement

That sounds very odd to me if you dont see any improvement at all, because that PR stops gameobjects as well as transport from being set to active. What tests have you done?

Anyway, I will push some changes soon that should further improve CPU usage.

**Comment by mpfans** [comment] 2023-10-14 14:55
Update time diff too high

**Comment by AGandrup** [comment] 2023-10-14 15:00
> Update time diff too high

How much is it for you?

**Comment by mpfans** [comment] 2023-10-14 15:02
> > Update time diff too high
> 
> How much is it for you?
`Update time diff: 325. Players online: 2054.`

before the update, only half of it

**Comment by mpfans** [comment] 2023-10-16 03:13
`git reset --hard 29af6cc88662ab2565bdcedcf60e12f0cc87cecf`

All the problems have disappeared

**Comment by mpfans** [comment] 2023-10-16 09:49
> revert

Yes, it must be revert

**Comment by mpfans** [comment] 2023-10-16 09:52
This bug https://github.com/azerothcore/azerothcore-wotlk/issues/17434 Same PR# https://github.com/azerothcore/azerothcore-wotlk/pull/15919 Causing

**Comment by Nyeriah** [comment] 2023-10-16 10:17
It’s being worked on by the author, if he doesn’t manage to address the issues then we will likely revert it. For the time being please revert it locally

**Comment by boom8866** [comment] 2023-10-16 18:09
Eluna module ？

**Comment by kissingers** [comment] 2023-10-19 03:06
I see the code have  2 for for loop, the code not exit before ,might this ?

**Comment by mpfans** [comment] 2023-10-20 02:09
> It’s being worked on by the author, if he doesn’t manage to address the issues then we will likely revert it. For the time being please revert it locally

Is there an approximate time frame? Or indefinitely? Because there are too many commits based on this PR in the future

**Comment by AGandrup** [comment] 2023-10-21 11:06
Hey! Can anyone test the latest changes done here: https://github.com/azerothcore/azerothcore-wotlk/pull/17480 and check if that fixes the issue? Thanks in advance 😬

**Comment by kissingers** [comment] 2023-10-23 16:02
update to 60e27511c530b0949fee361a89d3eb9d9f9125af
the first worldserver is the updated server
before update cpu 445%, players 100+
![6285c89a999bb610c48277a4a81ecd3](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/2ea010b9-8806-4a5e-8a2a-14a16da9d2d6)

after update and start about 10m, it seem fine, low to 50% , players 66+
![a6c5662a872733ec87999041fc1a175](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/9534ef5d-c237-4476-ae6d-583a73bf86c4)

after udate and start about 1 hour , sometimes the cpu more high then before to 500%, players 58+
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/e17caf78-abb6-4934-b5ad-04a277d983ec)

**Comment by Kitzunu** [comment] 2023-10-23 16:16
What the fuck

**Comment by kissingers** [comment] 2023-10-23 16:27
I set MapUpdate.Threads = 8 , and will set  MapUpdate.Threads = 4 and test
The PreloadAllNonInstancedMapGrids = 1 and  will set The PreloadAllNonInstancedMapGrids = 0 and test

**Comment by kissingers** [comment] 2023-10-23 16:31
after set MapUpdate.Threads = 4  and The PreloadAllNonInstancedMapGrids = 0  the server cpu very low at first, player 34+
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/046c42f7-5d49-473d-832d-1b03c0138d03)

**Comment by AGandrup** [comment] 2023-10-23 16:44
Sigh. 

Will look into it as soon as I can but im gonna need all the information I can get.

Can you try up the visibility notifier in confs? Just to see if it helps anything. Same for grid clean up delay.

**Comment by kissingers** [comment] 2023-10-23 16:54
> Sigh.
> 
> Will look into it as soon as I can but im gonna need all the information I can get.
> 
> Can you try up the visibility notifier in confs? Just to see if it helps anything. Same for grid clean up delay.

which config flags?

Ii seems the patch work well for very low MapUpdate.Threads and when PreloadAllNonInstancedMapGrids = 0
bug if MapUpdate.Threads large to such as my before config 8, and PreloadAllNonInstancedMapGrids = 1, the cpu is very high

config 4 and 0 with 25 players after reboot 30m
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/d80f3baa-2376-4a3f-8d07-d696434de5f0)

**Comment by AGandrup** [comment] 2023-10-23 17:03
> > Sigh.
> > Will look into it as soon as I can but im gonna need all the information I can get.
> > Can you try up the visibility notifier in confs? Just to see if it helps anything. Same for grid clean up delay.
> 
> which config flags?
> 
> Ii seems the patch work well for very low MapUpdate.Threads and when PreloadAllNonInstancedMapGrids = 0 bug if MapUpdate.Threads large to such as my before config 8, and PreloadAllNonInstancedMapGrids = 1, the cpu is very high
> 
> config 4 and 0 with 25 players after reboot 30m ![image](https://user-images.githubusercontent.com/33601959/277413352-d80f3baa-2376-4a3f-8d07-d696434de5f0.png)

Not home atm and can't remember the names exact but you should be able to find it just by searching in worldserver config "notify" and "gridcleanup"

Also what are the default settings for MapUpdate.Threads? Preloading of maps should be set to off (zero)

**Comment by kissingers** [comment] 2023-10-23 17:15
GridCleanUpDelay = 300000
Visibility.Distance.Continents = 100
Visibility.Distance.Instances = 170
Visibility.Distance.BGArenas = 533

**Comment by AGandrup** [comment] 2023-10-23 17:18
> GridCleanUpDelay = 300000 Visibility.Distance.Continents = 100 Visibility.Distance.Instances = 170 Visibility.Distance.BGArenas = 533

No, this is what you must look for:
Visibility.Notify.Period.OnContinents = 1000
Visibility.Notify.Period.InInstances  = 1000
Visibility.Notify.Period.InBGArenas   = 1000

GridCleanUpDelay is right, you could try fiddle with that as well.

Do you use any modules btw?

Also, I wonder if I can reproduce these issues if I install playerbots, hmm.

**Comment by AGandrup** [comment] 2023-10-23 17:36
> these seting are default volume Visibility.Notify.Period.OnContinents = 1000 Visibility.Notify.Period.InInstances = 1000 Visibility.Notify.Period.InBGArenas = 1000
> 
> > List enable modules:
> 
> * mod-anticheat
> * mod-bg-reward
> * mod-cfbg
> * mod-eluna
> * mod-multi-client-check
> * mod-npc-beastmaster
> * mod-pvp-titles
> * mod-reward-played-time   this changed by myself
> * mod-save-inventory
> * mod-server-auto-shutdown
> * mod-zone-difficulty      this simpled by myself
> * mod_spec_reward     this changed by myself

Alright, thank you. You could try increasing the notify period just for the sake of testing. Try set it to 1500 or higher, whatever you feel like.
I dont see how any of your modules should cause any problems, judging from their names, but feel free try disable those you think could have any impact.

**Comment by kissingers** [comment] 2023-10-23 17:47
I set these as  default and reboot
MapUpdate.Threads = 1 
The PreloadAllNonInstancedMapGrids = 0

before restart  MapUpdate.Threads = 4

and now cpu 33% before 71%

So I think the pr have good effect at default seting, but not good work for more map thread  and if preload all grids, 
 if set The PreloadAllNonInstancedMapGrids =1 , even SetAllCreaturesWithWaypointMovementActive = 0 will much cpu using

**Comment by AGandrup** [comment] 2023-10-23 17:51
> I set these as default and reboot MapUpdate.Threads = 1 The PreloadAllNonInstancedMapGrids = 0
> 
> before restart MapUpdate.Threads = 4
> 
> and now cpu 33% before 71%
> 
> So I think the pr have good effect at default seting, but not good work for more map thread and if preload all grids, if set The PreloadAllNonInstancedMapGrids =1 , even SetAllCreaturesWithWaypointMovementActive = 0 will much cpu using

Interesting, thank you. This should give me something to work with. I have been using default settings myself the whole time.

If you discover more things, please let me know!

**Comment by AGandrup** [comment] 2023-10-23 18:05
Ah, I think I am on to something already. Hold on.

**Comment by AGandrup** [comment] 2023-10-23 18:11
We shouldn't be trying to unload grids if we told the server to preload all grids...
Looks like I forgot to implement that setting which controls that lol. yikes.

**Comment by AGandrup** [comment] 2023-10-23 18:56
@kissingers Please test with https://github.com/azerothcore/azerothcore-wotlk/pull/17569

**Comment by Kitzunu** [comment] 2023-10-23 21:38
Should use Grafana, could help track down where the resources are going

**Comment by AGandrup** [comment] 2023-10-23 21:42
> Should use Grafana, could help track down where the resources are going

True, I did think of that, however I have only used Grafana like once, years ago, for some very basic metrics 😛 But will look into it.

**Comment by AGandrup** [comment] 2023-10-23 21:49
Oh I see AC already got something going with Grafana. Thats cool 🙌

**Comment by kissingers** [comment] 2023-10-24 04:28
Server without any player:
Before update test pr start 20m later, 
MapUpdate.Threads=8, PreloadAllNonInstancedMapGrids=1
 

Update test pr without change conf restart 20m later 
MapUpdate.Threads=8, GridUnload = 0, PreloadAllNonInstancedMapGrids = 1
 
It seems with test pr, the cpu to 75% whitout change config, but memory *5

Update test pr change conf restart 20m later
MapUpdate.Threads=1, GridUnload = 0, PreloadAllNonInstancedMapGrids = 1
 
It seems MapUpdate.Threads have less effect cpu 66% form 8 to 1

Update test pr change conf restart 20m later
MapUpdate.Threads=8, GridUnload = 1, PreloadAllNonInstancedMapGrids = 0
 
It seems PreloadAllNonInstancedMapGrids will use more memory and more cpu, need always keep 0 on any condition even with large players

Update test pr change conf restart 30m later
MapUpdate.Threads=1, GridUnload = 1, PreloadAllNonInstancedMapGrids = 0
 
It default config, seems good

Update test pr change conf restart 30m later
MapUpdate.Threads=1, GridUnload = 0, PreloadAllNonInstancedMapGrids = 0
 
Same as MapUpdate.Threads=1, GridUnload = 1, PreloadAllNonInstancedMapGrids = 0

Another Server for real players 50+ ,MapUpdate.Threads=1 the thread cpu 100%, if keep MapUpdate.Threads=1 , when players more than 200+, the server delay will add 3-10ms
 



So the test pr good for cpu use, but still not great effect PreloadAllNonInstancedMapGrids and MapUpdate
PreloadAllNonInstancedMapGrids=1 is not a good option on any condition
If MapUpdate thread not to 100%, keep MapUpdate.Threads = 1 is good select
If MapUpdate thread always 100%, keep MapUpdate.Threads  little enough each  MapUpdate not to 100%

**Comment by AGandrup** [comment] 2023-10-24 06:52
Thank you @kissingers, really appreciate your tests!
The memory increase with GridUnload off is expected, especially with Preloading on.

But the rest is still unacceptable. Im gonna try get Grafana going today, hopefully that can help cast some light on it.

Btw do you remember what your cpu usage and memory was before visibility/grid notifier got implemented?

**Comment by kissingers** [comment] 2023-10-24 08:34
> Thank you @kissingers, really appreciate your tests! The memory increase with GridUnload off is expected, especially with Preloading on.
> 
> But the rest is still unacceptable. Im gonna try get Grafana going today, hopefully that can help cast some light on it.
> 
> Btw do you remember what your cpu usage and memory was before visibility/grid notifier got implemented?

AMD 6800H 8*2 cpu，32GB Before with the config MapUpdate.Threads=8, PreloadAllNonInstancedMapGrids = 1  about 330% CPU and 30% RAM without client delay， with  MapUpdate.Threads=1, PreloadAllNonInstancedMapGrids = 0 about 220% CPU and 5% RAM but have client 3-5 ms delay.  about 100+ players.

**Comment by Kitzunu** [comment] 2023-10-24 11:43
Would be good if Kissinger got grafana too to try and help pinpointing us somewhere

**Comment by kissingers** [comment] 2023-10-24 12:05
now MapUpdate.Threads=2 ,100+ players ,cpu 206%, Update time diff: 3ms, average: 2ms. it seems need change to 3 or 4 threads, before 8 threads always Update time diff: 1ms, average: 1ms.

**Comment by moncat2005** [comment] 2023-10-26 09:46
AzerothCore rev. 29af6cc88662+ 2023-09-28
![0928-cpu](https://github.com/azerothcore/azerothcore-wotlk/assets/34859687/8de266cf-1136-44ed-a8e0-09295230abb5)


AzerothCore rev. 23a620007b38+ 2023-10-25
![1026-cpu](https://github.com/azerothcore/azerothcore-wotlk/assets/34859687/7544e6ab-8c7d-45bc-8f5b-6f986baf34d1)


The above is the CPU usage difference in the 0 player state after starting the program.

**Comment by AGandrup** [comment] 2023-10-26 09:54
> AzerothCore rev. [29af6cc](https://github.com/azerothcore/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf)+ 2023-09-28 ![0928-cpu](https://user-images.githubusercontent.com/34859687/278286212-8de266cf-1136-44ed-a8e0-09295230abb5.png)
> 
> AzerothCore rev. [23a6200](https://github.com/azerothcore/azerothcore-wotlk/commit/23a620007b38c03368bac441e4fd91c585935c01)+ 2023-10-25 ![1026-cpu](https://user-images.githubusercontent.com/34859687/278287253-7544e6ab-8c7d-45bc-8f5b-6f986baf34d1.png)
> 
> The above is the CPU usage difference in the 0 player state after starting the program.

What does your configuration look like?

**Comment by AGandrup** [comment] 2023-10-26 18:47
Okay, I am pretty sure I have found the issue and it is not even something I have changed. It is actually so stupid lol. More information coming, just need something else clarified first which I dont quite understand.

**Comment by AGandrup** [comment] 2023-10-26 22:36
Please see: https://github.com/azerothcore/azerothcore-wotlk/pull/17569#issuecomment-1781983068
Should be fixed now.

**Comment by moncat2005** [comment] 2023-10-27 04:44
AzerothCore rev. 79b39f965511+ 2023-10-26
![1027-cpu](https://github.com/azerothcore/azerothcore-wotlk/assets/34859687/124fc471-06de-4271-9ace-c59b1bf62312)

**Comment by AGandrup** [comment] 2023-10-27 07:08
Hmm, interesting. Not familiar with this setting so not sure how it is tied together with the rest of it 😛 but i'll look into it.

**Comment by mpfans** [comment] 2023-10-27 12:31
updated to 79b39f9655111088a741185c4dabd31dae7d85ea

```
GridUnload = 1
PreloadAllNonInstancedMapGrids = 0
```
console display: `Update time diff: 500. Players online: 2067.`

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18187177/0ceb5855-1d2b-4b8e-9c74-71e961c7b31c)

**Comment by AGandrup** [comment] 2023-10-27 12:35
> updated to [79b39f9](https://github.com/azerothcore/azerothcore-wotlk/commit/79b39f9655111088a741185c4dabd31dae7d85ea)
> 
> ```
> GridUnload = 1
> PreloadAllNonInstancedMapGrids = 0
> ```
> 
> console display: `Update time diff: 500. Players online: 2067.`
> 
> ![image](https://user-images.githubusercontent.com/18187177/278642542-0ceb5855-1d2b-4b8e-9c74-71e961c7b31c.png)

Holy...
Do you have Grafana or something installed to monitor this? I am kinda running out of ideas..

**Comment by mpfans** [comment] 2023-10-27 12:38
> Holy...
> Do you have Grafana or something installed to monitor this? I am kinda running out of ideas..

No installation, previously installed, but only the first few minutes of running have data, and then there is no data left

**Comment by AGandrup** [comment] 2023-10-27 12:51
> > Holy...
> > Do you have Grafana or something installed to monitor this? I am kinda running out of ideas..
> 
> No installation, previously installed, but only the first few minutes of running have data, and then there is no data left

Hmm okay - you might have to configure influxdb or something. Either way, im gonna need more information to solve this. Like what does your full worldserver conf look like? do you see any pattern in when you get this high cpu usage? Do players visit outland/northrend or are they locked to kalimdor and eastern kingdom only? Do you have anything custom/modules that could possibly have an impact? Etc.

I dont have the same load/2k players to test this with myself, so its really hard, not to say impossible, for me to reproduce this behavior.

**Comment by AGandrup** [comment] 2023-10-27 12:59
> TargetPosRecalculateRange

@moncat2005 This is a deprecated setting. There is not reference to it in the code, so I don't really understand how this could possibly impact performance(?) Is this something you have implemented in your core?

**Comment by mpfans** [comment] 2023-10-27 13:27
> > > Holy...
> > > Do you have Grafana or something installed to monitor this? I am kinda running out of ideas..
> > 
> > 
> > No installation, previously installed, but only the first few minutes of running have data, and then there is no data left
> 
> Hmm okay - you might have to configure influxdb or something. Either way, im gonna need more information to solve this. Like what does your full worldserver conf look like? do you see any pattern in when you get this high cpu usage? Do players visit outland/northrend or are they locked to kalimdor and eastern kingdom only? Do you have anything custom/modules that could possibly have an impact? Etc.
> 
> I dont have the same load/2k players to test this with myself, so its really hard, not to say impossible, for me to reproduce this behavior.

Please tell me your discord ID

**Comment by AGandrup** [comment] 2023-10-27 13:29
Swagkhalifa#5709 (dont judge)

**Comment by moncat2005** [comment] 2023-10-27 14:27
> > TargetPosRecalculateRange
> 
> @moncat2005 This is a deprecated setting. There is not reference to it in the code, so I don't really understand how this could possibly impact performance(?) Is this something you have implemented in your core?
> 
> It was removed in this commit #17544 and before that it didn't serve any purpose.

Yes, I have found commit #17544.

I have not modified the source code.

It was only discovered after the latest compilation that the conf default changed.

Removing or retaining this configuration parameter clearly has a direct impact on the CPU usage of the worldserver process.

**Comment by Kitzunu** [comment] 2023-10-27 22:28
That config option was literally just a string. It did nothing, so it is impossible it would've changed anything

**Comment by moncat2005** [comment] 2023-10-28 12:19
In my impression, this configuration parameter has always been used to set the attacking distance between players moving to the target.
In the description of the original parameter, it is clear that there is a significant difference in CPU usage caused by this parameter.

In AzerothCore rev. 79b39f9+ 2023-10-26
I have repeatedly tested whether to keep or cancel this parameter in the worldserver configuration file. 
After the worldserver service is started, there is indeed a significant difference in the CPU usage of the worldserver service process in 0 player state.

**Comment by AGandrup** [comment] 2023-10-28 12:41
> @Kitzunu In my impression, this configuration parameter has always been used to set the attacking distance between players moving to the target. In the description of the original parameter, it is clear that there is a significant difference in CPU usage caused by this parameter.
> 
> In AzerothCore rev. 79b39f9+ 2023-10-26 I have repeatedly tested whether to keep or cancel this parameter in the worldserver configuration file. After the worldserver service is started, there is indeed a significant difference in the CPU usage of the worldserver service process in 0 player state.
> 
> Based on the CPU usage reference point of a process, the usage rate of 0 players online can be used as a benchmark.

I am sorry, but that does not make any sense. That configuration was only ever used in TargetedMovementGenerator.cpp, so unless you added back that logic, it is dead code. Why you see a difference in CPU usage when you add it, I do not know, but again, it is not used so theres literally no reason for you to add it in the first place.

**Comment by moncat2005** [comment] 2023-10-28 13:06
Hmmm...Perhaps I overlooked an additional factor.

I will test the actual situation of AC native 79b39f9+

**Comment by AGandrup** [comment] 2023-10-28 14:04
Btw I assume when people test these changes, that they use clean AC. The only differences I expect are modules and non-default configurations.

**Comment by Kitzunu** [comment] 2023-10-28 19:58
The config option was an empty unused variable...

**Comment by moncat2005** [comment] 2023-10-30 07:05
The CPU usage test after fully recompiling the AC source code (79b39f9+) is as follows:（without mod and NPCbots）
There are two parameters in the configuration file that differ significantly from the default values:
1. Change MinWorldUpdateTime=1 to 10
2. Change MapUpdateInterval=10 to 100
![PURE-AC-1030](https://github.com/azerothcore/azerothcore-wotlk/assets/34859687/0889fa52-f9a7-4f77-bbd7-122c627ddfc2)
After the startup of the worldserver service, with 0 online players, the CPU usage rate is only 10%.

**Comment by AGandrup** [comment] 2023-10-30 07:28
> The CPU usage test after fully recompiling the Pure AC source code (79b39f9+) is as follows:（without mod and NPCbots） There are two parameters in the configuration file that differ significantly from the default values:
> 
> 1. Change MinWorldUpdateTime=1 to 10
> 2. Change MapUpdateInterval=10 to 100
>    ![PURE-AC-1030](https://user-images.githubusercontent.com/34859687/278964229-0889fa52-f9a7-4f77-bbd7-122c627ddfc2.png)
>    After the startup of the worldserver service, with 0 online players, the CPU usage rate is only 10%.

Okay, just to understand, were these configuration something you had before as well or something you felt needed to be adjusted with these new changes?

I have talked to @mpfans and he said the cpu usage has become better, but is still experiencing high diff after awhile, but this could be due to many things. He runs a server with about 2k players. 

We talked about reverting all of these changes and make a new PR, so it can be properly tested before merging into master.

I do wonder if anyone else is still experiencing similar issues or if its only mpfans (it could be some configuration of his, which needs to be adjusted now).

**Comment by moncat2005** [comment] 2023-10-30 07:42
The two parameters I modified were also caused by issue #16760. 
After modifying these two parameters, the CPU usage has significantly improved.

**Comment by kissingers** [comment] 2023-10-30 08:11
Chang MinWorldUpdateTime = 1  to 10  will  down to 20% cpu
chang MapUpdateInterval = 10 to 100 no much change
chang MapUpdateInterval = 10 to 1 also no much change

so might MinWorldUpdateTime force the  MapUpdateInterval ? or the   MapUpdateInterval  no effect ?

**Comment by mpfans** [comment] 2023-10-30 08:53
> The CPU usage test after fully recompiling the Pure AC source code (79b39f9+) is as follows:（without mod and NPCbots） There are two parameters in the configuration file that differ significantly from the default values:
> 
> 1. Change MinWorldUpdateTime=1 to 10
> 2. Change MapUpdateInterval=10 to 100
>    ![PURE-AC-1030](https://user-images.githubusercontent.com/34859687/278964229-0889fa52-f9a7-4f77-bbd7-122c627ddfc2.png)
>    After the startup of the worldserver service, with 0 online players, the CPU usage rate is only 10%.

Testing needs to be carried out with players, although the CPU has indeed improved significantly, there will be higher `Update time diff`

**Comment by mpfans** [comment] 2023-10-30 09:16
I updated to the latest AC version today and then locally reversed the 3 commits(https://github.com/azerothcore/azerothcore-wotlk/commit/79b39f9655111088a741185c4dabd31dae7d85ea ,https://github.com/azerothcore/azerothcore-wotlk/commit/2779833768bbe9967006d6d16888dace05b4bcb6,https://github.com/azerothcore/azerothcore-wotlk/commit/79b39f9655111088a741185c4dabd31dae7d85ea) , everything is working,`Update time diff: 63. Players online: 1308.`

**Comment by moncat2005** [comment] 2023-10-30 11:31
Update time diff: 63. Players online: 1308.
What is the CPU usage of worldserver at this time?
I think Update time diff is directly related to CPU usage.

Previously, you reported that when Update time diff=500, 
the CPU usage seemed to be 1200%, which means that the 12 logical processors were fully loaded.

**Comment by mpfans** [comment] 2023-10-31 02:51
> > Update time diff: 63. Players online:  1308.
> 
> What is the CPU usage of worldserver at this time? I think Update time diff is directly related to CPU usage.
> 
> Previously, you reported that when Update time diff=500, the CPU usage seemed to be 1200%, which means that the 12 logical processors were fully loaded.

`Update time diff: 73. Players online: 1289.`
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18187177/c92e660f-fdd7-41c5-926c-8d42a2d79403)

**Comment by moncat2005** [comment] 2023-10-31 07:38
@mpfans 
> reversed the 3 commits(79b39f9 , 2779833 , 79b39f9) 
Why are the first and third commit ids the same?

**Comment by mpfans** [comment] 2023-10-31 07:40
> @mpfans
> 
> > reversed the 3 commits(79b39f9 , 2779833 , 79b39f9) .
> > Why are the first and third commit ids the same?



https://github.com/azerothcore/azerothcore-wotlk/commit/79b39f9655111088a741185c4dabd31dae7d85ea


https://github.com/azerothcore/azerothcore-wotlk/commit/60e27511c530b0949fee361a89d3eb9d9f9125af

https://github.com/azerothcore/azerothcore-wotlk/commit/2779833768bbe9967006d6d16888dace05b4bcb6

**Closed** 2023-11-11 23:48 UTC

**Comment by JayPolah** [comment] 2026-01-03 17:25
Time to resurect this thread since I had the same issue and this was in the top search results (hope it will help others).

```ini
MinWorldUpdateTime = 10
MapUpdateInterval = 30
Console.Enable = 0
```

If you are running the world server as a service with systemctl you must disable the console. In my case it spammed a new line in a loop causing the high CPU usage.

**Comment by kissingers** [comment] 2026-01-03 17:30
> Time to resurect this thread since I had the same issue and this was in the top search results (hope it will help others).
> 
> MinWorldUpdateTime = 10
> MapUpdateInterval = 30
> Console.Enable = 0
> If you are running the world server as a service with systemctl you must disable the console. In my case it spammed a new line in a loop causing the high CPU usage.

Yes, have the problem. So I use PM2 replace systemctl.
