### ISSUE TITLE
this is a big bug!!!There is an abnormality after killing the first boss in the Trial of the champion！

### ISSUE THREAD

**Issue by ssdphp** [azerothcore/azerothcore-wotlk#13942] opened 2022-11-26 04:21 UTC
### Current Behaviour

In the first boss p2 stage in non-GM mode, let 3 bosses enter the battle together and defeat them normally, there will be a boss that will not leave the field, and will chase and kill the player, and cannot be killed. Existence, which makes it impossible to start the next battle normally. I have tested this problem 10 times, and 9 times have this problem
![QQ图片20221126022636](https://user-images.githubusercontent.com/16387049/204071811-54a48375-9e86-4032-ab91-335391534366.png)

### Expected Blizzlike Behaviour

3 bosses should leave

### Steps to reproduce the problem

1、Normal dialogue starts in non-GM mode Normal champion trial first boss fight
2、Beat the P1 stage on horseback
3、Defeat 3 bosses

### AC rev. hash/commit

AzerothCore rev. 55957fbb6e24+ 2022-11-24 18:23:27 -0300 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1c  28 May 2019 (library: OpenSSL 1.1.0j  20 Nov 2018)
Using Boost version: 1.74.0
Using MySQL version: 50727
Using CMake version: 3.21.3
Compiled on: Windows 10.0.19045
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014951 bytes
vmaps directory located in ./data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-eluna
- mod-transmog

### Operating system

 Windows 10 x64

**Comment by heyitsbench** [comment] 2022-11-26 16:47
Duplicate of #10717?

**Comment by noisiver** [comment] 2022-11-27 20:14
> Duplicate of #10717?

Yes. Not to mention the title is exaggerated.

**Comment by noisiver** [comment] 2022-11-27 20:17
That is, if the reporter doesn't mean that after killing the bosses on the mounts. In that case, this is a duplicate. I'm too tired and got confused a lot.

**Closed** 2022-11-28 07:21 UTC
