### ISSUE TITLE
[DB/Creature] Some ranged capable mobs are attacking ranged only once

### ISSUE THREAD

**Issue by ninjaskija** [azerothcore/azerothcore-wotlk#3478] opened 2020-09-13 19:50 UTC
CURRENT BEHAVIOUR:
It seems that all ranged capable mobs are attacking ranged only once then they are trying to get in melee range.

EXPECTED BLIZZLIKE BEHAVIOUR:
They should continue attacking range while they have resources (i.e mana for caster mobs)

i.e:

- Palemane Poacher should continue using **quick shot/shoot**.

- Palemane Tanner should use **wrath** until he gets out of mana.

STEPS TO REPRODUCE THE PROBLEM:
Engage the mobs and observe.

AC HASH/COMMIT:
`854dbef`

OPERATING SYSTEM:
Docker under Ubuntu 20.04

MODULES:
```
mod-autobalance/
mod-random-enchants/
mod-solocraft/
mod-solo-lfg/
```

**Comment by ninjaskija** [comment] 2020-09-13 19:59
Just noticed that the Razorman Hunter is working as intended. Probably someone could make a comparison between those.

**Comment by Knindzagxg** [comment] 2020-10-11 09:51
Both of them are sorted trough Mulgore update.
Tho, they won't spam it and will re-cast after some times.

**Comment by Hacaw** [comment] 2020-12-08 19:33
I can reproduce this, but I don't think it's an issue.
Based on this video: https://www.youtube.com/watch?v=Vuz_l6uH1y4 the Palemane Tanner casts once and then goes melee.
Since there is no retail documentation provided, I would propose to close this.


TESTING
---
1. .go c id 2949
2. .go c id 2951
3. observe their behavior
4. like @Knindzagxg mentioned, they don't spam their quick-attack/wrath-spells, but it will recast the skills after a couple of seconds 10~30 if you keep running.

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment] 2020-12-08 20:28
Thx for checking this @Hacaw !

**Closed** 2020-12-08 20:29 UTC
Labels: Invalid - CannotReproduce
