### ISSUE TITLE
[ZG] High Priest Thekal - Missing reset boundary.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12281] opened 2022-07-02 22:12 UTC
### Current Behaviour

Thekal can chase the player throughout the entire instance.

### Expected Blizzlike Behaviour

1. There should be a boundary at the base of the ramp leading to Thekal
2. When the boundary is reached, the boss will reset, and a emote from Hakkar will play, which is Yell: "Do not be lured into the mortals' trap.  Bathe in my power!  Be renewed and destroy the heretics!" (ID 10480) in broadcast_text

### Source

https://youtu.be/VFraeEvi2BQ?t=15

### Steps to reproduce the problem

1. `.go c 49310`
2. move outside the boss arena, see if emote plays

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/0de832cdca8bd109a87bb0a59dea579b8daf7788

### Operating system

Windows 10

**Comment by Maelthyrr** [comment] 2022-07-09 08:34
I remove for the moment "confirmed label" because need todo more research. The source seems to come from a pserver. Here there are no boundaries (https://www.youtube.com/watch?v=IkE_U9KXty4)

**Comment by Maelthyrr** [comment] 2022-07-09 08:39
Another here: https://youtu.be/0N-txlnNKbk?t=158

So I will just close the issue. Ping me if you have others sources that show the opposite

**Closed** 2022-11-01 15:56 UTC
Labels: Priority-Low, 60, Instance - Raid - Vanilla, temporary label
