### ISSUE TITLE
Core/Script: Wintergrasp

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#682] opened 2017-10-15 14:59 UTC
- Damage and hp cannons / machines do not scale from ilvl player.
- Damage to guns and cars is not correct.
- There is no part of the guns in the fortress and the towers.
- Some guns fall on the 1st floor of the towers.
- There is no notification of an attack on the relic gate and its destruction.
- Not the correct work of the buff Perseverance. The number of stacks depends on the number of people in the raid, and not on OLOs in general. The buff should be superimposed on the players of the side that is smaller, for every extra 10 people from the opponent - 1 stack, a maximum of 20 stacks (201 players vs. 1). This buff should also overlap the machines.
- Each time after the victory / loss, the inscription "The Alliance defended the Fortress of the Wintergrasp".
- The machine does not hang the buff "Perseverance".

Destroyer (http://wowroad.info/?npc=28094#abilities)
Standard Health: 55,000
Throw a boulder - Range: 70. Metaet burns a cobblestone that deals 2999 - 3002 damage. damage to enemies and 900 - 1101 damage. Siege damage to nearby buildings.
Taran - Range: 15. Inflicts 3000 damage per second. damage to opponents in front of the destroyer and pushes them back. Also deals 1500. siege damage to buildings.

Cannon (http://wowroad.info/?npc=28366#abilities)
Standard health: 50,000
Shot from the cannon - School Damage (Weapon) 7996 units.

Draft (http://wowroad.info/?npc=32627)
Standard Health: 85,000
Taran - Deals 3,000 damage per second. damage to opponents in front of the destroyer and pushes them back. Also deals 2000 damage. siege damage to buildings.

Catapult (http://wowroad.info/?npc=27881)
Standard Health: 35,000
The plague barrel is Boulder:
Effect # 1 School Damage (Weapon) Value: 2999. Radius: 10 yards.
Effect # 2 Summon Totem slot 1 Value: 665. Radius: 10 yards.
Effect # 3 Trigger Spell Plague Slime- Deals 1000 health. Nature damage inflicted every 3 sec for 9 sec.

Steps to reproduce the problem:

Wintergrasp use

AzerothCore rev. efbcb8f 2017-09-23 11:30:22 +0200 (master branch) (Unix, Release) (worldserver-daemon)

DEBIAN 8.9

ANTICHEAT
TRANSMOG
DUELRESET

clang report many unused variables during compilation

**Comment by Viste** [comment] 2018-03-31 21:32
https://github.com/azerothcore/azerothcore-wotlk/issues/676 can you make one issue against two

**Comment by irgc** [comment] 2018-05-26 22:17
hi
wintergrasp is buged?!

**Comment by gengarshadowball** [comment] 2020-02-10 09:36
This is unnacurate information 
```
Damage and hp cannons / machines do not scale from ilvl player.
Damage to guns and cars is not correct.
```
Can't reproduce this issue, everything looks fine
```
There is no part of the guns in the fortress and the towers.
Some guns fall on the 1st floor of the towers.
```
This issue has been fixed before too
```
Each time after the victory / loss, the inscription "The Alliance defended the Fortress of the Wintergrasp".
```

About tenacity I still need to test it and see what's going on.

**Comment by Kitzunu** [comment] 2021-04-25 00:06
Closing as this issue was deemed not reproducible / already fixed over a year ago.

If the issue still persists, make a new issue

**Closed by Kitzunu** 2021-04-25 00:06 UTC
Labels: Not confirmed, Priority - Medium
