### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by maikale** [azerothcore/azerothcore-wotlk#1452] opened 2019-02-12 11:26 UTC
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4715	'WorldSocket::ProcessIncoming': not all control paths return a value	game	c:\users\pc\desktop\azerothcore-wotlk-master\src\server\game\server\worldsocket.cpp	724	
Error	C2079	'spell_gen_model_visible::spell_gen_model_visible_AuraScript::_itemId' uses undefined class 'std::array<uint32,3>'	scripts	c:\users\pc\desktop\azerothcore-wotlk-master\src\server\scripts\spells\spell_generic.cpp	82	
Error	C2440	'initializing': cannot convert from 'initializer list' to 'int'	scripts	c:\users\pc\desktop\azerothcore-wotlk-master\src\server\scripts\spells\spell_generic.cpp	82	
Error	C2439	'spell_gen_model_visible::spell_gen_model_visible_AuraScript::_itemId': member could not be initialized	scripts	c:\users\pc\desktop\azerothcore-wotlk-master\src\server\scripts\spells\spell_generic.cpp	82	
Error	C2660	'Object::SetUInt32Value': function does not take 1 arguments	scripts	c:\users\pc\desktop\azerothcore-wotlk-master\src\server\scripts\spells\spell_generic.cpp	72	
Error	LNK1181	cannot open input file '..\scripts\Release\scripts.lib'	worldserver	C:\Users\PC\Desktop\Build\src\server\worldserver\LINK	1

**Comment by FrancescoBorzi** [comment] 2019-02-12 20:15
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/1451

**Closed by FrancescoBorzi** 2019-02-12 20:15 UTC
