### ISSUE TITLE
(Ulduar Heroic Mode 25): General Vezax

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3181] opened 2020-07-09 21:22 UTC
https://www.wowhead.com/npc=33271/general-vezax

**CURRENT BEHAVIOUR**:
General Vezax in Heroic mode (25), when he uses https://www.wowhead.com/spell=63364/saronite-barrier and summons saronite creatures, after killing 8 of them, and when he has 35% health, he does not call on the creature (I don’t know what he owes, as I understand it - https://www.wowhead.com/npc=33772/faceless-horror

**EXPECTED BLIZZLIKE BEHAVIOUR**:
General Vezax in Heroic mode (25), when he uses https://www.wowhead.com/spell=63364/saronite-barrier and summons saronite creatures, after killing 8 of them, and when he has 35% health, he should call on the creature (I don’t know what he owes, as I understand it - https://www.wowhead.com/npc=33772/faceless-horror

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Knindzagxg** [comment] 2020-07-17 17:48
Faceless Horror have nothing to do with Vezax boss fight.

Whole point of the fight, because is not mana friendly to keep killing Saronite Orbs (They give mana back to healers or etc)
If there are 6 at any moment, boss will gain shield and summon Animus which have to be killed in order to remove it.

Tested it as well, and no issues found.

**Comment by wowissues** [comment] 2020-07-17 18:10
> Faceless Horror have nothing to do with Vezax boss fight.
> 
> Whole point of the fight, because is not mana friendly to keep killing Saronite Orbs (They give mana back to healers or etc)
> If there are 6 at any moment, boss will gain shield and summon Animus which have to be killed in order to remove it.
> 
> Tested it as well, and no issues found.

Yes, this is my jamb. I do not know the name of the creature that he should call. I know that he should call for 35% health after killing 8 saronite creatures. Please do not close, this issue, I’ll try to confirm this as https://github.com/azerothcore/azerothcore-wotlk/issues/2891 , Give me some time so I can confirm

**Comment by FrancescoBorzi** [comment] 2020-11-28 19:28
closing as this hasn't been confirmed. If it will be confirmed, it can be reopened.

**Closed by FrancescoBorzi** 2020-11-28 19:28 UTC
Labels: Invalid - CannotReproduce
