### ISSUE TITLE
coredump

### ISSUE THREAD

**Issue by chendh123** [azerothcore/azerothcore-wotlk#1499] opened 2019-02-19 15:30 UTC
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f2f6a862700 (LWP 51132)]
0x0000000001b110aa in Trinity::Assert (file=0x259d550 "/home/cdh/workspace/azerothcore-wotlk/src/server/game/Grids/Notifiers/GridNotifiersImpl.h", line=540, 
    function=0x259da6f <Trinity::LocalizedPacketDo<Trinity::MonsterChatBuilder>::operator()(Player*)::__FUNCTION__> "operator()", message=0x259d528 "data->GetOpcode() != MSG_NULL_ACTION")
    at /home/cdh/workspace/azerothcore-wotlk/src/common/Debugging/Errors.cpp:20
20          *((volatile int*)NULL) = 0;
(gdb) where
#0  0x0000000001b110aa in Trinity::Assert (file=0x259d550 "/home/cdh/workspace/azerothcore-wotlk/src/server/game/Grids/Notifiers/GridNotifiersImpl.h", line=540, 
    function=0x259da6f <Trinity::LocalizedPacketDo<Trinity::MonsterChatBuilder>::operator()(Player*)::__FUNCTION__> "operator()", message=0x259d528 "data->GetOpcode() != MSG_NULL_ACTION")
    at /home/cdh/workspace/azerothcore-wotlk/src/common/Debugging/Errors.cpp:20
#1  0x000000000153dc0c in Trinity::LocalizedPacketDo<Trinity::MonsterChatBuilder>::operator() (this=<error reading variable: Cannot access memory at address 0xa0a0a0a0a09e2>, 
    this@entry=<error reading variable: Cannot access memory at address 0xa0a0a0a0a0a12>, p=<error reading variable: Cannot access memory at address 0xa0a0a0a0a09da>)
    at /home/cdh/workspace/azerothcore-wotlk/src/server/game/Grids/Notifiers/GridNotifiersImpl.h:540
(gdb)
```

**Comment by Mitradis** [comment] 2019-02-19 16:13
what happened? Write more info.

**Comment by FrancescoBorzi** [comment] 2019-02-19 16:17
@chendh123 please add your AC commit hash. The issue will be reopened when you add it.

**Comment by GitVerge** [comment] 2019-02-19 16:24
this is caused by an unnecessary assert in grid notifier. Related to https://github.com/azerothcore/azerothcore-wotlk/pull/1342

**Comment by chendh123** [comment] 2019-02-19 16:49
Thanks. 
By the way,
if MSG_NULL_ACTION is allowed, why used ASSERT before?

**Comment by GitVerge** [comment] 2019-02-19 17:24
Actually I just saw that in the pr this assert is moved to worldsession, so is basically the same, they did not remove it. To "fix" this issue one of the following changes could be done:

- If we don't want servers to just crash when MSG_NULL_ACTION is going to be sent, replace with an error output message and don't send the package.
- Fix the issue in db, same as #1342

This is a msg from server to client, I guess that if it arrives to the client it could cause wowerror or other  malfunctions, I never tried it before ^^

**Comment by chendh123** [comment] 2019-02-19 17:25
SHA-1: 3a39aaeed53d994d88d854dc63cfbc0cc80a6eb8

**Comment by Kitzunu** [comment] 2020-06-20 18:19
I will close this as we have no reports of it for over a year

**Closed by Kitzunu** 2020-06-20 18:19 UTC
