### ISSUE TITLE
If you dance with a PvP flagged player using D.I.S.C.O you get PvP flagged.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#7938] opened 2021-09-17 12:53 UTC
### Current Behaviour

The item DISCO makes a clickable dancing disco. If a flagged player clicks it, they PvP flag everyone else.

Not flagged dancing.

https://cdn.discordapp.com/attachments/779069112974049340/888406540208451624/WoWScrnShot_091721_134955.jpg

Flagged player joins DISCO dance and flags us all.

![WoWScrnShot_091721_135107](https://user-images.githubusercontent.com/61194190/133785613-40de4e8e-585e-4790-9210-ac215749d2eb.jpg)

### Expected Blizzlike Behaviour

PvP flag should only come from PvP activity, not /dance.

### Source

https://tbc.wowhead.com/item=38301/d-i-s-c-o

https://wowwiki-archive.fandom.com/wiki/PvP_flag

### Steps to reproduce the problem

Additem D.I.S.C.O
Place DISCO
Dance unflagged.
Dance flagged.
All flagged.

### AC rev. hash/commit

AzerothCore rev. 7e2e6f8ee85f+ 2021-09-13 14:16:29 +0000 

### Operating system

win10

### Custom changes or Modules

chromiecraft modules

**Comment by Ragelezz** [comment] 2021-09-21 16:51
Cannot reproduce even in party. Tried on multiple chars at once. Anyone else?

**Comment by FrancescoBorzi** [comment] 2021-09-29 13:07
> Cannot reproduce even in party. Tried on multiple chars at once. Anyone else?

@azerothcore/bug-triaging please verify this and close if invalid

**Comment by Azcobu** [comment] 2021-09-29 13:45
Verified. Just tried with two players, not in party, dancing together. Then manually flagged the druid, and the other player was flagged a second or so later. You can see the warrior's name tag go from blue to green here:

https://user-images.githubusercontent.com/81782124/135279722-6758d632-f3eb-40a1-ac87-87c3f04b59c4.mp4

Checked to make sure it wasn't just a cosmetic/visual bug, but both players saw the warr as being flagged.

![WoWScrnShot_092921_230530](https://user-images.githubusercontent.com/81782124/135280739-1b87b5a8-584c-4c59-a198-c0c8b7b173df.jpg)

**Comment by Ragelezz** [comment] 2021-09-29 13:54
Hm, will test again but I see Ultranix pushed a fix regarding this. Will come back later with feedback on this.

**Closed** 2021-10-03 16:12 UTC
Labels: Confirmed, ChromieCraft Generic, Priority-Trivial
