### ISSUE TITLE
Hunter Pet Threat Bug with Glyph of Mend Pet

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6755] opened 2021-07-05 15:24 UTC
### Current Behaviour

Glyph of mend pet causes your pet to get 10k+ threat on pull when mend pet is active

### Expected Blizzlike Behaviour

It should definitely not give your pet extra threat when using this glyph.

### Source

https://wowwiki-archive.fandom.com/wiki/Glyph_of_Mend_Pet

### Steps to reproduce the problem

Aggro mob with mend pet active
See that normal threat generation ( a few for the hunter for using mend pet)
Aggro mob with Mend pet + glyph of mend pet active
See that aggro is 10k+ on pull

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/532

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

### Operating system

Ubuntu 20.04

**Comment by necropola** [comment] 2021-07-25 04:21
Duplicate of #6190

**Closed** 2021-07-25 08:34 UTC
Labels: Class-Hunter, Confirmed, Priority-High
