### ISSUE TITLE
Quest items lootable by multiple party members.

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4415] opened 2021-02-02 17:10 UTC
### CURRENT BEHAVIOUR:
When looted in perfect sync (Interact with target activated via keybroadcasting), quest items which should drop only for one toon, can be looted with 2-5 toons. Without perfect sync, only one toon gets the reward.
Tested on Pygmy Surf Crawler and Makrura Spellhide for the quest "A Solvent Spirit".

### EXPECTED BLIZZLIKE BEHAVIOUR:
Only one quest item per corpse should be obtaiable for these kind of collection quests. Not one per toon.

### STEPS TO REPRODUCE THE PROBLEM:
To reproduce it one would need an external program, e.g. Hotkeynet.
Then have it send a key to all windows in perfect sync to make them all loot an once.

### EXTRA NOTES:
Does not affect normal solo play or not even normal party play.

### AC HASH/COMMIT:
https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

### OPERATING SYSTEM:
OS:
Ubintu 20.04

### MODULES:
Chromiecraft server

### OTHER CUSTOMIZATIONS:
Chromiecraft server

**Comment by Kitzunu** [comment] 2021-02-02 18:48
I remember seeing the fix for this on TC yesterday... Now I can't find it xd

**Comment by Kitzunu** [comment] 2021-02-02 18:51
https://github.com/TrinityCore/TrinityCore/commit/586c00fe2e226da99968ebe763d3226c6134658c

**Comment by FrancescoBorzi** [comment] 2021-02-02 18:58
> [TrinityCore/TrinityCore@586c00f](https://github.com/TrinityCore/TrinityCore/commit/586c00fe2e226da99968ebe763d3226c6134658c)

thanks @Kitzunu . It seems simple, can you please provide a PR?

**Comment by Kitzunu** [comment] 2021-02-02 19:00
Already working on it :D

**Comment by Zoidwaffle** [comment] 2021-02-04 09:21
I believe I can confirm the issue - I have seen some loot behavior where items that would usually only drop once, appear to be looted by multiple gnomes (but not all) if interacting as a group. I cannot reproduce it reliably though... I multibox 5 characters at once.

@Kitzunu if you make a fix, I can apply it and try to see if I can trigger the issue.

**Comment by Kitzunu** [comment] 2021-02-04 09:23
https://github.com/azerothcore/azerothcore-wotlk/pull/4420 @Zoidwaffle

**Closed** 2021-02-05 11:38 UTC
Labels: 1-19, Fix included
