### ISSUE TITLE
Non hitable mobs in Stonetalon Mountains

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4813] opened 2021-03-12 07:41 UTC
Originally reported https://github.com/chromiecraft/chromiecraft/issues/192

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

Quest lvl 21 (20-29)

##### SMALL DESCRIPTION:

While doing quest [Pridewings of Stonetalon] I've noticed that some mobs are non-hitable, I found one at the lake and one marked on map (screen attached) with location. Mobs sometimes are falling from the sky.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All mobs can be killed.

##### CURRENT BEHAVIOUR:

Can't mark and kill mob.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 - Go to Stonetalon Mountains
Step 2 - Seek those mobs and try to kill them.
Screens: https://imgur.com/a/Y5bs864

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment] 2021-03-12 09:53
duplicate of: https://github.com/azerothcore/azerothcore-wotlk/issues/4801

**Closed** 2021-03-12 09:53 UTC
Labels: ChromieCraft Generic, Confirmed, DB, Priority - Low
