### ISSUE TITLE
Problem display chat choices faction guard (frFR client)

### ISSUE THREAD

**Issue by Seigneur-fantome** [azerothcore/azerothcore-wotlk#6791] opened 2021-07-07 11:15 UTC
### Current Behaviour

hello, when i ask assistance to guard city, i have this problem (french lang):

![1](https://user-images.githubusercontent.com/79913664/124767102-cc607180-df37-11eb-9166-fecd0d8764da.png)
![2](https://user-images.githubusercontent.com/79913664/124767118-cf5b6200-df37-11eb-9e37-2ee3a84fc34d.png)

### Expected Blizzlike Behaviour

![3](https://user-images.githubusercontent.com/79913664/124767140-d4b8ac80-df37-11eb-9168-e2548c3d8543.png)
 (same thing with horde)

### Steps to reproduce the problem

go to city (hord or alliance) and ask help to guard with a frFR client

### Extra Notes

**Client: frFR**

### AC rev. hash/commit

AzerothCore rev. 695154ac9245+ 2021-07-04 22:14:09 +0000 (master branch) (Win64, Release, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

> Anticheat https://github.com/azerothcore/mod-anticheat
> mod_LuaEngine https://github.com/azerothcore/mod-eluna-lua-engine
> mod_multilogin https://github.com/azerothcore/mod-multi-client-check
> mod_pvptitles https://github.com/azerothcore/mod-eluna-lua-engine

**Comment by Sedatyf** [comment] 2021-07-07 11:35
Please, paste directly images in your post. We can't access your images because we can't access discord server where they came from

**Comment by Sedatyf** [comment] 2021-07-07 11:36
Also I edited your original post. You didn't precise that you have a client in frFR and not enUS

**Comment by Seigneur-fantome** [comment] 2021-07-07 13:14
sorry, i update ^^

**Comment by Seigneur-fantome** [comment] 2021-07-07 13:21
where i update this information?

**Comment by Sedatyf** [comment] 2021-07-07 13:23
I already changed it. Just make sure your images are readable for everyone by pasting it directly in your github issue and not with a discord link

**Comment by Seigneur-fantome** [comment] 2021-07-07 13:25
ok, now or next time sir?

**Comment by Sedatyf** [comment] 2021-07-07 13:26
Now. Because some of your images aren't readable

**Comment by Seigneur-fantome** [comment] 2021-07-07 19:10
done

**Comment by do1das** [comment] 2021-08-01 23:14
same issue with deDE Locales AzerothCore rev. 498e01e7fcb4+ 2021-07-29 12:18:36 +0000 (master branch):
![grafik](https://user-images.githubusercontent.com/58998008/127788100-1b249136-6cd0-4391-a2de-12494daa63c6.png)

**Comment by Sedatyf** [comment] 2021-08-02 08:52
Can you make another issue as this isn't the same client? @do1das We'll link them together so it won't be lost

**Comment by staircrusher** [comment] 2021-08-02 15:02
> 
> 
> Can you make another issue as this isn't the same client? @do1das We'll link them together so it won't be lost

Ok, i made another issue. Also i posted it under my main account. I accidently posted the comment in this issue with my hamradio related account :-)

https://github.com/azerothcore/azerothcore-wotlk/issues/7209

**Comment by Seigneur-fantome** [comment] 2021-09-11 17:45
when it's update and fixed? :o

**Comment by FrancescoBorzi** [comment] 2021-09-12 22:20
@Seigneur-fantome when someone provides a fix for it :) you can speed it up by [placing a bounty on it](http://www.azerothcore.org/wiki/Bountysource)

**Comment by Kitzunu** [comment] 2021-09-13 00:35
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7209

**Closed by Kitzunu** 2021-09-13 00:35 UTC
